[1단계 - 페이먼츠] 우연(전연지) 미션 제출합니다.
woowacourse/react-payments pull request #105
Opened 2022-04-29 00:55 UTC by ronci

안녕하세요 리뷰어님!

이번미션에서 리액트와 storybook을 사용해보며 많이 배운 것 같습니다!

리뷰 잘 부탁드립니다!!

### [storybook 배포](https://626ac781415552004a44256a-kuhpwdjpdk.chromatic.com/?path=/story/card--default-card)

### [데모페이지](https://hwangstar156.github.io/react-payments/)

## 기능 구현 사항

- [x] 카드 추가폼 구현

  - [x] 카드번호를 입력할수 있다.

    - [x] 앞에 8자리는 숫자가 보여지도록, 뒤에 8자리는 가려지도록 구현한다.

- [x] 만료일을 입력할수 있다.

- [x] 카드 소유자 이름을 선택적으로 입력할수 있다.

- [x] 카드 소유자 이름은 최대 30자까지 입력이 가능하다.

- [x] 보안코드를 입력할수 있다.

- [x] 보안코드는 3자리수만 가능하다.

- [x] 옆의 ? 버튼에 커서를 올렸을때 보안코드에 대한 설명을 보여준다.

- [x] 카드 비밀번호를 입력할수있다.

- [x] 카드 정보를 적을때마다 카드에 바로 반영된다.

- [x] 이름을 제외한 모든 입력이 채워질시 다음 버튼이 생긴다.

# 추가 기능 구현 사항

- [x] 카드 종류를 고를  수 있는 모달 구현

- [x] 가상키보드 구현

- [x] 보안코드, 비밀 번호 입력에 사용

- [x] 숫자를 랜덤으로 배열

# 배우고 시도해본점

1. redux와 같은 상태 관리 라이브러리를 왜 쓰는지 생각해 볼 수 있었습니다
    - components를 많이 작성하다보니 props에 대한 관리가 힘들었습니다. 예로 나중에 props 하나를 추가하기 위해서 여러 component를 들어가며 props를 추가해야했습니다.
    - 이점을 해결하기위해 쓴다는 걸 알 수 있었습니다.
2. map에 index 사용하는 것도 괜찮은 것 같습니다.
    - uuid()를 사용하면 virtual DOM에서
    - uuid()를 사용할때 다시 렌더링되면 새로 key값이 만들어지기 때문에 전의 key값과 달라서 react가 같은 것이지 인지하지 못하는 오류가 생긴다.
    - state가 변하지 않아도 부모가 변하면 전체가 바뀌는 문제가 생겼습니다.
    - 이 점을 해결하기 위해 index를 key값으로 주었습니다.
    - 렌더링될때를 생각하면서 조심해서 쓰면 좋은 key값이 될 수 있다고 생각했습니다.
3. 가상키보드 구현해보기
    - 보안숫자 입력과 비밀번호 입력에 사용했습니다.
4. CDD(Component-Driven Development) 해보기
    - 작은 component부터 만들어보면서 재사용할 수 있는 component를 만들기 위해 많이 생각해봤던 것 같습니다.
5. Storybook 사용
    - component 구현과 함께 storybook을 사용했는데 args를 지정해서 넣어주어 화면에서 어떻게 보이는 지 바로 확인할 수 있다는 점이 편했습니다!
6. custom hooks 사용
    - 이번에 react를 사용하고 state를 관리하며 custom hooks를 사용해보았습니다.
    - 데이터 관리나 validation등을 custom hooks에서 처리하니 코드가 훨씬 깔끔해지고 데이터를 관리하기 좋았습니다.

# 질문

1. 가상키보드 바깥영역을 누르면 제거하게 하고 싶었지만 어떻게 해야 할지 좋은 아이디어가 떠오르지 않습니다.
    - 가상키보드에서 focusIn되었을 때 가상키보드를 노출시키고 onBlur을 사용하려 제거하려 했습니다.
    - 하지만 가상키보드를 클릭하려 했을때 click이벤트보다 onBlur이벤트가 먼저 일어나 입력이 되지 않고 가상키보드가 원하지 않을 때 제거되는 현상이 일어났습니다.
    - 이럴 때 어떻게 해결할 수 있을까요?
2. 가상키보드로 input관리를 어떻게 해야할 지 모르겠습니다.
    - 가상키보드를 추가하기 전에는 카드 비밀번호를 입력하는 칸에서 자동으로 focus를 이동시키도록 구현해놓았습니다.
    - 가상키보드를 추가한 후에는 focus해야하는 input을 어떻게 찾아야 할지, value를 어떻게 넣어야할지 좋은 아이디어가 떠오르지 않았습니다.
    - 그래서 현재 비밀번호같은경우 무조건 첫번째 칸부터 채워지도록 바꾸었습니다.

2022-05-02 05:33 UTC, pocojang requested changes
안녕하세요
@ronci 

대타 리뷰어로 왔습니다.

질문이나 핵심적인 키워드 리뷰는 본 리뷰어이신 광휘님이 지나가시다가 슬쩍 달아주시겠죠?
저는 미션이 밀리지 않도록 조금 공통적인 리뷰만 봤습니다.

## 전반적인 의견

역시.. 페어와 특징이 확실하시네요.
심화 요구 사항 + 테스트까지 하시면서 구현 관점에 있어서 두 분은 빠른 속도를 지니셨네요
고생 많으셨어요

## 커스텀 훅 활용

일단 적극적으로 활용하신 점 칭찬합니다.
하지만 다음부터는 의식적으로 분리하도록 노력해보세요 :)
과도한 훅 분리, 유틸인지 훅인지 헷갈리는 녀석이 제법 보입니다

추가적으로 반환을 무조건 배열로하니 유연하지 못한 경우도 있어요.
그러다보니 커스텀 훅으로 분리는 했지만 결국 특정 컴포넌트에 의존적인 훅이 탄생해버리는 경우가 종종 보이네요.

결국 하나의 컴포넌트를 구성할때 아래와 같은 구성이 한 세트로 움직이고 있습니다.

- `AA.component.jsx`
- `AA.css`
- `AA.stories.jsx`
- `useAA.jsx`


## 리액트와 관련 없는 코드

리액트 컴퓨넌트나 훅에 의존성이 없는 코드들이 간간히 보여요.
이런 경우를 `유틸`, `lib` 형태로 분리해내고는 하는데요.
그런 로직이 보인다면 과감히 분리해서 다른 파일로 넘겨보세요

## 컴포넌트 구성

`Hooks` 활용은 적극적이지만 그 외에는 아쉽네요
다음부터는 `children`을 적극적으로 활용해보세요.
또한 조건부 렌더링도 어떤 기준을 가지고 해볼까 고민해보시면 좋습니다.
라우팅에 들어가기전에 많이 고민해보시면 좋아요

## 파일 네이밍

약간은 아쉬운 부분이 보입니다.
분명 일관성을 지키고 있으나 왜 그런 결정을 했을까?
개인적으로는 의문부호가 종종 듭니다.

## 폼

정말 상당히 많은 고민과 코드가 녹아져 들어가있는데요
분리도 엄청나게 하셨으나 그리 유연해보이지는 않아보입니다.
하나하나의 결합도가 상당히 커보이고요.
그러다보니 불필요한 상태 값들도 늘어나고 자연스럽게 `Props`도 엄청 생기고 있어요.
빠른 시간에 구현하다보니 당연한 현상이라고 생각합니다.
차차 공부해보면서 개선해보면 자연스럽게 해결되겠죠?!

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/component/Input/input.component.jsx
> +          {idx && connector ? <p className="connector">{connector}</p> : null}
`: null` 해당 부분이 꼭 필요할까요?

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/hooks/useCanShowModal.jsx
> +const useCanShowModal = () => {
`Modal`아닌 곳에서도 모두 사용 가능한 불리언 플래그 훅 아닐까요?

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/hooks/useCardNumber.jsx
> +  return [[first, second, third, fourth], onChangeCardNumber, cardNumberReady];
내보낼때 꼭 배열로 내보내야할 이유가 있을까요?

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/hooks/useCardPassword.jsx
> +  };
차라리 `setState()` 내부에 분기문이 들어오거나 `reducer`로 관리하는게 좋을 수도 있어보이네요

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/pages/CardAddPage/CardAddPage.stories.jsx
> +  const canvas = within(canvasElement);
Wow 👍

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/pages/CardAddPage/CardAddPage.stories.jsx
> +CompleteCardAddPage.play = async ({ canvasElement }) => {
본 테스트에 `async & await`를 사용하는 이유는 어떻게 되시나요?

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/util/index.js
> +};
단순히 체크만하는 게 아닌 걸로 보이네요.
또한 UI의 포커스 행위에 관여도 하고 있고요

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +const CardAddPage = () => {
한 페이지에 폼이 굉장히 많은데요
자세히 보면 폼이 아닌 `Input` 하나하나로 보입니다.
`Input`이 아닌 `Form`으로 명명하신 이유가 있으신가요?

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +import useUserName from "../../hooks/useUserName";
앞으로도 순서가 잘 지켜기질 바랍니다... 👀

2022-05-02 05:33 UTC, pocojang commented on react-payments/src/component/VirtualKeyboard/keyboard.component.jsx
> +const VirtualKeyboard = ({
심화요구사항.. 대다나다

2022-05-02 06:57 UTC, Vallista requested changes
안녕하세요 우연님!
코드리뷰가 늦어서 굉장히 죄송합니다 ㅠ
나중에 밥 한끼 사겠습니다..

# 전반적인 피드백

- 전반적으로 커스텀 훅을 잘 이용하신 것 같아서 좋았습니다 :) 굿굿
- 그런데, 커스텀 훅으로 너무 빼다보니, 이 커스텀 훅은 훅보단 컴포넌트 단위로 들어가는게 나을수도 있었겠다 하는 부분이 보였어요 :) 대표적으로 카드 번호를 입력하는 부분인데요! 요 부분은 범용적으로 사용되는 범위가 컴포넌트 자체의 폼을 가져다 쓸 수 있기 때문에, 컴포넌트 단위로 관리가 될 수 있을 것으로 보입니다!
- 그러한 부분들을 확인해보시고, 컴포넌트 단위로 만들어서 재사용할 수 있는것은 무엇인가 고민해보시면 좋겠습니다! 물론, 해당 로직이 컴포넌트 안에 들어간다고 하더라도 커스텀 훅의 로직들은 유지가되어 재사용이 될꺼지만요. 
- 나머지 피드백은 코드라인에 달아두었습니다!

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/Card/card.css
> +  transform: translate(0px, 5px);
0px!?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/ColorBox/colorBox.component.jsx
> +          currentCardType === cardInfos[idx].cardType ? "selected" : ""
빈 공백으로 해주는게 맞을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/ColorBox/colorBox.component.jsx
> +        className={`${colorType} color-box `}
className={`${colorType} color-box `} 를 해주려면 뒷 공간을 계속 빈공간을 넣어주고 있는데, 이럴 필요없이 해줄 수 있는건 없을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/Form/form.component.jsx
> +const inputEnum = {
일반적인 enum은 값에 함수가 들어갈 수 없습니다! enum이라고 표현하신 이유가 있을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/Form/form.component.jsx
> +  "card-user": (props) => (
form.component 인데 card-user라는 레이아웃을 별도로 관리할 필요가 있을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/Form/form.component.jsx
> +        (props.ready ? (
ready 는 boolean인지 잘 확인할 수 있을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/Input/input.component.jsx
> +    <div className={`input-box ${inputClass}`}>
썩 유쾌하게 스타일이 들어가지 않네요 ㅠ 어떤 다른 방법으로 넣을 수 있는게 없을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/Input/input.css
> +  margin-top: 0.375rem;
rem 으로 진행하신 이유가 있을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/VirtualKeyboard/keyboard.component.jsx
> +const VirtualKeyboard = ({
function을 안쓰시고 arrow function을 쓰면 어떤 이점이 있어서 쓰신걸까용?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/component/VirtualKeyboard/keyboard.component.jsx
> +const getShuffleArray = () => {
getShuffleArray 는 상단에 있는게 맞을까요 하단에 있는게 맞을까요? 어떤의도로 하신건지 궁금해용

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/hooks/useCanShowModal.jsx
> +const useCanShowModal = () => {
useCanShowModal 이게 필요한 이유가 근데 있나요..?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/hooks/useCardNumber.jsx
> +  const { first, second, third, fourth } = cardNumber;
first, second, third, fourth 로 카드 번호를 분류하는게 맞는걸까용? 더 좋은 방법은 없을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/hooks/useCardNumber.jsx
> +const useCardNumber = () => {
커스텀 훅으로 잘 표현해주셨어요!
혹시 요것을 커스텀훅도 훅인데, 카드 넘버를 관리하는 컴포넌트 하나단위로 만들 수 있지도 않을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/hooks/useCardPassword.jsx
> +const isInValidCardPassword = (cardPassword) =>
벨리데이트 로직은 어디 한 군데에서 한번에 관리하는게 나을수도 있지 않을까요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/hooks/useCardPassword.jsx
> +  checkReady();
checkReady 는 렌더링 타임마다 계속 호출하는 것인가요?

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +      <Form
폼이 너무 많은데, 폼이 아니라 input 하나 단위로 생각하는게 낫지 않을까요?
어차피 궁극적으로 서버엔 폼 데이터 전체가 하나만 가게 되니까요!

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +    <div className="card-add-page">
그리고 div가 아니라 form이 되는게 더 낫지 않을까 싶어요.

2022-05-02 06:57 UTC, Vallista commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +            value: expireDate[0],
expireDate[0] 과 [1]로 데이트를 구분하는건 어려울 것 같아요!

2022-05-02 06:58 UTC, Vallista commented
나머지는 전반적으로 포코님이 해주셔서..

2022-05-02 12:43 UTC, pocojang commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +      <Form
![야나두짤3](https://user-images.githubusercontent.com/23068523/166235420-7df15a23-d66a-410b-89cb-ac48cc60428c.png)

2022-05-02 12:43 UTC, pocojang commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +    <div className="card-add-page">
![야나두짤3](https://user-images.githubusercontent.com/23068523/166235420-7df15a23-d66a-410b-89cb-ac48cc60428c.png)

2022-05-02 12:43 UTC, pocojang commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +            value: expireDate[0],
![야나두짤3](https://user-images.githubusercontent.com/23068523/166235420-7df15a23-d66a-410b-89cb-ac48cc60428c.png)

2022-05-03 08:25 UTC, ronci commented on react-payments/package.json
> +  "dependencies": {
사용하지 않는 `uuid`는 삭제하였고 `gh-pages`는 devDependencies로 옮겼습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/public/index.html
> +<html lang="en">
`ko`로 수정하였습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/component/Card/card.component.jsx
> +            {cardNumbers.map((cardNumber, idx) => {
`uuid`를 사용했더니 렌더링 될때마다 계속 key값이 변하면서 정상작동이 되지 않는 문제가 있었습니다.
그래서 이번에는 추가되는 요소가 없어서 index를 사용하더라도 key값이 변하지 않을 것 같아 index를 사용하였습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/component/Card/card.component.jsx
> +    <div className="card-box" onClick={toggleModal} data-testid="card">
storybook의 interaction test에서 DOM을 셀렉팅할때 data-testid를 사용했습니다. 
이 때 공식문서에서 data-testid형태로 사용해서 이렇게 사용하였습니다!
https://testing-library.com/docs/queries/bytestid/

2022-05-03 08:25 UTC, ronci commented on react-payments/src/component/Card/card.css
> +  background: #e5e5e5;
컬러를 css 변수로 관리하도록 수정하였습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/component/Form/form.component.jsx
> +const inputEnum = {
이것도 step2에 수정하도록 하겠습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/component/Form/form.component.jsx
> +    <div className="input-container">
즉시 실행 함수 안의 if else, &&, 삼항 연산자 등 다양한 조건부 렌더링 방법에 대해서 알 수 있었습니다.
현재는 하나의 컴포넌트에서 5개의 기능을 구현하려해서 다음과 같이 삼항연산자가 반복되는 현상이 일어나고 있습니다.
후에는 5개의 기능을 분리할 예정이라 삼항연산자 또한 줄어들 것 같습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/component/Form/form.component.jsx
> +  const { formType } = props;
enum을 이용하기 위해 formType을 준 것이기 때문에 기본값은 필요없다고 생각하여 사용하지 않았습니다.

2022-05-03 08:25 UTC, ronci commented on react-payments/src/component/HelpBox/helpBox.stories.jsx
> +  await userEvent.hover(canvas.getByRole("button", { hidden: true }));
helpBox위에 마우스를 올렸을 경우 메세지가 나오는 지 확인하는 테스트입니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/component/Input/input.component.jsx
> +          {idx && connector ? <p className="connector">{connector}</p> : null}
아닙니다! ?를 &&로 변경하면서 제거했습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/hooks/useCanShowModal.jsx
> +const useCanShowModal = () => {
hooks로 분리할 필요가 없는 것 같아 component 내부에서 useReducer를 사용하여 구현하는 방법으로 변경하였습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/hooks/useCardNumber.jsx
> +  return [[first, second, third, fourth], onChangeCardNumber, cardNumberReady];
아닙니다! useState에서 배열로 사용하면서 자연스럽게 배열을 사용했던 것 같습니다.
순서를 따로 고려하지 않아도 되는 객체가 좋은 것 같습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/hooks/useCardPassword.jsx
> +  };
다음과 같이 setState 내부에서 분기문을 처리하도록 수정하였습니다!
```jsx
const onClickCardPasswordBackspaceButton = () => {
    setCardPassword((prev) => {
      if (cardPassword.second === "") {
        return { ...prev, first: prev.first.slice(0, -1) };
      }
      return { ...prev, second: prev.second.slice(0, -1) };
    });
  };
```

2022-05-03 08:25 UTC, ronci commented on react-payments/src/pages/CardAddPage/CardAddPage.stories.jsx
> +CompleteCardAddPage.play = async ({ canvasElement }) => {
공식문서에서 `async & await`를 사용하여 다음과 같이 구현하였는데,
await가 다음 테스트에 영향이 없는 것을 알고 제거했습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/util/index.js
> +};
지금 다시 확인해보니 네이밍을 잘못한 것 같습니다.
`focusNextElement`, `focusPrevElement`로 수정했습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +const CardAddPage = () => {
`Form`보다 `Input`이 더 맞는 방향같습니다.
다음 step2에서는 하나의 `Form`안에 다섯 개의 'Input'을 주는 구조로 변경해보도록 하겠습니다!

2022-05-03 08:25 UTC, ronci commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +import useUserName from "../../hooks/useUserName";
노력하겠습니다! 😊

2022-05-03 11:18 UTC, ronci commented on react-payments/package.json
> +    "@testing-library/jest-dom": "^5.16.4",
일부 배포 스크립트가 동작하지 않을 수도 있기에 의도적으로 모든 패키지를 dependencies 에 넣었다고 하여 따로 위치를 변경하지 않았습니다!
https://github.com/facebook/create-react-app/issues/6180

2022-05-03 11:18 UTC, ronci commented on react-payments/package.json
> +    "react-scripts": "5.0.1",
위와 동일한 문제로 변경하지 않았습니다!

2022-05-03 11:18 UTC, ronci commented on react-payments/package.json
> +    "build-storybook": "build-storybook -s public",
cypress때도 `cypress:run` 형태로 사용했었던 것 같네요! 수정했습니다!

2022-05-03 11:18 UTC, ronci commented on react-payments/package.json
> +  "browserslist": {
browserslist를 이용하여 대응할 브라우저와 버전을 정할 수 있는 것으로 알고 있습니다!

2022-05-03 11:18 UTC, ronci commented on react-payments/public/manifest.json
> +{
Web App을 만들 때 사용되고 App에 대한 정보를 담고 있는 JSON 파일입니다.
배경색, 앱의 이름, 아이콘 등의 다양한 정보들이 있으며 PWA를 할 때 필수적으로 작성해야하는 것입니다.

2022-05-03 11:18 UTC, ronci commented on react-payments/src/component/Card/card.component.jsx
> +          <div className="small-card__chip"></div>
어떤 것을 말씀하시는 지 잘 이해를 못했습니다....
혹시 좀 더 자세히 알려주실 수 있으신가요??

2022-05-03 11:18 UTC, ronci commented on react-payments/src/component/Card/card.component.jsx
> +            {cardNumbers.map((cardNumber, idx) => {
저는 다음 로직이 html안에 있어도 괜찮다고 생각하여 다음과 같이 구현했습니다!
발리스타님은 어떻게 생각하시는 지 들어볼 수 있을까요?

2022-05-03 11:18 UTC, ronci commented on react-payments/src/component/Card/card.css
> +  transform: translate(0px, 5px);
0px에서 0으로 수정했습니다! 추가적으로 다른 css 파일에 있던 0px도 0으로 수정했습니다!
그저 지나쳤는데 이런게 모이면 큰 낭비가 될 수 있겠군요..!

2022-05-03 11:18 UTC, ronci commented on react-payments/src/component/Card/card.css
> +  background: #e5e5e5;
색상 값을 css 변수로 관리하도록 수정하였습니다!

2022-05-03 11:18 UTC, ronci commented on react-payments/src/component/ColorBox/colorBox.component.jsx
> +          currentCardType === cardInfos[idx].cardType ? "selected" : ""
`&&`을 사용하여 빈 공백을 제거하였습니다!

2022-05-03 11:18 UTC, ronci commented on react-payments/src/component/ColorBox/colorBox.component.jsx
> +        className={`${colorType} color-box `}
`${colorType} color-box_` 맨 뒤에 _ 공백 부분이 말씀하시는 것이 발리스타님께서 말씀하시는 빈공간 맞을까요??
color-box 뒤 공백은 제거했습니다!

`이럴 필요없이 해줄 수 있는건 없을까요?` 라는 말씀이 잘 이해가 안되는 데,
혹시 자세히 알려주실 수 있으신가요??

2022-05-03 11:19 UTC, ronci commented on react-payments/src/component/Form/form.component.jsx
> +const inputEnum = {
여러 상황에 따른 component를 구현하고 싶어서 조건부 렌더링을 검색하던 와중 enum을 이용한 방법을 찾게 되었습니다!
https://codingapple.com/unit/react-if-else-patterns-enum-switch-case/
return 내부에서 enum을 사용하면 좋지 못한 코드 같아서 밖으로 분리하려고 하다보니 함수가 된 것 같습니다.

inputEnum, labelEnum을 inputSelector, labelSelector로 네이밍 수정했습니다!

2022-05-03 11:19 UTC, ronci commented on react-payments/src/component/Form/form.component.jsx
> +        (props.ready ? (
TypeScript나 PropTypes를 사용해야하겠네요!
나중에 step3때 TypeScript로 구현한다고 하니 그 때 수정해봐야겠습니다.
추가적으로 props와 state가 많아지니 type관리에도 필요성이 많이 느껴지는 것 같습니다!

2022-05-03 11:19 UTC, ronci commented on react-payments/src/component/Input/input.component.jsx
> +    <div className={`input-box ${inputClass}`}>
이번에 구현해보면서 기본 css를 적용했을 때는 감이 잘 잡히지 않는 것 같습니다.
step2때는 styled-components를 적용해 보면서 좀 더 좋은 스타일로 만들어보겠습니다!

2022-05-03 11:19 UTC, ronci commented on react-payments/src/component/Input/input.css
> +  margin-top: 0.375rem;
주어진 마크업을 사용해서 rem이 사용된 지 몰랐었습니다.
추가적으로 찾아보니 

`em`과 `rem`은 상대 단위로
`em`의 경우 해당 단위가 사용되고 있는 요소의 font-size 속성 값이 기준이 되고,
`rem`은 브라우저에서 html 요소의 font-size 속성값이 기준이 된다고 합니다!

2022-05-03 11:19 UTC, ronci commented on react-payments/src/component/VirtualKeyboard/keyboard.component.jsx
> +const VirtualKeyboard = ({
arrow function은 function과 달리 arguments와 prototype 프로퍼티가 없습니다.
그래서 이를 사용하지 않을꺼면 arrow function을 사용하는 것이 더 좋다고 생각합니다!

2022-05-03 11:19 UTC, ronci commented on react-payments/src/component/VirtualKeyboard/keyboard.component.jsx
> +const getShuffleArray = () => {
렌더링 될 때 마다 가상 키보드의 숫자 순서를 바꿔주는 것이 가상 키보드의 동작이라고 생각했습니다.

그래서 함수는 렌더링 될 때마다 다시 선언되는 것을 막기위해 상단에서 선언하였고,
렌더링 될 때마다 함수를 사용하기 위해 하단에서 함수를 실행시켰습니다.

2022-05-03 11:19 UTC, ronci commented on react-payments/src/hooks/useCardNumber.jsx
> +  const { first, second, third, fourth } = cardNumber;
다른 방법을 찾아보기 위해 검색해보았으나,
앞의 8자리는 BIN이라고 명명되어있지만 그 뒤 번호들은 다른 이름이나 규칙이 없었습니다.
그래서 네이밍을 어떻게 해야할 지 몰라서 다음과 같은 네임으로 구현하였습니다.

혹시 발리스타님께 좋은 아이디어 하나 들을 수 있을까요??

2022-05-03 11:19 UTC, ronci commented on react-payments/src/hooks/useCanShowModal.jsx
> +const useCanShowModal = () => {
과도한 훅 분리였던 것 같습니다!
useReducer을 이용하여 한 줄로 수정할 수 있어서 cardAddPage에서 바로 사용할 수 있도록 수정하였습니다.

2022-05-03 11:19 UTC, ronci commented on react-payments/src/hooks/useCardNumber.jsx
> +const useCardNumber = () => {
훅 대신에 카드 넘버를 관리하는 컴포넌트를 만들고 이 로직들을 컴포넌트 안에 넣는 것으로 이해했습니다!
제가 이해한 방향이 맞을까요??

2022-05-03 11:19 UTC, ronci commented on react-payments/src/hooks/useCardPassword.jsx
> +const isInValidCardPassword = (cardPassword) =>
넵! validator.js로 분리해서 관리하도록 수정하였습니다!

2022-05-03 11:19 UTC, ronci commented on react-payments/src/hooks/useCardPassword.jsx
> +  checkReady();
cardPassword가 바뀔 때마다 호출 해 주었습니다!
현재는 checkReady 대신에 useEffect를 이용해서 다른 값들이 변할 때 ready를 수정할 수 있도록 수정했습니다!

2022-05-03 11:19 UTC, ronci commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +      <Form
넵 잘못 구현한 부분인 것 같습니다ㅠ
step2에 구조 변경하면서 수정하도록 하겠습니다!

2022-05-03 11:19 UTC, ronci commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +    <div className="card-add-page">
이 부분도 step2에 수정하도록 하겠습니다!

2022-05-03 11:19 UTC, ronci commented on react-payments/src/pages/CardAddPage/CardAddPage.component.jsx
> +            value: expireDate[0],
expireDate을 month와 year로 분리해서 관리하도록 변경하였습니다!

2022-05-03 11:33 UTC, ronci commented
소중한 피드백 감사합니다! 포코, 발리스타! 
피드백을 두 분에게 받게 되어서 코드에 대해 더 많이 생각해 볼 수 있었던 소중한 기회였던 것 같습니다!

피드백 주신 내용 중에 수정할 수 있는 부분은 수정하고 모르는 부분은 질문을 남겼습니다!

구조와 커스텀 훅 부분은 좀 더 고민이 필요한 것 같습니다!
또한 수정하기 시작하면 머지 권장 시간 또한 지키지 못할 것 같습니다.
그래서 아쉽지만 이 부분은 step2에 수정하여 제출하도록 하겠습니다!

2022-05-04 03:02 UTC, Vallista commented on react-payments/src/component/Card/card.component.jsx
> +            {cardNumbers.map((cardNumber, idx) => {
선언적인 코드라면, html에 있는게 맞고, 로직이 들어간다면 따로 빼는게 맞다고 생각합니다 :)

2022-05-04 03:02 UTC, Vallista commented on react-payments/src/component/ColorBox/colorBox.component.jsx
> +        className={`${colorType} color-box `}
className을 string 을 이용해 조합하고 하는 형태로 하고 있는데,
classNames 같은 라이브러리로 더 쉽게 사용할 수 없을까? 에 대한 질문이었습니다 :)

2022-05-04 03:05 UTC, Vallista commented on react-payments/src/hooks/useCardNumber.jsx
> +  const { first, second, third, fourth } = cardNumber;
서버나 로직 내부에서 데이터를 처리할땐 인풋을 4개로 나뉘어 표현하진 않을 것 같아요 :) 

이게 무슨말이냐면, 서버는 12자리 (아멕스는 11자리)를 받으려고 할텐데, 12자리를 4자리씩 띄워주는 것은 사용자에게 보여주기위한 필드일 뿐이지, 내부적인 처리는 12자리로 이루어져야 한다는게 제 의견입니다 :) 

사용자에게 보이는 성격의 부분은, 실제 데이터 12자리를 잘라서 보여주는 용도로만 쓰고,
실제 데이터 (cardNumber)는 데이터 하나로 있어도 충분하지 않을까 싶네요.

2022-05-04 03:06 UTC, Vallista commented on react-payments/src/hooks/useCardNumber.jsx
> +const useCardNumber = () => {
네네 그렇게 이해하셔도 좋고, 단지 훅으로 로직만 빼기보단 레이아웃도 공통화를 시킬 수 있겠다는 생각이 들어 말씀드렸습니다 :)

2022-05-04 03:07 UTC, Vallista commented
커밋이... 


@hwangstar156
[refactor: 1단계 첫번째 피드백 수정](https://github.com/woowacourse/react-payments/pull/105/commits/d35056f95d9aa18b9b65d7b095c674af0c3459e0)
[d35056f](https://github.com/woowacourse/react-payments/pull/105/commits/d35056f95d9aa18b9b65d7b095c674af0c3459e0)
@ronci
[refactor: 1단계 포코 피드백 추가 수정](https://github.com/woowacourse/react-payments/pull/105/commits/53bd2fcfd21a3791a33958ad23103570f28c172f) 
[53bd2fc](https://github.com/woowacourse/react-payments/pull/105/commits/53bd2fcfd21a3791a33958ad23103570f28c172f)
@ronci
[fix: index가 0일때 0이 렌더링되는 현상 수정](https://github.com/woowacourse/react-payments/pull/105/commits/822f8e40e13bfd4950d9beef6e0879c43c7ad864)
[822f8e4](https://github.com/woowacourse/react-payments/pull/105/commits/822f8e40e13bfd4950d9beef6e0879c43c7ad864)
@ronci
[refactor: 1단계 발리스타 피드백 추가 수정](https://github.com/woowacourse/react-payments/pull/105/commits/c2816383f7d7657efbd11c900b32082a2cf80e00) 
[c281638](https://github.com/woowacourse/react-payments/pull/105/commits/c2816383f7d7657efbd11c900b32082a2cf80e00)

조금 아쉽네요 ㅠㅠ

2022-05-04 03:09 UTC, Vallista approved these changes
안녕하세요 연지님~

빠르게 피드백을 적용해주셔서 감사합니다 :)
해당 부분 확인했고, 2단계에서 다시, 전반적으로 피드백 드리도록 하겠습니다

수고 많으셨어요~~

(p.s. 리펙토링 커밋, 피쳐단위로 쪼개주세요!)

2022-05-04 03:09 UTC, merged