[2단계 - 페이먼츠] 꼬재(고재증) 미션 제출합니다.
woowacourse/react-payments pull request #126
Opened 2022-05-07 22:13 UTC by kkojae91

안녕하세요! 오스틴님! 😁

이것 저것..! 만지고 지우고 하다보니..! PR이 조금 늦어진 점 정말 죄송합니다...!! 🥲

리액트에 조금은 적응했나...?! 싶다가도 코드를 보면 한숨이 많이 나왔던 것 같아요!
스토리북도 조금은 디벨롭을 했지만, 만족스럽지는 못한 것 같아요...!!
피드백 반영하면서 추가로 반영할 수 있는 부분들은 반영하도록 하겠습니다!

STEP1에서 useMemo를 사용한 부분을 우선 걷어내고, 성능을 생각하지 않고 코드를 작성했습니다! 
(이 부분도 추가로 학습하여 적용하도록 하겠습니다...!!) 
추가로 피드백 받았던 state를 배열 -> 객체로 관리하는게 조금 더 명시적으로 확인할 수 있는 부분이 있어 좋을 수 있다 말씀해주셔서 객체로 바꿔 미션을 진행해봤습니다.

### 데모 페이지: [DEMO](https://kkojae91.github.io/react-payments/)
### 스토리북 페이지: [STORYBOOK](https://6276e11a083636004a2a567a-myuxqxhjia.chromatic.com/?path=/story/addcard--add-card-template)

질문
---

#### 질문1
상황에 따라 css의 변화가 많은 경우 props가 많이...! 늘어나게됬습니다.
해당하는 부분을 객체로 묶어 props로 내려주면 조금은 더 깔끔하지 않을까 싶어 객체로 묶어 props로 내려줬는데..?!
조금 더 간편한 방법이 있을까요..?!
```js
const bigCardCss = {
  width: "293px",
  height: "183px",
  fontSize: "14px",
  cardContainerMarginBottom: "25px",
  cardChipWidth: "55px",
  cardChipHeight: "35px",
  cardNameMargin: "8px 0 30px",
  cardChipMarginBottom: "20px",
  cardNumberMarginBottom: "20px",
};
const smallCardCss = {
  // ...
}
```

#### 질문2.
contextAPI를 처음으로 사용해봤는데, 궁금한 점이 있습니다!
contextAPI를 사용하더라도?! state, actions를 사용하려던 컴포넌트의 부모에서 contextAPI로 state를 받아와 자식 컴포넌트에 props로 전달하는 방법을 택해도 되는건지..?! 궁금합니다.
미션 예)
초기 페이지(보유 카드 페이지)에서 localStorage에 저장된 값들을 불러와 렌더링을 해줄때 재활용하려는 컴포넌트(CardPreview)를 사용하려면 
 CardPreview에서 useContext를 사용하는 방법보다는 CardPreview 부모 컴포넌트에서 useContext를 사용한 후 필요한 state를 props로 내려주는게 조금 더 용이하다 판단했습니다. 오스틴님 생각은 어떠신지?! 궁금합니다..!!
```js
function CardPreview({ canProceed, cardCss, cardNumber, holderName, expireDate }) {
 // ...
}
```

시간도,, 실력도,, 부족해 여러모로 아쉬움이 가득한 미션이었던것 같습니다...!!!
STEP2 리뷰도 잘 부탁드리겠습니다!! 🙇🏻‍♂️

2022-05-09 10:40 UTC, austinpark420 requested changes
안녕하세요 꼬재!
step2 구현하시느라 고생 많으셨습니다 👍 
코드 관련해서 궁금한 부분 코멘트 남겨놨습니다 확인부탁드릴게요!!

### 질문1
상황에 따라 css의 변화가 많은 경우 props가 많이...! 늘어나게됬습니다.
해당하는 부분을 객체로 묶어 props로 내려주면 조금은 더 깔끔하지 않을까 싶어 객체로 묶어 props로 내려줬는데..?!
오스틴님의 경우 어떠한 방식을 택해 props로 내려주시는지 궁금합니다! :hushed:
> 저도 css뿐만 아니라 props값을 전달할 때, 코드가 길어지게되면 따로 객체로 묶어서 관리합니다. :smile:

### 질문2
contextAPI를 처음으로 사용해봤는데, 궁금한 점이 있습니다!
contextAPI를 사용하더라도?! state, actions를 사용하려던 컴포넌트의 부모에서 contextAPI로 state를 받아와 자식 컴포넌트에 props로 전달하는 방법을 택해도 되는건지..?! 궁금합니다.
미션 예)
초기 페이지(보유 카드 페이지)에서 localStorage에 저장된 값들을 불러와 렌더링을 해줄때 재활용하려는 컴포넌트(CardPreview)를 사용하려면
CardPreview에서 useContext를 사용하는 방법보다는 CardPreview 부모 컴포넌트에서 useContext를 사용한 후 필요한 state를 props로 내려주는게 조금 더 용이하다 판단했습니다. 오스틴님 생각은 어떠신지?! 궁금합니다..!! :hushed:
> 음.. 그렇게된다면 굳이 ContextAPI를 사용할 필요가 없어보입니다. 현재 프로젝트에서 depth가 깊지않아서 더 그렇게 생각하실 수도 있으실 것 같습니다. 다만 이번 미션에 요구조건에 ContextAPI를 사용해야하는 룰이 있었고 말씀하신대로 부모 컴포넌트에서 useContext를 설정하고 자식 컴포넌트에서 props가 아닌 Context으로 값을 받아오면 될 것 같습니다.

### 질문3
password, cvc 값들을 은닉하기 위해 state에 실제 비밀번호를 넣어주지 않고,
onChange를 통해 value의 valid를 확인후 state에 "*"값을 넣어줘 개발자 도구로 비밀번호를 확인하지 못하게 만들었습니다.
> 우선 값을 입력할 때 개발자도구에서 비밀번호가 보여도 크게 문제가 될것 같지는 않습니다. 인증과 보안에 대해서 학습해보시면 좋을것 같습니다. [참고블로그1](https://tansfil.tistory.com/58) [참고블로그2](https://www.palindrom615.dev/client-side-hashing-is-not-helping) 

비제어 컴포넌트의 경우 구글링을 해보면 ref를 사용하여 처리를 많이 하던데,
아래 예제 코드처럼 value만 관리하지 않더라도?! 비제어 컴포넌트라 할 수 있는지 궁금합니다..!! :hushed:
> 제어 컴포넌트와 비제어 컴포넌트는 value의 사용여부라기보다는 컴포넌트 역할이나 목적에 맞게 사용하시면 됩니다! [참고블로그](https://velog.io/@yukyung/React-%EC%A0%9C%EC%96%B4-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EC%99%80-%EB%B9%84%EC%A0%9C%EC%96%B4-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90-%ED%86%BA%EC%95%84%EB%B3%B4%EA%B8%B0)

2022-05-09 11:48 UTC, kkojae91 commented on src/components/AddCard/AddCard.jsx
> +        {isNextButtonClicked && <CardConfirmModal />}
카드 별칭을 작성하는 것 까지 카드 정보를 입력하는 하나의 과정으로 생각해서 Link로 페이지 이동을 하지 않고 modal 창으로 구현했습니다!

2022-05-09 11:49 UTC, kkojae91 commented on src/components/AddCard/CardSecurityCodeInput.jsx
> +export const SECURITY_CODE_DESCRIPTION =
엇.. 해당 부분은 파일에서 STEP1때 상수를 해당 파일에서 관리하자고 했었는데..!
constants 파일로 뺀다는 것을 깜빡하고 제거하지 못한 것 같습니다!
같은 파일에서 관리해주도록 하겠습니다!

2022-05-09 15:46 UTC, kkojae91 commented on src/App.jsx
> +          <Route path={ROUTES.POSSESS_CARD} element={<PossessCard />} />
"/"해당 path는 필요가 없겠군요...!
"/react-payments"와 "/react-payments/possess-card"를 두개 둔 이유는 처음 사이트에 접근한 home과 카드 등록을 마친 후 접근하는 path를 따로 뒀었습니다!

특정 사이트 이름은 생각나질 않지만...! 이렇게 path가 바뀌는 사이트를 본 것 같아 적용해봤습니다!
이 부분은 "/react-payments" path 하나로 통일해도 되는 부분일까요?! 😯

2022-05-09 15:49 UTC, kkojae91 commented on src/Hooks/useResetInput.jsx
> +import { useContext } from "react";
음 이부분은 reset 해주는 함수를 따로 분리하려다 보니, 커스텀 훅으로 분리했던 것 같습니다.

useInput에서 각각의 reset함수를 가져와 input들을 reset하는 것 보다 좋을 것 같다 판단했습니다!
오스틴님은 어떻게 생각하시나요?! 😯

2022-05-11 14:12 UTC, pocojang approved these changes
리뷰 요청 마감일이 지났기때문에 PR 머지하겠습니다
리뷰어와의 코멘트는 소통은 가능합니다.
이후 미션에 대한 완주 의지가 있다면 일단 장바구니 미션에 집중하시고 다음 스텝3에서 수행해주세요 :)

2022-05-11 14:12 UTC, merged

2022-05-30 03:49 UTC, kkojae91 commented on src/constants/initialState.js
> +    keyType: "firstCardNumber",
Object.keys(), Object.entries()를 사용하게 된다면 keyType을 대신할 수 있겠군요!!
말씀해주신 방향으로 수정했습니다.

근데 여기서 궁금한 점이 있습니다.
keyType을 사용하게 되면, map으로 컴포넌트를 생성할 때 곧바로 접근할 수 있는 이점이 존재하는 것 같은데, 객체 key로 접근해서 해당하는 key값을 설정해주는 것과의 어떤 차이가 있는지 말씀해주실 수 있을까요?! 😯

2022-05-30 03:49 UTC, kkojae91 commented on src/components/AddCard/AddCard.jsx
> +import { useState } from "react";
오스틴님이 말씀해주신 것 처럼 통일성을 주면 코드를 읽게되는 사람입장에서는
어떻게 진행될 지 예상할 수 있기 때문에 코드를 읽어 나가기 더 수월할 것 같네요!!

말씀해주신 방향으로 수정했습니다.

2022-05-30 03:49 UTC, kkojae91 commented on src/contexts/CardInfoContext.jsx
> +  };
해당하는 부분은 useReducer로 리팩터링 진행했습니다!

리팩터링을 진행하고 나니 useReducer의 역할을 useInput이라는 어설픈 훅을 만들어 사용했다는 생각이 들더라구요...!
의미 있는 리팩터링이였던 것 같습니다!

[커밋](https://github.com/kkojae91/react-payments/commit/cc7a120ea8355a0288b16f2f4abde37a4c3d40b4)

2022-05-30 03:52 UTC, kkojae91 commented on src/App.jsx
>  import GlobalStyle from "./globalStyles";
import 구문이 너무 길어지는 것 같아..보여..! 비슷해 보이는 컴포넌트 단위 package 단위 로 나눴는데,
다시 살펴 보니 의미가 명확하지 않는 것 같아 보이네요..! ㅠ

오스틴 님은 import 구문이 많아 질 경우 개행은 따로 진행하지 않으시나요?!
혹은 개행을 진행한다면 어떤 기준을 가지고 줄바꿈처리를 하는지 여쭤봐도 될까요?! 😯

2022-05-30 03:55 UTC, kkojae91 commented on src/components/AddCard/CardConfirmModal.jsx
> +import { useContext } from "react";
modal 디렉터리를 따로 관리해주는 방향이 한 번에 modal 컴포넌트를 찾을 수 있어 좋은 것 같아요!

[커밋](https://github.com/kkojae91/react-payments/commit/7a727e64c920d05e5835131c3a943df96fe0310b)

2022-05-30 03:57 UTC, kkojae91 commented on src/components/AddCard/CardInfoForm.jsx
> +  };
해당하는 부분은 useFormHandler 훅으로 분리하고,
onKeyDown event에서 모두 처리해주었습니다.

[커밋](https://github.com/kkojae91/react-payments/commit/eda575d333ffafe485a620b63f52829245efed8b)

2022-05-31 06:12 UTC, yongminpark420 commented on src/App.jsx
> +          <Route path={ROUTES.POSSESS_CARD} element={<PossessCard />} />
제 개인적인 생각이지만 다르게 만든 사이트는 사용자 로그수집을 위해서 그렇게 만든 것 같네요ㅎㅎ
위에 처럼 두개를 다르게 설정해야할 수 밖에 없는 이유가 있다면 그렇게하지만 그게 아니라면 하나로 통일해도 무방할 것 같습니다 😄

2022-05-31 06:16 UTC, yongminpark420 commented on src/Hooks/useResetInput.jsx
> +import { useContext } from "react";
제 개인적인 생각으로는 useInput안에서 input에 대한 핸들링을 모두하는 것이 좋다고 생각합니다! input을 핸들링하는데 관리포인트가 2개로 늘어난 느낌이네요 ㅠㅠ

2022-05-31 06:21 UTC, yongminpark420 commented on src/App.jsx
>  import GlobalStyle from "./globalStyles";
import가 많아지게되면 비슷한 개념끼리 묶고 개행을 합니다. 예를들어 외부라이브러리, 사내라이브러리, 커스텀훅 등으로 그룹핑을 합니다!

2022-05-31 06:28 UTC, austinpark420 commented on src/App.jsx
> +          <Route path={ROUTES.POSSESS_CARD} element={<PossessCard />} />
제 개인적인 생각이지만 다르게 만든 사이트는 사용자 로그수집을 위해서 그렇게 만든 것 같네요ㅎㅎ
위에 처럼 두개를 다르게 설정해야할 수 밖에 없는 이유가 있다면 그렇게하지만 그게 아니라면 하나로 통일해도 무방할 것 같습니다 😄

2022-05-31 06:28 UTC, austinpark420 commented on src/Hooks/useResetInput.jsx
> +import { useContext } from "react";
제 개인적인 생각으로는 useInput안에서 input에 대한 핸들링을 모두하는 것이 좋다고 생각합니다! input을 핸들링하는데 관리포인트가 2개로 늘어난 느낌이네요 ㅠㅠ

2022-05-31 06:29 UTC, austinpark420 commented on src/App.jsx
>  import GlobalStyle from "./globalStyles";
import가 많아지게되면 비슷한 개념끼리 묶고 개행을 합니다. 예를들어 외부라이브러리, 사내라이브러리, 커스텀훅 등으로 그룹핑을 합니다!

2022-05-31 06:54 UTC, austinpark420 commented on src/constants/initialState.js
> +    keyType: "firstCardNumber",
map을 사용해서 접근이 가능하긴하지만 keyType이 중복되는 값이기 때문에 Object.keys() 사용하는 편이 낫다고 생각했습니다!~