[2단계 - 페이먼츠] 도리(박선호) 미션 제출합니다.
woowacourse/react-payments pull request #130
Opened 2022-05-08 07:55 UTC by prefer2

안녕하세요 월터님! 즐거운 주말 보내고 계시길바래요 😆 2단계 제출합니다~

### [데모페이지](https://prefer2.github.io/react-payments/)
### [storybook](https://626b91d7e2fe43004ae0d268-wzlgptqbwn.chromatic.com/?path=/story/cvcfield--cvc)

## 1단계 수정사항
>inputInfo 을 배열을 받을 정도 큰 InputBox 가 필요한가라는 생각이 들긴해요. Input 컴포넌트를 여러 개 써도 크게 무방할 것 같고 필요하다면 데이터만 관련된 배열을 순회하면서 Input 반환하게 하면 되지 않나?라는 생각이 듭니다!

저도 다시 돌아보니 inputBox는 스타일링만 해줄뿐 큰 필요성이 없더라고요. 스타일컴포넌트로 감싸는 방식으로 변경했습니다!

- 1단계에서 구현하지 못했던 카드사 선택 모달을 추가했습니다. addPage에서 카드 모양을 클릭하면 카드사 선택 모달이 나타납니다. 카드사까지 선택해야 다음 페이지로 넘어갈 수 있도록했습니다.
- Autofocus 관련 로직과 localStorage 관련 로직을 커스텀훅으로 구현하였습니다. 분리를 하다보니 재사용이 가능하고 코드가 간결해졌습니다. 다른 곳에서도 커스텀 훅을 사용해보려 시도했는데 구현까지는 완성하지 못했습니다. 한 곳에서만 사용하게 되거나 너무 구현이 복잡해지더라고요. 월터님은 언제 커스텀훅을 작성하는지 재사용성이나 복잡도는 어느정도로 결정하는지 궁금합니다!
- 다양한 hook을 학습하고 사용해보려했습니다. useReduce, useMemo등을 사용해보고 학습하는데 의의를 두었습니다. useMemo도 사용해보고 싶었는데 아직 적절한 사용 위치를 못찾았네요. 보시면서 적절한 사용인지 더 학습해보면 좋을 부분 있으면 많은 피드백 주세요~~

## 2단계
- Context API를 사용해보았습니다. 카드 정보 상태를 관리합니다. 이번 미션에서 어디까지 context를 사용해야하나 고민했습니다. 카드 정보를 전부 넣게 되어 한 값만 바꿔도 모두 재렌더링이 되어 아쉽습니다.관련해서 좀 더 공부해보고 월터님 피드백 통해서 개선해보겠습니다.  context를 사용하다보니 너무 전역변수 느낌으로만 사용한 것 같습니다. 월터님는 언제 context를 어떻게 사용하는게 좋다고 느끼는지 궁금합니다!
- 카드들은 localstorage에 저장했습니다. 동일한 카드번호를 가진 카드는 등록이 불가능하도록 하였습니다. 메인페이지에서 등록한 카드를 누르면 닉네임 변경이 가능합니다.
- 미션 요구사항 중 제어/비제어 컴포넌트 사용해보기가 있어 어디에서 써볼까 고민을 했습니다. 따로 validation이 필요 없는 nickname input에서 사용할 수 있을 것 같아 nickname input을 비제어로 사용해보았습니다.

2022-05-09 14:10 UTC, inwalter99 commented
> Autofocus 관련 로직과 localStorage 관련 로직을 커스텀훅으로 구현하였습니다. 분리를 하다보니 재사용이 가능하고 코드가 간결해졌습니다. 다른 곳에서도 커스텀 훅을 사용해보려 시도했는데 구현까지는 완성하지 못했습니다. 한 곳에서만 사용하게 되거나 너무 구현이 복잡해지더라고요. 월터님은 언제 커스텀훅을 작성하는지 재사용성이나 복잡도는 어느정도로 결정하는지 궁금합니다!

커스텀훅으로 분리하는 건 재사용을 위한 것도 있지만, 로직이 복잡해져 추상화를 위함도 있습니다. 커스텀훅으로 분리하는 명확한 기준은 없지만, 보통 2-3개 이상 컴포넌트에서 로컬 상태를 갖고 동일한 로직을 수행한다면 커스텀 훅으로 분리하는 것 같네요. 코드가 길어져 가독성을 해치고 로직을 한눈에 파악하기 어려울 때도 커스텀훅으로 분리하기도 합니다;

2022-05-09 15:14 UTC, inwalter99 commented
> styled-component도 컴포넌트로 봐야하는 걸까요? 아니면 component를 style해준다고 이해해야할까요?

둘 다 아닐까요?ㅎㅎ styled-component 또는 css-in-js 가 나오게 된 배경을 이해해보면 좋을 것 같아요 https://velog.io/@teo/css-history-1 이 아티클 공유드립니다!

2022-05-09 15:16 UTC, inwalter99 requested changes
2단계도 수고많았습니다 도리, 코드 잘 봤어요.
특히 말씀주신 커스텀훅같은 부분을 신경써서 구현해주신 게 좋았고, context api 적용도 의도에 맞게 잘 된 것 같아요!

하나하나 코멘트를 달다보니 꽤 많아졌는데요 ㅜ 확인부탁드릴게요! 질문주신 부분들에 대해서도 코멘트 드렸는데 부족하거나 추가로 드는 궁금증 있으면 말씀주세요~!

2022-05-10 00:38 UTC, prefer2 commented on src/hooks/useAutoFocus.jsx
> +export default useAutoFocus
얼마든지요! 고민해서 만들어봤는데 기분 좋네요~~

2022-05-11 00:34 UTC, inwalter99 commented
안녕하세요! 
미션들이 점점 복잡해지고 어려워지죠?! 
일단 미션의 목적이 기능 구현이 아니라 **학습**을 하는 거니까, 너무 완성하는 데 부담감을 안느끼셨으면 좋겠습니다 :grinning:
아마 제가 드린 코멘트 `어차피 대부분 앞으로 다시 마주칠 문제들`이라 리뷰를 반드시 반영하지 않아도 좋아요! **(반영하지 마세요!! 쉬세요!! 제발~!)**
**대신 확인했다 정도와 여유가 있다면 입코딩 부탁드립니다!**

**진심입니다ㅋㅋ!** 말씀드렸던 것처럼 어차피 대부분 다시 마주칠 문제들이라 쉬는 게 더 중요하니까 확인 및 입코딩만 부탁드릴게요!
(쉬어서 다음 미션에 집중해서 얻는 이득 >>>>>>>>> 쉬지도 못하고 이전 미션에 얽매여 스트레스 받아서 해낸 이득)

2022-05-11 00:42 UTC, prefer2 commented on src/pages/CardAddCompletePage/index.jsx
> +    )
localStorage 관련은 커스텀 훅으로 분리해두었습니다! [8107403](https://github.com/woowacourse/react-payments/pull/130/commits/81074037e48fd1f21bc59c5a96ce17223ac7a332)

2022-05-11 00:57 UTC, prefer2 commented on src/pages/NickNamePage/index.jsx
> +  )
https://github.com/woowacourse/react-payments/pull/130#discussion_r867981675 path 상수화와 함께 수정했습니다 [1a2223e](https://github.com/woowacourse/react-payments/pull/130/commits/1a2223e06b79190e160056af7d200fb001656c2a)
해도해도 상수화는 맨날 까먹네요 🙃

2022-05-11 14:13 UTC, merged

2022-05-13 06:19 UTC, prefer2 commented on src/hooks/useAutoFocus.jsx
> +    if (target.value.length < maxLength) return
생각나는 방법은 maxLength를 배열로 받기 정도인 것 같아요. `const curIndex = refList.current.indexOf(target)`를 먼저 계산해서 인덱스 값을 계산해서 maxLength에서 이를 가져와 쓸 수 있을 것 같아 변경해보았습니다!

2022-05-13 08:01 UTC, prefer2 commented on src/components/AddCard/OwnerField/index.jsx
> +  }
네이밍에 대해 더 생각해보게 되네요! 고민 없이 네이밍을 지었던 것 같아요. 변경했습니다~

2022-05-14 09:29 UTC, inwalter99 commented on src/components/AddCard/OwnerField/index.jsx
> +  }
코멘트달면서 저도 반성합니다..ㅎ