[2단계 - 페이먼츠] 안(안수진) 미션 제출합니다.
woowacourse/react-payments pull request #145
Opened 2022-05-09 05:41 UTC by jin7969

안녕하세요 월터님 ~ 😄 리뷰신청이 늦었네요 ㅠㅠ ;;
아직 리액트에 대해 개념이 잡히지 않아 미숙하네요;;  리뷰 부탁드립니다!!

### [데모페이지](https://jin7969.github.io/react-payments/)                                                                                                                           

## 추가 사항
1. 카드사 modal을 이용하여 회사를 선택할 수 있습니다.
2. auto focus를 사용해서 자동으로 input focus가 이동됩니다.
3. 말씀해주신 절대경로는 적용해보았으나, 오류가 발생하여 반영 하지 못하였습니다. 다시 해결해보겠습니다!
4. 스토리북은 context api 오류가 생겨 구현하지 못하였습니다. 수정하겠습니다!

## 질문사항
- 현재 context api 에서 cards(배열) 상태를 가지고 있는데요. 일단 context api 를 이용하여 동작이 되도록 만들었는데.. 
아래의 코드와 같이 사용을 하는것에 대하여 월터님 의견이 궁금합니다.
```jsx
function CardsProvider({ children }) {
  const [cards, setCards] = useState([]);

  return <CardsContext.Provider value={{ cards, setCards }}>{children}</CardsContext.Provider>;
}

// cardForm이 전부 입력이 되면 useContext 배열에 추가 한다. ex) [ {카드1정보}, {카드2정보}, ...]
  const handleCardFormSubmit = () => {
    setCards((prevCards) => [...prevCards, card]);
    ...
  };
```
<br>

- 폴더안에 파일명을 어떻게 하시나요?

1. cardForm 폴더안에 CardForm.jsx 파일을 만든다.
2. cardForm 폴더안에 index.jsx 파일을 만든다.

2022-05-10 10:40 UTC, inwalter99 commented on src/App.jsx
> +          <Route exact path="/react-payments" element={<CardList />} />
이전에도 열심히 훈련(?)했던것처럼, path 명은 상수로 관리 부탁드립니다 :)

2022-05-10 10:40 UTC, inwalter99 commented on src/components/addCard/cardCompany/CardCompany.jsx
> +}
Quiz
```suggestion
function CardCompany({ handleCompany, company, theme }) {
  const handleClick = () => {
    handl
    eCompany(company, theme)
  }
  return (
    <div className="modal-item-container">
      <div className={`modal-item-dot bg-${theme}`} onClick={handleClick} />
      <span className="modal-item-name">{company}</span>
    </div>
  );
}
```

2022-05-10 10:45 UTC, inwalter99 commented
에고 리뷰 중간에 잘못눌렀네요! 아직 리뷰 중입니다!

2022-05-10 11:06 UTC, inwalter99 commented on src/components/cardList/CardList.jsx
> +        </>
https://reactjs.org/docs/lists-and-keys.html 한 번 읽고, 잘못된 점 찾아서 수정부탁드려요!

2022-05-10 11:07 UTC, inwalter99 requested changes

2022-05-10 11:07 UTC, inwalter99 commented on src/components/register/Register.jsx
> +      <Card card={cards[cards.length - 1]} />
심화 미션 중에 목록을 선택해서 카드 닉네임 수정하는 게 있을텐데요, 그걸 구현하지 않을 예정이라도 어느정도 고려해서 개발이 되면 좋겠습니다 :) 

물론 페이지를 다르게 하면 영향이 없을 수도 있겠죠!
그런데 만약 https://github.com/woowacourse/react-payments/pull/145/files#diff-d00b82332264d336086699f7def3312e7209886f75bd7335ac82c27b3db1dc4fR37 에서 추가된 카드가 가장 앞에 오게 변경된다면 어떨까요! 요기도 영향을 주겠군요..! 이 부분 잘 고려해서 개선 부탁드릴게요 :) 아마 https://github.com/woowacourse/react-payments/pull/145#discussion_r869089452 이거와도 밀접하게 연관되어있을 것 같습니다 :)

```jsx
// AS-IS
setCards((prevCards) => [...prevCards, card]);
// TO-BE
setCards((prevCards) => [card, ...prevCards]);

2022-05-10 11:11 UTC, inwalter99 requested changes
수고하셨습니다 안 :) 

리액트에 대해 미숙하다고 말씀해주셨는데, 사용하고 계신 부분들에 대해서는 꽤 이해도가 높은 것 같습니다! 저도 배운 점이 여럿 있습니다 🤓
그렇지만,,, 부족한 점이 많이 보이는 것도 사실인데요, 놓치고 계신 부분이나 잘못 사용하고 있는 부분들에 대해서 코멘트 드렸습니다! **혹시 추가로 기능 구현 중이라면, 제가 드린 코멘트 먼저 해결해보면 좋을 것 같아요!**

질문 주신 부분에 대해서는 따로 코멘트 드릴게요!! 이에 대해서 적극적인 피드백 부탁드릴게요~!
코멘트 해결하면서 이해가 안가는 부분이나 질문 있으면 리뷰 요청전에도 코멘트로 멘션걸어주세요ㅎㅎ

2022-05-10 11:17 UTC, inwalter99 commented
> 현재 context api 에서 cards(배열) 상태를 가지고 있는데요. 일단 context api 를 이용하여 동작이 되도록 만들었는데..
> 아래의 코드와 같이 사용을 하는것에 대하여 월터님 의견이 궁금합니다.

먼저 [context api 를 왜 사용하는 지](https://reactjs.org/docs/context.html#:~:text=Context%20provides%20a%20way%20to%20share%20values%20like%20these%20between%20components%20without%20having%20to%20explicitly%20pass%20a%20prop%20through%20every%20level%20of%20the%20tree.) 에 대해서 이해를 해보면 좋을 것 같습니다 :)
저는 context api 를 사용하는 가장 큰 이유는 props drilling 을 피하기 위해서 사용한다고 생각해요! `안`이 적용해준 코드는 context api 를 사용하긴 했는데, 기존에 props 를 넘기던 코드들이 그대로 존재해서 이 부분을 props 를 최대한 넘기지 않는 방향으로 수정해보면 좋을 것 같아요! (물로 지금 구조에서는 props drilling 이 깊지가 않아서 사실 수정할 필욘 없어보이나 학습을 위해서 수정해보면 좋겠어요!)

`안`이 적어준 코드에서 더 나아가서 setCards 같은 함수는 따로 넘기지 않고, Provider 에서 addCard, updateCard 같은 메서드를 만들어서 사용하게 할 수도 있고, 지금처럼 사용할 수도 있는데요 핵심은 [context api 를 왜 사용하는 지](https://reactjs.org/docs/context.html#:~:text=Context%20provides%20a%20way%20to%20share%20values%20like%20these%20between%20components%20without%20having%20to%20explicitly%20pass%20a%20prop%20through%20every%20level%20of%20the%20tree.)에 있다고 생각합니다 :)

2022-05-10 11:19 UTC, inwalter99 commented
> 폴더안에 파일명을 어떻게 하시나요?
> cardForm 폴더안에 CardForm.jsx 파일을 만든다.
> cardForm 폴더안에 index.jsx 파일을 만든다.

보통 `components/CardForm/index.jsx` 또는 `components/CardForm.jsx` 또는 다르게.. 로 갈리는 것 같아요!
사실 개인의 취향과 팀의 컨벤션에 따르는 것 같습니다! 저희 팀에선 따로 컨벤션이 크게 없어 혼재되어 있고, 개인적으론 후자의 경우 컴포넌트가 많아지면 너무 헷갈려져서 (+스토리, 테스트까지 하면..ㄷㄷ) 후자 `CardForm/index.jsx`를 선호합니다!

2022-05-10 11:23 UTC, inwalter99 commented
는 PR 프로세스가 좀 늦어졌군요 ;ㅁ; 최대한 되는대로 해주세요! ㅠㅠ

2022-05-11 00:35 UTC, inwalter99 commented
안녕하세요 안 :) 디엠 주셔서 답장드렸는데 추가로 코멘트 남겨요
일단 미션의 목적이 기능 구현이 아니라 **학습**을 하는 거니까, 너무 완성하는 데 부담감을 안느끼셨으면 좋겠습니다 :grinning:
아마 제가 드린 코멘트 `어차피 대부분 앞으로 다시 마주칠 문제들`이라 리뷰를 반드시 반영하지 않아도 좋아요! **(반영하지 마세요!! 쉬세요!! 제발~!)**
**대신 확인했다 정도와 여유가 있다면 입코딩 부탁드립니다!**

**진심입니다ㅋㅋ!** 말씀드렸던 것처럼 어차피 대부분 다시 마주칠 문제들이라 쉬는 게 더 중요하니까 확인 및 입코딩만 부탁드릴게요!
(쉬어서 다음 미션에 집중해서 얻는 이득 >>>>>>>>> 쉬지도 못하고 스트레스 받아서 해낸 이득)

2022-05-11 14:05 UTC, pocojang approved these changes
리뷰 요청 마감일이 지났기때문에 PR 머지하겠습니다
리뷰어와의 코멘트는 소통은 가능합니다.
이후 미션에 대한 완주 의지가 있다면 일단 장바구니 미션에 집중하시고 다음 스텝3에서 수행해주세요 :)

2022-05-11 14:05 UTC, merged

2022-05-11 17:01 UTC, jin7969 commented on src/components/addCard/cardCompany/CardCompany.jsx
> +}
고민해보겠습니다!!

2022-05-11 17:14 UTC, jin7969 commented on src/components/addCard/AddCard.jsx
> +  const handleCompany = (company, theme) => {
카드회사 이름과, 해당 회사의 배경색을 추가하는 기능이니깐,
addCompanyState 어떨까요??

2022-05-13 13:50 UTC, jin7969 commented on src/components/addCard/cardCompany/CardCompany.jsx
> +}
제 생각을 말씀드리면,
`onClick={() => handleCompany(company, theme)}` 콜백함수를 따로 선언하지 않고 바로 사용한 이유는
1. 단순히 handleCompany() 함수를 호출만 하기 때문에 굳이 따로 선언 할 필요가 없다고 생각하였습니다.
2. 비용적인 측면에서 아래와 같이 `useCallbaack` 을 사용하여도 어차피 함수를 선언하였고, useCallback 자체도 비용이 발생하기 때문에 성능상 비슷할 것이다! 생각 됩니다.
```js
const onClickCardCompany = useCallback(
 handleCompany(company, theme) ,
  []
)
```

월터님의 의견이 궁금합니다!! 🙏

2022-05-13 16:45 UTC, jin7969 commented on src/components/cardList/CardList.jsx
> +        </>
최상위 요소에 key값을 부여해야 하군요! 
아래와 같이 수정하였습니다.
```jsx
  {cards.map((card) => {
    const { id, category } = card;
    return (
      <React.Fragment key={id}>
        <Card card={card} />
        <span className="card-nickname">{category}</span>
      </React.Fragment>
    );
  })}
```

2022-05-13 17:30 UTC, jin7969 commented on src/components/register/Register.jsx
> +      <Card card={cards[cards.length - 1]} />
너무 좋은 의견이네요 😆
`navigate`에서 props로 register 페이지에 id값을 전달하고, `useLocation` 으로 id값을 받아서
그 id 값을 이용해서 해당 카드 정보를 랜더링 한다! 이 말씀 이신가요??

만약 제가 이해한게 맞다면 월터님이 말씀하신 변경사항이 생겼을 때, id값을 이용한다면, 로직을 변경할 필요가 없겠네요!!
감사합니다!! 🙏

2022-05-14 09:34 UTC, inwalter99 commented on src/components/addCard/AddCard.jsx
> +  const handleCompany = (company, theme) => {
저도 addCompany 같이 회사정보를 추가하는 뜻만 담기면 뭐든 좋을 것 같습니다 👍

2022-05-14 09:39 UTC, inwalter99 commented on src/components/addCard/cardCompany/CardCompany.jsx
> +}
`단순히 handleCompany() 함수를 호출만 하기 때문에 굳이 따로 선언 할 필요가 없기` 보다 아래와 같은 흐름으로 이어지면 좋을 것 같아요! (2번의 내용은 맞습니다)

인라인함수는 컴포넌트가 렌더링될 때마다 새롭게 생성 되므로
보통 핸들러를 따로 선언하고 메모이제이션을 통해 생성되는 비용을 줄이고자 합니다.
하지만 useCallback 으로 메모이제이션을 하더라도 지금 컴포넌트가 리렌더링이 되는 주기와 디펜던시가 걸릴 company, theme props 가 변경되는 주기 (메모이제이션이 새롭게 되는 주기)가 **동일하므로** 메모이제이션으로 얻는 이득이 전혀 없기 때문에 인라인 함수로 선언해도 문제없다..!

2022-05-15 05:51 UTC, jin7969 commented on src/components/addCard/cardCompany/CardCompany.jsx
> +}
와... 설명이 깔끔하네요 ㅠㅠ;
저도 렌더링과 메모이제이션에 대해서 더 공부하겠습니다 ㅎ