[1단계 - 페이먼츠 미션] 피터(안현철) 미션 제출합니다.
woowacourse/react-payments pull request #19
Opened 2021-04-30 06:59 UTC by iborymagic

안녕하세요! 
이번에 심바와 함께 페어 프로그래밍을 진행한 피터입니다.
리액트 페이먼츠 1단계 미션 PR 제출합니다.
Storybook도 그렇고 Styled Component도 이번에 처음으로 써봤는데, 
컴포넌트 주도 개발 과정이 굉장히 흥미로웠습니다. (물론, 옳게 한 건지는 의문이지만요..)
새삼스레 개발이 정말 재밌는거였구나 하고 느꼈던, 매우 신선한 경험이었습니다.

## 페이먼츠 기능 구현 모습
<img src="https://user-images.githubusercontent.com/42052110/116653538-5f25e280-a9c2-11eb-96bf-8f7e50053ece.gif" width="350" height="500" />

## ⚙ 기능 구현 목록
### 카드 목록 - default page
[ ] 보유 카드 목록을 볼 수 있어야한다.
    - 보유 카드 목록은 `Scroll` 방식으로 한다.
    - 최대 카드 갯수는 10개로 한다.
    - `Scroll` 바가 최상단 및 최하단 일 경우, `Scroll` 방향을 알려준다.
    - 보유 카드에는 카드 정보가 보인다.
[ ] `+` 버튼을 누르면 `카드 추가` 페이지로 이동한다.

### 카드 추가
[ ] 카드 정보를 입력할 수 있다.
    - 카드사 입력은 `카드 이미지`를 누르면 나오는 `Modal` 창에서 한다.
    - 잘못된 값을 입력하면 `input` 아래에 안내 문구가 나온다.
    - 카드번호 뒷 8자리, CVC 3자리, 카드 비밀번호 앞 2자리는 블라인드 처리가 된다.

    - 카드사 (카드 색상)
    - 카드번호
    - 만료일
        - `MM` 은 0부터 12까지이다.
        - `YY` 는 21부터 26까지이다.
        - 입력한 날짜가 오늘 날짜보다 커야한다.
    - 카드 소유자 이름
        - 카드 소유자 이름 입력은 선택이다.
        - 최대 글자 수는 30자이다.
    - CVC
    - 카드 비밀번호
[ ] `?` 을 누르면 CVC 설명이 나온다.
[ ] 카드 정보를 모두 입력하면 `다음` 버튼이 나온다.
[ ] `다음` 버튼을 누르면 `카드 추가 완료` 페이지가 나온다.
[ ] `<` 를 누르면 `카드 목록` 페이지로 돌아간다.

### 카드 추가 완료
[ ] `카드 추가`페이지에서 입력한 카드 정보가 보여진다.
[ ] 카드 이름을 입력할 수 있다.
    - 카드 이름은 중복일 수 없다,
[ ] `확인` 버튼을 부르면 `카드 목록` 페이지로 이동한다.
[ ] `카드 목록` 페이지에는 방금 등록한 카드가 보유 목록에 추가된다.

## 🗃 컴포넌트 설계도
![1](https://user-images.githubusercontent.com/42052110/116653664-a318e780-a9c2-11eb-8b43-0194a3cdd02c.PNG)
![2](https://user-images.githubusercontent.com/42052110/116653670-a57b4180-a9c2-11eb-8e20-441c27b07395.PNG)
![3](https://user-images.githubusercontent.com/42052110/116653677-a7450500-a9c2-11eb-8ccd-9afc222d5607.PNG)
![4](https://user-images.githubusercontent.com/42052110/116653680-aa3ff580-a9c2-11eb-8323-fc8b96f1eab1.PNG)
![5](https://user-images.githubusercontent.com/42052110/116653685-ac09b900-a9c2-11eb-9434-fc1cb21d283b.PNG)
![6](https://user-images.githubusercontent.com/42052110/116653690-add37c80-a9c2-11eb-8169-953782b488ec.PNG)
![7](https://user-images.githubusercontent.com/42052110/116653698-b035d680-a9c2-11eb-86e6-2acde8961cfa.PNG)

## 📁 폴더 구조
```
│  App.js
│  index.js
│  style.js
│
├─components
│  ├─assets
│  │      cvc.png
│  │
│  ├─Button
│  │  └─CardButton
│  │          CardButton.stories.js
│  │          index.js
│  │          style.js
│  │
│  ├─Card
│  │      Card.stories.js
│  │      index.js
│  │      style.js
│  │
│  ├─InputForm
│  │  ├─CardCreateForm
│  │  │      CardCreateForm.stories.js
│  │  │      index.js
│  │  │      style.js
│  │  │
│  │  ├─InputButton
│  │  │      index.js
│  │  │      InputButton.stories.js
│  │  │      style.js
│  │  │
│  │  ├─InputContainer
│  │  │  │  index.js
│  │  │  │  InputContainer.stories.js
│  │  │  │  style.js
│  │  │  │
│  │  │  ├─CvcInputContainer
│  │  │  │      index.js
│  │  │  │      style.js
│  │  │  │
│  │  │  ├─NickNameInputContainer
│  │  │  │      index.js
│  │  │  │      style.js
│  │  │  │
│  │  │  ├─NumbersInputContainer
│  │  │  │      index.js
│  │  │  │      style.js
│  │  │  │
│  │  │  ├─OwnerInputContainer
│  │  │  │      index.js
│  │  │  │      style.js
│  │  │  │
│  │  │  ├─PasswordInputContainer
│  │  │  │      index.js
│  │  │  │      style.js
│  │  │  │
│  │  │  ├─ValidDayInputContainer
│  │  │  │      index.js
│  │  │  │      style.js
│  │  │  │
│  │  │  └─ValidMessage
│  │  │          index.js
│  │  │          style.js
│  │  │
│  │  └─NickNameForm
│  │          index.js
│  │          NickNameForm.stories.js
│  │          style.js
│  │
│  ├─Modal
│  │  │  index.js
│  │  │  Modal.stories.js
│  │  │  style.js
│  │  │
│  │  └─ModalBody
│  │      └─CardCompanyList
│  │          │  CardCompanyList.stories.js
│  │          │  index.js
│  │          │  style.js
│  │          │
│  │          └─CardCompanyItem
│  │                  CardCompanyItem.stories.js
│  │                  index.js
│  │                  style.js
│  │
│  └─Page
│      │  index.js
│      │  Page.stories.js
│      │  style.js
│      │
│      ├─Body
│      │  ├─CardList
│      │  │  │  CardList.stories.js
│      │  │  │  index.js
│      │  │  │  style.js
│      │  │  │
│      │  │  └─CardItem
│      │  │          CardItem.stories.js
│      │  │          index.js
│      │  │          style.js
│      │  │
│      │  ├─CardRegister
│      │  │      CardRegister.stories.js
│      │  │      index.js
│      │  │      style.js
│      │  │
│      │  └─CardRegistered
│      │          CardRegistered.stories.js
│      │          index.js
│      │          style.js
│      │
│      └─Header
│              Header.stories.js
│              index.js
│              style.js
│
└─utils
        validators.js
```

## 🙄 느낀 점
1. 이번에 컴포넌트 주도 개발을 처음 해봤습니다. 
가장 작은 단위부터 컴포넌트로 차근차근 만들어가면서 마치 레고처럼 이리저리 조립하다보니 
점점 더 큰 컴포넌트가 되고, 앱이 완성되어가는 것을 보고 신기하다고 생각했습니다. 굉장히 신선한 재미가 있었습니다. 
특히 Styled Component와 Storybook을 처음 써봤는데, 사실상 개발 서버를 후반부에 로직을 짤 때만 썼다고 봐도 될 정도로 
적게 사용했던 것 같습니다. 물론 처음이다보니 컴포넌트들을 짜는 데에만 한세월이 걸렸지만 
컴포넌트를 다 짜고나니 기능 개발은 후루룩 되어서, 조금 더 익숙해진다면 효율적으로 개발할 수 있겠다는 생각이 들었습니다.

2. { ...props }와 children을 활용하니 훨씬 더 편하게 코딩을 할 수 있었던 것 같습니다. 
특히 InputContainer를 만들 때 컴포넌트들을 배열에 담아서 children으로 받아줬는데, 
올바른 사용 방법인지는 잘 모르겠지만 props가 길어지는 것을 막을 수 있어서 좋았던 것 같습니다.

## 🤔 궁금한 점
1. 제일 작은 컴포넌트들(button, input, ...)부터 시작해서 차근차근 쌓아올리는 방식으로 개발을 진행했습니다.
작은 컴포넌트들을 조립해서 큰 컴포넌트들을 만드는 과정에서 페어와 함께 재사용성에 대해서도 고민을 꽤 많이 했습니다.
처음 설계가 거의 그대로 반영된 코드라고 생각하는데, 재사용성을 고려해서 컴포넌트를 잘 나눴다고 봐도 될런지 궁금합니다.

2. 폴더 구조를 나누면서, 이정도면 체계적으로 잘 나눴다고 페어와 우스갯소리를 하기도 했는데,
생각보다 프로그래밍을 진행하면서 폴더 구조에 대해 의문을 느낀 적이 좀 있었던 것 같습니다.
저희는 Page라는 컴포넌트에 들어가는 'Body'를 갈아끼우는 방식으로 페이지 전환을 구현했습니다. 
그래서 Page 컴포넌트 안에 Body가 있고, 거기에 CardRegister가 끼워지고, 그 안에 CardCreateForm이 들어가고, 
거기에는 다수의 InputContainer가 들어있고, 그 InputContainer를 활용해서 NumberInputContainer를 만들고.. 
이런 식이다보니, Body에 문제가 생겨서 CardCreateForm에 가보면 사실은 거기가 아니고 CardRegister에 문제가 있었다던가, 
NumberInputContainer 문제인 줄 알고 거기로 갔는데 사실은 InputContainer 코드에 문제가 있었다던가 그런 식입니다.
이런 문제는 컴포넌트가 많아지면 불가피한 문제인지, 아니면 저희의 구조에 어떤 문제가 있는 것인지, 
해결하는 방법은 어떤 방법이 있을지가 궁금합니다.

3. 컴포넌트 관련 정보를 내려주고 싶을 때, 컴포넌트 자체를 통째로 상위에 만들어서 children으로 내려준다던가 하는 게 좋은지, 아니면 그냥 컴포넌트에 들어가는 정보들을 전부 props로 넘겨주는 게 좋은 지 모르겠습니다.
사실 당장 느끼기에는 컴포넌트를 상위에 만들어서 children으로 내려주는 것이 훨씬 깔끔한 것 같아서 그렇게 하고 있는데,
중간에 잠깐 고민했었던 기억이 떠올라서 여쭤보게 되었습니다!

4. validation 코드가 너무 길어져서 좀 고민이 됩니다. 
폼을 다루는 부분에 있어서 이번 미션도 그렇고, 이전 로또 미션에서도 굉장히 어려움을 느꼈는데 
최대한 사용자의 행동을 모두 대비한 validation 출력을 만들어보고 싶었기에(물론 잘 대비하지도 못했지만요..)
원래 폼을 다루는 코드가 이렇게 복잡하고 길어지는건지 궁금합니다.
리액트를 다루면서 다른 것들도 많이 어렵지만, 폼을 다루는 부분에 있어서 제일 고민이 많이 되는 것 같습니다.
원래 폼을 다루는 코드들이 이렇게 길어질 수밖에 없는지, 제어와 비제어 중 어떤 것을 선호하시는지 여쭤보고 싶습니다.
혹시 저희가 작성한 validation 코드를 보시고, 어떤 식으로 코드의 양을 줄일 수 있을지에 관해서 
말씀을 해주실 수 있으신지도 한 번 여쭤보고 싶습니다.
어떤 부분인지는 아래에 코멘트로 남겨놓겠습니다!

매번 피가되고 살이되는 리뷰로 저를 성장시켜주셔서 정말 감사드립니다!

2021-04-30 07:02 UTC, iborymagic commented on src/components/Page/Body/CardRegister/index.js
> +};
보시다시피, 카드 정보를 입력해서 카드를 생성하는 폼의 코드가 매우매우 깁니다..
blur 이벤트와 change 이벤트에 모두 대비하려다보니 코드가 너무 길어졌는데, 
혹시 코드를 효율적으로 줄일 수 있는 방법이 있을지에 관해 여쭤보고 싶습니다..

2021-04-30 12:23 UTC, JaeYeopHan requested changes
열심히 해주신 것 같아서 저도 리뷰를 열심히 해보려고 코멘트가 많아졌습니다.
다만 이 정도로 큰 사이즈의 PR에 props drilling 심해서 코드를 전부 다 세세하게 확인은 못했습니다 ㅠㅠ
props drilling을 어떻게 해소할 수 있을지 고민해보셔도 좋을 것 같아요! (redux 아님)

---

> 제일 작은 컴포넌트들(button, input, ...)부터 시작해서 차근차근 쌓아올리는 방식으로 개발을 진행했습니다. 작은 컴포넌트들을 조립해서 큰 컴포넌트들을 만드는 과정에서 페어와 함께 재사용성에 대해서도 고민을 꽤 많이 했습니다. 처음 설계가 거의 그대로 반영된 코드라고 생각하는데, 재사용성을 고려해서 컴포넌트를 잘 나눴다고 봐도 될런지 궁금합니다.

제 생각엔 재사용 가능한 컴포넌트가 거의 없다고 생각되는데요;;ㅎㅎㅎㅎㅎㅎ
자세한 내용은 코멘트에 남겨봤습니다~

> 폴더 구조를 나누면서, 이정도면 체계적으로 잘 나눴다고 페어와 우스갯소리를 하기도 했는데, 생각보다 프로그래밍을 진행하면서 폴더 구조에 대해 의문을 느낀 적이 좀 있었던 것 같습니다. 저희는 Page라는 컴포넌트에 들어가는 'Body'를 갈아끼우는 방식으로 페이지 전환을 구현했습니다. 그래서 Page 컴포넌트 안에 Body가 있고, 거기에 CardRegister가 끼워지고, 그 안에 CardCreateForm이 들어가고, 거기에는 다수의 InputContainer가 들어있고, 그 InputContainer를 활용해서 NumberInputContainer를 만들고.. 이런 식이다보니, Body에 문제가 생겨서 CardCreateForm에 가보면 사실은 거기가 아니고 CardRegister에 문제가 있었다던가, NumberInputContainer 문제인 줄 알고 거기로 갔는데 사실은 InputContainer 코드에 문제가 있었다던가 그런 식입니다. 이런 문제는 컴포넌트가 많아지면 불가피한 문제인지, 아니면 저희의 구조에 어떤 문제가 있는 것인지, 해결하는 방법은 어떤 방법이 있을지가 궁금합니다.

각 컴포넌트가 분리된 이유를 찾기 힘든 경우가 있었습니다. 컴포넌트를 역할에 따라 나눈다면 해결될 것 같습니다. (많아진다고 발생하는 문제는 아니라고 생각해요~)

> 컴포넌트 관련 정보를 내려주고 싶을 때, 컴포넌트 자체를 통째로 상위에 만들어서 children으로 내려준다던가 하는 게 좋은지, 아니면 그냥 컴포넌트에 들어가는 정보들을 전부 props로 넘겨주는 게 좋은 지 모르겠습니다. 사실 당장 느끼기에는 컴포넌트를 상위에 만들어서 children으로 내려주는 것이 훨씬 깔끔한 것 같아서 그렇게 하고 있는데, 중간에 잠깐 고민했었던 기억이 떠올라서 여쭤보게 되었습니다!

어떤 고민이 있었는지 좀 더 알려주셔야 할 것 같아요~ 그리고 상위에서 만든다는게 무슨 말인지 모르겠어요!

> validation 코드가 너무 길어져서 좀 고민이 됩니다. 폼을 다루는 부분에 있어서 이번 미션도 그렇고, 이전 로또 미션에서도 굉장히 어려움을 느꼈는데 최대한 사용자의 행동을 모두 대비한 validation 출력을 만들어보고 싶었기에(물론 잘 대비하지도 못했지만요..) 원래 폼을 다루는 코드가 이렇게 복잡하고 길어지는건지 궁금합니다. 리액트를 다루면서 다른 것들도 많이 어렵지만, 폼을 다루는 부분에 있어서 제일 고민이 많이 되는 것 같습니다. 원래 폼을 다루는 코드들이 이렇게 길어질 수밖에 없는지, 폼을 다룰 때 제어와 비제어 중 어떤 것을 선호하시는지도 여쭤보고 싶습니다. 더불어, 혹시 저희가 작성한 validation 코드를 보시고, 어떤 식으로 코드의 양을 줄일 수 있을지에 관해서 말씀을 해주실 수 있으신지도 한 번 여쭤보고 싶습니다. 어떤 부분인지는 아래에 코멘트로 남겨놓겠습니다!

폼은 정말 어려운 문제입니다 ㅠㅠ 다만 모든 상태를 한 곳에서 관리하다보니 모든 validate가 한 곳에서 이뤄지게 되었는데 이것을 책임에 따라 분리해보면 좋을 것 같습니다.
(이렇게 하고 나면 각각의 state에 어떻게 접근하지? 라는 의문이 생기실텐데, 여러 practice가 있으니 살펴보고 장단점을 비교하여 문제를 해결해보셔도 좋을 것 같아요~)

저는 비제어 (uncontrolled)를 선호하며 상황에 따라서 복잡한 것은 controlled로 만들어 추상화시킨 후 uncontrolled로 사용합니다. ㅎㅎㅎ

2021-04-30 12:23 UTC, JaeYeopHan commented on src/components/Modal/ModalBody/CardCompanyList/index.js
> +  const cardCompanies = [
컴포넌트 안에 있어야 할 필요가 없어 보여요~

2021-04-30 12:23 UTC, JaeYeopHan commented on src/components/Page/Body/CardList/CardItem/index.js
> +        />
```suggestion
export const CardItem = ({ card: { nickName, ...cardProps }) => {
  return (
    <>
      <Styled.Container>
        <Card
          size={'small'}
          {...cardProps}
        />
```

불필요한 destructuring을 이렇게도 줄여볼 수 있을 것 같네요

2021-04-30 12:23 UTC, JaeYeopHan commented on src/components/Page/Body/CardList/CardItem/index.js
> +        />
하지만 이렇게 하기 전에 props drilling이 발생하고 있는 이 상황이 정상인가 먼저 고민해보셔야 할 것 같아요~

2021-04-30 12:23 UTC, JaeYeopHan commented on src/components/InputForm/InputContainer/OwnerInputContainer/style.js
> +  type: 'text',
type은 style이 아니라고 생각합니다! (다른 부분의 코멘트와 비슷한 맥락)

2021-04-30 12:23 UTC, JaeYeopHan commented on src/components/InputForm/InputContainer/ValidDayInputContainer/index.js
> +    <Styled.Container onBlur={handleBlur} isValid={isValid}>
div에서 onBlur는 언제 발생하나요?

2021-04-30 12:23 UTC, JaeYeopHan commented on src/components/Card/index.js
> +            <Styled.Numbers size={size}>{numbers.first && numbers.first}</Styled.Numbers>
`numbers.first && numbers.first` 이건 어떤 의미인가요?

2021-05-03 08:12 UTC, iborymagic commented on src/components/InputForm/InputContainer/ValidDayInputContainer/index.js
> +    <Styled.Container onBlur={handleBlur} isValid={isValid}>
요건 각 input에 onBlur를 걸어주는 것보다 컨테이너에 이벤트 위임을 해주는 게 낫지 않을까 싶어서 그렇게 했습니당

2021-05-03 08:49 UTC, iborymagic commented on src/components/Card/index.js
> +            <Styled.Numbers size={size}>{numbers.first && numbers.first}</Styled.Numbers>
JSX에서는 undefined, null, false 등을 렌더링하면 아무것도 나타나지 않는다는 사실을 어렴풋하게만 알고 있었는데,
이번 기회에 확실히 알고 가네요. 바로 수정했습니다.

2021-05-03 17:57 UTC, iborymagic commented on src/components/Page/style.js
> +  width: 25.9rem;
요거는 figma에서 width로 지정되있던 값을 rem 단위로 변환한 값입니닷

2021-05-03 18:30 UTC, iborymagic commented on src/components/Button/CardButton/style.js
> +  justify-content: center;
해당 스타일들을 모아서 별도의 styled component로 분리해놓고 해당 컴포넌트를 확장해서 사용하도록 했습니당

2021-05-09 14:04 UTC, JaeYeopHan approved these changes
리뷰요청을 다시 주시지 않으셨고, 아직 리뷰들도 다 반영되지 않은 것 같지만 어느 정도 반영된 것 같아 남은 리뷰들은 2단계에서 고려해보면 어떨까 싶습니다

2021-05-09 14:04 UTC, merged