[페이먼츠 미션 Step 1] 슬링키(임우찬) 미션 제출합니다.
woowacourse/react-payments pull request #190
Opened 2023-04-20 07:43 UTC by dladncks1217

작성중

2023-04-22 12:27 UTC, devhyun637 requested changes
안녕하세요 슬링키~ 티케입니다!
리액트 프로젝트를 제대로 시작해본 소감이 어떠신가요?

리뷰를 줄여보려고 매우 열심히 노력을 해보았지만,, 실무에서 사용하다보니 회사에서 코드리뷰를 하는 것 만큼 꼼꼼하게 보고싶은 욕심에 리뷰 수가 조금 많습니다..! 개중에는 몇 번의 리뷰 핑퐁을 통해서 나중에 할 수 있는 부분은 지웠는데, 당장에 적용하기 어렵거나 제가 `(선택)`이라고 한 부분에 대해서는 이모지만 남기고 넘어가셔도 좋습니다. 

```
첫번째 리뷰: UX, 전체적인 코드, 컴포넌트에 대한 리뷰
두번째 리뷰: 스토리북에 대한 리뷰
```
이런식으로 Step1에 대한 리뷰를 남기려고 하기 때문에 이번에는 스토리북에 대한 리뷰는 남기지 않았어요~ 참고해주세요 :)

### 전체적인 피드백
1.  `CRA`를 통해서 프로젝트 설정을 하는 것이 두번째라고 알고 있는데, `Create-React-App`란 어떤 기능을 제공해주고 있고, 어떤 단점들이 있을까요? 이런 부분들을 하나씩 공부해가면 좋을 것 같아요. 현재 프로젝트에서는 필요없는 부분도 많아 삭제가 필요한 파일들이 몇개 보이네요. 또, 새로운 리액트 공식문서에서는 더이상 CRA에 대한 설명이 없어졌어요! 트렌드가 변화하고 있다는 걸 의미하기도 하죠. 아래 달라진 두 공식문서를 시간날때 살펴보세요~

- 예전 리액트 문서: https://ko.legacy.reactjs.org/docs/create-a-new-react-app.html
- 최신 리액트 문서: https://react.dev/learn/start-a-new-react-project

2. 파일의 `import` 순서도 한번 고려해볼까요? eslint, prettier로도 관리를 할 수 있는데, 이건 당장에는 어려울테니 슬링키만의 컨벤션을 가지고 정리해보면 좋을 것 같아요.

3. 코드들의 개행에 대한 일관성이 없고, 전체적으로 가독성이 안좋습니다. 개행만 해줘도 가독성이 훨씬 올라갈 수 있는데 한번 본인의 코드를 보면서 전체적으로 가독성을 높일 수 있는 방법에 대해서 고민해보는건 어떨까요?

---

### 질문 & 답변
> Q. 수업에서 배운 내용으로는 컴포넌트 주도 개발은 컴포넌트 단위로 빠른 피드백을 받는 것이 목적이라고 배웠습니다. 그래서 저는 스토리북을 통해 자신이 개발한 컴포넌트를 빠르게 시각적으로 보고 테스트할 수 있다는 점이 그렇다고 생각하는데, 제가 생각하는 방향이 맞을까요?

CDD에 대한 생각이 맞는지 여쭤보신 걸까요? 아니면 스토리북에 대한 생각을 여쭤보신걸까요?
일단, 스토리북은 컴포넌트를 빠르게 시각적으로 보고 테스트할 수 있다는 장점을 가지고 있는 것은 맞습니다. 여러가지 다른 기능들도 사용해 볼 수 있구요. 그리고 CDD를 해서 컴포넌트 단위로 빠른 피드백을 받을 수 있는건 맞지만, 그게 컴포넌트 주도 개발의 목적이라고 보기엔 부족할 것 같아요. 
컴포넌트 단위로 개발을 하면 어떤 점이 좋을까요? 그렇다면 어떤 컴포넌트를 개발해야할까요? 컴포넌트를 개발해서 컴포넌트 단위로 빠른 피드백을 받으면 어떤 좋은 점이 있을까요? 이런 질문들을 가지고 CDD에 대해서 좀 더 고민해보면 좋을 것 같아요~

> Q. 처음에 input 태그를 만들 때 value나 onChange등 몇개의 prop만 필요할 줄 알았는데, 앱이 점점 커지면서 필요한 props도 많아지게 되었습니다. props가 기존에 설계했던 것보다 많이 늘어난 것 같아 잘못 설계한게 아닌가 하는 생각이 들었습니다🥲 이건 제 코드 구조 문제인지, 어쩔 수 없는 부분인 것일지 궁금합니다!

`React`의 `HTMLAttributes`를 공부하시면 도움이 좀 될 것 같아요~

2023-04-22 12:33 UTC, devhyun637 reviewed
아 제출 눌러버려서 UX에 대한 피드백 이어서 남기겠습니다 :)

2023-04-23 14:49 UTC, dladncks1217 reviewed
정말 꼼꼼한 리뷰 감사드립니다 티케!
남겨주신 리뷰 반영하면서 새롭게 알게 된 내용도 많았고, 코드 보면서 '왜 이랬지...' 하며 부끄러움도 많이 느꼈던 것 같습니다.
코드를 이렇게까지 꼼꼼하게 리뷰해주시기 쉽지 않을 것 같은데, 리뷰이로서 감동이었습니다.🥺

리뷰 남겨주신 내용들 모두 반영해보았고, UI/UX에 관한 피드백들도 반영해보았습니다!

2023-04-23 14:49 UTC, dladncks1217 commented on src/components/InputCardData.tsx
> +  Ref,
우선 refObject로 한번 수정해보겠습니다!

2023-04-25 19:55 UTC, devhyun637 approved these changes
안녕하세요 슬링키~ 티케입니다!
피드백이 많았는데 전부 적용하고 또 공부하느라 고생많으셨습니다 👏👏 하나를 알려드리면 열을 아는 분이신 것 같네용! 저도 리뷰어로써 기분이 좋네용 ✨🫶 원래 스토리북 리뷰를 해보려고 했는데, 이번에는 UI 랜더링이 학습목표였어서 별로 리뷰할 게 없더라구요! Step2에서 스토리북 고도화가 되면 좀 더 리뷰를 남겨보겠습니다~ 

### 질문
1. 여러 컴포넌트들 중 소수만 스토리북으로 만들었는데, 어떤 기준으로 선택한 건지 알 수 있을까요?

2023-04-25 19:55 UTC, devhyun637 commented on src/stories/InputCardData.stories.ts
> +};
Step2에서 잘 챙겨주시겠죠?.?

2023-04-25 19:55 UTC, devhyun637 commented on public/index.html
아직 `lang`이 `en`이네용!

2023-04-25 19:55 UTC, devhyun637 commented on src/components/Card.css
> +}
어느정도 글자가 넘어가면 글자를 작게 하는 방법도 있고, 실제 어플리케이션에서는 어떻게 보여주는지 참고해서 구현하면 도움이 될 것 같아요~

2023-04-25 19:55 UTC, devhyun637 commented on src/components/InputCardPassword.tsx
> +const InputCardPassword = ({
삼항이 아닌 `<input>` 안의 속성에 조건문을 통해서 만들어볼수도 있을 것 같아요~

2023-04-25 19:55 UTC, devhyun637 commented on src/utils/util.ts
> +  }
```tsx
{inputError ? <span className="expired-error">만료일이 초과된 카드입니다!</span> : ''}
```
친절한 메세지 좋네요! 다만 다른 오류가 났을때는 어떻게 처리할지 좋을지 고민해보면서 유연한 코드를 만들어보면 좋을 것 같습니다~

2023-04-25 19:55 UTC, devhyun637 commented on src/utils/util.ts
> +  if (expireDate.length > 1 && !MONTH_DATA.includes(`${expireDate[0]}${expireDate[1]}`)) return '';
밑에서 어차피 걸러지기 때문에 위 코드가 필요없을거라고 생각했는데, 이건 좀 더 보고 Step2에서 다시 피드백드릴게용!

2023-04-25 19:55 UTC, devhyun637 commented on src/hooks/useInput.ts
> +  formatCallback: (data: string) => string
> 조건에 맞도록 검사하는 콜백

네이밍이 `check-` 로 시작해도 좋을 것 같아요!

++ `nextCallback`이 쓰이지 않네용~

2023-04-25 19:55 UTC, devhyun637 commented on src/utils/fetchData.ts
> +export const fetchData = (data: Omit<CardType, 'id'>): boolean => {
오 이부분도 Step2에서 다시한번 보면 좋을 것 같아요.
안에 있는 함수들이 fetch말고도 다른 일을 하는 것 같아서 더 분리를 해보는 건 어떨까요?

2023-04-25 19:55 UTC, merged