[1단계 - 페이먼츠 미션] 인치(한창희) 미션 제출합니다.
woowacourse/react-payments pull request #20
Opened 2021-05-01 04:31 UTC by hchayan

페이먼츠 미션 1단계 제출합니다...!
잘부탁드립니다 😆

## 🖥 [데모페이지](https://gallant-benz-da6e7c.netlify.app/)
![페이먼츠](https://user-images.githubusercontent.com/11311739/116769832-13cf0b00-aa7a-11eb-8774-aa406fc8ecdb.gif)

## 🎯 Step1 요구사항
#### 카드 추가 구현

- [x] 카드 추가 컴포넌트가 렌더링됨과 동시에 카드 종류 선택 모달이 보여진다.
- [x] **카드 추가** 라는 문구가 상단에 위치해야한다.
- [x] 아래 폼에 작성하는 내용이 카드 미리보기에 실시간으로 보여진다.
- [x] 카드 미리보기를 클릭하면 카드 종류 선택 모달이 보여진다.
- [x] 카드 종류를 선택하면 모달이 닫힌다.
- [x] 현재 입력 input 배경 색이 있다.(focus)

1. **카드 번호 입력**
   - [x] 카드번호 숫자 16자리중 뒤의 8자리는 `•` 로 숨김처리 된다.
   - [x] 카드번호 4자리마다 `-` 가 자동으로 보여진다.

2. **만료일 입력**
   - [x] 만료일 숫자는 4자리 입력 가능하다.

3. **카드 소유자 이름 입력**
   - [x] 카드 소유자 이름은 입력하지 않아도 된다.
   - [x] 카드 소유자 이름은 `String`이어야 한다.

4. **보안 코드 입력**

   - [x] 보안 코드 숫자는 3자리 입력 가능하다.
   - [x] 보안 코드 입력 칸 오른쪽에 물음표 버튼이 있다.
   - [x] 물음표 버튼을 누르면 CVC 코드설명 모달이 보여진다.
   - [x] CVC 모달은 화면 아래에 뜬다.
   - [x] CVC 모달에는 보안카드 설명 이미지가 있다.
   - [x] CVC 모달의 확인버튼을 누르면 모달이 닫힌다.

5. **카드 비밀번호 입력**
   - [x] 카드 비밀번호 입력칸 하나에는 0~9 사이의 숫자가 들어간다.
   - [x] 위의 입력 form이 다 입력되어야 다음버튼이 활성화 된다.
   - [x] 다음버튼을 누르면 카드추가완료 컴포넌트가 렌더링된다.

#### 다음 버튼을 누르면 입력값 유효성 검증을 수행한다.

- [x] 유효성 검증을 실패하면, 가장 먼저 에러가 발생한 입력칸에 붉은 테두리와 함께 바로 아래에 에러메세지가 뜬다.
- **카드번호를 덜 입력하셨어요! :(**
  - [x] 카드번호는 16자리를 입력해야한다.
  - [x] 카드번호는 `Number`이어야한다.
- **유효한 연월이 아니에요. :(**
  - [x] 월은 01 ~ 12 사이의 숫자만 허용된다.
- **만료일이 정확하지 않아요. :(**
  - [x] 오늘 연월보다 유효한 이후 연월이여야 한다.
- **이름에 특수문자, 숫자, 30글자 이상의 글자는 작성할 수 없어요. :(**
  - [x] 카드 소유자 이름은 30글자 이하여야 한다.
- **CVC 코드를 덜 입력하셨어요! :(**
  - [x] CVC 번호는 3자리 입력해야한다.
  - [x] CVC 번호는 `Number`이어야한다.
- **카드 비밀번호를 덜 입력하셨어요! :(**
  - [x] 카드 비밀번호는 `Number`이어야한다.
  - [x] 카드 비밀번호는 input 당 한자리 숫자여야 한다.

#### 카드추가 완료 구현

- [x] 앞서 만든 카드에 대한 미리보기가 보여진다.
- [x] 카드 이름을 등록할 수 있다.
- [x] 카드 이름이 비어져있으면 확인버튼 활성화되지 않는다.

## 🛠 디렉터리 구조
```
📦src
 ┣ 📂assets
 ┃ ┗ 📜cvv-300x300.png
 ┣ 📂common
 ┃ ┣ 📜Button.js
 ┃ ┣ 📜Button.stories.js
 ┃ ┣ 📜Card.js
 ┃ ┣ 📜Card.stories.js
 ┃ ┣ 📜Input.js
 ┃ ┣ 📜Input.stories.js
 ┃ ┣ 📜Modal.js
 ┃ ┗ 📜Modal.stories.js
 ┣ 📂components
 ┃ ┣ 📂CardAdditionComplete
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┗ 📜index.styles.js
 ┃ ┣ 📂mixin
 ┃ ┃ ┣ 📂ButtonMenu
 ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┃ ┗ 📂Nav
 ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┣ 📂ModalContents
 ┃ ┃ ┣ 📂CardColor
 ┃ ┃ ┃ ┣ 📂CardColorItem
 ┃ ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┃ ┗ 📂CVCHelp
 ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┗ 📂NewCardForm
 ┃ ┃ ┣ 📂CardCVCInput
 ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┃ ┣ 📂CardExpireDateInput
 ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┃ ┣ 📂CardNumberInput
 ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┃ ┣ 📂CardPasswordInput
 ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┃ ┣ 📂CardUserInput
 ┃ ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┃ ┗ 📜index.styles.js
 ┃ ┃ ┣ 📜cardFormValidator.js
 ┃ ┃ ┣ 📜index.js
 ┃ ┃ ┗ 📜index.styles.js
 ┣ 📂constants
 ┃ ┗ 📜constant.js
 ┣ 📂utils
 ┃ ┗ 📜util.js
 ┣ 📂__snapshots__
 ┃ ┗ 📜storybook.test.js.snap
 ┣ 📜App.js
 ┣ 📜App.styles.js
 ┣ 📜global.styles.js
 ┣ 📜index.js
 ┗ 📜storybook.test.js
```

## 😥 고민되는 부분
### 1. 제어 컴포넌트와 비제어 컴포넌트 사이에서의 갈등
처음엔 source of truth를 위해 제어 컴포넌트 방식으로 newCardForm을 구현해나가기 시작했습니다.
하지만 프로젝트를 진행하면서,
하나의 input에서 뒷 8자리를 password 처리하거나,
input 채워졌을때 다음 input으로 autoFocusing 되거나 하는 기능들을 구현하려면
결국, ref를 이용한 비제어 컴포넌트 방식이 아니면 구현이 거의 불가능했습니다.
그래서 이미 제어 컴포넌트로 구현한 상태에서, 위와 같은 기능들을 위해 ref도 붙여두면
결국 두가지 방식을 동시에 사용하는거 같아, 제어 컴포넌트 방식으로만 구현했는데
이런경우 애초에 source of truth를 개발자에게 어느정도 맡기고 비제어 방식으로 아예 넘어가야 될거같은데
아니면 두가지 방법을 혼용해서 쓰는 실 사례도 많은지, 아니면 지양해야하는지 고민됩니다.

### 2. 색상 및 폰트 상수화에 대해
처음엔 그렇게 제어할게 많지 않을줄 알고, 자주사용할 것 같은 css 상수 값을 상수화 해놓고 사용했으나
요구사항에서 필요한 색상 및 폰트 들이 점차 다양화되고 커져서 결국 비효율적이게 되고, 또 근처 파일에 있지도 않아
괜히 사용했다라는 생각이 들었습니다.
물론 이번 미션 요구사항이 일관성이 부족했긴 했지만 YAGNI 법칙을 지키면서 했어야 했는지 잘못된 선택이였던것 같습니다.
그런데 실제 현업에서 웹디들이 이런 규칙들을 미리 정해놓고 사용하라고 하는 케이스가 많은지가 궁금합니다.

2021-05-01 07:08 UTC, JaeYeopHan requested changes
수고하셨습니다!

css-in-js에서 classname을 통한 스타일링을 해주셨는데, 이렇게 적용하게 된 계기가 궁금하네요 ㅎㅎ

---

> 1. 제어 컴포넌트와 비제어 컴포넌트 사이에서의 갈등
처음엔 source of truth를 위해 제어 컴포넌트 방식으로 newCardForm을 구현해나가기 시작했습니다.
하지만 프로젝트를 진행하면서,
하나의 input에서 뒷 8자리를 password 처리하거나,
input 채워졌을때 다음 input으로 autoFocusing 되거나 하는 기능들을 구현하려면
결국, ref를 이용한 비제어 컴포넌트 방식이 아니면 구현이 거의 불가능했습니다.
그래서 이미 제어 컴포넌트로 구현한 상태에서, 위와 같은 기능들을 위해 ref도 붙여두면
결국 두가지 방식을 동시에 사용하는거 같아, 제어 컴포넌트 방식으로만 구현했는데
이런경우 애초에 source of truth를 개발자에게 어느정도 맡기고 비제어 방식으로 아예 넘어가야 될거같은데
아니면 두가지 방법을 혼용해서 쓰는 실 사례도 많은지, 아니면 지양해야하는지 고민됩니다.

전 프런트엔드 개발에서 어렵다고 할 수 있는 부분이 비동기 그리고 폼이라고 생각해요
상황에 맞는 방법을 사용하는 것이 중요하다고 생각합니다. 내부적으로는 controlled 방식이지만 외부에 공개하는 인터페이스는 uncontrolled로 하는 등 조합하여 사용해도 문제가 된다고 생각하지 않습니다 ㅎㅎ
말씀해주신 single source of truth를 잘 지키면서 인터페이스를 설계해보세요!

> 2. 색상 및 폰트 상수화에 대해
처음엔 그렇게 제어할게 많지 않을줄 알고, 자주사용할 것 같은 css 상수 값을 상수화 해놓고 사용했으나
요구사항에서 필요한 색상 및 폰트 들이 점차 다양화되고 커져서 결국 비효율적이게 되고, 또 근처 파일에 있지도 않아 괜히 사용했다라는 생각이 들었습니다. 물론 이번 미션 요구사항이 일관성이 부족했긴 했지만 YAGNI 법칙을 지키면서 했어야 했는지 잘못된 선택이였던것 같습니다. 그런데 실제 현업에서 웹디들이 이런 규칙들을 미리 정해놓고 사용하라고 하는 케이스가 많은지가 궁금합니다.

1. '웹디'가 뭔가요?
2. color code, typography 등 정해진 규칙 기반하에 적용합니다. 코드 상에서도 상수화는 중요하구요~
3. 다만 현재 프로젝트에서의 상수화는 의미가 없어보입니다~ 컬러 코드는 도메인에 종속되면 안 되는데 CARD.RED 방식으로 카드라는 도메인에 묶여있기 때문입니다. <- 이 부분 때문에 재사용이 거의 불가능해진 컬러 코드들이 생겨났고 그래서 괜히 사용했다는 생각이 드셨던 것 같네요.

2021-05-01 07:08 UTC, JaeYeopHan commented on src/components/NewCardForm/CardNumberInput/index.js
> +        <Input
모든 input에 label이 없는 것이 아쉽네요!

2021-05-01 07:08 UTC, JaeYeopHan commented on src/common/Card.js
> +  ${({ add }) => (add ? AddCard : CardInfo)}
`add`라는 props가 무엇인지 좀 더 이해할 수 있도록 네이밍해보면 어떨까요?

2021-05-01 07:08 UTC, JaeYeopHan commented on src/common/Modal.js
> +  height: 270px;
이 모달은 재사용을 하기 위해 만들어진 것 같은데, height가 270이 아닐 경우 재사용 할 수 없을 것 같아요!

2021-05-01 07:08 UTC, JaeYeopHan commented on src/components/ModalContents/CVCHelp/index.js
> +      <img className='cvc-help-img' src={cvcImage} />
alt값도 넣어주면 좋겠네요!

2021-05-01 07:08 UTC, JaeYeopHan commented on src/components/ModalContents/CVCHelp/index.styles.js
> +  overflow: hidden;
이 스타일링의 의도를 잘 모르겠어요! 👀

2021-05-01 07:08 UTC, JaeYeopHan commented on src/App.js
> +  });
저는 필요한 모달이 두 개라면 모달이 필요한 페이지에서 모달을 각각 정의했을 것 같아요!

2021-05-01 11:41 UTC, hchayan commented on src/common/Card.js
> +const Card = ({ add, cardInfo, handleModalOpen }) => {
처음에 해당 컴포넌트에 구현된 메서드는 `on-*` 으로 App에서 내려주는 메서드는 `handle-*` 로 분류해 구현하다가
일관성이 없어진거 같습니다!
저도  `on-*` prefix가 더 마음에 들어서 해당방식으로 동일했습니다!

2021-05-01 11:47 UTC, hchayan commented on src/components/mixin/Nav/index.js
> +const Nav = () => {
다음 요구사항에서 또 이 Nav가 필요한 시점이 있어 별도로 분리해뒀습니다!
현재는 재활용되지 못하는 컴포넌트지만 다음 미션에서 개선해 사용하겠습니다. 👀

2021-05-01 12:37 UTC, hchayan commented on src/components/ModalContents/CardColor/CardColorItem/index.js
> +const CardColorItem = ({ name, color, handleCardColor }) => {
이벤트위임 방식이 리액트에선 사용되지 않는 줄 알았는데, 
이런경우에 사용하면 유의미한 차이(props의 개수)가 있는거 같습니다!

2021-05-02 03:00 UTC, hchayan commented on src/components/ModalContents/CardColor/CardColorItem/index.styles.js
> +  align-items: center;
전역적으로 styled.css 를 만들어서 가져다 사용해도 좋을것 같습니다!
그런데 아직 flex를 사용하는 곳에서 그렇게 많이 공통되지 않아서 그런지 몰라도,
이렇게 전역적으로 import 해서 사용하되, 오버라이딩하는 방식으로 구현하는게 적절한지는 잘 모르겠습니다 ㅠㅠ

2021-05-02 03:12 UTC, hchayan commented on src/components/ModalContents/CardColor/index.js
> +      {Object.keys(CARD).map((key, index) => (
내부에서 key, value 모두 사용하는 경우에 사용하면 될거같습니다.
객체를 배열로 만들어 map하는데만 집중하다보니 keys로 만 회전한것 같습니다 감사합니다!

2021-05-02 03:28 UTC, hchayan commented on src/common/Button.js
> +const Button = styled.button`
기존에는 html 자체를 조건부 렌더링 형태로 처리했는데,
styled css에 props에 disabled 속성을 줘서 처리하는 방식으로 해결했습니다.
css의 역할을 css에게 위임하는 방식이라 역할 구분이 명확한것 같습니다!

(visibility는 해당 영역에 대한 공간을 유지해야되기문에 사용했습니다.)

2021-05-02 03:59 UTC, hchayan commented on src/common/Input.js
> +  text-align: ${({ textAlign }) => textAlign || 'center'};
default value를 선언해, props로 전달해주지 않은 요소에 대해서 default value를 사용하게끔 구현했습니다.
해당 styled-component를 이용한 새로운 컴포넌트를 만들어 override 하는 방식이 아닌
해당 component만을 최대한 이용할 수 있게 하기 위해 구현했습니다.

2021-05-02 04:10 UTC, hchayan commented on src/components/NewCardForm/CardNumberInput/index.js
> +        <Input
웹접근성 고려...! 맞습니다 ㅠㅠㅠㅠ

2021-05-02 04:11 UTC, hchayan commented on src/components/ModalContents/CVCHelp/index.js
> +      <img className='cvc-help-img' src={cvcImage} />
마찬가지로 웹 접근성 고려입니다...!

2021-05-02 04:13 UTC, hchayan commented on src/common/Card.js
> +  ${({ add }) => (add ? AddCard : CardInfo)}
앞에서 Card라는 컴포넌트에서 사용하는 속성이라 `add` 라고 만 했는데, `addCard` 라는 이름으로
명확히 선언해주는게 더 좋은거 같습니다!

2021-05-02 04:18 UTC, hchayan commented on src/common/Modal.js
> +  height: 270px;
모달의 최소 높이는 두고 싶어서
`min-height` 속성으로 개선했습니다!

2021-05-02 04:19 UTC, hchayan commented on src/components/ModalContents/CVCHelp/index.styles.js
> +  overflow: hidden;
[이 커밋](https://github.com/woowacourse/react-payments/pull/20#discussion_r624434263) 에서 피드백해주신 내용을
적용하면서 자연스럽게 `overflow` 에 대한 제한이 필요 없어졌습니다!
제거했습니다!

2021-05-02 04:21 UTC, hchayan commented on src/App.js
> +  });
지금은 너무 글로벌적으로 모달을 관리하고 있는거 같습니다!
말씀해주신 방법이 그 책임을 가까이 위치할수 있어서 적절한거 같습니다!

2021-05-02 05:06 UTC, hchayan commented
## 피드백 기반 개선 사항
작성해주신 피드백과 답변 보고 리팩토링했습니다!
감사합니다 !!!

### 1. 색상 도메인 상수 종속성 제거
### 2. `handle-*`  메서드,` on-*` 메서드 on-* 방식으로 일관성 유지
### 3. Object.keys를 Object.entries 방식으로 개선
### 4. css들의 의존성 구분 보다 명확히 개선
  : model의 height를 100%로주고, 이를 사용하는 외부에서 명시적으로 크기를 지정해주는 방식
  : Button 커스텀 css 에 속성을 통한 disable 처리 방식으로 개선 (css의 역할이기에 css에게 위임)
### 5. 웹 접근성 개선
  : 웹 접근성을 위한 label 사용, img alt 사용
### 6. 기타
  : 이 외에도 피드백 해주신 부분들을 개선했고, 남겨주신 피드백에 답글 형태로 작성했습니다! 감사합니다!

2021-05-02 05:40 UTC, JaeYeopHan commented on src/common/Card.js
> +  ${({ add }) => (add ? AddCard : CardInfo)}
`addCard`도 무슨 목적의 props인지 잘 모르겠는 것은 마찬가지 인 것 같습니다 ㅎㅎ
boolean이라면 그것으 드러내거나 네이밍이 이상하다면 잘못 설계된 props라는 의심을 해보면 좋을 것 같아요~

2021-05-02 05:41 UTC, JaeYeopHan commented on src/components/ModalContents/CardColor/CardColorItem/index.styles.js
> +  align-items: center;
https://chakra-ui.com/docs/layout/flex
이런 느낌은 어떨지요?

2021-05-02 05:44 UTC, JaeYeopHan approved these changes
수고하셨습니다

2021-05-02 05:44 UTC, merged

2021-05-02 16:56 UTC, hchayan commented
> 수고하셨습니다!
> 
> css-in-js에서 classname을 통한 스타일링을 해주셨는데, 이렇게 적용하게 된 계기가 궁금하네요 ㅎㅎ
> 
> > 1. 제어 컴포넌트와 비제어 컴포넌트 사이에서의 갈등
> >    처음엔 source of truth를 위해 제어 컴포넌트 방식으로 newCardForm을 구현해나가기 시작했습니다.
> >    하지만 프로젝트를 진행하면서,
> >    하나의 input에서 뒷 8자리를 password 처리하거나,
> >    input 채워졌을때 다음 input으로 autoFocusing 되거나 하는 기능들을 구현하려면
> >    결국, ref를 이용한 비제어 컴포넌트 방식이 아니면 구현이 거의 불가능했습니다.
> >    그래서 이미 제어 컴포넌트로 구현한 상태에서, 위와 같은 기능들을 위해 ref도 붙여두면
> >    결국 두가지 방식을 동시에 사용하는거 같아, 제어 컴포넌트 방식으로만 구현했는데
> >    이런경우 애초에 source of truth를 개발자에게 어느정도 맡기고 비제어 방식으로 아예 넘어가야 될거같은데
> >    아니면 두가지 방법을 혼용해서 쓰는 실 사례도 많은지, 아니면 지양해야하는지 고민됩니다.
> 
> 전 프런트엔드 개발에서 어렵다고 할 수 있는 부분이 비동기 그리고 폼이라고 생각해요
> 상황에 맞는 방법을 사용하는 것이 중요하다고 생각합니다. 내부적으로는 controlled 방식이지만 외부에 공개하는 인터페이스는 uncontrolled로 하는 등 조합하여 사용해도 문제가 된다고 생각하지 않습니다 ㅎㅎ
> 말씀해주신 single source of truth를 잘 지키면서 인터페이스를 설계해보세요!
> 
> > 1. 색상 및 폰트 상수화에 대해
> >    처음엔 그렇게 제어할게 많지 않을줄 알고, 자주사용할 것 같은 css 상수 값을 상수화 해놓고 사용했으나
> >    요구사항에서 필요한 색상 및 폰트 들이 점차 다양화되고 커져서 결국 비효율적이게 되고, 또 근처 파일에 있지도 않아 괜히 사용했다라는 생각이 들었습니다. 물론 이번 미션 요구사항이 일관성이 부족했긴 했지만 YAGNI 법칙을 지키면서 했어야 했는지 잘못된 선택이였던것 같습니다. 그런데 실제 현업에서 웹디들이 이런 규칙들을 미리 정해놓고 사용하라고 하는 케이스가 많은지가 궁금합니다.
> 
> 1. '웹디'가 뭔가요?
> 2. color code, typography 등 정해진 규칙 기반하에 적용합니다. 코드 상에서도 상수화는 중요하구요~
> 3. 다만 현재 프로젝트에서의 상수화는 의미가 없어보입니다~ 컬러 코드는 도메인에 종속되면 안 되는데 CARD.RED 방식으로 카드라는 도메인에 묶여있기 때문입니다. <- 이 부분 때문에 재사용이 거의 불가능해진 컬러 코드들이 생겨났고 그래서 괜히 사용했다는 생각이 드셨던 것 같네요.

웹디는 웹디자이너를 말한것입니다 ㅠㅠㅠ 제가 실수로 줄여말했네요