[페이먼츠 미션 Step 1] 라잇(강영민) 미션 제출합니다.
woowacourse/react-payments pull request #202
Opened 2023-04-20 08:10 UTC by kangyeongmin

2023-04-21 15:19 UTC, InSeong-So requested changes
안녕하세요, 라잇! 리뷰어 파랑입니다🤗
어마어마한 요구사항들이 많은 리액트 페이먼츠 미션... 고생 많으셨습니다!
form 유효성 검사가 이번 미션에서 많은 러닝을 요구할거에요.

CardInput Component의 경우, 아마 다음 스탭을 진행하면서 더 많은 고도화를 할 거에요. 여기에 커스텀 훅으로 UI와 독립적인 비즈니스 로직을 입맛대로 합칠 수 있는 상황을 만드는 것에 초점을 두면 좋겠습니다.

react-router-dom! 좋은 라이브러리입니다👍 router path 등을 상수로 관리해보는 것도 추천드려요.

Storybook은 현재 단위에서는 큰 메리트를 못 느낄 수 있습니다. 저는 PM/PD/Backend와 협업할 때 정말 요긴하게 사용하고 있어요. 피그마 디자인에 명시된 컴포넌트를 개발했을 때 이렇고, 유저 인터렉션과 여러 테마를 적용할 때 어떻게 보이는지 미리 검증할 수 있고, 타입에 대한 정의를 사전에 내릴 수 있기 때문입니다.

나머지는 코멘트 확인해주세요🙇‍♂️
고생 많으셨어요🤭 확인 후 재요청 주세요!

2023-04-24 05:10 UTC, kangyeongmin commented on src/index.tsx
> +  </>
넵, useEffect안의 콘솔로그가 두번 씩 찍혀서 제거하였는데 다음과 같은 이점들이 있군요!

- 안전하지 않는 생명주기를 사용하는 컴포넌트 발견
- 레거시 문자열 ref 사용에 대한 경고
- 권장되지 않는 findDOMNODE 사용에 대한 경고
- 예상치 못한 부작용 검사
- 레거시 context API 검사
- Ensuring reusable state

개발환경에서만 그렇고 실제 배포에서는 두번씩 실행되는 점들이 사라지는 것 또한 알게되었습니다👍🏻
지적해주셔서 감사합니다!

2023-04-24 05:12 UTC, kangyeongmin commented on src/assets/index.ts
> +export { ArrowLeft, IcChip, QuestionMark };
우옷! 이런 꿀팁이 있군요. 👍🏻👍🏻

2023-04-24 05:19 UTC, kangyeongmin commented on src/components/Card.tsx
> +            );
`crypto.randomUUID()`라는 것이 있군요!!

> 또 지금 JSX 코드는 letterSpacing만 다른 것 같아요.
급하게 개발하다보니, 이런 부분까지 놓쳤네요.. 수정하겠습니다👍🏻

2023-04-24 05:32 UTC, kangyeongmin commented on src/components/CardInput.tsx
> +  onKeyDown?: (e: React.KeyboardEvent<HTMLInputElement>) => void;
CardInputType이 HTMLInputElement의 속성들을 상속받은 다음, 
최대한 외부에서의 의존성이 강해지지 않도록 수정해보았습니다!

2023-04-24 05:55 UTC, kangyeongmin commented on src/pages/MyCard.tsx
> +              cardNumber={card.cardNumber}
```javascript
{cards.map(({ color, ownerName, expiredDate, cardNumber }: CardType) => (
        <CardWrapper key={crypto.randomUUID()}>
          <Card
            color={color}
            ownerName={ownerName}
            expiredDate={expiredDate}
            cardNumber={cardNumber}
          />
        </CardWrapper>
      ))}
```
이런식으로 수정해보았습니다!

근데 고민을 해보니...
그냥 card객체를 통째로 넘겨줘서 
Card component에서 속성들을 구조분해해서 사용하는 것도 괜찮을 것 같은데 

어떤 방법을 더 추천하시는지 궁금합니다!!🧐

2023-04-24 06:02 UTC, kangyeongmin commented on src/utils/index.ts
> +};
리턴 타입을 명시해주는 방식으로 수정하겠습니다~!

2023-04-24 06:22 UTC, kangyeongmin commented on src/components/common/Header.tsx
> +  return (
구조분해를 통하니 일일히 props. 로 가져오지 않아도 되서 가독성이 좋아졌네요!

메모이제이션에 대해 궁금한 점이 있습니다!
현재 `Page`와 `Header`컴포넌트에 대해서만 메모이제이션 적용을 추천해주셔서
React.memo()가 컴포넌트의 props가 바뀌지 않았다면, 재렌더링을 하지 않게 해준다는 것을 알게되었습니다.
그래서, **'음, 그러면 모든 컴포넌트에 메모이제이션을 적용해주는것이 좋은게 아닌가?'**라는 의문이 들었습니다.

찾아보니, 굳이 렌더링 최적화를 하지 않아도 될 컴포넌트에 메모이제이션을 적용하는 것은 
불필요한 props비교만 하는 것이라는데..!

그렇다면, 메모이제이션 적용의 기준은
props의 변경이 자주 일어나지 않는 컴포넌트라고 정립하면 되는 것일까요?

2023-04-24 06:28 UTC, kangyeongmin commented on src/pages/AddCard.tsx
> +    setLocalStorage("card", [...cards, card]);
해당 메소드 내에 console.log()가 남아있었는데,,
그 부분을 말씀하시는건지
집어주신 두줄의 코드를 말씀하시는건지
헷갈리는데,
혹시 어떤 부분을 의도하신걸까요~?

(콘솔로그는 빠르게 삭제하겠습니다 ㅎㅎ😅)

2023-04-24 07:14 UTC, kangyeongmin commented on src/App.tsx
> +};
App.tsx 에 있는 router를 컴포넌트로 분리하는 것 외에는 
말씀해주신 내용이 이해가 잘 가지 않습니다..!

혹시 만든다면, components/common 폴더에 두는 것이 맞을지도 고민되네요..

그 외에 구체적인 설명 부탁드려도 될까요? 🧐

2023-04-24 08:41 UTC, kangyeongmin commented on src/components/CardInputForm.tsx
> +      : (card.cardNumber = e.target.value);
카드 Input 핸들러와 관련된 자잘한 로직들을 utils/card에 분리해보았습니다!

1ff062274f4206ccd46c1611601f5bc9d384a3fc <-해당 커밋

2023-04-24 10:57 UTC, kangyeongmin commented on src/components/CardInputForm.tsx
> +  const [isAnswered, setIsAnswered] = useState<boolean>(false);
현재는 화면에 보여지는 input value들을 다루는 로직을 utils로 분리를 해두었는데,
분리하고보니 무엇을 커스텀 훅으로 만들어야 할지 고민이네요,,,

주위의 크루에게도 물어봤는데 추상적으로 두가지 상황이 떠올랐어요!

현재, 다음과 같이
```javascript
newCard.cardNumber = getSeperatedCardNumber(
      getReplacedCardNumber(e.target.value)
    );
    setCard(newCard);
```
객체의 프로퍼티를 수정하고 set하는 로직이 반복되고 있는데, 
해당 부분에 초점을 둔 커스텀 훅을 만들어야 할지

utils/card에 포함한 많은 로직을 가지고 있는 
cardNumber와 expiredDate의 input에 관한 커스텀 훅을 만들어야 할지가
고민입니다!!

파랑은 혹시 어떤 부분을 의도하시고 커스텀 훅 구현에 대한 말씀을 주신걸까요??

2023-04-25 03:17 UTC, kangyeongmin commented on src/pages/MyCard.tsx
> +              cardNumber={card.cardNumber}
++ 마지막은 이런식으로 변경하였습니다!
```javascript
<Card {...newCard} />
```

2023-04-25 08:51 UTC, InSeong-So approved these changes
step 2를 함께 진행하면서 많은 코드가 리팩토링 되었네요!
코멘트와 리뷰 다시 남겼으니 확인만 해주세요.
스텝3에 적용하면 어떨까 싶네요!

크게 수정할 부분보다... 스텝3과 함께 개발하고 피드백하는 게 좀 더 좋을 것 같아 머지하겠습니다.
고생 많았습니다🥰

2023-04-25 08:51 UTC, InSeong-So commented on src/constants/index.ts
> +} as const;
중복되는 프로퍼티가 있는데 이렇게 설정해야 할까요~?

2023-04-25 08:51 UTC, InSeong-So commented on src/pages/AddCard.tsx
> +    color: CARD_COLOR[Math.floor(Math.random() * 10)],
유틸 함수로 만들어두면 어떨까요?

2023-04-25 08:52 UTC, merged

2023-04-26 03:40 UTC, kangyeongmin commented on src/components/CardInput.tsx
> +    />
우와 저런 작성이 가능하군요!!
꿀팁 감사합니다☺️

2023-04-26 04:25 UTC, kangyeongmin commented on src/components/Card.tsx
> +  const cardNumberArray = cardNumber.replaceAll(" - ", " ").split(" ");
cardNumber가 변경될때만 수행되어야 하는 로직이기 때문에, useMemo가 유용하겠네요!

수정하겠습니다!!

2023-04-26 05:37 UTC, kangyeongmin commented on src/constants/index.ts
> +} as const;
생각해보니 ownerName(소유자 이름) 빼고는 입력 길이가 한정적이기 때문에, minLength를 줄 필요가 없더라구요..
심지어 ownerName은 선택 입력이기 때문에, 더욱 필요가 없어졌습니다!

하나의 객체만 남기는 방식으로 수정하겠습니다!!