[페이먼츠 미션 Step 1] 파인(임낭경) 미션 제출합니다.
woowacourse/react-payments pull request #203
Opened 2023-04-20 08:10 UTC by nangkyeonglim

[배포 페이지](https://react-payments-psi.vercel.app/)

2023-04-23 16:02 UTC, bigsaigon333 commented
일단 리뷰가 늦어져 죄송하다는 말씀 먼저 드립니다 🙇🏻🙇🏻
이제 리뷰 시작할게요!!!

2023-04-23 17:29 UTC, bigsaigon333 requested changes
파인 안녕하세요! 

일단 리뷰가 늦여저서 죄송하다는 말씀을 먼저 전달합니다..
이걸로 충분하지는 않겠지만, 제가 밥한번 사겠습니다..

세부적인 사항은 코멘트 확인 부탁드려요!

당부드리고 싶은 말씀 두가지는

1. dataset-* 은 가능하면 다 리액트 상태로 치환했으면 좋겠다는 점입니다. 
 - html 요소 자체에 어떤 값을 넣어서 보존하는 방법이 굳이 필요할까? 라는 생각입니다. 리액트에서는 useState로 그냥 상태를 관리할 수 있으니까요. 

2. 선언적인 컴포넌트를 작성하자는 점입니다. 그냥 컴포넌트명과 props만 보고도 이렇게 작동할거 같은데? 라고 떠올릴 수 있게 컴포넌트를 작성했으면 좋겠습니다.(Input 컴포넌트 쪽에 좀더 자세한 리뷰를 남겼습니다!)


시간이 너무 지체되어서 2단계 진행이 좀 어려울거 같다는 판단이 드시면, 적당히 리뷰 반영해주시고 말씀주세요!!
리뷰를 어디까지 받아들일까는 리뷰이의 선택입니다. 😄 

---

아래는 PR본문에 적어주신 사항에 대한 답변입니다!

> 컴포넌트
> ErrorMessage, Header, Input, CardPreview는 모두 재사용 가능한 컴포넌트로 설계하였습니다!
> 
> 특히 Input을 추상화하는데 가장 많은 시간을 들였는데요.
> 공통된 스타일아래, type이 number, text, ..., input의 개수, placeholders, 최대 길이, 중앙정렬인 경우 등등의 props를 넘겨주었는데요.
> 하나하나 추상화하다보니 넘겨주어야하는 props가 많고, 또 예외 경우가 많아서 이렇게 추상화하는 것이 옳은 것일까 생각을 많이 했습니다.
> 특히 input type이 number인 경우 maxLength, minLength 적용이 안되서 직접 handling하였고,
> 카드 소유자 이름은 영어만 가능한데 input type이 text인 경우는 영어, 한글, 숫자 다 가능하니까 Input 안에서가 아닌 Input을 사용하는 곳에서 validation을 해주었습니다.
> 또한 카드 만료일은 number인데 날짜가 현재 날짜 이전의 만료일을 적용한 경우 다시 입력하도록 에러 메시지를 띄우는 처리를 하였습니다.
> 이런 예외 사항이 많다보니 addCardContainer가 아주 커졌는데요. 동동의 의견이 궁금합니다!

일단 세부적인 구현에 대한 리뷰는 코멘트를 참고 부탁드린다는 말씀 먼저 드립니다.

전체적인 설계 관점에서 보자면,
addCardContainer가 커지는건 어쩔수 없는 일이라고 생각합니다.
어떤 컴포넌트는 도메인을 로직을 수행해야 하고, 그러한 많은 도메인 로직이 모여진 곳이 addCardContainer 였다고 생각합니다.

그러한 도메인 로직을 잘 수행할 수 있도록 Input 컴포넌트가 잘 설계되었냐가 핵심이라고 생각하는데요,
사실 이 미션만 놓고 본다면 충분히 잘 설계되었다고 생각해요.
그러나 재사용가능한 컴포넌트는 미션이라는 컨텍스트를 뛰어넘어서도 살아남을 수 있어야 합니다.
이건 경험이 필요한 부분일수도 있어요. 다른 프로젝트 만들 때는 이러한 Input의 기능이 필요하던데... 라는 일종의 경험칙이 쌓여야 하기도 하고, 유명한 디자인 시스템 라이브러리를 보면서 인사이트를 얻을 수도 있습니다.


 
> input focus 자동 이동
> 현재 useRef를 사용하여서 각 input그룹내에서 maxLength를 이용하여 다음 input으로 넘어가도록 구현을 하였습니다.
> 현재 input이 총 10개 인데 10개의 ref를 만들어서 다음 ref를 focus하는 것이 최선인지 궁금합니다.

1. 일단 focus를 주기위해서는 ref를 사용하는 방법밖에 없습니다.
(왜 ref 밖에 없을까요? useState로는 왜 안되는걸까요?? 숙제입니다.)

4. 모든 것을 상태로 생각해야합니다. 여러개의 컴포넌트가 있다면 그 중 어떤 하나의 컴포넌트만 focus를 가지게 됩니다. 그러면 그 컴포넌트만 props로 isFocused=true를 전달받고,
- 그 컴포넌트 안에서 isFocused가 true이면 ref로 focus()를 하고...

기억해야하는 모든것을 상태로 바꿔서 생각하고, 상태나 ref는 가능하면 가장 작은 스콥의 컴포넌트에서 격리시켜주세요. 

ref를 여러개 가지고 이걸 다 제어하겠다는 생각은 리액트에서 버려주세요.




> storyBook
> 추상화된 컴포넌트(props에 따라 다른 형태를 띄는) 컴포넌트만 UI 렌더링 테스트를 진행해보았습니다.
> 이러한 추상화된 컴포넌트를 테스트할 때는 바로바로 props만 넣어주면 렌더링이 어떻게 되는지 볼 수 있어서 편리했습니다.
> 다만 뭔가 이벤트관련된 로직이나 props로 함수를 받는 컴포넌트의 경우 어떻게 테스트하면 좋을지 의견 부탁드립니다!

스토리북은 UI 테스트 도구입니다. 이거를 가지고 버튼을 누르면 상태가 변경되고 어떤 로직이 실행되고 이런걸 테스트하는게 주 목적은 아니라고 생각합니다. (가능하다는거를 잘 알고는 있습니다.)

즉, 버튼을 누르거나 포커스가 되면 어떤 이벤트가 발생한다 정도만 확인하는 단계에서 끝을 내는게 좋다고 생각해요!

2023-04-23 17:29 UTC, bigsaigon333 commented on src/App.tsx
> +    <CardContext.Provider value={{ cardList, setCardList }}>
cardList가 Provider에 주입되기만 한다면

cardList와 Provider를 하나의 컴포넌트로 분리하는게 어떨까요?

2023-04-23 17:29 UTC, bigsaigon333 commented on src/components/AddCardContainer.tsx
> +      if (!(e.target instanceof HTMLInputElement)) return;
```suggestion
    (e: ChangeEvent<HTMLInputElement>) => {
```

런타임에 체크하는 건 저도 선호하는방식이긴 한데,
요 경우에는 굳이 필요없을거 같아요

참고로 이벤트 핸들러 함수는 `ChangeEventHandler<T> ` 로도 많이 선언됩니다~!

2023-04-23 17:29 UTC, bigsaigon333 commented on src/components/AddCardContainer.tsx
> +            e.target.value = e.target.value.replace(regEx.notNumber, '');
값을 재할당하는 방식은 함수형 프로그래밍에서 지양해야할 패턴입니다.

이런 패턴이 반복되면 언제 값이 왜 변경되었는지 추적하기가 굉장히 까다로워질 수 있어요

2023-04-23 17:29 UTC, bigsaigon333 commented on src/components/AddCardContainer.tsx
> +    };
위의 코멘트와 동일한 맥락인데,
기존에 선언된 참조값의 속성값을 변경하는 패턴은 지양하는 것이 좋습니다.
이런식으로 값이 변경된 새로운 참조값을 선언해주세요.


```suggestion
      const targetId = Number(e.target.dataset.id);
      const nextState = state.map((val, index) => index === targetId ? e.target.value : val);
      setState(nextState);
    };
```

2023-04-25 05:42 UTC, nangkyeonglim commented on src/utils/localStorage.ts
> +  return item ? JSON.parse(item) : [];
로컬스토리지 유틸의 성격에 맞게 제네릭을 사용해서 수정해보았습니다.
initalValue를 받아 배열이 초기값이 아닌 경우도 직접 입력할 수 있도록 수정하였고, JSON.parse의 반환값 타입이 any로 추론되기 때문에 반환시 타입을 정제하여 반환하도록 수정하였습니다!

2023-04-25 06:20 UTC, nangkyeonglim commented on src/styles/global.ts
기존 레벨 1의 영화 리뷰 미션에서 템플릿으로 제공되었던 reset CSS 파일입니다.
찾아보니 2011년에 만들어진 reset CSS라서 최근에 만들어진 reset CSS로 교체하였습니다!

2023-04-26 00:59 UTC, nangkyeonglim commented on src/components/CardPreview.tsx
> +`;
오 column-gap은 grid layout에서만 쓸 수 있는 줄 알았습니다!
flexbox 아래 있는 자식요소를 모두 column/row-gap을 이용해서 간격을 조정할 수 있도록 변경해보았습니다!

2023-04-26 03:30 UTC, nangkyeonglim commented on src/components/Input.tsx
> +    .map(() => React.createRef<HTMLInputElement>());
destructuring하는 확실히 기준이 없었던 것 같습니다🥲
불필요한 import react구문을 다 없애고, 타입같은 것은 바로 React.~ 으로 사용하고 
나머지는 destructuring하여 사용하도록 바꿔보았습니다:)

2023-04-26 03:52 UTC, nangkyeonglim commented on src/components/AddCardContainer.tsx
> +      if (!(e.target instanceof HTMLInputElement)) return;
확실히 input element에만 쓰이기 때문에 런타임에 체크할 필요가 없군요!
런타임 체크하는 로직 모두 변경하였습니다!

2023-04-26 03:59 UTC, nangkyeonglim commented on src/components/CardPreviewList.tsx
> +    setLocalStorage('cardList', cardList);
step1 진행할 때 시간이 부족해서 상수화를 진행하지 못했었는데 get/setLocalStorage시 쓰는 키 모두 상수화하였습니다!

2023-04-26 04:33 UTC, nangkyeonglim commented on src/App.tsx
> +    <CardContext.Provider value={{ cardList, setCardList }}>
CardListProvider로 분리를 진행해보았는데요 확실히 App이 깔끔해지고 가독성도 높아진 것 같습니다

2023-04-26 05:39 UTC, nangkyeonglim commented on src/components/AddCardContainer.tsx
> +            e.target.value = e.target.value.replace(regEx.notNumber, '');
값을 재할당하지 않고 validation을 통과한 값들만 setState가 작동하도록 변경해보았습니다!

2023-04-26 07:36 UTC, nangkyeonglim commented on src/components/Input.tsx
> +const Input = ({ labelText, inputInfoList, children }: InputProps) => {
그렇네요! 해당 컴포넌트는 label과 input들이 함께 있으므로 InputGroup으로 변경하였습니다.
step2 진행하면서 Input도 따로 분리해보겠습니다!

2023-04-26 14:47 UTC, nangkyeonglim commented
안녕하세요 동동🙂
리팩토링 반영 사항은 코멘트와 함께 남겨두었습니다!
DM으로도 남겼지만 남은 리팩토링은 step2와 함께 진행하려고 합니다
좋은 리뷰 감사합니다🤗

2023-04-27 01:53 UTC, bigsaigon333 commented on src/components/Input.tsx
> +    .map(() => React.createRef<HTMLInputElement>());
타입은 왜 React.~ 으로 사용하시나용?
타입이랑 타입이  아닌 것에 구분을 두고 싶으신걸까요..?

2023-04-27 01:57 UTC, bigsaigon333 commented on src/components/Input.tsx
> +    .map(() => React.createRef<HTMLInputElement>());
(심화) 그리고 React를 import 하지 않아도 React.~ 타입을 사용할 수 있는 이유는 무엇일까요?

2023-04-27 01:59 UTC, bigsaigon333 commented on src/components/Header.tsx
> +};
```suggestion: -4
};
```

2023-04-27 02:02 UTC, bigsaigon333 commented on src/components/Header.tsx
> +};
```suggestion
const title = {
  '/': '보유카드',
  '/addCard': '카드 추가',
};
```
객체 리터럴과 index signature의 차이도 찾아보시면 좋겠습니다~
타입읂 항상 좁혀서 써야한다는 것두요!

2023-04-27 02:04 UTC, bigsaigon333 commented on src/components/Input.tsx
> +  }
👍🏻👍🏻👍🏻👍🏻👍🏻

2023-04-27 02:07 UTC, bigsaigon333 commented on src/components/CardPreview.tsx
> +`;
Flexbox의 column-gap, row-gap 은 , Safari에서 지원하는 os 버젼이 높다는 단점이 있어서

실무에서는 파인이 기존에 했던 것처럼 코드를 작성하는 경우가 많습니다!

이러한 점을 알고 쓰신건지 아닌지 궁금해서 한번 여쭤봤어요!

(물론 지금은 미션이니까 그냥 최신버젼을 가정하고 column-gap 쓰셔도 큰 문제가 없다고 생각합니다!)


https://caniuse.com/?search=flex%20column-gap

2023-04-27 02:09 UTC, bigsaigon333 approved these changes
파인 안녕하세요~

리뷰 반영하시느라 고생하셨습니다!

소소하게 코멘트 몇개 추가로 남겼으니 슥 확인만 해주세요~

2단계도 화이팅 💪🏻

2023-04-27 02:09 UTC, merged