[페이먼츠 미션 Step 1] 윤생(이윤성) 미션 제출합니다.
woowacourse/react-payments pull request #205
Opened 2023-04-20 08:16 UTC by 2yunseong

안녕하세요 파랑! 윤생입니다~!

이번 미션은 3주네요~! 3주간 잘 부탁드립니닷!!

이번 미션은 스토리북을 통한 컴포넌트 주도 개발을 중점적으로 잡아보려 했는데, 제한 시간 내에 문제에 대한 기능 요구사항도 전부 구현하지 못할 것 같아서 일단 스토리북 사용 자체도 뒤로 미루었습니다 ㅠ (페어와 저와 모두 처음이였어서요) 남은 기간 동안 천천히 적용해보겠습니다.

## 질문

Q. 수업에서 배운 내용으로는 컴포넌트 주도 개발은 컴포넌트 단위로 빠른 피드백을 받는 것이 목적이라고 배웠습니다. 그래서 저는 스토리북을 통해 자신이 개발한 컴포넌트를 빠르게 시각적으로 보고 테스트할 수 있다는 점이 그렇다고 생각하는데, 제가 생각하는 방향이 맞을까요?

Q. 처음에 input 태그를 만들 때 value나 onChange등 몇개의 prop만 필요할 줄 알았는데, 앱이 점점 커지면서 필요한 props도 많아지더라구요. 이건 어쩔 수 없는 부분인 걸까요? 왠지 props 가 기존에 설계했던 것보다 늘어날수록 잘못 설계한게 아닌지 하는 생각이 들어서요.

Q. 컴포넌트 네이밍이 어렵습니다.ㅠ 파랑만의 컴포넌트 네이밍 방식이 있으신가요? 혹시 보시다가도 별로인 네이밍이 있다면 피드백 부탁드리겠습니다.

## 미 충족 사항

- 만료일 입력이 에러가 납니다. 1이나 0을 입력하고 다시 지우면 안지워지는 문제가 있어요.
- 카드 소유자 이름에서 공백을 발생시키면 카드가 세로로 늘어나는 문제가 있습니다.
- 카드 소유자 이름은 선택이지만 필수로 동작합니다.

## 배포 링크

이번 미션은 모바일 웹/앱입니다! 앱 으로써의 접근성이 떨어지는 부분도 피드백 해주시면 감사드리겠습니다!!

[페이먼츠 바로가기](https://deploy--eclectic-chaja-ec3e84.netlify.app/)

2023-04-20 08:26 UTC, 2yunseong reviewed
몇 가지 질문 코멘트로 남기었습니다!

2023-04-20 08:26 UTC, 2yunseong commented on src/components/FormCardAdd.tsx
> +          />
중간에 계속 겹치기는 하는데, 값의 유효성 검사를 html 태그의 속성을 이용한 것들과 자바스크립트 로직을 이용한 것을 섞어놓았습니다. 그래서 드리는 질문인데, 만약 HTML 속성으로 가능한 기능이라면 가능한 한 HTML 속성을 사용해 처리하는 게 나을까요?

2023-04-21 15:37 UTC, InSeong-So requested changes
안녕하세요, 윤생! 리뷰어 파랑입니다🤗
긴 미션 동안 잘 부탁드려요! 많은 도움이 되면 좋겠네요💪

Q. 수업에서 배운 내용으로는 컴포넌트 주도 개발은 컴포넌트 단위로 빠른 피드백을 받는 것이 목적이라고 배웠습니다. 그래서 저는 스토리북을 통해 자신이 개발한 컴포넌트를 빠르게 시각적으로 보고 테스트할 수 있다는 점이 그렇다고 생각하는데, 제가 생각하는 방향이 맞을까요?
- 개발을 하다보면 꼭 특정 상황에 **의존하는** UI가 등장합니다. 로그인을 했을 때 보이는 컴포넌트라던가... 말이죠! 스토리북은 이런 상황에서 props를 유저가 직접 조작하면서 컴포넌트를 확인할 수 있는 장점이 있습니다. 개발자 뿐만 아니라 PM, PD, QA가 전부 가능하죠. 따라서 윤생이 생각한 것도 좋은 방향이랍니다☺

Q. 처음에 input 태그를 만들 때 value나 onChange등 몇개의 prop만 필요할 줄 알았는데, 앱이 점점 커지면서 필요한 props도 많아지더라구요. 이건 어쩔 수 없는 부분인 걸까요? 왠지 props 가 기존에 설계했던 것보다 늘어날수록 잘못 설계한게 아닌지 하는 생각이 들어서요.
- 잘못 설계한 것이 아니라, 그 상황에서는 그게 옳았을 뿐입니다. props가 많아져 확장을 해야하는 상황이 온다면 그 시점에 리팩토링을 하거나, 기술부채를 남기고 기능 구현을 우선하는 방법 중에 선택하는 것이죠. 일반적으로 네이티브 태그가 가진 속성에 대한 props 설계는 크게 변하는 일이 없지만, 요구사항에 따른 도메인 종속적인 컴포넌트는 천차만별 바뀌기 때문에 많은 컴포넌트를 개발하고 확장의 여지를 남겨두는 경험을 쌓는 것이 좋습니다.

Q. 컴포넌트 네이밍이 어렵습니다.ㅠ 파랑만의 컴포넌트 네이밍 방식이 있으신가요? 혹시 보시다가도 별로인 네이밍이 있다면 피드백 부탁드리겠습니다.
- 저는 공통 컴포넌트라면... Todo App이나 날씨 앱에 두었을 때 이상하지 않는가? 를 기준으로 작성합니다. 우선 Header, Footer, Sidebar, Modal 등이 있겠네요. 도메인이라면 templates 라는 폴더 하위에 페이지(라우팅) 이름으로 하나하나 스탭을 맞춰가면서 작성합니다. `/add-card` 가 라우팅이라면 AddCardTemplate > AddCardWrapper > AddCardForm > AddCardButton 처럼 되겠네요!

스토리북은 처음 접할 때 어려움이 많아 포기하는 분들이 많습니다. 이걸 이겨내면 여러 컴포넌트에 대한 시각적 접근, 설계에 대한 고민, 빠른 수정과 피드백을 받을 수 있는 창구를 만들어 낼 수 있으므로 꼭 이겨내길 바래요.

코멘트 확인해보시고, 재요청주세요!

2023-04-22 05:54 UTC, 2yunseong commented on src/components/Header.tsx
> +};
한번 공부해보겠습니다!

2023-04-22 09:19 UTC, 2yunseong commented on src/hooks/usePasswordInput.ts
> +  return [value, onChange] as const;
사용부분에서 타입 추론을 (T | (e:React.ChangeEvent~) => void)[] 로 해서 임의로 튜플로 지정해주었습니다!
이렇게 되면 onChange를 사용하는 부분에서 callable 하지 않을수 있다는 오류가 떠서요!

2023-04-22 12:19 UTC, 2yunseong commented on src/pages/CardListPage.tsx
> +  const cardList = JSON.parse(localStorage.getItem('cardList') ?? '[]');
`fetchData`의 네이밍이 잘못되었네요...ㅎㅎ `fetchData`는 `localStorage`에 생성한 카드 목록을 저장하는 로직인데, 다소 혼란이 있는 네이밍을 사용한 것 같습니다 ㅠㅠ 이런 실수는 진짜 큰거같아요!

2023-04-22 12:20 UTC, 2yunseong commented on src/pages/CardListPage.tsx
> +  const cardList = JSON.parse(localStorage.getItem('cardList') ?? '[]');
기존에 쓰이던 fetchData의 네이밍도 변경하고(post나 그런식으로요) 이 로직을 `fetchData`로든 빼는 방향으로 생각해보겠습니다!

2023-04-23 11:42 UTC, 2yunseong commented on src/components/InputCardPassword.tsx
> +  value,
넵! 참고 하겠습니다 :D

2023-04-23 11:43 UTC, 2yunseong commented on src/hooks/usePasswordInput.ts
> +  };
이 부분은 신용카드 번호를 저장하는 Custom Hook인데요, 그러면 자리별로 따로 분리해서 관리하는게 나을까요?

2023-04-23 12:13 UTC, 2yunseong commented on src/index.tsx
> +root.render(<RouterProvider router={router} />);
```
### Strict 모드
- 자손들에 대한 부가적인 검사와 경고를 활성화 한다.
- Strict 모드는 개발모드에서만 활성화
```
확실히 적용하니 key 누락 등의 오류가 보이네요!! 감사합니다!

entry 파일이 가볍게 유지되야 하는건 어떤 이유에서인가요?

2023-04-24 05:26 UTC, 2yunseong commented on src/pages/AddCardPage.tsx
> +  };
`useCallback`을 사용해 불필요한 `Header`의 `button`의 렌더링을 줄일 수 있겠네요!
그런데 제 생각에는 Header 컴포넌트 같은 경우는 렌더링에 계산이 많이 들어가는 컴포넌트가 아니라 메모이제이션을 하는 게 더 큰 비용이지 않을까 생각이 들었습니다!
이에 대해 파랑에 의견은 어떠신가요?
[useCallback](https://react.dev/reference/react/useCallback)
<img width="666" alt="image" src="https://user-images.githubusercontent.com/56749516/233906772-bbbd2d36-0bdf-4dee-b8eb-3964090f7e6b.png">

실제로 렌더링에 큰 영향이 없는 것까지 확인했습니다.
<img width="677" alt="image" src="https://user-images.githubusercontent.com/56749516/233907056-92c5293b-9609-4100-bb02-c0650d2490ae.png">

2023-04-24 06:51 UTC, 2yunseong commented on src/components/InputCardData.tsx
> +const InputCardData = ({ value, onChange, name, className }: InputProps) => {
> 단, 이 경우 input 태그의 자유도를 높이기 위해서는 기본 attributes를 주입받을 수 있게 해줘야 하므로 React에서 제공하는 타입을 활용해보길 추천드려요.

혹시 추천해주실만한 검색 키워드가 있나요?! 스스로 검색을 해보는데 해당 내용에 대해 잘 나오지 않네요 ㅠㅠ

2023-04-24 08:12 UTC, 2yunseong commented on src/utils/fetchData.ts
> +    });
넵! 지금봐도 많이 난잡하군요.. 감사합니다!

2023-04-24 09:57 UTC, 2yunseong commented on src/hooks/useInput.ts
> +) => {
메모이제이션을 적용하였는데 계속 다시 안되는 오류가 있었습니다. 아래는 `usePasswordInput` 커스텀 훅 입니다.
```tsx
// usePasswordInput.tsx
// ...
  const onChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      setValue({
        ...value,
        [e.target.name]: e.target.value,
      });
    },
    [value]
  );
```
메모이제이션을 적용해도 안되는 이유는.. 여기가 계속 바뀌어서 그런것 같았습니다.
메모이제이션은 잘 되었다고 생각했고, 여기서 매번 새로운 값을 할당해주었기 때문에 렌더링이 일어났을거라 추측했습니다.
```tsx
// AddCardNumberInput.tsx
  const [cardNumber, onChangeCardNumber] = usePasswordInput<CardNumber>({ initialValue.. });
  const cardNumberProps: InputHook<CardNumber> = {
    value: cardNumber, // <- 메모이제이션 된 값
    onChange: (e: React.ChangeEvent<HTMLInputElement>) => {
      const lastWord = e.target.value[e.target.value.length - 1];

      if (e.target.value.length > 4) return;
      if (e.target.value.length > 0 && !isNumberInput(lastWord)) return;

      onChangeCardNumber(e);
    },
   // ... 전달하는 cardNumber가 항상 바뀌면서 렌더링이 일어남
          <AddCardForm
          cardNumber={cardNumberProps} // cardNumberProps의 value가 바뀌지 않더라도  cardNumberProps가 항상 바뀜
          cardExpire={cardExpire}
          cardOwner={cardOwner}
          securityCode={securityCode}
          cardPassword1={cardPassword1}
          cardPassword2={cardPassword2}
        />
  };
```
그래서 객체로 넘겨주던 props를 분리해 넘겨주고.. 리팩터링 했습니다. 여기부터는 코드가 너무 길어져서 생략하겠습니다.
<img width="477" alt="image" src="https://user-images.githubusercontent.com/56749516/233963750-02145a86-42aa-4bba-b0e9-5fcfa6ed8331.png">
<img width="478" alt="image" src="https://user-images.githubusercontent.com/56749516/233963925-1ddc2363-993c-44b8-a8c8-28ae633fe2f6.png">

그 결과입니다~! 공부를 하면서 정말 재밌었던 것 같아요!! 또 객체로 다 묶어서 props로 전달하면 이런 부분에서 문제가 발생할수도 있겠구나 싶었습니다.

2023-04-24 10:17 UTC, 2yunseong commented
안녕하세요 파랑~ 일단 코멘트 주신 내용 궁금한 점이나 논의하고 싶은 점 바탕으로 어느정도 한 것 같아 한번 더 제출합니다! 물론 아직 미흡한 점이 많지만, 지금까지 공부한 것이랑 생각한 것에 대해 피드백 받고 싶어 리뷰 요청 보내드립니다! 감사합니다 :)

2023-04-24 10:29 UTC, 2yunseong commented on src/stories/AddCardExpireDateInput.stories.tsx
> +};
스토리북에서 `onChange`등의 동작을 확인하기 위해 이런식으로 사용하는게 맞을까요?
[참고한 링크](https://storybook.js.org/docs/react/writing-stories/introduction#working-with-react-hooks)입니다.

2023-04-25 08:53 UTC, InSeong-So commented on src/components/InputCardData.tsx
> +const InputCardData = ({ value, onChange, name, className }: InputProps) => {
HTMLInputElement 타입과, InputHTMLAttributes 타입을 적용해보길 추천드려요!

2023-04-25 08:56 UTC, InSeong-So commented on src/hooks/usePasswordInput.ts
> +  };
코드 수를 줄이기 위해 다소 난해할 수 있는 내용을 암묵적으로 용인하는 것은 추후 문제가 생길 수 있는 부분을 덮고 가는 것과 같아요😂
피드백의 중점적인 내용은 `name` 속성이 필수값이 아니기 때문에 값이 없다면, setValue에 들어가는 저 키가 undefined일 수 있기 때문입니다. 이에 대한 방어 코드가 존재하지 않아 드린 코멘트에요~!

2023-04-25 08:56 UTC, InSeong-So commented on src/hooks/usePasswordInput.ts
> +  return [value, onChange] as const;
배열이 아닌 객체로 내보내는 것은 어떨까요~?

2023-04-25 08:58 UTC, InSeong-So commented on src/index.tsx
> +root.render(<RouterProvider router={router} />);
가볍다라는 것은 용량적인 크기가 아니라, **관심사**의 크기입니다. 현재는 CRA로 만들어진 앱이라 index.tsx, App.tsx 가 존재하게 되는데요, 우리는 App.tsx에서 전역적인 컴포넌트나 라우팅, 스토어 등을 설정합니다. 왜냐하면 JSX 구문이 깊어지고 실제 프로젝트가 구동될 때 설정을 총동원하는 파일이라서 그럽니다.

반면 index.tsx는 리액트가 "구동되기 위한" 단계로써 해당 프로젝트에 필요한 정적 리소스 등을 셋업하는 과정이기 때문에, 명확한 관심사의 분리가 필요하다는 관점에서 설명 드린겁니다~!

2023-04-25 09:01 UTC, InSeong-So commented on src/pages/AddCardPage.tsx
> +  };
navigate를 의존성으로 갖고 있기 때문에 지속적으로 리렌더링이 일어나지 않을까 싶네요!

리액트 진영에서 메모이제이션 적용 시점에 대한 의견은 분분하나, 지금은 공부를 하면서 어떻게 동작하고 무엇이 어떤 효과를 일으키는지를 더 많이 확인해보는 게 좋을 것 같아요. 그 경험을 통해 메모이제이션을 하면 좋은 곳, 그럴 필요 없는 곳을 명확하게 안 다음, 추후 큰 프로젝트를 진행하면서 취사선택이 가능하게 자시의 의견을 정리해두는 것은 어떨까요!?

저도 메모이제이션을 하지 않는 파였지만, 최근에는 대부분의 로직에 메모이제이션을 적용하고 있습니다😊 파일 갯수, 연산 내용이 많아지면 이런 장치 하나만으로 UX가 개선되기도 하거든요.

2023-04-25 09:13 UTC, InSeong-So approved these changes
아이고, 리뷰가 늦었네요!
궁금증에 대한 답변도 달았고, 리뷰도 남겨두었으니 확인바랍니다!

좀 더 핑퐁을 하는 것보다, 크게 재요청 하지 않고 스탭2를 진행하면서 점진적으로 고치는 것이 더 좋을 것 같아요.
따라서 이만 머지하도록 할게요!

궁금한 내용, 이해가 되지 않는 부분은 스탭2에 이어서 진행하면 좋겠습니다!

2023-04-25 09:13 UTC, InSeong-So commented on src/stories/AddCardExpireDateInput.stories.tsx
> +};
넵넵 잘 접근하셨어요!

2023-04-25 09:13 UTC, InSeong-So commented on .storybook/main.ts
> +const config: StorybookConfig = {
👀 한줄 띄어쓰기!

2023-04-25 09:13 UTC, InSeong-So commented on package.json
> +    "web-vitals": "^2.1.4"
CRA든, CVA든, CNA든 항상 의존성 파일을 유심히 보도록 해요!

2023-04-25 09:13 UTC, InSeong-So commented on src/components/AddCardExpireDateInput.tsx
> +        onChange={cardExpire.onChange}
value, onChange는 `AddCardExpireDateInput` 내부에 두는 것도 좋을 것 같네요!
꼭 props를 할당할 필요는 없어보입니다.

2023-04-25 09:13 UTC, InSeong-So commented on src/components/AddCardForm.tsx
> +    navigate('/');
try 스코프에 `navigate('/');`를 위치시켜도 좋을 것 같네요~!

2023-04-25 09:13 UTC, InSeong-So commented on src/components/AddCardForm.tsx
> +  const onSubmit = (e: React.FormEvent) => {
FormEvent의 제네릭 타입에 HTMLFormElement를 할당하면 좀 더 명확한 타이핑이 가능해집니다.

2023-04-25 09:13 UTC, InSeong-So commented on src/components/AddCardNumberInput.tsx
> +  const { first, second, third, fourth } = cardNumber;
객체로 값을 할당받게 되면 memo가 의미 없어집니다! memo의 동작 원리를 공부해보면 좋겠네요🤓

2023-04-25 09:13 UTC, InSeong-So commented on src/index.tsx
> +root.render(<AppRouter />);
엄격 모드!

2023-04-25 09:13 UTC, InSeong-So commented on src/pages/AddCardPage.tsx
> +    [onChangeCardNumber]
이게 어떻게 동작....하죠?
e는 이벤트 타입이고, onChangeCardNumber는 CardNumber인데....

2023-04-25 09:13 UTC, InSeong-So commented on src/pages/AddCardPage.tsx
> +      if (e.target.value.length > 0 && !isNumberInput(lastWord)) return;
`e.target.value` 를 변수로 선언해두면 어떨까요? 읽기가 조금 난해하네요🙃

2023-04-25 09:13 UTC, InSeong-So commented on src/pages/cardInputCondition.ts
> +};
단순 팁인데, React를 import하는 코드가 많다면 hook으로 분리하길 추천드립니다!

2023-04-25 09:13 UTC, InSeong-So commented on src/router/AppRouter.tsx
> +    <React.StrictMode>
오... 스트릭트 모드는 여기에 있는 것보다 index.tsx가 좋겠네요....! 관심사 분리 목적에서 말이죠🤗

2023-04-25 09:13 UTC, InSeong-So commented on src/stories/AddCardExpireDateInput.stories.tsx
> +export default meta;
```suggestion
export default {
  title: 'AddCardExpireDateInput',
  component: AddCardExpireDateInput,
  decorators: [
    (Story) => (
      <div
        style={{
          width: '210px',
        }}
      >
        <Story />
      </div>
    ),
  ],
} as Meta<typeof AddCardExpireDateInput>
```

export default 구문이 변수로 등장해버리면 대부분 스토리북의 보일러 플레이트 사용자 경험을 헤칠 수 있어서... 요렇게 추천 드립니다.

2023-04-25 09:13 UTC, InSeong-So commented on src/stories/AddCardExpireDateInput.stories.tsx
> +};
이렇게 진행할 때, AddInputHooks에 props를 동적으로 할당해야 한다면 어떻게 할 지 고민해보면 좋겠네요!

2023-04-25 09:14 UTC, merged

2023-04-25 09:25 UTC, 2yunseong commented on src/hooks/useInput.ts
> +) => {
진짜 많은 걸 배워갔습니다 :) 감사합니다

2023-04-25 14:56 UTC, 2yunseong reviewed
파랑 안녕하세요! 1단계 리뷰 감사드려요!

남겨주신 사항은 말씀 주신 것 처럼 2단계 때 점진적으로 반영하도록 하겠습니다!!

감사합니다 😃

2023-04-25 14:56 UTC, 2yunseong commented on src/hooks/usePasswordInput.ts
> +  return [value, onChange] as const;
`useState`처럼 비구조화 할당할 때 이름을 편리하게 붙이기 위해 배열을 리턴하였습니다!
안그러면 Hook을 사용할 때 마다 해당 이름을 다시 선언해 줘 불필요하게 코드가 길어진다고 생각합니다.
기능적인 차이는 어차피 배열 자체도 객체라고 생각했고, 여기서는 그렇게 큰 차이가 있지 않다고 생각해서 저는 배열로 선택하였습니다!
참고한 문서들 입니다.
https://tjinlag.medium.com/react-hooks-should-return-array-or-object-81b0a0fd4447
https://stackoverflow.com/questions/55214935/why-react-usestate-return-const-array

2023-04-25 14:56 UTC, 2yunseong commented on src/pages/AddCardPage.tsx
> +    [onChangeCardNumber]
네이밍이 심히.. 잘못되었습니다 .. 구조부터요... 다음 미션에 수정하겠습니다!!

2023-04-25 15:00 UTC, 2yunseong commented on src/pages/AddCardPage.tsx
> +  };
그렇군요 ㅎㅎ 남은 리액트 미션을 진행하면서도 고민을 많이 해봐야겠습니다 ..!! 파랑 덕분에 이번 미션에서 재밌고 깊게 공부해본 것 같아요!! 감사합니다!