[2단계 - 페이먼츠 미션] 도비(김정혁) 미션 제출합니다.
woowacourse/react-payments pull request #21
Opened 2021-05-01 18:14 UTC by zereight

안녕하세요 자프님!!

1단계에 이어서 2단계 미션 제출합니다!

일단! 1단계 PR에 남긴 피드백에 코멘트를 남겼습니다. [1단계 PR](https://github.com/woowacourse/react-payments/pull/5)
+ useMemo, useCallback도 모두 제거하였습니다.
+ 이번 미션에서는 styled-component를 Styled객체로 묶어서 전개하는 방식을 유지하겠습니다.

저는 2단계에서 추가적으로 적용할 수 있는 아래 사항 5가지 중에 3가지를 적용하였습니다.
- [x] 가상키보드 적용 (1단계-심화)
- [ ] Context API를 활용해 전역 상태 관리 및 계층 재구성 (선택)
- [x] 카드 목록 구현 (필수)
- [x] 카드 목록 CRUD (심화)
- [ ] JSON server 등을 활용한 비동기 통신 (심화)

Context API는 적용할 필요성을 아직 찾지 못하여 적용하지 않았습니다! 
JSON server는 fetch로 로직을 바꾸고, JSON server가 로컬 서버이므로 배포일때는 localStroage저장, 로컬일때는 JSON server로 동작 으로 환경변수로 코드를 분리하는데 대한 고민이 있어서, 시간상 step2 피드백 반영 시 또는 개인공부로 진행할 예정입니다 ㅎ.ㅎ;

## 추가된 기능 요구사항
- 가상 키보드
  - [x] 마스킹 처리된 값 입력시 사용
  - [x] 숫자를 랜덤으로 배열
  
- 카드 목록
  - [x] 카드 목록을 조회할 수 있다.
  - [x] 카드 목록은 최신순(내림차순)으로 정렬된다.
  - [x] 목록 최상단에 `+`을 누르면 카드 추가 페이지로 이동한다.
  - [x] 카드를 클릭하면, 카드 별칭 수정(카드 추가 완료 페이지)로 이동한다.
  - [x] 카드를 삭제할 수 있다.
    - [x] 카드를 2초이상 press시 삭제 버튼이 보여진다.

## 중점적으로 봐주셨으면 좋겠는 부분
- Context API를 적용하면 더 괜찮아질 수 있는 부분이 있는지?
- 가상키보드 컴포넌트가 잘 분리된것 같은지?
- 1단계에서 보이지 않았던 개선사항이 있는지?

## 질문있어요!
- **지금 PR 코드에는 반영되어 있지 않지만**, JSON server를 <del>다른 브랜치에서</del> 구현하면서, 생긴 질문들이 있습니다!
  1. useFetch의 구현
  ```js
    import { useState, useCallback, useEffect } from 'react';
    
    export default (defaultURL, defaultOption = { method: 'GET' }) => {
      const [url, setURL] = useState(defaultURL);
      const [option, setOption] = useState(defaultOption);
      const [data, setData] = useState([]);
    
      const fetchUrl = useCallback(async () => {
        const response = await fetch(url, option);
        const json = await response.json();
      
        if (option.method === 'GET' || option.method === 'PATCH') {
          setData(json);
        }
      }, [url, option]);
    
      useEffect(() => {
        try {
          fetchUrl();
        } catch (error) {
          console.error(error);
        }
      }, [fetchUrl]);
    
      return { data, setURL, setOption, fetchUrl };
    };
  ```
  저 나름대로 useFetch라는 커스텀훅을 구현하다가 의문이 들었습니다.
  fetch자체는 성공/실패가 있는 사이드 이펙트이므로 useEffect에 넣고, url/option/반환 data를 상태로 받고 있는 fetch 코드인데요.
  이 fetch 커스텀 훅에 대해서도 짧게나마 자프님의 의견을 듣고 싶습니다! (<del>best practice를 알려주시면 더 좋고</del>)

2. 이것도 JSON server를 구현하다가 생긴 질문입니다. JSON server는 로컬 환경의 서버이므로, gh-pages등에 호스팅했을때 사용할 수 없습니다. 
그래서 
> 배포환경(REACT_APP_ENV="stage")일때 -> 현재처럼 localStorage에 카드 정보 저장,
로컬환경(REACT_APP_ENV="dev")일때 -> JSON server에 카드 정보 저장

으로 동작하도록 구현하고 있었는데요. 환경변수를 통한 분기로 코드를 분리할때, 어떤 식으로 코드를 작성해야하나요?

제가 생각해본 방식은 아래와 같습니다.
```js

// 1번
// 한 개의 파일

// Component.js
if(process.env.REACT_APP_ENV === "dev"){
  import useLocalStorage from "./hooks";
  
  const [value, setValue] = useLocalStorage();
}else if(process.env.REACT_APP_ENV === "stage"){
  import useJsonServer from "./hooks";
  
  const [value, setValue] = useJsonServer();
}

// 2번
// 2 개의 파일(dev, stage)로 분리 후, 상위 컴포넌트에서 분기

//App.js
import Component from "./Component.js";
import ComponentDev from "./Component.dev.js";
process.env.REACT_APP_ENV === "dev" ? <ComponentDev/> : <Component/>

// Component.js
import useLocalStorage from "./hooks";
const [value, setValue] = useLocalStorage();
  
// Component.dev.js
import useJsonServer from "./hooks";
const [value, setValue] = useJsonServer();

```

제 생각에는 2번은 
- 파일을 분리해야하고
- 공통된 부분변경 시, 유지보수가 어려우며, 
- 컴포넌트에 대한 조건부 렌더링을 사용하는데, 해당 컴포넌트 하위에서 hook 사용 (조건부 렌더링되는 컴포넌트에서 hook사용은 지양해야함)

을 이유로 1번을 써야한다고 생각합니다.
근데 1번은 조건문 내부에 hook을 사용하므로, hook 사용 규칙에 위배(최상단이 아님)되어서 사용을 하지 못하고 있습니다.

실행 환경에 따라서 코드를 분기하고 싶으면 어떻게 해야하는지 조언을 듣고 싶습니다!

2021-05-02 09:12 UTC, wow9144 commented
1. 통신 부분을 useFetch 와 같은 커스텀 훅으로 사용하게 되면 컴포넌트에서 해당 훅을 사용할 것이므로 컴포넌트와 통신레이어가 바로 맞닺게 될 것 같습니다.
물론 컴포넌트 -> 훅 -> useFetch 도 되겠지만...
따라서 hook 이라는 틀 안에 fetch를 가둬놔서 설계의 유연성이 떨어질 것 같고, 그냥 fetch를 래핑한 함수와 비교해서 hook으로 만들었을 때 어떤 이점이 있을지 잘 모르겠습니다.

2. 환경변수를 통해 분기된다는 그 사실 자체를 사용하는 측에서 모르게 하면 됩니다.
useLocalStorage, useJsonServer를 추상화하는 좋은 이름을 하나 선정하시어...useF 라고 가정 할 때
컴포넌트에서는 그저 const [value, setValue] = useF() 로 쓰로 useF 의 구현부에서 환경에 따라 분기 쳐서 리턴 하면 될 것 같습니다.

2021-05-02 10:00 UTC, wow9144 requested changes
코드를 읽어내려가면서 2단계도 깔끔하게 한번에 머지 될것 같아서 흐뭇 하면서도 너무 코멘트가 없으면 서운(?)해 하실까봐 짜내려고 유심히 봤는데..... 
매우 위험한 폭탄이 하나 숨어있었네요! :)
저도 현직장인 쿠팡에서 3년전쯤 결제 관련 장애를 냈던적이 있는데(쿠팡캐시가 있어도 못쓰게 만드는ㅋㅋ) 그 때 생각이 났더랍니다...
각설하고.... 폭탄 제거 이쁘게 한 번 부탁드립니다.

2021-05-02 10:00 UTC, wow9144 commented on src/hooks/useMousePressTimer.js
> +let timer = null;
컴포넌트 내부에 state로 두는게 어땠을까 싶습니다.
useMousePressTimer를 동시에 여러곳에서 쓴다면 두번째 타이머가 실행되었을 때 값이 대체되어 첫번째 타이머가 clearTimer를 하면 두번째 타이머가 클리어 될 것 같습니다.

2021-05-02 10:00 UTC, wow9144 commented on src/components/VirtualNumericKeyboard/VirtualNumericKeyboard.js
> +      del
실무라고 가정하고....
도비님이 이렇게 만들어서 배포를 나갔고.... 그렇게 운영되다가 도비님이 퇴사를 하시고 제가 후임자로 들어갔습니다.
그 후 요구사항이 변경되었습니다. (디자이너의 단순 변심이든, 기획자나 PO의 요청이든.)

요구사항
as is
del

to be 
<- 모양의 아이콘.

단순히 버튼의 글자를 바꿔달라는 요청이라서 저는 글자만 바꾸고 배포를 나갔더니 결제가 안된다는 고객문의가 폭주하는 장애를 맞게 됩니다.
(실무에선 QA가 있으니 배포전에 발견 할수도 있겠지만 이 정도 변경사항은 보통 QA를 안돌립니다)
글자만 바꿨는데 키보드가 왜 망가졌지? 하고 코드를 거슬러 올라가서 커밋내역을 보고 누가 이렇게 만들었는지 확인을 하고 .......... 저는 모든 코드는 그렇게 된 이유가 있다고 생각하면서 넓은 마음으로 넘어갈 것입니다 :)


굉장히 위험하게 구현되었습니다. 
슬쩍봐서는 어디가 문젠지 명확하게 알수 없어서 발견하기도 어렵고, 발견했다고 한들 코드 진행이 많이 되어 있어서 덩치가 커진 상태라면 고치기도 어렵습니다. 

이 부분만 깔끔하게 수정 되면 2단계도 머지 할 수 있을 것 같습니다.

2021-05-02 11:16 UTC, zereight commented on src/components/VirtualNumericKeyboard/VirtualNumericKeyboard.js
> +      del
엌 제가 너무 안일한 코드를 작성했군요.. 예시를 너무 와닿게 설명해주셔서 공감이 되었습니다. 🥶
감사합니닷 ㅎㅎ

2021-05-02 11:24 UTC, zereight commented on src/hooks/useMousePressTimer.js
> +let timer = null;
앗; timer를 한곳에서만 사용해서 timer를 굳이 상태로 관리해야하나? 라는 생각이 들었었는데, 여러곳에서 사용할 수 있군요; 구현하다보니 현재 상황에 편협한 시각을 가지게 되는 것 같습니다. 반성..😞

2021-05-02 17:16 UTC, zereight commented on .env
> +REACT_APP_JSON_SERVER_PORT = 3001
취약점이 있는 변수가 아니라서 `.env` 파일도 커밋했습니다!

2021-05-02 17:17 UTC, zereight commented on src/App.js
> +    <span>{process.env.REACT_APP_ENV}</span>
현재 stage인지 dev인지 판단하기 위해 UI에 그려줬었습니다 ㅎ.ㅎ;

2021-05-02 17:18 UTC, zereight commented on src/api/requestCard.js
> +
fetch 코드를 추상화한것인데 요기 리뷰받고 싶습니다!

2021-05-02 17:20 UTC, zereight commented on src/hooks/useJsonServer.js
> +};
JSON server를 훅으로 최대한 빼보았는데요... 여기도 리뷰받고 싶습니다!!

2021-05-02 17:23 UTC, zereight commented on src/hooks/useLocalStorage.js
> +  return { value: parsedValue, setValue, addEntity, updateEntity, deleteEntity };
useLocalStorage 코드를 useJsonServer랑 사용형식을 맞추려고 하다보니 코드가 저렇게 되었습니다. ㅜㅜ
여기도 리뷰한번 부탁드립니다..😭
(stage/dev를 hook에서 import할때 분리하다보니 코드상에서는 사용형식이 동일해야했음)

2021-05-02 17:25 UTC, zereight commented on src/hooks/index.js
> +
요기서! 환경변수에 따라 localStorage hook을 사용하여 카드정보를 저장할지,
Json server hook을 사용할지 정해서, 실제 코드단에서는 환경변수를 모르도록 했습니다!

2021-05-02 17:30 UTC, zereight commented
안녕하세요! 자프님!
피드백 주신부분 반영하면 바로 머지해주실까봐. 😏
피드백을 더 받고 싶어서, 환경변수에따라 stage -> localStorage / dev -> JSON server를 분기하여 사용하는 코드를 추가로 작성했습니다!

추가적인 피드백 부탁드리겠습니다 ㅎ.ㅎ 🙏🙇‍♀️
- fetch 코드
- localStorage / JSON server custom hook 코드
위주로 리뷰를 부탁드리겠습니다 >_<//!!

2021-05-02 17:33 UTC, zereight commented on package.json
> +    "start:server": "json-server --watch db.json --port 3001",
stage/dev 실행 스크립트 2개, JSON server 구동 스크립트 1개가 추가되었습니닷

2021-05-03 02:53 UTC, zereight commented on src/api/requestCard.js
> +export default requestCardByType;
fetch 코드를 따로 추출하여 작성했는데요. 요기 리뷰받고 싶습니다!

2021-05-04 07:45 UTC, wow9144 requested changes
레전드의 길은 멀고도 험합니다.
조금 더 힘을 내세요 곧 될 것 같습니다. :)

2021-05-04 07:45 UTC, wow9144 commented on src/api/requestCard.js
> +  GET: [],
GET 리퀘스트중 문제가 생겼을 때 []을 디폴트값으로 한 것은 GET의 디폴트값으로 [] 이 적절하기 때문이 아니라, `카드리스트를 요청할 때` 라는 특정 상황이 여기의 구현에 영향을 미쳤을 것입니다.
구현부와 사용부를 한 사람이 한 시점에 같이 만들면, 구현부에서 해야 하는 관심사에 맞는 적절한 행위가 아니라 사용부에 특화된 로직이 구현부에 말려들어가는 경우가 생길 수 있으니 이런 부분을 인지하고 개발해야 합니다.
GET의 initial 값으로 적절한 값이 있다면 null 이 가장 적절 할 것 같습니다.
그럼 여기를 null로 바꾸면 기존 코드들이 최소한 [] 이 올것이라고 가정하고 작업이 되어 있을텐데 그 부분들이 다 수정되어야 하니까 여기 한군데만 손을 대는게 편한게 아니냐 라고 할 수 도 있는데, 그런 일을 해야 할 곳은 여기가 아니라 여기와 기존 코드의 사이 입니다.

2021-05-04 07:45 UTC, wow9144 commented on src/hooks/index.js
> +
👍

2021-05-04 07:45 UTC, wow9144 commented on src/hooks/useJsonServer.js
> +};
좋습니다. 
useJsonServer와 useLocalStorage 의 내부 구현은 다르지만 외부로 공개될 인터페이스를 동일하게 맞춰서 외부에서는 무엇을 쓰는지 모르게 하는 것 그것이 핵심인데 잘 하신 것 같습니다.
💯

2021-05-04 07:45 UTC, wow9144 commented on src/hooks/useLocalStorage.js
> +  return { value: parsedValue, setValue, addEntity, updateEntity, deleteEntity };
지금까지 useLocalStorage, useJsonServer 가지고 하신게 바로 객체지향 설계 5원칙중 5번째것인 Dependency Inversion Principle 이라고 보시면 됩니다. 👏 👏 👏 👏 👏 
1. 사용 형식이 동일해야 했다는 것을 알게 되셨고(동일한 인터페이스)
2. 그렇게 되니 사용하는쪽에서는 구체적으로 무엇을 쓰는지 몰라도 되고(구체적인것이 아닌 추상화에 의존)
세부 구현이 억지스러운 느낌이 들 수도 있지만 지금도 충분히 괜찮습니다. 
중요한것은 세부구현이 아니라 지금과 같은 탄탄한 설계 입니다.
아주 잘하셨습니다 👍

2021-05-04 07:45 UTC, wow9144 commented on src/components/VirtualNumericKeyboard/VirtualNumericKeyboard.js
> +      {DELETE_KEY}
위험도가 아주 약간 감소 되었으나 여전히 위험합니다.
그리고 사용하는측에서 키보드 내부의 구현을 너무 강하게 알고 있다는 설계 관점의 문제는 여전히 고쳐지지 않았습니다.
예전 코드는 이 키보드의 버튼에 변화가 생기면 그저 망가지는 것 뿐이었다면,
지금은 변화가 생길 때 그것을 처리하는 사람이, 내부에서 DELETE_KEY를 의존하고 있는 곳을 따라가서 CardAddForm에서 의존 하고 있다는 것을 알아차리고 둘 다 적절히 바꿔주겠거니 하는 가정이 깔려 있습니다.
이걸 알아차리지 못한다면 키보드는 또 망가질 것입니다.
내부 구현이 바뀌어도 사용하는 쪽에서 변경이 일어나지 않게 해야 합니다.
고로 사용하는쪽에서 if 문으로 이곳의 컨텐츠를 확인할 수 밖에 없게끔 디자인된 것이 폭탄입니다.
제안 드리고 싶은 방향은, 
1. 인터페이스를 onClick 하나로 해결하기 보다는 숫자입력과 지우기 2개로 나누거나, 
2. 하나로 한다면 여기서 결정된 숫자를 사용자측으로 넘겨주고 사용자는 지워진건지 숫자가 입력된건지를 아예 모르게 하는 방법이 있을 것 같습니다.(onChange 같은 느낌)

이 외에 다른 좋은 방향이 있다면 시도해보셔도 좋습니다.
이 폭탄은 제거되어야 머지를 해드릴 수 있을 것 같습니다. :)

2021-05-04 15:31 UTC, zereight commented on src/api/requestCard.js
> +    const res = await request.get(query);
> 가독성을 중요하게 챙겨야 할 곳이 있고, 그렇지 않아도 될 곳이 있다. (바뀔일이 거의 없는 곳)

"무조건 가독성이 높은 코드가 좋은 코드다" 라는 생각이 제 머릿속에 내재되어있었는데, 이때까지 작성했던 코드를 다시 생각해보게되는 말씀이시네요! 

언젠가 예전 리뷰에는 가독성을 위해서 다른 곳에 코드를 담아 놓고 쓰면 좋다고 리뷰를 주셨었는데 혼란럽습니다! @_@
<img width="676" alt="스크린샷 2021-05-05 오전 12 25 52" src="https://user-images.githubusercontent.com/42544600/117028223-76552f00-ad38-11eb-9433-a77a6bb5cdfd.png">

아마 `request`에서 `FETCH_METHOD.GET`같은 상수로 해당 동작을 유추할 수 있고, 
바뀔일이 거의 없는 코드이므로 
가독성이 좀 안좋더라도 
코드를 간단히해서 전체 코드가 눈에 들어오게 하는게 더 좋다.

라고 생각하면 될까요!

어떤 코드는 간단히 하는 것보단 가독성을 높이는 것이 좋고, 어떤 코드는 가독성을 낮추고 간단히 하는 것이 좋고...!
머리로 이해하는 것보다 몸으로 느껴보기위해서 자프님 말씀대로 바꿔보겠습니다!

2021-05-04 15:55 UTC, zereight commented on src/api/requestCard.js
> +
앗 놓친 부분 찾아주셔서 감사합니다!
request.js라는 이름으로 util 폴더에 분리하였습니다.

2021-05-04 16:38 UTC, zereight commented on src/api/requestCard.js
> +const headers = {
앗 header를 고정해두었군요! 
`useJsonServer`에서 header 초기값과 인자를 머지하여 requestEntity에 전달할 수 있도록 변경했습니다!

2021-05-04 16:43 UTC, zereight commented on src/api/requestCard.js
> +const requestCardByType = async (type, ...args) => {
핳; 네이밍 때문에 혼선을 드렸군요!!
`requestCardByType`을 `requestEntity`으로 변경하였고 파일분리는 하지 않았습니다!!

2021-05-04 16:54 UTC, zereight commented on src/api/requestCard.js
> +  GET: [],
오오 여기입니다. 이 부분이 애매하게 헷갈렸던 부분인데 정확히!! 짚어주셨습니다! (감사합니다 >_<)
카드리스트요청에 의존한 리턴값 때문에 위의 네이밍을 저렇게 했던것 같아요!

말씀주신대로 에러났을때 리턴값을 null로 통일하고, `useJsonServer` 훅에서 값이 유효하지 않으면 얼리 리턴을 해주었습니다! (null로 setValue가 되게 하지 않기 위해)

2021-05-04 23:16 UTC, zereight commented on src/components/VirtualNumericKeyboard/VirtualNumericKeyboard.js
> +      {DELETE_KEY}
ㅎㅎ 이 부분을 어떻게 해결하면 좋을지에 대해 고민하느라 밤을 홀딱 새웠네요!
수정한 부분에 대해서 코멘트를 남겼으니 제대로 수정되었는지 확인부탁드립니다!!

2021-05-04 23:18 UTC, zereight commented on src/components/VirtualNumericKeyboard/VirtualNumericKeyboard.js
>        {DELETE_KEY}
`VirtualNumericKeyboard`는 이제 숫자버튼에 걸어줄 onClick이벤트와 삭제버튼에 걸어줄 onClick을 따로 넘겨 받도록 하였습니다!

2021-05-04 23:19 UTC, zereight commented on src/hooks/useVirtualNumericKeyboard.js
> +        />
`useVirtualNumericKeyboard` 훅에서도 같은형식으로 수정되었습니다

2021-05-04 23:20 UTC, zereight commented on src/pages/CardAddForm/CardAddForm.js
> +
CVC, PasswordDigit에 대한 add/delete 함수를 따로 구현하여서 VirtualKeyboard에 인자로 넘겨줍니다.

2021-05-04 23:21 UTC, zereight commented on src/pages/CardAddForm/CardAddForm.js
> +
원하는 시점에 가상키보드 모달이 닫히게 하기위한 코드입니다 ㅎ.ㅎ

2021-05-04 23:29 UTC, zereight commented on src/hooks/useModal.js
> +  const closeModal = useCallback(() => setModalOpened(false), []);
[여기](https://github.com/woowacourse/react-payments/pull/21/commits/75e4e83ca19654608e42401c578314c2b65721da#r626170158)
useEffect내부의 `closeModal`이 계속 갱신되어 
[focus를 주면 -> 모달이 열리고 -> `closeModal`이 갱신되어 useEffect내부의 로직이 실행되고 -> 값이 모두 채워져있으므로 바로 닫힘] 
과정이 반복되어서 어쩔 수 없이 useCallback으로 감싸놨습니다. (값이 모두 채워진 상태에서도 focus주면 모달이 뜨게 하고 싶었습니다!)
(useEffect에서 closeModal 부분을 deps array에서 제거하는 방법도 있었으나 eslint의 경고 때문에 useCallback 사용)

2021-05-05 15:26 UTC, wow9144 commented on src/api/requestCard.js
> +    const res = await request.get(query);
일단 `가독성`이라는 말 자체가 모두에게 똑같이 객관적으로 적용되기 어렵다는 점을 알아두실 필요가 있습니다.
예를 들어 프로그래밍을 수십년 해와서 어렵고 복잡하고 잘못 설계된 스파게티 코드도 잘 읽을 수 있는 사람이 있는가 하면 프로그래밍을 접한지 얼마 되지 않아서 혹은 홀로 일한 세월이 많아서 남의 코드는 쉽든 어렵든 그냥 읽기 힘든 사람이 있을 수 있습니다.
이처럼 똑같은 코드라고 할지라도 코드를 읽는 사람의 수준 상태에 의해 누군가에게는 가독성이 좋게 느껴질수도, 누군가에게는 나쁘게 느껴질 수도 있고... 이처럼 예가 극단적이지 않고 비슷한 경력을 예로 든다고 할지라도 value는 v로, key는 k 로 index는 i로 이렇게 약어로만 변수를 짜왔던 사람이나 그렇게 해왔던 팀은, 그렇지 않고 풀어쓰는 사람이나 팀과 일할 때 좋은 `좋은 가독성`이 무엇이냐를 놓고 부딪히기 쉽습니다.
따라서 `가독성`도 결국 팀의 수준에 맞춰서 그 정도를 정한다고(정해진다고) 러프하게 생각하시는게 일단 좋을 것 같습니다.

어쨌든 전제가 위와 같고,
가독성이 좋으면 얻을 수 있는 장점은 코드를 쉽게 알아 볼 수 있고 그러니 수정하기도 쉬울 것 입니다.
다시 말하면 수정 할 일이 없으면 굳이 까서 볼 필요도 없고 볼 필요가 없으니 쉽게 알아 볼 필요도 없습니다.
다시 역으로 말하면 비즈니스는 계속 바뀔 수 있으니 비즈니스와 관련된 코드는 최대한 알아보기 쉽게 작성해야 한다는 결론이 나오겠습니다.
수정 할일이 없다고 미리 단언하는 것도 위험하고 설사 그렇다고 하더라도 일부러 암호처럼 작성하지는 않을테니 트레이드오프를 감안해서 상황에 따라 적절한 선에서 타협을 하시면 되겠습니다.

위 코드는 어떻게 해도 상관없을 것 같습니다.
다만 제 눈에는 await (await f1()).f2() 가 가독성을 논하고 자시고 할 정도가 아니라 그냥 평범한 일상적인 코드로 보이기 때문에...
혹시 이런식의 패턴을 모르셨으면 그냥 이렇게도 할 수 있구나 정도로 생각하고 넘어가셔도 될 것 같습니다.

2021-05-05 15:30 UTC, merged

2021-05-05 15:31 UTC, wow9144 commented
수고 많으셨습니다 👍