[페이먼츠 미션 Step 1] 엽토(김건엽) 미션 제출합니다.
woowacourse/react-payments pull request #216
Opened 2023-04-20 08:46 UTC by yeopto

안녕하세요 리트!
처음 뵙겠습니다! 솔로스타와 함께 페어프로그래밍을 진행한 엽토라고 합니다!

정말 어려웠던 미션이었습니다. 첫 번째 미션인 점심 뭐 먹지보다 몇 배는 어렵게 느껴졌습니다.
새로운 테스트 도구 사용과 TSX, Custom Hook 분리등 익숙하지 않은 것을 하다보니 더 어렵게 느껴진 것 같습니다.

저는 리액트를 다뤄본 경험이 별로 없습니다! 이번에 페어인 솔로스타에게 리액트와 타입스크립트에 대해 많이 배웠습니다.
솔로스타가 타입스크립트를 저보다 능숙하게 다룰 줄 알아서 많이 배우려고 노력했습니다.
하지만 제가 기초가 아직 부족해서 페어가 알려주는 것 중 타입관련하여 이해하지 못한 코드도 있습니다.
이해하고 넘어가고 싶었지만 미션 제출 기한이 있기 때문에 어떤 느낌인지만 이해하고 넘어간 부분이 있습니다..😂
그 부분에 대해서와 아래 코멘트에 남겨 놓겠습니다😅

이번 미션에서는 컴포넌트의 재사용성에 대해 고민을 많이 하며 미션에 임한 것 같습니다.
최대한 반복적으로 사용될 컴포넌트들이 뭐가 있을지에 대한 고민을 했고, 변화에 유한 범용성있는 컴포넌트를 만들고 싶었습니다.
저희가 생각한 범용적인 컴포넌트들은 `common` 디렉토리에서 관리해주었습니다.

컴포넌트 스토리들은 `common`에서 관리되는 컴포넌트 위주로 작성해봤습니다.
대부분의 컴포넌트들의 스토리를 작성하고 싶었지만 시간이 부족했습니다..
또, 처음 써보는 툴이라 이해하며 사용하는게 쉽지 않았던 것 같습니다.
하지만, 단일 컴포넌트를 바로바로 테스트 해볼 수 있다는건 큰 장점이란 생각은 들었습니다.

미흡한 코드입니다.. 앞으로 리액트 학습을 해나가면서 어떤 부분을 중점적으로 생각하며 학습하면 좋을지 알려주시면 정말 감사하겠습니다!
리뷰 잘 부탁드립니다 리트😿

[배포링크](https://yeopto.github.io/react-payments/)

2023-04-20 08:48 UTC, yeopto commented on src/components/App.tsx
> +};
Context API를 사용하여 Props Drilling을 최소화 해보았습니다!

2023-04-20 08:52 UTC, yeopto commented on src/hooks/useValidation.ts
> +};
useValidation이 위에서 제가 말했던 타입을 다 이해하지 못하고 넘어간 부분입니다.. 너무 어려운 것 같습니다 타입스크립트...

2023-04-20 20:31 UTC, lsw1164 requested changes
PR에는 어렵다고 하셨지만, 잘 구현해주셔서 놀랐습니다. 
생소함에서 오는 어려움은 지금처럼 피드백을 받고 성장하다보면 시간이 해결해줄 거 같아요 ㅎㅎ

공통화 시도한 부분도 좋습니다. 
컴포넌트 뿐만 아니라 hook도 잘 추출해주셨어요.

기본적인 리액트의 생명 주기는 익숙해지신 거 같아요.  
혹시 새로운 개념을 보신다면 공식 문서는 꼭 읽어보시고요.  

custom hook을 추출하고 활용하는 연습을 최대한 많이 해보는 걸 권장합니다.
지금 어려워하시는 타입스크립트도 계속 봐야됩니다. 
물론, 이미 생존형 공부법으로 아주 빠르게 익히고 계신거 같습니다ㅎㅎ;

2023-04-20 20:31 UTC, lsw1164 commented on src/components/common/Page.tsx
공통 레이아웃을 잡아주고 있군요?

2023-04-20 20:31 UTC, lsw1164 commented on src/context/PaymentsContext.tsx
> +    localStorage.setItem('creditCards', JSON.stringify(nextCreditCards));
같은 키를 공유한다면 상수화하면 어떨까요?  


localStorage가 아니라 백엔드 웹 요청을 통해 가져오는 코드로 바뀌었다고 가정해볼게요.  
어떻게 추상화할 수 있을까요? 그럴땐 localStorage에 직접 접근하지 않고 다른 방법으로 풀어가야 됩니다.

2023-04-20 20:31 UTC, lsw1164 commented on src/components/pages/NewCreditCardPage.tsx
에러 처리 깔끔하네요. 
한 번에 모든 오류를 보여주는 거 좋습니다.

2023-04-21 08:32 UTC, yeopto commented on src/components/App.tsx
> +};
Context Provider에서 값이 바뀐다면 Provider 하위 컴포넌트들도 re-render되기 때문에 적절하게 사용해야한다는 정도만 알고 있습니다!

2023-04-22 08:01 UTC, yeopto commented on src/hooks/useValidation.ts
> +};
일단 에러 메세지를 상수화해주었고, 성공 여부 메세지를 추가로 상수화했습니다.

상수를 이용하여 검증결과 타입을 만들봤는데요!
`ErrorMessage` 타입을 만들어주고, `SuccessMessage` 타입을 만들어 `isValidateMessage`라는 유니온 타입을 만들었습니다.

기존 검증 결과 타입인 `string | null`에서 `ErrorMessage | SuccessMessage`로 변경해주었습니다.
타입 변화에 따라 기존 null이면 통과하던 것을 `SUCCESS_MESSAGE`면 통과하도록 바꾸어주었구요!

이 변경이 리트가 말씀하신 의도가 맞겠죠..?😅

2023-04-22 08:11 UTC, yeopto commented on src/types/CreditCard.ts
> +  expirationDate: [string, string];
Month, Year을 명시적으로 해주었습니다!

2023-04-22 08:31 UTC, yeopto commented on src/components/CreditCardView.tsx
> +          <Text size="small" key={index}>
partialCardNumbers가 카드번호 배열인지라 key값으로 고유 id를 넣어줄 방법이 없었습니다. 그 값 자체를 key값으로 넣자하니 뒤에 두칸의 입력 숫자들은 ••••, ••••이라서 key 값이 겹쳐서요.. 그렇다고 lint rules에 추가하면 다른 곳에서 에러를 안 뱉을테니 어쩔 수 없이 주석으로 남겼습니다 🤣

2023-04-22 08:54 UTC, yeopto commented on src/context/PaymentsContext.tsx
> +    localStorage.setItem('creditCards', JSON.stringify(nextCreditCards));
일단 상수화는 해주긴했습니다..

근데 밑에 말씀해주신 부분을 잘 이해하지 못했습니다..😥

localStorage의 접근해서 가져온 것과 요청을 통해 가져오는 것은 로직이 다를텐데 두 방법을 한번에 할 수 있도록 추상화를 시켜보란 말씀이신가요? 그렇다면 그것이 상수화와 어떤 관련이 있는건지 잘 모르겠습니다! 제가 잘못 이해하는 것 같습니다..

2023-04-22 08:57 UTC, yeopto commented
리트!
피드백 주신 것들을 반영해보았습니다!
피드백 주신 의도와 맞게 제가 잘 반영한건지 모르겠네요!! 
혹여나 다른 부분이 있다면 말씀해주시면 열심히 반영해보겠습니다!!

추가로 카드번호 입력시 카드에 카드번호가 뒤로 밀려나길래 그거 수정해줬습니다!

2023-04-22 16:24 UTC, lsw1164 requested changes
엽토, 피드백 반영한 부분 확인했어요👍  
빠르게 잘 수행해주셨습니다.  
다음 스텝으로 넘어가도 좋을 거 같아서 merge 할게요.
못끝낸 코멘트 대화는 이어서 남겨주세요.

다음 제출에는 스토리북 배포 링크도 남겨주시면 좋을 거 같아요🙇‍♂️

2023-04-22 16:24 UTC, lsw1164 commented on src/context/PaymentsContext.tsx
> +    localStorage.setItem('creditCards', JSON.stringify(nextCreditCards));
제가 혼동을 드렸어요😭
네, 상수화는 키값 한정입니다. 잘 수정해주셨고요. 
추상화 얘기는 상수랑 별도의 Context입니다. 

추상화 얘기를 따로 해보자면 관심사 분리를 생각해서 드렸던 피드백입니다. 
지금 creditCards 정보를 어딘가에서 가져오고 저장하고 있는데요.  
그 `어딘가`를 사용처 입장에서 일반화 해보면 `신용카드 정보 저장소`라고 할 수 있을 거 같아요.  

그런데 `신용카드 정보 저장소`가 `로컬스토리지를 사용하는 지`, `웹 요청을 통하는 지`는 `사용처의 관심사가 아니라고 생각`했어요. 그래서 레이어를 한 단계 두고 추상화하는 연습을 해보면 좋겠다고 생각했어요.  
그렇게 추상화해두면 나중에 웹 요청하도록 바꾸더라도, `신용카드 정보 저장소` 한 곳만 수정해주면 되겠죠?

2023-04-22 16:25 UTC, merged