[1단계 - 페이먼츠 미션] 그루밍(강민경) 미션 제출합니다.
woowacourse/react-payments pull request #22
Opened 2021-05-02 03:54 UTC by ddongule

안녕하세요! 
인치(@hchayan)와 함께 페이먼츠 미션을 진행한 그루밍입니다!
앞선 로또 미션 2단계에서 배웠던 함수형 컴포넌트를 사용해 미션을 구현했습니다.
리액트로 미션을 구현하니.. 편하고 또 신기한 점이 정말 많습니다...!
점점 재미있어져서.. 자꾸 기능을 더하고 싶다는 욕심이 생기지만..
이번 미션은 기본에 충실하면서 기존에 배웠던 내용을 조금 더 Deep하게 공부했습니다!
아직 부족한 코드지만.. 리뷰 잘 부탁드립니다아!!!!!!!!! 🧡🔥!!!!!!!!!!!!!!!! 
감사합니다아!!!!!!✨✨

[데모 페이지](https://ddongule-payments.netlify.app/)

## 🧪 구현한 기능 및 테스트
**Preview**
![1](https://user-images.githubusercontent.com/26598561/116800730-b9e44900-ab3e-11eb-83b9-517531e37c66.gif)

#### Storybook 테스트
- [x] `Storybook` 상호 작용 테스트

#### 카드 추가 구현
- [x] 카드 추가 컴포넌트가 렌더링됨과 동시에 카드 종류 선택 모달이 보여진다.
- [x] 아래 폼에 작성하는 내용이 카드 미리보기에 실시간으로 보여진다.
- [x] 카드 미리보기를 클릭하면 카드 종류 선택 모달이 보여진다.
- [x] 카드 종류를 선택하면 모달이 닫힌다.

1. **카드 번호 입력**
   - [x] 카드번호 숫자 16자리중 뒤의 8자리는 `•` 로 숨김처리 된다.
   - [x] 카드번호 4자리마다 `-` 가 자동으로 보여진다.
   - [x] 카드번호 8자리 채워지면 키보드 모달이 자동으로 보여진다.
   - [x] 키보드 모달은 총 11개의 버튼이 있다. (0~9숫자, 지우기)
   - [x] 지우기 버튼은 고정, 숫자는 모달 열릴때마다 랜덤으로 배치된다.
   - [x] 카드번호 16자리 입력하거나, 지우기로인해 7자리 이하로 떨어지면 키보드 모달이 자동으로 닫힌다.
2. **만료일 입력**
   - [x] 만료일 숫자는 4자리 입력 가능하다.
3. **카드 소유자 이름 입력**
   - [x] 카드 소유자 이름은 입력하지 않아도 된다.
   - [x] 카드 소유자 이름은 `String`이어야 한다.

4. **보안 코드 입력**
   - [x] 보안 코드 숫자는 3자리 입력 가능하다.
   - [x] 보안 코드 입력 칸 오른쪽에 물음표 버튼이 있다.
   - [x] 물음표 버튼을 누르면 CVC 코드설명 모달이 보여진다.
   - [x] CVC 모달은 화면 아래에 뜬다.
   - [x] CVC 모달에는 보안카드 텍스트, 이미지, 확인버튼 내용이 있다.
   - [x] CVC 모달의 확인버튼을 누르면 모달이 닫힌다.

5. **카드 비밀번호 입력**
   - [x] 카드 비밀번호 입력칸 하나에는 0~9 사이의 숫자가 들어간다.
   - [x] 위의 입력 form이 다 입력되어야 다음버튼이 활성화 된다.
   - [x] 다음버튼을 누르면 카드추가완료 컴포넌트가 렌더링된다.

#### 유효성 검증
- **카드번호를 덜 입력하셨어요! :(**
  - [x] 카드번호는 16자리를 입력해야한다.
  - [x] 카드번호는 `Number`이어야한다.
- **유효한 연월이 아니에요. :(**
  - [x] 월은 01 ~ 12 사이의 숫자만 허용된다.
  - [x] 년도는 올해 이상이여야 한다.
- **만료일이 정확하지 않아요. :(**
  - [x] 오늘 연월보다 유효한 이후 연월이여야 한다.
- **이름에 특수문자, 숫자, 30글자 이상의 글자는 작성할 수 없어요. :(**
  - [x] 카드 소유자 이름은 30글자 이하여야 한다.
- **CVC 코드를 덜 입력하셨어요! :(**
  - [x] CVC 번호는 3자리 입력해야한다.
  - [x] CVC 번호는 `Number`이어야한다.
- **카드 비밀번호를 덜 입력하셨어요! :(**
  - [x] 카드 비밀번호는 `Number`이어야한다.
  - [x] 카드 비밀번호는 input 당 한자리 숫자여야 한다.

## 📁 폴더 구조
```
├── App.js
├── App.styles.js
├── __snapshots__
│   └── storybook.test.js.snap
├── common
│   ├── Button.js
│   ├── Button.stories.js
│   ├── Card.js
│   ├── Card.stories.js
│   ├── Input.js
│   ├── Input.stories.js
│   ├── Modal.js
│   └── Modal.stories.js
├── components
│   ├── CardAdditionComplete
│   │   ├── index.js
│   │   └── index.styles.js
│   ├── ModalContents
│   │   ├── CVCHelp
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   ├── CardColor
│   │   │   ├── CardColorItem
│   │   │   │   └── index.js
│   │   │   └── index.js
│   │   └── Keyboard
│   │       ├── index.js
│   │       └── index.styles.js
│   ├── Nav
│   │   ├── index.js
│   │   └── index.styles.js
│   ├── NewCardForm
│   │   ├── CardCVCInput
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   ├── CardExpireDateInput
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   ├── CardNumberInput
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   ├── CardPasswordInput
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   ├── CardUserInput
│   │   │   ├── index.js
│   │   │   └── index.styles.js
│   │   ├── cardFormValidator.js
│   │   ├── index.js
│   │   └── index.styles.js
│   └── assets
│       └── cvv-300x300.png
├── constants
│   └── constants.js
├── global.styles.js
├── index.js
├── storybook.test.js
└── utils
    └── utils.js
```
## 📝 느낀점
### Style - Styled-Components 사용
지금까지는 그냥 css/scss만을 사용해 스타일을 적용했었다가 이번에 저는 Styled Component를 처음 사용해보았습니다! 원래는 JS에서 `addClass`, `removeClass` 등을 이용해야했었는데 styled-components를 사용하니 조건을 따라 스타일링 해줄 수 있어서 굉장히 사용하기 편리하기도 하면서 인상깊었습니다. 
그렇게 사용하면서 이번 미션에서는 font-size, font-weight, color 등을 constants로 관리해줬었는데요, 생각해보니 굳이 이렇게 JS파일로 관리하지 않고도 global style에 미리 css 변수를 지정해두고 사용하는 방법을 택해도 되었을 것 같다는 생각이 듭니다. 스타일링을 적용하는 방법도 굉장히 다양하다는 것을 느꼈고, 여러가지 적용해보면서 스타일링도 더 잘 만들어나가고 싶다는 생각이 들었습니다. 다른 크루들이 쓰는 tailwind-css 등도 궁금하네요호~!! 👀 😆 

## 🧐 궁금한 점
### 1. Controlled Components vs Uncontrolled Components 
#### 제어/비제어 두가지, 함께 써도 될까요?
  이번 미션을 진행하면서 제어/비제어 컴포넌트에 대해 새로 배웠습니다. 이번 미션은 input을 이용해 form을 다루는 내용이 많았던 만큼   제어/비제어 컴포넌트에 대해 공부해보고 더 잘 사용해보고 싶었는데요, 생각보다 쉽지 않았습니다 ㅠㅠ !! 
단순히 값만을 제어한다면 구현하기 어렵지 않았지만, 그 뿐만 아니라 사용자 경험을 위한 auto focus와 같은 기능들을 넣으려면 결국 두가지를 혼용해서 사용해야 한다고 생각했습니다. 그런데 이렇게 사용하면 결국 제어컴포넌트도 비제어컴포넌트도 아닌 것이 되어버리는 것 같습니다ㅠㅠ..😭 혹시 리뷰어님께서는 auto focus와 같은 기능들을 제어 컴포넌트에서 구현하실 때 어떤 방법을 사용하시나요? 이렇게 두가지를 모두 사용하는 방식에 대해서도 어떻게 생각하시는지 궁금합니다!

### 2. 컴포넌트를 만드는 과정!
`src/common`을 보시면 가장 기본적인 컴포넌트들, 재사용이 많은 컴포넌트들을 만들어 넣어두었습니다. 이 기본적인 컴포넌트들을 먼저 만들고 거기에 곁다리를 더해서 컴포넌트들을 만들어나갔는데요! 가장 작은 단위부터 만들어나가는 것이라서 전체적인 페이지 구조를 이해하며 미션을 구현하는 데에는 도움이 많이 되었지만, 가끔 컴포넌트들을 만들 때 추가해야 하는 내용 때문에 기본 컴포넌트를 조금씩 수정해야 하는 일이 생기기도 했습니다.💣💣 그래서 아예 만들어보고 그중에서 공통된 부분을 빼는 방식을 사용해보면 어떨까 라는 생각이 들기도 했습니다. 혹시 리뷰어님은 어떤 방식을 더 선호하시는지 궁금합니다! 

🔥⭐️🔥⭐️🔥⭐️🔥
최대한 컴포넌트를 유용하게 사용해 미션을 구현해나가려고 했는데.. 코드를 읽기 쉽게 만들었는지는 의문입니다.. 😭😭😭
그렇지만.. 열심히 했습니다.. 하하..
항상 부족한 코드 잘 살펴봐주셔서 감사합니다!!!!!!!!!!!!!!!!!!!!
이번 미션도 잘 부탁드립니다!!!!!!  >>ㅑ!!!!!!!✨✨
여러가지 다양한 말씀 기다리고 있겠습니다 !!!!!!!!!!!!!
감사합니다!!!!!

2021-05-03 14:11 UTC, HyeonaKwon commented on src/App.js
> +    },
배열로 하지 않고 객체로 한 이유가 있을까요??

2021-05-03 14:12 UTC, HyeonaKwon commented on src/App.js
> +  };
16~35 라인에서 사용하는 객체와 똑같은데 중복을 줄일 수 있는 방법은 없을까요~?

2021-05-03 15:14 UTC, HyeonaKwon requested changes
안녕하세요! 1단계 미션 잘 봤습니다 :)
세부적인 내용은 코멘트로 남겼으니 확인 부탁드립니다!

질문
1. 음 제가 보기엔 비제어 컴포넌트를 어디에 사용하셨는지 보지 못했는데 코드 짚어주실 수 있으실까요?
2. 프로젝트를 본격적으로 구현하기 시작할 때 이미 `필요하겠다!` 싶은 기본 컴포넌트들이 있잖아요! 그런것들은 먼저 개발해두고 시작합니다. 저희팀은 보통 동료들과 같이 개발하는 경우가 많기 때문에 공통 컴포넌트를 미리 만들고 그걸 같이 사용할 수 있도록 해둡니다. 이 후 개발하다보면 공통 컴포넌트로 뺄 수 있었겠다 싶은 컴포넌트들이 보이잖아요! 그런것들은 리팩토링 때 공통 컴포넌트로 빼기도 합니다. 그루밍님께서 고민하신 부분은 충분히 공감해요. 그래서 공통 컴포넌트는 다른 속성값을 추가하기 쉽도록 만드는게 중요합니다. 확장성있게요!

UI
1. 카드 16자리 입력하니 UI 가 깨지네요!
![image](https://user-images.githubusercontent.com/46472795/116894746-5efd3f80-ac6d-11eb-893d-adb43a9c79cd.png)
2. validation 이 true 였다가 false 가 될 때 또는 그 반대일 때 바로 '다음' 버튼이 없어지는게 아니라 좀 아쉽네요. onBlur 때문이겠죠?
![image](https://user-images.githubusercontent.com/46472795/116894969-a1268100-ac6d-11eb-8823-7ffd4185d89b.png)

2021-05-03 15:14 UTC, HyeonaKwon commented on src/components/NewCardForm/cardFormValidator.js
> +};
그리고 이 파일은 컴포넌트가 아닌데 components 폴더에 있네요!  
utils 로 빼지 않은 이유가 있을까요?

2021-05-04 12:33 UTC, ddongule commented on src/App.js
> +    },
헛.. 배열로 만드는 것을 처음부터 고려해보지를 않았었네요..! 제자신.. 왜 그랬을까요..? 😲😲😲 (충격)
다음부터는 어떤 State를 만들 때 생각나는대로 구현하지 않고 (ㅠㅠ) 다양한 형태를 고려하고 만들도록 연습해야겠습니다..! 찝어주셔서 감사합니다 >__ㅇ!!!!
순서가 있는 형태이고 key가 first, second, third, fourth 라는 형태라면 배열로 한번 만들어봤어도 괜찮았을 것 같다는 생각이 드는군요..
그런데.. 만약 배열로 만들었었어도 아래와 같은 이유로 객체의 형태로 다시 바꾸지 않았을까.. 하는 생각도 듭니다! 

`CardInfo` 안에 있는 depth가 필요한 친구들을 비슷한 형태(객체)로 만든 덕분에 사용자에게 Validation Message를 보여주는 로직을 구현할 때에 추상화를 잘 할 수 있었다고 생각하기 때문입니다!! 포홍홍ㅎㅎ

(요 로직입니다!)

```js
// NewCardForm/index.js
  const onChangeCardInputObject = ({
    target: {
      name,
      value,
      dataset: { detail },
    },
  }) => {
    const message = messageObject[name](value);
    setErrorMessage({
      ...errorMessage,
      [name]: message,
    });

    if (message !== '') return;

    setNewCardInfo((prevInfo) => ({
      ...prevInfo,
      [name]: { ...prevInfo[name], [detail]: value },
    }));
  };
```

만약 배열로 만들었으면 Input마다 onChange함수를 따로 만들어야하는 번거로움이 생겼을 것 같습니다 허헛 
이런 이유로 제가 생각했을 때 배열로 만드는 것보다 이렇게 객체로 만드는 편이 더 괜찮은 선택이었다는 생각이 듭니다. 혹시 리뷰어님께서는 어떻게 생각하실까요!?

2021-05-04 12:38 UTC, ddongule commented on src/App.js
> +  };
헉 중복됨을 인지하지 못하고 있었습니다! 
중복되는 `CardInfo` 객체를 `defaultCardInfo`로 분리해 재사용했습니다! 
감사합니다 >__<!!! 😉

커밋 링크: [`83ba633`](https://github.com/woowacourse/react-payments/pull/22/commits/83ba633b35b00e5b7950ec26219dd0a96c79e242)

2021-05-04 12:42 UTC, ddongule commented on src/App.js
> +  });
헛 그렇겠네요! 말씀주신 두가지 이유에서 state을 위로 올리는 편이 더 좋을 것이라는 생각에 동감합니다! 
다른 State들과 함께 조금 더 위로 올리고 싶었으나.. `openModalContent`에서 쓰이는 `modalContentsObject`, `handleCardColor`가 있어서 부득이하게 그 아래로 위치를 바꾸어놓았습니다!

커밋 링크: [`af15b10`](https://github.com/woowacourse/react-payments/pull/22/commits/af15b101e9a0ad47039871ca5f56122d922c8438)

2021-05-04 12:56 UTC, ddongule commented on src/App.js
> +        )}
오우 그렇군요! 안그래도 `App` 부분이 너무 비대해져서 보기가 조금 불편하다고 생각하고 있었습니다..!
온갖 State들과 handler들로 고통받는 제 App이 조금이라도 가벼워질 수 있다면. . . 흑흑  😢 😢 
Components로 분리하는 편이 훨씬 보기 좋네요! 감사합니다!!

커밋 링크: [`613bd4f`](https://github.com/woowacourse/react-payments/pull/22/commits/613bd4f0fa659a15bc7c231e5ea3e89320a8d7a0)

그런데 문득 궁금한 점은.. 원래 이렇게 App이 뚠뚠해지는게 맞을까요? 🐷 🐷 .. 따흐흑
State를 따로 관리해주는 이유에 이런 이유도 포함될까요..? 허헛헛

2021-05-04 13:02 UTC, ddongule commented on src/App.js
> +        )}
오우.. 댑악 저번 react-lotto 리뷰에서도 한번 말씀 듣고 조금 찾아보기만 하고 적용해보지 못했었는데..
원하는 DOM을 선택해 Render가 가능하고 상태관리는 이전과 같이 사용할 수 있다는 점에서 굉장히 모달에 적합한 내용인 것 같습니다! 
2단계 미션에서 한번 리팩토링 해보는 형태로 가져가보겠읍니다. . . (2단계의 내자신에게 위임. . . )
2단계에서 제가 적용하지 않았다면 혼내주세요. . . 🔥 🔥 🔥

2021-05-04 13:09 UTC, ddongule commented on src/common/Card.js
> +      year: '',
defaultProps에 아무리 default 값을 정해놓아도 `''` undefined가 아닌 빈 String 형태가 들어가다보니 먹히지가 않더라구요. . . 사실 여기에 적어뒀던 `user: 'NAME'`도 안먹히고 있었습니다! (충격) 😮😮😮 ㅋㅋㅋ ㅠㅠ
혹시 이렇게 빈 String이 기본 State로 들어갈 때에도 default Props를 주는 방법이 따로 있을까요?
초기 State를 설정할 때에 `undefined`를 주어야할까요..? 
제 생각에는 이렇게 undefined로 초기화하는 방법은 초기 State를 설정할 때에 알맞지 않은 방법 같아서 일단 현재 상태 그대로 두고 비록 적용되지는 않지만 defaultProps에 말씀주신대로 명시만 해두었습니다...! 
더 나은 방법이 있으시다면 힌트를 주실 수 있을까요..?! 따흐흑.. 힌트를 보고 다시 반영하겠습니다..!

2021-05-04 13:12 UTC, ddongule commented on src/common/Input.js
> +  color: #383838;
헉 상수화를 할 때에 미처 함께 데리고 가지 못한 친구들이 곳곳에 남아있나봅니다. . . ^ ^ . . . 
뒤처진 친구들을 주섬주섬 상수화 시켜보았습니다 . . ^ ^ . . 
감사합니다. . . ! >>ㅑ륵 . . . !!!!! 

커밋 링크: [`00cfb3a`](https://github.com/woowacourse/react-payments/pull/22/commits/00cfb3a24976d9950e8975cffc6920e4e1ca7f02)

2021-05-04 13:12 UTC, ddongule commented on src/common/Input.js
> +  background-color: white;
[요 리뷰](https://github.com/woowacourse/react-payments/pull/22#discussion_r625125774)에서 모두 상수화 시켰습니다! 감사합니다 >__ <!!

2021-05-04 13:15 UTC, ddongule commented on src/components/CardAdditionComplete/index.js
> +    alert('새 카드가 등록되었습니다.');
오.. 지당하신 말씀입니다! 노티를 addNewCard가 끝난 후 보여질 수 있게 변경했습니다! 감사합니다 👍 >__<!!

커밋 링크: [`1ca0520`](https://github.com/woowacourse/react-payments/pull/22/commits/1ca05207c4a5f9864d457fb3452ff452687f6ec6)

2021-05-04 13:19 UTC, ddongule commented on src/components/NewCardForm/cardFormValidator.js
> +  if (value.length > 4) {
따흑 요부분은 상수화를 생각하지 못했네요 AddCard Component로 분리하면서 상수화를 같이 진행했습니다. . .!!! (커밋을 나눈다는걸. . 깜빡했네요. . ) 하핫핫 !!! 
상수화!!! 더 신경쓰도록 하겠습니다!!! 

커밋 링크: [`613bd4f`](https://github.com/woowacourse/react-payments/pull/22/commits/613bd4f0fa659a15bc7c231e5ea3e89320a8d7a0)

2021-05-04 13:23 UTC, ddongule commented on src/components/NewCardForm/cardFormValidator.js
> +};
[요 링크](https://github.com/woowacourse/react-payments/pull/22#discussion_r625140448)에서 상수화 같이 진행했습니다!

헉 그렇군요.. 요 부분은 앱 전체에서 범용적으로 쓰이는 `util`이라기 보다는 CardForm에서만 쓰이는 친구라고 생각해서.. 함께 쓰이는 친구들끼리 요렇게 묶어주었습니다! 
항상 요렇게 `util`로 보기는 애매하고 `Components`는 또 아닌 친구들을 어떻게 빼야할지에 대해 고민이 들곤 합니다. . ! 이런 친구들도 util로 빼는 것이 좋을까요? util을 어디까지로 봐야할지에 대한 고민이 듭니다. . . 흠. . .

리뷰어님께서는 어떻게 생각하시나요?!?

2021-05-04 13:24 UTC, ddongule commented on src/components/NewCardForm/index.js
> +      cardInfo.cvc.length === 3;
요 친구들도 [요기 링크](https://github.com/woowacourse/react-payments/pull/22#discussion_r625140448)에서 상수화 같이 진행했습니다! 감사합니다악!!

2021-05-04 13:24 UTC, ddongule commented on src/components/NewCardForm/index.js
> +    if (cardInfo.cardName === 'DEFAULT') {
마찬가지로.  . .  [요기 링크](https://github.com/woowacourse/react-payments/pull/22#discussion_r625140448)에서 상수화 같이 진행했습니다아!!!!!! 감사합니다악!! 👍

2021-05-04 13:27 UTC, ddongule commented on src/components/ModalContents/CardColor/index.js
> +// TODO : style 분리
허허허 미처 발견못한 TODO가 남아있었군요 ^ ^ ; ; ; 
이친구도 슥 Style 분리를 해주었습니다 호호홋 ^ ^ !!!  💘 , , , 

커밋 링크: [`613bd4f`](https://github.com/woowacourse/react-payments/pull/22/commits/613bd4f0fa659a15bc7c231e5ea3e89320a8d7a0)

2021-05-04 13:43 UTC, ddongule commented on src/components/NewCardForm/CardNumberInput/index.js
> +      </div>
오우 페어와 저도 이 부분을 map을 사용해 돌리는 방법을 생각해봤으나.. `data-detail`, `value`가 달라서 실패했었습니다 따흐흑 ㅠㅠ 말씀주신대로 다시 해보니 중복을 제거할 수 있었습니다!!!
객체라서 `Object.keys`를 사용해 중복을 제거해 보았습니다! 감사합니다!! >___< 

커밋 링크: [`c1a6549`](https://github.com/woowacourse/react-payments/pull/22/commits/c1a6549c8e50d47d6ce39d2d588d9ca9395ce935)

2021-05-04 13:49 UTC, ddongule commented on src/components/NewCardForm/index.js
> +  };
오우 렌더링 될 때마다 messageObject를 다시 만들 필요가 없겠네요! 말씀주신대로 validation 폼에서 import 하는 방식이라면 messageObject를 다시 만들지 않고도 사용할 수 있을 것 같아 분리했습니다! 알려주셔서 감사합니다 >__< 홍홍홍!! ❤️ 


커밋 링크: [`81ea0ab`](https://github.com/woowacourse/react-payments/pull/22/commits/81ea0abd7d06b444396abaf313a0b01d02a2a2f4)

2021-05-04 15:29 UTC, ddongule commented on src/common/Card.js
> +      add={add}
오.. 혹시 enum이 타입스크립트에서 주로 사용하는 내용이 맞을까요? 자바스크립트에서 어떻게 써야하는지 감이 잘 오지 않아서.. 혹시 힌트를 조금 더 주실 수 있을까요? ㅠㅠ 따흐흑 

add라는 이름은 명시적인 이름이 아닌 것 같아서 cardMode로 네이밍을 변경했습니다! 

커밋 링크: [`c69da51`](https://github.com/woowacourse/react-payments/pull/22/commits/c69da51b9103931e44ff049c0c2c73dbfd0a99c8)

2021-05-04 15:51 UTC, ddongule commented
안녕하세요 리뷰어님!!!!!!!!!! 
먼저 세심한 리뷰 정말정말 감사드립니다아!!!!!!!!! 🥰 🥰

남겨주신 리뷰에 대해서 반영해보고 궁금한 점을 코멘트로 남겨보았습니다 허헛 ㅠㅅ ㅠ!! 
그리고 제가 PR에 질문을 명확히 쓰지 못했나봅니다! 따흐흑 죄송합니다 ㅠㅅ ㅠ

> 1. 음 제가 보기엔 비제어 컴포넌트를 어디에 사용하셨는지 보지 못했는데 코드 짚어주실 수 있으실까요?

→ 결론은 사용하지 않았습니다! 혼용해서 쓰는것이 맞는것인지에 대한 고민이 들어서.. 일단 제어 컴포넌트로 구현했습니다! 

> 2. 카드 16자리 입력하니 UI 가 깨지네요! 

→ 혹시 어떤 브라우저로 들어가신걸까요?! 저는 크롬에서 잘 보이는데 ㅠㅠ 따흐흑 알려주시면 참고해서 반영해보겠습니다!! 

> 3. validation 이 true 였다가 false 가 될 때 또는 그 반대일 때 바로 '다음' 버튼이 없어지는게 아니라 좀 아쉽네요. onBlur 때문이겠죠?

→ 헉 맞습니다! onChange에 validation과 setCardInfo를 두개 다 넣어봤는데. . 이것도 실시간으로 반영이 되지는 않더라구요. . 왜그런지 아직 이유를 찾지 못했는데.... 다시 한 번 생각해보고 고쳐보겠습니다 ㅠㅠ!!! 

부족한 부분이 많지만.. 꼼꼼히 봐주셔서 감사합니다 😭 😭
하지만 아직 해결되지 않은 궁금한 점이 많아,, 송구스럽습니다,, 따흐흑 
힌트 주시면 다시 한 번 고쳐보겠습니다..!!!!!!!!!!!!! >>ㅑ!!!!!
리뷰 주셔서 감사합니다!!!!!!!!!!!!!🥺☀️🥺☀️🥺 ㅠㅠ

언제나 행복한 하루 되세요 >__ _<🧡

2021-05-04 15:54 UTC, ddongule commented on src/components/ModalContents/Keyboard/index.js
> +            className='keyboard-node'
오우 styled-components의 권고 사항을 지키는 것이 맞는데 제가 두가지를 혼용해서 사용하고 있었군요..! 이부분에 대해서는 생각하지 못했는데 알려주셔서 감사합니다!
권고사항에 맞추어 styled-components를 사용하기 위해 className들을 없애보았습니다! 
다음부터는 더 유의해서 만들어보도록 하겠습니다아!! 감사합니다!! 


커밋 링크: [`86e8b66`](https://github.com/woowacourse/react-payments/pull/22/commits/86e8b66a2695ceb7edbe735f86384b9ce37addcd)

2021-05-06 14:37 UTC, HyeonaKwon commented on src/App.js
> +    },
그것도 사실 first, second, third, fourth 를 0, 1, 2, 3 의 인덱스라고 생각했다면 달라질 건 없었다고 봅니당!
수정했으면 좋겠다는 건 아니었구 왜 객체를 선택했나 궁금했어요~

2021-05-06 14:43 UTC, HyeonaKwon commented on src/App.js
> +  });
아아 그런데 지금보니까 모달 컨텐츠를 state 로 가지고 있어야할 이유가 궁금해지네요! 굳이 state 로 들고 있는 이유가 있을까요?
만약 그 이유가 모달 종류에 따라서 모달 컨텐츠가 변경될 수 있기 때문에 그걸 반영하기 위해서라면, modalMode 같은 enum 값을 isModalOpen 과 같이 저장하고 modalMode 에 따른 컴포넌트를 렌더링해도 좋을 것 같네요!

2021-05-06 14:46 UTC, HyeonaKwon commented on src/App.js
> +        )}
state 를 따로 관리해주는거는 부모 자식간 같은 데이터를 공유하기 위해 state 리프팅이 너무 많이 일어나기도 하고, 같은 관심사의 정보들을 잘 나눠서 관리하기 위해 라이브러리들을 사용하곤 합니다.  
아마 지금은 router 를 적용하지 않아서 App 이 무겁다고 생각하실 것 같아요!  
곧 해소될거라 생각합니다 ㅎㅎ

2021-05-06 14:46 UTC, HyeonaKwon commented on src/App.js
> +        )}
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ좋습니당

2021-05-06 14:54 UTC, HyeonaKwon commented on src/common/Card.js
> +      add={add}
아!!!!!!!!! 제가 아무생각없이 타입스크립트 문법을 추천해드렸네요😭  
https://www.typescriptlang.org/docs/handbook/enums.html 일단 enum 은 요거 참고만 해주시고 나중에 타입스크립트 적용할 때 다시 봐보시면 좋을 것 같아요!
```javascript
// key 값은 그루밍님 마음대로 하시면 될 것 같아요!
const CARD_MODE = {
  ADD: 'ADD',
  MODIFY: 'MODIFY',
  ...
}

const Card = ({ cardMode }) => {
  ...
  return (
    <CardWrapper ... add={cardMode === CARD_MODE.ADD}>
      {cardMode === CARD_MODE.ADD ? <></>}
      {cardMode === CARD_MODE.MODIFY ? <></>}
    </CardWrapper>
  )
}
```
이런식이요!

2021-05-06 15:01 UTC, HyeonaKwon commented on src/components/NewCardForm/cardFormValidator.js
> +};
맞아요 애매한 부분이 있죠! 그래도 컴포넌트는 아니기 때문에 저라면 util 로 옮겼을 것 같아요!

2021-05-06 15:07 UTC, HyeonaKwon commented on src/common/Card.js
> +      year: '',
빈 string 이 state 로 들어오는 경우에 default 값 설정은 어려워보입니당!😭

2021-05-06 15:08 UTC, HyeonaKwon commented
저는 크롬으로 봤습니당! 코멘트들 다시 한 번 확인완료되면 2단계로 넘어가도 될 것 같아요!

2021-05-06 22:07 UTC, ddongule commented on src/App.js
> +    },
<img width="229" alt="Screen Shot 2021-05-07 at 7 04 02 AM" src="https://user-images.githubusercontent.com/26598561/117371177-68eba080-af02-11eb-8962-900dc8a3e6d7.png">

아항항@@!!!!!! index!!! 그러네요!!! 현재 객체로 되어있는 numbers, expiredate, password를 모두 배열로 만들고 Validation 로직도 그에 맞추어 만들었었어도 괜찮았을 것 같습니다!!!!! 오오오우
다음부터는 상태를 저장할 때에 어떤 데이터 형태를 쓸 지에 대해서도 충분히 고민해보고 들어가야겠다는 교훈을 얻었습니다!!! 객체형태로 저장하는 것밖에 생각해보지 못했는데 다양한 방법 알려주셔서 감사합니다 🥰🥰
시야가 넓어진 느낌이에요!!!!

2021-05-06 22:10 UTC, ddongule commented on src/App.js
> +        )}
아하 그렇군요!! 
얼른 state 관리도 체계적으로 해보고 router도 해보고싶네요 >>ㅑ륵 !!!
알려주셔서 감사합니다 >___<!!!!😍

2021-05-06 22:15 UTC, ddongule commented on src/common/Card.js
> +      year: '',
따흑 그렇군요..!!!!! 😱 
요 부분에 있어서는 기본 값을 어떻게 주어야할 지 지속적으로 고민해봐야 할 것 같습니다!
감사합니다~!!! ☀️

2021-05-06 22:49 UTC, ddongule commented on src/components/NewCardForm/cardFormValidator.js
> +};
아하아항! 확실히 Components 폴더에 다른 Component들과 함께 들어가 있는 것이 부적합해 보입니다! 
말씀주신대로 utils 폴더로 옮겼습니다! 파일을 어디에 두어야할 지에 대해서는 프리코스때부터 쭉 고민해왔던 부분인데 더 고민을 해나가야 할 것 같습니다 헤헷.. 💘💘
수정해서 커밋했습니다 감사합니다아!!!!

커밋 링크: [`ba04694`](https://github.com/woowacourse/react-payments/pull/22/commits/ba046947c53a3ed4930d319f4cd5c7c36592955b)

2021-05-08 04:46 UTC, ddongule commented on src/common/Card.js
> +      add={add}
헉쓰쓰 그렇군요! 🥺 🥺
흠 살펴보았지만 아직 기존 코드와 요 코드의 다른 점을 잘 느끼지 못하고 있씁니다 또흐흑 😱 😱
ㅠㅠ 나중에 Typescript 적용하게 되면 다시한 번 살펴봐야 할 것 같아요!!!!!
좀 더 공부하고 다시 봐야겠어요 ㅠㅠㅠㅠ 따흐흑 감사합니다!!!

2021-05-08 04:55 UTC, ddongule commented on src/App.js
> +  });
요것도 [아래 리뷰](https://github.com/woowacourse/react-payments/pull/22#discussion_r625119825)에서 추천해주신 방식과 같은 결일까요?! 
추천해주신 코드를 봤는데도 아직 크게 와닿지가 않습니다 따흐흑 
공부를 더 해보도록 하겠씁니다... 🌟😭

2021-05-08 09:23 UTC, HyeonaKwon commented on src/App.js
> +  });
상태에 따른 컴포넌트를 state에 저장하는게 아니라 상태를 state에 저장하면 좋겠다는 말이었어요! 지금 어떤 모달이 떠야하는지를 데이터로 가지고 있고, 그에따른 컴포넌트 선택은 렌더링에서 하는거죠!
2단계에서 더 고민해봐주세요!

2021-05-08 09:25 UTC, merged