[페이먼츠 미션 Step 1] 우스(김영길) 미션 제출합니다.
woowacourse/react-payments pull request #232
Opened 2023-04-20 08:57 UTC by Gilpop8663

안녕하세요 유조! 만나뵙게 되어 반갑습니다 👍

이번에는 페이먼츠라는 앱을 만드는 것이 미션이였습니다. 

미션에서 핵심 기능으로는 카드 등록이 핵심 기능이였습니다.

## 사이트 보러가기
### <a href="https://gilpop8663.github.io/react-payments/">페이먼츠 사이트</a>

### CDD (컴포넌트 주도 개발)

코치 준의 수업시간에서 배운 CDD 전문가 사이클 7단계를 생각하여 개발해보았습니다.

- 1. 전체 문제가 해결되었을 때 어떤 상태일지 상상하기. 결국 내가 뭐하려는 걸까?
저희는 핵심을 `사용자가 카드 등록을 쉽게 할 수 있다.` 로 생각했습니다.

- 2. 적당한 난이도로 문제를 쪼개거나 변형하기. 단, 핵심을 포함하게
그래서 저희는 필요한 컴포넌트를 잘게 쪼개보아서 가장 필요한 컴포넌트로 Input이라고 생각하여서 Input부터 개발을 시작했습니다. 

그리고는 Input을 사용하는 InputField라는 컴포넌트 -> 각각의 종류의 Input 덩어리 등을 만들고, 카드 , 페이지 순으로 만들어보았습니다.
이 때 컴포넌트 UI를 만들면서 피드백을 스토리북을 통해서 받았는데요. npm run start를 하지 않고 컴포넌트들을 쉽게 확인해볼 수 있어서 좋았던 경험이였습니다. 

### useInput 커스텀 훅

input을 state값으로 다룰 때 useState, onChange가 반복적으로 사용되는 것을 보고 커스텀 훅으로 만들기로 했습니다. 그리고 useInput의 리턴값을 {value, onChange}로 받아서 전개구문을 이용해 input에 {...}으로 주는 방식을 택했습니다. 단순 반복작업을 줄일 수 있어서 좋았습니다. 그리고 개발을 하던 중 날짜에 관련된 예외 처리를 해주려고 했습니다. `월은 0~12, 년도는 현재 년도~ 현재 년도 +5`와 같이요. 그래서 useInput의 두 번째 인자로 옵션값을 받도록 해서 예외 처리하는 함수, 에러 메세지, 이름 등을 받아서 error를 리턴할 수 있도록 했습니다. 너무 많은 역할을 하는 것 같다는 생각도 들지만 이 훅이 저는 마음에 듭니다. ㅎㅎ 👍

리뷰해주셔서 감사합니다.

2023-04-20 22:25 UTC, yujo11 requested changes
안녕하세요 우스~ 

만나서 반갑습니다~

레벨2 들어와서 본 코드 중에 가장 깔끔하게 작성되어 있어서 코드를 확인하기 좋았습니다~ Storybook을 열심히 사용하신 점도 좋았네요! 👍 👍 👍 💯 💯 

코멘트로 남긴 내용 외에 추가로 말씀 드리고 싶은 부분이 있습니다~

1. 폴더구조

현재 `components/ ` 폴더 아래에 모든 페이지와 컴포넌트들이 들어있는데요. 그래서 파일트리를 탐색하는 과정이 조금 힘들었습니다 😅

`componets/` 하위에 있는 컴포넌트들은 역할이 제각각인데요.

`AddCardPage`같은 경우는 컴포넌트를 합성해서 페이지로 사용하고, `CardNumberInput`같은 경우는 특정 페이지(AddCard)에서만 사용하고, `Input`은 좀 더 범용적으로 앱 전체에 활용할 수 있는 컴포넌트인데요.

이런 컴포넌트들을 폴더로 나눠서 관리해보셨으면 좋겠습니다!

3. 컴포넌트
PR본문에 작성해주신 내용을 보니 CDD 방식으로 개발을 진행하신거 같은데요. 아주아주 칭찬할만한 부분이라고 생각합니다 👍 👍 👍 💯 💯 💯 

그런데 공통으로 사용되는 `Input` Component는 좋았지만 버튼 하나하나마다 `~~Button` 컴포넌트가 있는 점은 조금 아쉬웠습니다.

`NextButton`을 예시로 들면 현재 `NextButton`은 "다음"이라는 텍스트가 들어있는 버튼이 필요할 때만 재사용이 가능한데요. 이런 컴포넌트는 유연하게 사용하지 못 하기 때문에 재사용성이 많이 떨어집니다.

HTML Element 단위로 재사용이 가능한, 조금 더 말랑말랑한 컴포넌트를 만드는 시도를 계속해서 해보셨으면 좋겠습니다!

---

짧은 시간 동안 미션 진행하는게 쉽지 않으셨을텐데 고생 많으셨습니다! 

다음 리뷰 때 다시 뵙겠습니다~~ 👍 👍 👍

2023-04-20 22:25 UTC, yujo11 commented on src/components/Homepage.tsx
> +            key={`${card.owner}${index}`}
새로 카드를 등록할 때 임의로 ID를 설정해주고 ID를 key값으로 써도 좋을거 같네요~

2023-04-20 22:25 UTC, yujo11 commented on src/components/ExpiracyInput.tsx
> +      {year.error && <ToolTip text={year.error} />}
에러 메세지 처리 좋네요~~ 👍 👍 👍

2023-04-20 22:25 UTC, yujo11 commented on src/components/ExpiracyInput.tsx
> +      {year.error && <ToolTip text={year.error} />}
그런데 메세지가 조금 잘려서 보이는군요 🥲

당장 수정할 필요는 없지만 알고 계심 좋을거 같아요!

<img width="494" alt="image" src="https://user-images.githubusercontent.com/61097373/233496784-2be16401-7fcd-4a24-8ae0-cb8d2fbe5740.png">

2023-04-20 22:25 UTC, yujo11 commented on src/components/InformationButton.tsx
요것도 범용적으로 사용할 수 있는 Button Component를 만들어서 사용하면 좋겠네요~

2023-04-20 22:25 UTC, yujo11 commented on src/components/Input.tsx
> +      onInput={isNumber ? onInput : defaultOnInput}
`defaultOnInput`은 아무 동작도 하지 않고 있는데 넣으신 이유가 있을까요?

2023-04-20 22:25 UTC, yujo11 commented on src/hooks/useInput.tsx
멋진 훅이네요 👍👍👍

2023-04-20 22:25 UTC, yujo11 commented on src/hooks/useLocalStorage.tsx
> +  return [value, setState];
내보낼때도 이름이 [value, setValue] 처럼 통일되면 좋을거 같아요~

2023-04-20 22:25 UTC, yujo11 commented on src/hooks/useLocalStorage.tsx
> +  }, []);
그리고 보통 useEffect 같은 컴포넌트 생명주기와 관련 있는 Hook들은 return 문 바로 위에 작성하는데요

일반적인 컨벤션을 따라 코드를 작성하면 보기가 더 편할거 같네요~

2023-04-21 06:03 UTC, Gilpop8663 commented on src/App.tsx
> +    </div>
아직 필요성을 느끼지 않아서 스테이트로 구현해보았습니다. 👍👍 react-router-dom을 설치하지 않더라도 window.locationn.hash를 이용해서 카드 등록 페이지의 url을 입력하면 카드 등록 페이지를 보여주는 방법을 할 수 있을 것 같아요.

2023-04-21 06:09 UTC, Gilpop8663 commented on src/components/AddCardPage.tsx
> +    return Number(month) <= 12 && Number(month) >= 0;
input의 onChange를 이용하려다 보니 입력 값 입력에 불편함이 생겨 0을 추가했습니다. onChange 말고 onSubmit에서 유효성 검사를 시도해볼 것 같아요.

2023-04-21 06:10 UTC, Gilpop8663 commented on src/components/AddCardPage.tsx
> +    const currentYear = new Date().getFullYear();
처음에 현재 년도. currentYear %100 , (current%100) +5 와 같이 시도하려 했지만. onChange여서 입력부터 제대로 되지 않은 이슈가 생겨서 우선 기능이 돌아가게 두자 라고 해서 사용하지 않았습니다. form의 onSubmit에서 유효성 검사를 하며 다시 사용해볼 것 같아요

2023-04-21 06:12 UTC, Gilpop8663 commented on src/components/AddCardPage.tsx
> +  ]);
유저가 실시간으로 모든 값을 채웠을 때 다음 버튼이 활성화되는 것을 원해서 required가 있는 모든 인풋의 value를 감시하여 cardForm.current.checkValidity() 이 true 값이 되는지 확인해보았습니다. 리팩터링하면서 다른 방법이 있는 지 확인해보려고 합니다.

2023-04-21 06:13 UTC, Gilpop8663 commented on src/components/AddCardPage.tsx
> +          <NextButton isDisable={isFormfilled} />
사용성을 높이기 위해 필수 값이 전부 들어오지 않으면 제출할 수 없도록 제어해보았습니다. 👍👍

2023-04-21 06:14 UTC, Gilpop8663 commented on src/components/ExpiracyInput.tsx
> +      {year.error && <ToolTip text={year.error} />}
알려주셔서 감사합니다. 👍👍 참고하여 리팩터링 진행해보겠습니다.

2023-04-21 06:14 UTC, Gilpop8663 commented on src/components/Homepage.tsx
> +            key={`${card.owner}${index}`}
좋은 아이디어 감사합니다 !! 👍👍

2023-04-21 06:22 UTC, Gilpop8663 commented on src/components/Input.tsx
> +      onInput={isNumber ? onInput : defaultOnInput}
onInput={ isNumber && onInput } 과 같이 해보려 했지만 기본적으로 undefined 값이 들어올 수 있기에 빨간 줄이 나왔습니다. 다른 해결방법으로 onInput 함수에서 분기 처리해주는 방식으로 고쳤습니다. 불필요한 코드를 줄일 수 있어서 이 방법이 더 좋다고 생각됩니다 👍👍👍


```tsx

export default function Input({
  textAlign = "baseline",
  isNumber,
  ...rest
}: InputProps) {
  const onInput = (event: ChangeEvent<HTMLInputElement>) => {
    if (!event.currentTarget) return;

    if (isNumber) {
      event.currentTarget.value = event.currentTarget.value.replace(
        /[^0-9]/g,
        ""
      );
    }
  };

  return (
    <StyledInput
      textAlign={textAlign}
      inputMode={isNumber ? "numeric" : "text"}
      onInput={onInput}
      {...rest}
    />
  );
}
```

2023-04-21 06:23 UTC, Gilpop8663 commented on src/hooks/useInput.tsx
감사합니다. 커스텀 훅을 만들어보면서 어떻게 만들어야 하는 지 숙달하고 있어요 ㅎㅎ 👍👍

2023-04-21 06:24 UTC, Gilpop8663 commented on src/hooks/useLocalStorage.tsx
> +  }, []);
특별한 이유로 저렇게 둔 것이 아니기에 일반적인 컨벤션을 따르도록 하겠습니다 👍👍

2023-04-21 06:26 UTC, Gilpop8663 commented on src/hooks/useLocalStorage.tsx
> +  return [value, setState];
네 저도 그 편이 더 좋아보이네요 !  일반적인 컨벤션을 따르도록 하겠습니다 👍👍👍

2023-04-25 08:20 UTC, Gilpop8663 commented on src/components/AddCardPage.tsx
> +    const currentYear = new Date().getFullYear();
```ts
export const yearValidate = (year: string) => {
  const currentYear = new Date().getFullYear() % 100;
  return Number(year) >= currentYear && Number(year) <= currentYear + 5;
};

```

다음과 같이 만들어보았습니다~ 👍

2023-04-25 08:21 UTC, Gilpop8663 commented on src/components/AddCardPage.tsx
> +    return Number(month) <= 12 && Number(month) >= 0;
```ts
export const monthValidate = (month: string) => {
  return Number(month) <= 12 && Number(month) >= 1;
};

```

submit에서 유효성 검사를 하면서 monthValidate 함수에 1 이상 12 이하로 되도록 고쳤습니다 ~ 👍

2023-04-25 08:26 UTC, Gilpop8663 commented on src/components/AddCardPage.tsx
> +  ]);
```tsx
         <NextButton
            isDisable={
              cardForm.current ? !cardForm.current.checkValidity() : true
            }
            text="다음"
          />
```

useEffect에서 너무 많은 값을 감시하며 다음 버튼 활성화/비활성화 하던 것은 제가 의도치 않은 성능 변화가 있을 것 같아 변경해보았습니다.

다음과 같이 바로 Props에 들어가도록 고치니 나름(?) 잘 작동하는 것 같아 고쳐보았습니다. 

다만 이렇게 코드를 구현했을 때 입력된 값을  지웠을 경우에는 버튼 활성화/비활성화가 잘 될때가 있고 잘 안될때가 있는데 다시 되돌리는 것이 맞을까요?

2023-04-25 08:27 UTC, Gilpop8663 commented on src/components/InformationButton.tsx
? 말고도 ! 로도 사용할 수 있겠네요 👍

2023-04-25 08:51 UTC, Gilpop8663 commented
안녕하세요 유조! 꽤 오랫동안 스텝1에서 머물렀던 것 같습니다. 

## 스토리북 배포 링크 

### <a href="https://gilpop8663.github.io/react-payments/storybook">우스 스토리북</a>


---- 


스텝 1에서 추가하고 싶은 기능들이 많아서 오래 걸렸습니다. 

추가하고자 하는 기능들은 `사용자가 쉽게 카드 등록을 할 수 있어야 한다.`를 초점에 두고 기능 구현을 했습니다.

### 궁금한 점

1. 저는 원래는 input에서 유효성 검사를 했지만 input의 onChange에서 달, 연도를 validate하는 방법을 모르겠어서 submit에서 유효성 검사하는 것으로 변경했습니다. 제가 생각하기엔 input에서 onblur를 할 때 사용자에게 에러 메세지를 보여주며 즉각적인 피드백을 주는 것이 더 좋은 사용자 경험을 느껴집니다. 그 이유는 submit에서 유효성 검사를 했을 경우 다음 버튼을 누르고 잘못된 값을 바꾼 후 제출을 했을 때 또 다른 에러 메세지가 있다면 또 고쳐야 하니 사용자 입장에서 좋은 경험은 아닐 것 같다는 생각이 듭니다. 유조는  유효성 검사를 input과 submit 둘 중 하나만 하시는 편인지, 둘 다 하시는 편인지 궁금합니다 😀👍

2. input 타입이 패스워드 타입일 때 사용자 검사를 통해 value 값을 확인할 수 있었는데요. 네이버 카드 등록에 보니 패스워드 타입에서 인풋 입력마다 &이 입력되도록 하였는데 저는 onChange마다 value를 &로 변환하는 방법을 모르겠어서 아예 password 타입에서는 value를 주지 않는 방식으로 해결했습니다. 이렇게 카드 등록 과정에서 카드 번호, cvc value값을 숨겨야 하는 것이 조금 더 맞는 방향인지 , 아니면 굳이 숨겨야할 정보가 아닌데 제가 조금 오바한 것인지가 궁금합니다. 맞는 방향이라면 현재 password처럼 보이도록 css를 설정했는데 이 css도 안보이도록 숨겨야하는지도 궁금합니다.   😳😵


리뷰해주셔서 감사합니다 !

2023-04-25 17:04 UTC, yujo11 approved these changes
안녕하세요 우스~

지난 리뷰 때 코멘트로 남긴 부분들을 꼼꼼히 확인하고 코드에 반영해주셨군요 👍 

우스가 남겨준 코멘트나 리팩터링한 코드를 보면서 구체적인 언급이 없었음에도 탐구하고, 개선하는 우스의 모습을 보면서 정말 보기 좋고 멋지다는 생각을 했습니다 👍 👍 👍 💯 💯 💯 

이전 코드도 깔끔해서 코멘트로 남길만한 내용들이 많지 않았는데, 리팩터링한 코드들에도 소소한 코멘트들만 남겨서 이번 step은 여기에서 merge하고 다음 step에서 반영해보셔도 좋을거 같습니다~

---

>저는 원래는 input에서 유효성 검사를 했지만 input의 onChange에서 달, 연도를 validate하는 방법을 모르겠어서 submit에서 유효성 검사하는 것으로 변경했습니다. 제가 생각하기엔 input에서 onblur를 할 때 사용자에게 에러 메세지를 보여주며 즉각적인 피드백을 주는 것이 더 좋은 사용자 경험을 느껴집니다. 그 이유는 submit에서 유효성 검사를 했을 경우 다음 버튼을 누르고 잘못된 값을 바꾼 후 제출을 했을 때 또 다른 에러 메세지가 있다면 또 고쳐야 하니 사용자 입장에서 좋은 경험은 아닐 것 같다는 생각이 듭니다. 유조는 유효성 검사를 input과 submit 둘 중 하나만 하시는 편인지, 둘 다 하시는 편인지 궁금합니다 😀👍

이거는 상황마다 다를거 같다고 말씀 드릴 수 밖에 없네요 😅

지금은 10~20개 남짓되는 Input이지만 실제 우스가 개발을 하다보면 훨씬 더 많은 수백개의 Input을 다루는 상황이 올 수도 있는데요.

이런 경우에는 제어 컴포넌트로 구현할 경우 성능 상의 이슈 때문에 비제어 컴포넌트로 구현을 하는 경우가 많습니다.

비제어 컴포넌트로 구현하는 경우에는 사용자가 입력한 값을 submit 시점이 되어야 알 수 있으니 선택지가 없다고 할 수 있겠네요

이런 경우가 아니라 제어 컴포넌트로 구성하는 경우에는 `blur` 시점보다는 사용자로 인해 `change`가 발생하는 시점에 에러 메세지를 보여주는게 좋다고 생각합니다.(비밀번호 입력 같은 경우를 제외하면요!)

현재 우스의 앱도 제어 컴포넌트로 구성되어 있는데요. 이 말은 change 이벤트가 발생할 때마다, 즉 유저로 인해 Input의 value가 변할 때마다 그것을 인지할 수 있다는 말인데요.

사용자가 특정 행동을 통해서 의도치 않은 동작을 했을 때, 해당 동작에 대한 피드백은 빠를수록 좋다고 생각합니다. 10글자의 숫자를 입력해야 하는데 첫번째 입력을 문자로 했다가 10글자를 모두 입력하고 다음 Input으로 넘어갔을 때와 첫번째 입력을 하는 시점에 피드백을 주는 경우를 떠올려보시면 좋겠네요!

>input 타입이 패스워드 타입일 때 사용자 검사를 통해 value 값을 확인할 수 있었는데요. 네이버 카드 등록에 보니 패스워드 타입에서 인풋 입력마다 &이 입력되도록 하였는데 저는 onChange마다 value를 &로 변환하는 방법을 모르겠어서 아예 password 타입에서는 value를 주지 않는 방식으로 해결했습니다. 이렇게 카드 등록 과정에서 카드 번호, cvc value값을 숨겨야 하는 것이 조금 더 맞는 방향인지 , 아니면 굳이 숨겨야할 정보가 아닌데 제가 조금 오바한 것인지가 궁금합니다. 맞는 방향이라면 현재 password처럼 보이도록 css를 설정했는데 이 css도 안보이도록 숨겨야하는지도 궁금합니다. 😳😵

코드 뿐만 아니라 실제로 더 잘 구현하기 위해 여러 레퍼런스를 참고하시는군요 멋집니다 우스 👍 👍 👍 

네트워크에 대해 공부하시면서 알게 되시겠지만 사실 프론트엔드에서 완벽한 보안을 갖추는 것은 불가능에 가깝습니다.

현재 단계에서 우스가 할 수 있는 최선을 다해 은닉하려는 것만으로도 충분하다고 생각합니다!

그래도 이런 고민들은 멈추지 않고 계속 하시면 좋겠네요!

---

이번 step 고생 많으셨습니다 우스! 다음 step에서 다시 만나요~~~

2023-04-25 17:04 UTC, merged

2023-04-26 01:57 UTC, Gilpop8663 commented on .prettierrc.js
기존에 아이크 노트북으로 진행했었을 때 아이크의 prettier 설정으로 하다보니 쌍따옴표로 진행했더라구요. 저는 개인적으로 홀따옴표 설정을 선호해서 다른 컴퓨터로 진행할 때 이런 일이 없도록 미리 설정해주었습니다. 다른 default 옵션들은 대부분 airbnb 코드 컨벤션을 따르고 있습니다. 그 이유는 제가 airbnb 스타일에 익숙해서 이렇게 설정했습니다~ 👍👍👍

2023-04-26 01:57 UTC, Gilpop8663 commented on public/index.html
> +    <title>Wus Payments - 결제를 더 편리하게</title>
ㅋㅋㅋ 약간 의도하고 만든 것은 맞습니다 😂

2023-04-26 01:57 UTC, Gilpop8663 commented on src/App.tsx
> +      {page === 'addCardPage' && (
알려주신대로 설정하니 개발자가 실수할 일을 줄일 수  있게 되었어요 ㅎㅎ 👍👍

2023-04-26 01:57 UTC, Gilpop8663 commented on src/components/card/Card.tsx
> +  const onwerName = owner.length > 10 ? owner.slice(0, 10) : owner;
상수 선언 후 사용해보도록 하겠습니다 😅

2023-04-26 01:57 UTC, Gilpop8663 commented on src/components/card/input/CardNumberInput.tsx
극찬 !!! 감사합니다 👍👍👍

2023-04-26 01:57 UTC, Gilpop8663 commented on src/components/card/input/CardNumberInput.tsx
> +          tabIndex={0}
중간에 CVC/CVV 안내 버튼에 탭 인덱스가 가는 것을 방지하고자 설정해주었습니다 👍👍

2023-04-26 01:57 UTC, Gilpop8663 commented on src/components/card/input/CvcInput.tsx
> +            tabIndex={7}
너무 좋은 아이디어 주셔서 감사합니다 👍👍

2023-04-26 01:57 UTC, Gilpop8663 commented on src/components/common/Input.tsx
감사합니다 👍👍

2023-04-26 01:57 UTC, Gilpop8663 commented on src/constant.ts
> +export const ADD_CARD_PAGE = 'addCardPage';
알려주셔서 감사합니다 유조 👍👍

2023-04-26 01:57 UTC, Gilpop8663 commented on src/hooks/formValidate.ts
> +  });
함수 분리를 통해서 더 읽기 쉽게 할 수 있겠네요 ~ 함수 분리를 통해 가독성을 높여보도록 하겠습니다 👍

2023-04-26 01:57 UTC, Gilpop8663 commented on src/hooks/useInput.ts
칭찬 감사합니다 유조 !  미션을 통해서 만든 훅들을 한 가지 미션에서만 사용하기 아까워서 npm 패키지에 등록해보고 싶은 생각이 있어요 😀

2023-04-26 01:57 UTC, Gilpop8663 commented on src/pages/AddCardPage.tsx
> +  });
저도 사용하면서 느낀 점이 재사용성을 더 높일 수 없을까 라는 생각이 들었습니다. 저는 react-hook-form을 즐겨 사용했었는데 라이브러리처럼 {...register("인풋이름") ,{옵션}} 이런 방향으로 가야할 지 아니면 저만의 방식으로 재사용성을 높이는 시도를 해볼 지 고민을 해보겠습니다. 고민할 거리를 주셔서 감사합니다  👍👍👍

2023-04-26 02:31 UTC, Gilpop8663 commented on src/App.tsx
> +    </div>
react-router-dom 공식 문서에서도 이유는 나와있지 않고 지양하라고 나와 있네요. 

<img width="986" alt="image" src="https://user-images.githubusercontent.com/80146176/234447716-8a548a35-7c40-4f24-ac04-9ac246f6fbda.png">

그래서 이유가 궁금해 찾아보았습니다.

해시 라우팅의 문제는 해시 라우팅이 약간 부적절해 보인다는 것입니다. 사용자는 깨끗하고 간단한 URL에 익숙하기 때문입니다. 따라서 중간에 있는 해시가 이상하게 보일 수 있습니다.

1. 사용자는 # 이 붙어있는 URL에 익숙하지 않습니다. 자칫 잘못된(해킹된) 사이트로 오해할 수 있습니다.
2. 일반적인 URL에 비해 SEO가 좋지 않을 수 있습니다. 


이 이유들 이외에는 다른 이유는 찾지 못했습니다 ~ 👍

출처 : 

https://reactrouter.com/en/main/router-components/hash-router

https://stackoverflow.com/questions/51974369/what-is-the-difference-between-hashrouter-and-browserrouter-in-react

https://dev.to/thedevdrawer/single-page-application-routing-using-hash-or-url-9jh