[페이먼츠 미션 Step 2] 해온(백솔비) 미션 제출합니다.
woowacourse/react-payments pull request #245
Opened 2023-04-28 05:44 UTC by hae-on

### [배포 사이트](https://hae-on.github.io/react-payments)

안녕하세요 포코!
Step2를 마치고 돌아왔습니다.

## 달라진 점
1. local storage에 값 저장
2. context api 사용

크게 달라진 점에는 이 2가지가 있습니다. 
특히 이번에는 Context API를 사용해보았는데요. 
card 상태에 대한 Context를 만들어보았습니다. 
제대로 만든게 맞는지 모르겠네요 😅

특히 이번에는 은행 선택에 대해서 고민이 많았습니다.
처음에는 아예 백드롭이나 ESC로 모달을 못 닫게 할까 생각을 했는데 
그건 너무 사용자에게 강제적인 선택 강요(?)를 하는게 아닐까 싶어
그냥 기본값을 '기타 은행'으로 두고 무조건 선택하지 않아도 되도록 구현하였습니다.

## 궁금한 점
진행하다보니 점점 기본적으로 쓰는 컴포넌트에 스타일이 계속 추가가 되는데요.
input만 하더라도 form에 쓰이다가 카드 별칭 지정하는 곳에서도 쓰이니까
종류에 따라 스타일링을 props로 받아서 사용하고 있습니다.
그럴수록 점점 input 스타일링이 복잡해지고 있구요.
어느곳에서나 만능으로 쓰이는 Input을 만드는건 불가능한걸까유...?
나중에는 만능 input보다는 조금 더 세분화해서 (numberInput.. 뭐 이런식으로 ) 컴포넌트로 만드나요?
궁금합니다!!

그럼 리뷰 잘 부탁드립니다!

2023-04-29 08:01 UTC, pocojang requested changes
@hae-on 👋 

정말 빠르게 미션해주셨네요!

---

## 피드백

### ContextAPI

음 크루들의 전체적인 반응이 `ContextAPI` 그저 전역 상태 용도 아니야?
`ContextAPI` 없어도 되잖아?..?
라는 반응인 것으로 보이던데 해온도 딱 전역상태처럼 넣어주셨어요!

물론 처음이라 그럴 수 있다고 봅니다
`ContextAPI`는 상태를 맥락마다 나눠쓸 수 있는 것이라고 보시는게 좋겠어요.
앞으로 레벨3부터 수 많은 라이브러리들을 사용하실텐데요!
대부분 `ContextAPI`를 통해 라이브러리 기능들을 제공된다는 사실을 아시나요?
(물론 `ContextAPI`

즉 `ContextAPI`를 특정 상태를 맥락으로 묶어 제공(Proivder), 사용(Consumer)하게 되는겁니다!
이런 관점을 꼭 깨우치셨으면 좋겠어요.

그냥 전역 공간이다...! No!! ❌ 

### Components

잘해주셨어요!
물론 `BottomSheetComponents`, `CardListPageComponents` 같은 경우 위치가 좀 애매해서 바뀌는게 어떨까 싶기도한데 전반적으로 잘 적성해주신 것 같습니다.
여기서 더 발전시킨다면 `Prmitive` 형태의 컴포넌트를 만드는 훈련을 조금씩 더 해보면 좋겠어요
`BankImage`보다는 `AvatarImage` or `RoundImage`가 더 확장성이 가득하겠죠?
레퍼런스는 [Radix UI](https://www.radix-ui.com), [Rebass](https://rebassjs.org) 라이브러리들의 구성을 잘 참고해보세요!


또한 `useBottomSheet()`는 `HeadlessUI`의 좋은 사례로 보여요 👍 
향후 `useToggle()`과 같은 네이밍으로 바꿔서 사용하실 수 있겠습니다!

## Q&A

### 어느곳에서나 만능으로 쓰이는 Input을 만드는건 불가능한걸까유...?
>나중에는 만능 input보다는 조금 더 세분화해서 (numberInput.. 뭐 이런식으로 ) 컴포넌트로 만드나요?

불가능보다는 굳이? 라고 생각듭니다!
확장성이 좋은 컴포넌트를 만드는 욕망이나 훈련은 아주 훌륭하다고 봅니다.

하지만 때로는 확장을 넘어.. 분리까지 고려해야겠죠?
제어 컴포넌트와 비제어 컴포넌트를 여기에 대입해서 생각해보시면 좋아요.

만능 Input은 성격이 너무나 좋아서 누구와도 잘 지내는 크루가 알고보니 하나하나 다 맞춰주고 있고 스트레스가 있다고 볼 수 있죠...!
만능 Input이 외부의 변화에 제어 당하느냐 아니면 제어하지 않느냐 관점이에요...
그래서 적절히 `Children`, `Render Props`를 열어주는게 중요합니다 ㅎㅎ
그리고 그 맥락에 어울리는 상태는 `Context API`로 제공하는거죠!

---

전반적으로 합리적인 코드를 잘 작성해주신 것 같아요 👏 
그럼 코드 수정 후 다시 리뷰 요청해주세요!

2023-04-30 14:01 UTC, hae-on commented on src/components/BottomSheetComponents/BankList.tsx
> +  const bankNames = Object.keys(CONVERT_BANK_NAME);
맞습니다..! 저번에도 내부에 작성했는데 매번 깜박하네용 🥲

2023-04-30 14:01 UTC, hae-on commented on src/components/cardForm/ExpirationDateInput.tsx
>    const refs = [useRef<HTMLInputElement>(null), useRef<HTMLInputElement>(null)];
inputRefs로 수정했습니다!

2023-04-30 14:01 UTC, hae-on commented on src/utils/InputValidate.ts
> +export const isOverLength = (inputValue: string, maxLength: number = 30) => {
상수화해서 처리하였습니다!

2023-04-30 14:02 UTC, hae-on commented on src/components/pages/CardAdditionCompletionPage.tsx
> +  }
card가 없을 때는 다른 화면이 뜨도록 수정하였습니다!

2023-04-30 14:03 UTC, hae-on commented on src/components/common/BankItem.tsx
> +        />
카드사 이미지가 없을 때를 대비한 대체 이모지를 추가하였습니다!

2023-04-30 14:11 UTC, hae-on commented on src/context/CardContext.tsx
> +export const CardContextProvider = ({ children }: CardProviderProps) => {
정말 정확하게 맞추셨습니닷… ‘여기서 Context API가 왜 필요하지? 그래도 시도는 해봐야겠다!’ 라는 마음으로 했습니다! 그래서 전역 상태처럼 사용했습니다. 그런데 단지 그런 용도로 사용하는게 아니였군요…! 특히 Context API를 통해 라이브러리 기능이 제공된다는건 처음 알았답니다! 아직 전역 상태 이상으로는 어떻게 써야할 지 감이 오지 않지만 더 공부해서 제대로 된 사용을 해보도록 하겠습니다!!!

2023-04-30 14:14 UTC, hae-on commented on src/utils/Constants.ts
> +};
키만 따로 모아서 관리한다는게 

```js
export const BANK_NAME = [
  'BC카드',
  '신한카드',
  '카카오뱅크',
  '현대카드',
  '우리카드',
  '롯데카드',
  '하나카드',
  '국민카드',
]
```
이런식으로 key만 뽑아서 활용하라는 뜻일까요...?
그래서 위의 CONVERT_BANK_NAME와 CARD_COLOR의 key 대신 사용하는건가요?
어떤 의미인지 궁금합니다!!

2023-05-01 07:36 UTC, pocojang approved these changes
그 누구보다 빨리 제출해주셨네요!
이정도면 스텝3로 넘어가셔도 될 것 같습니다

물론 중간중간 부족하거나 아쉬운 부분이 있긴한데 스텝3까지 하려면 빨리 머지되어야겠죠?

정말 잘하셨고요.
제가 봤을때 아쉬운 몇가지 포인트만 달아놓을테니 스텝3 진행하면서 점검만 한번 해보세요!

## 아쉬운 점

### 1. `src/components/common`의 구성

공통 컴포넌트와 아닌 컴포넌트들의 구성을 보면 이게 여기가 맞나...? 싶은 컴포넌트들이 계속 보입니다.
위치 교정이 필요할 수 있어요

### 2. `CardContext` 용도

그 자체로 전역 스토어 역할을 하고 있어요!
맥락 관점에서 `Context`를 나누거나 범위를 좁혀보세요 :)

### 3. `Context` & `Hooks`

현재는 `Context` & `Component`와 `Hooks` & `Component`의 형태로 사용하는 법은 어느정도 익숙해지신 것 같아요!

그 다음 레벨은  `Context` & `Hooks` & `Component` 모두 적절하게 사용하는 것이라고 봅니다 ㅎㅎ
물론 너무 억지로 사용할 필요는 없어요. 한번 브레인 스토밍은 시도해보세요
횡단 관심사를 처리할때 `Context` & `Component`와 `Hooks` & `Component` 2가지 케이스만 고려했다면 분명히 한계는 있었을거에요.

이제부터는 `Context` & `Hooks` & `Component` 모두 적절하게 일을 줘보세요!
하실 수 있을겁니다!

그럼 이만 머지할게요.
스텝3에서 뵈어요 👋

2023-05-01 07:36 UTC, pocojang commented on src/App.tsx
> +    setCardList((prevCardList) => [cardItem, ...prevCardList]);
ㅋㅋㅋ일부러 모른척 넘어갔었는데 찾아내셨군요 👀

2023-05-01 07:36 UTC, pocojang commented on src/App.tsx
> +  const { bankName, cardName, setCard, setCardList } = useContext(CardContext);
거의 100% 추상화시켜버렸군요.
현재 앱 규모에서는 나쁘지 않은 것 같네요 👍

2023-05-01 07:36 UTC, pocojang commented on src/components/pages/CardListPage.tsx
> +        {!cardList && (
이제 `length` 체크는 안해도 되는걸까요? (궁금해서.. 💭 )

2023-05-01 07:36 UTC, pocojang commented on src/components/common/BankItem.tsx
> +  };
꼭 필요한 추상화일까 싶기도 한데.. 네이밍은 또 설득력 있네요 ㅎㅎ

2023-05-01 07:36 UTC, pocojang commented on src/components/common/BankItem.tsx
> +        ) : (
이런 세심한 방어처리 좋아요 💯

2023-05-01 07:36 UTC, pocojang commented on src/components/pages/CardAdditionCompletionPage.tsx
>    }
잘하셨습니다
나중에는 `Suspense` & `Fallback` 조합도 사용할 수 있도록 성장해보세요 💪

2023-05-01 07:36 UTC, pocojang commented on src/components/cardForm/ExpirationDateInput.tsx
> +        const nextInputRef = inputRefs.at(inputIndex + 1);
상당히 명시적이네요 💯

2023-05-01 07:36 UTC, pocojang commented on src/App.tsx
> +    cardName: '',
나중에는 `initState` or `INIT_STATE`정도로 관리하는 것도 나쁘지 않겠다? 생각이 드네요!

2023-05-01 07:36 UTC, pocojang commented on src/stories/BankItem.stories.tsx
> +};
`Storybook 7.0` 넘어오면서부터 문법이 좀 바뀌지 않았나요? 💭 
[Migration guide for Storybook 7.0](https://storybook.js.org/docs/react/migration-guide) 확인해보시고요
CSF2 => CSF3 에 대해서도 한번 확인해보세요 :)

2023-05-01 07:36 UTC, pocojang commented on src/utils/Constants.ts
> +};
이번 질문은 `Step3`까지 보류해보겠습니다 ㅎㅎ
그때까지 한번 고민해보세요!

2023-05-01 07:36 UTC, merged

2023-05-02 05:18 UTC, hae-on commented on src/App.tsx
> +    setCardList((prevCardList) => [cardItem, ...prevCardList]);
새로고침 할때마다 순서가 바뀌더라구요 😂😂😂

2023-05-02 05:19 UTC, hae-on commented on src/components/pages/CardListPage.tsx
> +        {!cardList && (
넵! 이제 context에서 cardList를 가져오게 했더니 length 체크가 필요 없어졌습니다!

2023-05-02 05:20 UTC, hae-on commented on src/stories/BankItem.stories.tsx
> +};
스토리북 파일마다 이것저것 다 섞어쓰고 있었네요...! 바뀐 문법으로 다시 정리하였습니다!