[페이먼츠 미션 Step 2] 우스(김영길) 미션 제출합니다.
woowacourse/react-payments pull request #247
Opened 2023-04-28 08:36 UTC by Gilpop8663

안녕하세요 유조! 스탭 2 미션의 기능들을 구현해보았습니다. 

## 사이트 보러가기

### <a href="https://gilpop8663.github.io/react-payments/">페이먼츠 사이트</a>

## 스토리북 배포 링크 

### <a href="https://gilpop8663.github.io/react-payments/storybook">우스 스토리북</a>

-----

- [ ] Context API를 활용해 전역 상태 관리 및 계층 재구성 

다음과 같이 Context API를 활용하는 요구 사항이 있었지만 아직 적용하지 않은 상태입니다.

현재 저의 코드에는 Context API가 필요하지 않으나 학습을 위한 목적으로 사용해보려고 주말 ~ 월요일에 구현해보려고 합니다

유조의 피드백을 받아 더 좋은 코드를 작성하고자 코드 리뷰를 보내봅니다. 😀

## 1. 구현한 것

- useInput 훅 사용으로 인해 올라가는 코드 복잡성을 제어하고자 useInput을 관리하는 훅을 만들었습니다. - https://github.com/woowacourse/react-payments/commit/04f5022301020c143a63fd29b6dba0a40e326716

- 카드 컴포넌트에서 카드 별칭, 카드 회사, 카드 색 표시하는 기능 구현

- 모달이 열렸을 때 스크롤을 막는 훅을 구현했습니다. - https://github.com/woowacourse/react-payments/commit/583e3b38f685010aa1c3a476b184a8c4e4e05db7

- 모바일에서 뒤로가기 버튼을 터치하였을 때 정말 뒤로 갈 것인지 물어보는 기능 구현 - https://github.com/woowacourse/react-payments/commit/7fb3315a526e607652a36976d68d536f33486c41

- 인풋을 사용할 때 모바일 환경 키보드에서 enter key를 다음으로 바꾼 후 다음으로 넘어가도록 신경썼습니다.

- 사용자 이름을 적을 때 모바일에서 영어 대문자로 설정하는 기능을 신경썼습니다.

- 인풋에서 유효성 검사를 하고, 폼에서도 동일한 내역의 유효성 검사 하는 것이 중복된다고 생각하여서 useInput을 관리하는 훅에서 설정한 옵션으로 폼에서도 유효성 검사를 하도록 함수를 만들었습니다. 다만 이 과정에서 개발자가 알아보기 힘든 코드가 되었다고 생각해요 😢 - [getFormValidateResult.ts](https://github.com/woowacourse/react-payments/commit/19cac19907954befb64f53c878d598bc06535b91#diff-054bdeb9fa49c40dd543fcfb9495568cd2d62cd3a2e01dce7eb4cfe718f402ba)

## 2. 고민한 점

AddCardPage 에서 onCardInfoSubmit 함수의 길이가 너무 길어져서 분리하고 싶었으나 분리하기 어려웠습니다. useInput에서 ref도 사용한다면 더 간단히 만들 수 있겠으나 모든 input에 ref를 걸어야 할 필요성을 못 느껴서 useInput의 반환 값들과 submit 이벤트에서 알려주는 input 엘리먼트로 제가 생각한 코드를 구현하고자 노력했습니다. 😀

그리고 현재 react에 관련된 함수가 아닌데도 hook 폴더에 있는 함수가 있는데 유틸로 옮길 생각입니다. 

엄청나게 친절한 리뷰 해주셔서 감사합니다 유조! 👍👍👍

덕분에 코드 작성에 힘이 났어요 👍👍

2023-04-29 12:49 UTC, yujo11 requested changes
안녕하세요 우스~

리뷰가 늦어지게 되어 죄송합니다 🙇‍♂️

지난번 step을 리뷰할 때도 코드가 전체적으로 깔끔하다는 인상을 받았었는데요~

이번 step을 진행하시면서도 대부분 코드를 깔끔하게 잘 작성해주셨네요! 👍 👍 👍 

---

>다음과 같이 Context API를 활용하는 요구 사항이 있었지만 아직 적용하지 않은 상태입니다.
현재 저의 코드에는 Context API가 필요하지 않으나 학습을 �위한 목적으로 사용해보려고 주말 ~ 월요일에 구현해보려고 합니다
유조의 피드백을 받아 더 좋은 코드를 작성하고자 코드 리뷰를 보내봅니다. 😀

좋습니다~ Context API는 실제로도 굉장히 많이 사용되기 때문에 우스가 말씀해주신 것처럼 학습의 목적으로 한번 적용해보시면 좋을거 같아요.

아래 글도 한번 읽어보시면 좋겠네요!

[다른 사람들이 안 알려주는 리액트에서 Context API 잘 쓰는 방법
](https://velog.io/@velopert/react-context-tutorial#provider%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EC%95%8A%EC%9D%84-%EA%B2%BD%EC%9A%B0)

---
### 구현한 것

사용성을 신경 쓰면서 구현하신 부분이 많군요 아주 좋네요! 👍 👍 👍 💯 💯 💯 

++)소소하게 이전 페이지로 이동 시, Alert 메세지가 조금 더 친절하게 변경되어도 좋을거 같아요 ex) 이전 페이지로 이동하시면 입력하신 내용이 사라집니다. 이동하시겠습니까?
---

### 고민한점
>AddCardPage 에서 onCardInfoSubmit 함수의 길이가 너무 길어져서 분리하고 싶었으나 분리하기 어려웠습니다. useInput에서 ref도 사용한다면 더 간단히 만들 수 있겠으나 모든 input에 ref를 걸어야 할 필요성을 못 느껴서 useInput의 반환 값들과 submit 이벤트에서 알려주는 input 엘리먼트로 제가 생각한 코드를 구현하고자 노력했습니다. 😀

이 부분은 우스가 작성해준 위 내용을 보고 다시 코드를 확인해봤는데요. 이 부분은 Load diff가 떠서 제가 리뷰를 진행할 때 놓친거 같네요 😅

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/61097373/235303032-56b05928-942b-4676-b7f0-43043501d839.png">

현재 우스가 작성하신 `onCardInfoSubmit`을 보면 Submit Event 객체에서 값을 가져와서 그 값을 재가공하는데요.

일단 이 부분이 조금 어색하게 느껴졌습니다.

우스가 현재 작성하신 Form안에 있는 Input 컴포넌트들은 제어 컴포넌트로 구성되어 있는데요. 이것을 다시 말하면 Input 컴포넌트들에 입력되는 값들은 입력되는 시점에 이미 React 애플리케이션에서 알고 있다는 것을 의미합니다.

그렇기 때문에 Input에 존재하는 값들을 다시 Event 객체에서 뽑아서 사용하는 것이 아니라 React 어딘가에서 이미 상태로 관리되고 있는 값들을 활용하시면 좋을거 같아요. 우스가 생각하셨던 `ref`를 등록하는 방법도 전혀 필요없을거 같습니다!

몇 가지 더 하고 싶은 얘기가 있는데 그건 코드에 코멘트 남기겠습니다!

>그리고 현재 react에 관련된 함수가 아닌데도 hook 폴더에 있는 함수가 있는데 유틸로 옮길 생각입니다.

이 부분은 React에서 사용되는 컨벤션과 다르게 작성된 부분들이 있어 코드를 읽으면서 혼란스러워 코멘트로도 남겼는데요. 우스도 이미 인지하고 계셨군요 👍 👍 👍 

>엄청나게 친절한 리뷰 해주셔서 감사합니다 유조! 👍👍👍
덕분에 코드 작성에 힘이 났어요 👍👍

우스가 이렇게 말해주시니 저도 힘이 나네요

제 리뷰가 우스에게 도움이 될 수 있도록 열심히 리뷰 해보겠습니다! 👍 👍 

---

step2도 고생 많으셨습니다 우스~

2023-04-29 12:49 UTC, yujo11 commented on src/components/card/RegisteredCard.tsx
> +  cardTitle: UseInputProps;
`cardTitle`이라는 이름만 보면 string일거 같은데 `UseInputProps`로 많은 정보를 한번에 받고 있네요

2023-04-29 12:49 UTC, yujo11 commented on src/components/card/RegisteredCard.tsx
> +interface RegistredCardProps extends CardProps {
그리고 소소하게 오타가 있는데 spell checker 같은 extension을 설치하시면 두고두고 잘 써먹으실 수 있을거에요!

2023-04-29 12:49 UTC, yujo11 commented on src/components/card/RegisteredCard.tsx
> +              bgColor="#fff"
이런 색상들은 공통으로 관리해봐도 좋겠네요!

2023-04-29 12:49 UTC, yujo11 commented on src/components/card/RegisteredCard.tsx
> +    const { cardTitleInput } = event.currentTarget;
이 부분은 조금 이해가 안 되는데요.

1. event.currentTarget을 통해 요소를 가져오는 이유가 있을까요?
2. event.currentTarget에서 가져온 cardTitleInput는 어떤 타입일까요?

2023-04-29 12:49 UTC, yujo11 commented on src/components/card/BankInfo.tsx
BankInfo는 SelectBank Component에서만 사용되는 요소이니 아래처럼 묶어봐도 좋을거 같아요

```
SelectBank(폴더)
- index.ts(SelectBank를 re-export) -> 요건 개인 취향입니다 ㅋㅋ
- SelectBank.tsx
- BankInfo.tsx
```

2023-04-29 12:49 UTC, yujo11 commented on src/components/card/BankInfo.tsx
그리고 그에 따라 네이밍도 SelectBankItem 같이 변경되면 해당 파일을 볼 때 연관성을 한번에 확인할 수 있어서 좋을거 같네요!

2023-04-29 12:49 UTC, yujo11 commented on src/components/card/RegisteredCard.tsx
> +const Form = styled.form``;
이건 왜 필요한걸까요?

2023-04-29 12:49 UTC, yujo11 commented on src/components/card/SelectBank.tsx
> +          <BankInfo key={bank} kind={bank} onClick={() => onClick(bank)} />
`onClick`이라는 이름만으로는 `BaknInfo`를 클릭했을 때 어떤 동작을 할지 예상할 수 없는데요.

조금 더 친절하게 네이밍 해보는건 어떨까요?

2023-04-29 12:49 UTC, yujo11 commented on src/components/common/ChangeButton.tsx
이 `ChangeButton`은 `Button`을 이용하지 않고 별도로 구현하신 이유가 있을까요?

2023-04-29 12:49 UTC, yujo11 commented on src/components/common/Modal.tsx
> +}
앞으로 범용적으로 쓰일 수 있는 이러한 컴포넌트들을 구현하실 때 Antd, Chark 같은 디자인 컴포넌트를 제공해주는 라이브러리들에서 어떤 식으로 구현되어 있는지 props등을 참고해보셔도 좋을거 같아요!

당장 뭘 변경하라는 얘기는 아니고 그냥 참고하셨으면 좋겠어서 코멘트 남깁니다!

2023-04-29 12:49 UTC, yujo11 commented on src/components/common/Modal.tsx
> +  z-index: 1;
이런 `z-index`도 묶어서 공통으로 관리해보시면 좋겠네요! 

상수화를 하면 관리가 편해지고 나중에 `z-index`를 가지는 요소가 늘어나면 순서를 맞추기 위해 여기저기 파일을 찾아다니는 수고를 덜 수 있답니다 ㅋㅋ

2023-04-29 12:49 UTC, yujo11 commented on src/constant.ts
> +};
👍 👍 👍

2023-04-29 12:49 UTC, yujo11 commented on src/constant.ts
> +  dismiss: 999,
요건 그냥 의견인데 상수로 쓰이는 값들이 아래처럼 대문자로 관리되면 코드를 볼 때 상수임을 한 눈에 확인할 수 있어서 좋을거 같아요

```suggestion
export const TAB_INDEX_INFO = {
  DISMISS: 999,
```

2023-04-29 12:49 UTC, yujo11 commented on src/hooks/createFormInputValue.ts
hook들은 `use-` prefix를 붙여주는게 react의 컨벤션인데요.

컨벤션에 따라 네이밍을 해주시면 좋을거 같아요~

2023-04-29 12:49 UTC, yujo11 commented on src/hooks/createFormInputValue.ts
> +export const createFormInputValue = (
이름을 직역하면 Form의 Input Value를 생성한다는거 같은데요.

이 이름을 보고 왜 Form의 Input Value를 생성하지? 라는 의문이 들었습니다.

이 hook은 어디에서 어떤 용도로 사용하기 위해 만들어진걸까요?

2023-04-29 12:49 UTC, yujo11 commented on src/hooks/useFocusInput.ts
> +      setNextInputFocus(formRef.current);
함수를 분리하셨군요 👍

2023-04-29 12:49 UTC, yujo11 commented on src/utils.ts
uril 함수가 많아짐에 따라 하나의 파일 안에 많은 함수가 선언되어 있어 코드를 확인하기 어려워진 느낌이 드는데요.

비슷한 역할을 수행하는 util 함수끼리 나눠보시면 좋을거 같아요~

2023-04-29 12:49 UTC, yujo11 commented on src/utils.ts
> +};
위에도 `use-` prefix에 대한 얘기를 남겼는데요.

hook에 `use-` prefix를 붙이는게 컨벤션이다보니 hook이 아닌 일반 함수에 `use-` prefix가 붙으면 hook이라고 착각하는 상황이 생길거 같아요~

이름을 변경해보시면 좋겠네요!

2023-04-29 12:49 UTC, yujo11 commented on src/utils.ts
> +};
이런 함수는 내장 함수를 사용하는 곳에서 직접 호출하는게 더 좋을거 같네요.

내장 메서드로 기능할 수 있는 부분들을 별도의 함수로 분리하게 되면 코드를 볼 때 알아야 하는 정보가 늘어나는 것에 비해 얻을 수 있는 이점이 없을거 같아요

2023-04-29 12:49 UTC, yujo11 commented on src/utils.ts
> +};
이 부분도 마찬가지로 굳이 함수로 분리해서 사용할 필요가 있는지 의문이 드네용

2023-04-29 12:49 UTC, yujo11 commented on src/utils.ts
> +};
그리고 사실 이것 역시 별도의 함수가 필요할지 모르겠습니다 🫠

2023-04-29 12:49 UTC, yujo11 commented on src/stories/card/Card.stories.tsx
이거는 정해진건 아니지만 보통은 `*.stories` 파일들은 해당 컴포넌트와 가까운 위치에 두는데요. 참고하시면 좋겠네요!

ex)
```
Card
- Card.tsx
- Card.stories.tsx
```

2023-04-29 12:49 UTC, yujo11 commented on src/pages/AddCardPage.tsx
>    const onCardInfoSubmit = (event: FormEvent<HTMLFormElement>) => {
그리고 `onCardInfoSubmit`라는 이름으로는 어떤 동작인지 예측하기가 어려운데요.

동작을 알기 위해 `onCardInfoSubmit` 함수의 내용을 읽은 후에도 여전히 어떻게 동작하는지 헷갈리네요 😵‍💫

2023-04-29 12:49 UTC, yujo11 commented on src/pages/AddCardPage.tsx
>    const onCardInfoSubmit = (event: FormEvent<HTMLFormElement>) => {
함수의 이름을 변경해보시고, 코드도 조금 더 다음어보셨으면 좋겠습니다!

도메인에 따라 복잡한 로직을 수행하는 함수는 적절하게 주석을 남기는 것도 도움이 될 수 있는데요. 어려우시면 주석을 남기는 방법을 활용해보셔도 좋을거 같아요!

2023-04-30 01:03 UTC, Gilpop8663 commented on src/components/card/BankInfo.tsx
> +  letter-spacing: -0.085em;
피그마를 통해 필요한 CSS 속성을 알 수 있었습니다. 😀

2023-04-30 13:16 UTC, Gilpop8663 reviewed
리뷰해주셔서 감사합니다 유조! 그리고 Context API 사용 방법에 대한 좋은 블로그 글도 공유해주셔서 좋았습니다. 👍👍 리뷰해주신 내용들 위주로 리팩터링 해보려고 합니다  😀

2023-04-30 13:16 UTC, Gilpop8663 commented on src/utils.ts
> +};
[useInput.ts](https://github.com/woowacourse/react-payments/pull/247/files#diff-89e9134080bdc2a367ab1d383352eaa937372bebf6a1df518aea093c5e301c00)에서 convertValue의 함수로 넘겨주려다 보니 별개의 함수로 만들어 넘겼는데요. 유조의 의견은 유틸 함수에 내장 메서드를 이용하는 함수가 별도로 있는 것은 코드를 이해하는 비용이 더 늘어나니 이용하는 곳에서 내장 메서드를 직접 이용하는 것이 코드 이해에 더 도움이 될 것같다는 것으로 이해했습니다. 유조의 의견을 이해하니 유틸 함수에 굳이 내장 메서드를 다른 함수명으로 바꾼 것이 코드 이해에 더 어려워 졌다는 것에 공감이 갔습니다 👍👍 알려주셔서 감사합니다

2023-04-30 13:16 UTC, Gilpop8663 commented on src/utils.ts
> +};
유틸 함수에 있을 필요가 없는 것 같습니다 😅

2023-04-30 13:16 UTC, Gilpop8663 commented on src/utils.ts
> +};
use~ 가 접두사로 있어서 훅으로 오해할 수 있겠네요! 리엑트에서는 함수명 만들 때 주의 해야겠다고 느꼈습니다. 그리고 이 함수도 유틸에 굳이 없어도 될 것 같습니다. callback을 ()=>void 타입인 매개변수로 주려다가 더 복잡해질 것 같아요 짚어주셔서 감사합니다 👍👍👍

2023-05-01 09:02 UTC, Gilpop8663 commented
## 폴더 구조를 나누고 index.ts를 통해 Re-Export를 하였습니다.

스토리북 파일과 컴포넌트를 가까이 두고,  연관성 있는 컴포넌트끼리 묶어서 폴더를 관리하였습니다. 찾기 더 편해진 것 같아요 😀


## 스타일드 컴포넌트에 글로벌 스타일을 적용하고, 테마를 적용했습니다.

테마를 통해 전역적으로 색상을 관리할 수 있어서 좋았습니다. 

## 상수 오브젝트에서 고민이 있었습니다. 다음의 코드는 카드 데이터를 오브젝트로 만든 코드인데요. 상수를 오브젝트로 사용할 때 데이터로 사용하기 때문에 소문자가 자연스러워 보여서 우선 지금 코드엔 소문자로 진행했습니다.

```jsx
export const DATA_AA = {
  DEFAULT: {
    source: '',
    title: '',
    color: '#FFFFFF',
    backgroundColor: '#333333',
  },
};

export const DATA_BB = {
  DEFAULT: {
    SOURCE: '',
    TITLE: '',
    COLOR: '#FFFFFF',
    BACKGROUND_COLOR: '#333333',
  },
};
```

## 반면에 오브젝트라고 할지라도 상수가 간단한 경우에는 모두 대문자로 하였습니다.

```jsx
export const TAB_INDEX_INFO = {
  DISMISS: 999,
  ADD_CARD_PAGE: {
    FIRST_CARD_NUMBER: 0,
    SECOND_CARD_NUMBER: 1,
    THIRD_CARD_NUMBER: 2,
    FOURTH_CARD_NUMBER: 3,
    MONTH: 4,
    YEAR: 5,
    OWNER: 6,
    CVC: 7,
    FIRST_PASSWORD: 8,
    SECOND_PASSWORD: 9,
    SUBMIT: 10,
  },
};

```


## 카드 유효성 검사하는 로직이 너무 복잡해보여서 useRef를 사용해서 필요없는 유틸 함수 2개를 제거하고 코드 가독성을 늘렸습니다. 많이 깔끔해진 것 같지만 useFormInputs에서 관리하는 input이 1000개가 넘어가게 된다면, 한 페이지에 5개만 필요한 인풋 데이터를 불러오기 위해서 995개를 다 불러와야 하는 불상사가 생길 것 같아 고민이 되었습니다. 아직 더 좋은 방법을 생각하지 못했어요 🥶🥶

```jsx
  const { formInputs } = useFormInputs();
```

## 시간이 모자라 Context API를 아직 적용하지 못했습니다. 

리뷰해주셔서 감사합니다 유조! 👍👍👍

2023-05-01 14:04 UTC, yujo11 approved these changes
안녕하세용 우스~

지난번 리뷰를 주고받을 때도 느꼈지만 우스는 하나만 얘기해도 둘을 공부해서 적용하시는군요 정말 멋집니다 👍 👍 👍 💯 💯 💯 

전체적으로 이전 리뷰 때보다 파일명, 함수명 등 네이밍이 직관적이고 일관된 컨벤션을 따르게 변경되어서 코드를 읽기가 아주 좋았네요 ! 👍 👍 👍 

>상수 오브젝트에서 고민이 있었습니다. 다음의 코드는 카드 데이터를 오브젝트로 만든 코드인데요. 상수를 오브젝트로 사용할 때 데이터로 사용하기 때문에 소문자가 자연스러워 보여서 우선 지금 코드엔 소문자로 진행했습니다.
>반면에 오브젝트라고 할지라도 상수가 간단한 경우에는 모두 대문자로 하였습니다.

이 부분은 조금 더 고민해보셨으면 좋겠다는 생각이 들어요

우스가 남겨주신 부분 중 `TAB_INDEX_INFO `를 먼저 보고 `DATA_AA`를 보게 된다면 저는 아마 상수라고 생각하지 못 할거 같아요. 실제로 코드 리뷰를 진행할 떄도 그랬구요.

하나의 코드베이스에서 일정한 코드 컨벤션을 따르지 않으면 코드를 보는 사람이 쉽게 인지 부하를 느끼는 요인이 되는데요.

같은 상수이고 변경되지 않을 값이지만 어디에서는 소문자, 어디에서는 대문자로 표기를 하는 지금의 상수 표기법이 저에게는 그러했습니다.

이런 식으로 간다면 상수임을 나타내는 prefix나 suffix를 붙이던지 "상수는 이렇게 작성한다."로 귀결되었으면 좋겠어요

"상수는 이렇게 작성하거나 저렇게 작성한다"가 되면 코드를 볼 때 혼란이 오니까요!

---

전체적으로 코드가 많이 깔끔해져서 남긴 코멘트들이 많지 않은데요

코멘트로 남긴 내용들은 다음 step 진행하면서 적용해보시면 좋을거 같네요!

고생 많으셨습니다 우스! 👍 👍 👍 

++) 아 그리고 Context API는 미션 요구사항이기도 하니 학습 목적으로라도 꼭 한번 적용해보셨으면 좋겠네요~

2023-05-01 14:04 UTC, merged

2023-05-02 07:23 UTC, Gilpop8663 reviewed
리뷰해주셔서 감사합니다 ! 👍👍👍👍👍 !

2023-05-02 07:23 UTC, Gilpop8663 commented on src/components/addCardPage/CardNumberInput/CardNumberInput.tsx
> +          tabIndex={FIRST_CARD_NUMBER}
좋은 의견 감사합니다 👍👍👍

2023-05-02 07:23 UTC, Gilpop8663 commented on src/components/common/Button/Button.tsx
> +    color ? color : isDisable ? theme.colors.gray : theme.colors.primaryText};
네 한번 보기 좋게 개선해보겠습니다 👍👍

2023-05-02 07:23 UTC, Gilpop8663 commented on src/hooks/useInput.ts
> +    }
네 한번 해보겠습니다~ 👍

2023-05-02 07:23 UTC, Gilpop8663 commented on src/pages/AddCardPage/AddCardPage.tsx
코드가 너무 길어지면 코드 흐름 파악하는 것이 어려운데 styled 코드를 분리한다면 코드의 흐름을 파악하는데 도움이 되겠네요 감사합니다 👍

2023-05-02 07:23 UTC, Gilpop8663 commented on src/pages/AddCardPage/AddCardPage.tsx
> +  모든 인풋의 정보에서 카드 타이틀을 뺍니다.
`모든 인풋의 정보에서 카드 타이틀을 뺍니다.` 그 이유는 formInputs 에서 page별로 useInput 사용하는 것을 관리하고자  addCardPage에서 카드 타이틀에 관련한 useInput도 있는데요. formValidate에 CardTitle을 포함한 정보를 보내게 된다면 cardTitle이 빈 값이기 때문에 유효성 검사에서 실패해서 카드 타이틀을 빼게 되었습니다.

이런 코드를 없애는 방법으로 cardTitle을 필수 값이 아니여도 되어서 유효성 검사에서 통과 되게 한다거나 별도로 cardTitle을  addCardPage와는 다른 키값으로 관리하는 방법이 있겠습니다. 더 깔끔하게 코드를 작성하는 방향으로 생각해보도록 하겠습니다 🧐🧐

2023-05-02 07:23 UTC, Gilpop8663 commented on src/pages/AddCardPage/AddCardPage.tsx
> +    delete cardInformation.cardTitle;
아직 작성하지 않은 cardTitle을 지워줌으로써 유효성 검사에서 통과시키기 위해서였습니다.🧐

2023-05-02 12:56 UTC, yujo11 commented on package.json
> +          "pathGroups": [
다음번 미션을 진행할 때는 절대경로를 통해 import 하도록 적용해보셔도 좋을거 같네요 ㅎㅎ

tsconfig 에 `baseUrl`만 추가하시면 됩니다.

2023-05-02 12:57 UTC, yujo11 commented on src/pages/AddCardPage/AddCardPage.tsx
> +    delete cardInformation.cardTitle;
특정 타입이나 검사에 맞추기 위해서 객체의 속성을 `delete`하는 부분이 어색하게 느껴지는데요 다른 방법을 고민해보셔도 좋을거 같네요!