[페이먼츠 미션 Step 2] 헤다(윤다혜) 미션 제출합니다.
woowacourse/react-payments pull request #249
Opened 2023-04-28 09:50 UTC by Dahyeeee

헤인티 안녕하세요! step2로 돌아왔습니다. 
약간의 기능이 추가 되었다고 구현하고 UI를 보는 재미가 좀 있었습니다.ㅎㅎ
여전히 미흡한 부분이 많지만 일단 기능구현을 완료해서 PR올리고 리팩토링 진행해 나가겠습니다.

[배포페이지](https://dahyeeee.github.io/react-payments/)

### 이전 PR comment 관련
> router 중 browserRouter 를 사용하신 이유와 다른 router 들은 뭐가 있는지 알아볼까요? 
크루들과 이야기해보고 영상과 공식문서를 읽어보고 대략적인 이해를 했는데 제가 url 작동방식과 서버와 통신 등에 대한 이해가 적어서 아직 제 언어로 정리를 못하겠네요 ㅠㅠㅠ 😭
HashRouter의 경우 서버사이드랜더링이 필요할 경우 서버가 #이후 url을 알지 못해서 불가능한 점 때문에 보통은 browserRouter를 사용하는정도로 이해했습니다. 지금 미션같은 경우 서버와 통신이 필요없기 때문에 hashRouter가 좀더 쉽게 사용할 수 있는 점이 있지만 보통은 서버와 통신하는 앱을 구축하기 때문에 browserRouter를 사용해도 괜찮을 것 같습니다.

> context api 에 관해서
여러 컴포넌트에서 사용되는 값을 최상단에서 프롭스 드릴링을 하는 것보다 context api를 이용해 조금은 간단하게 사용할 수 있게 해주는 장점이 있는 거 같습니다. cardList가 사실상 현재 존재하는 모든 3페이지에서 사용되고 있어서 context로 관리해주기로 결정했습니다. 

> 이거는.. 상태를 사용하기 위해 억지로 끼워맞춘 느낌이 듭니다. 단순 유효성 체크라 함수 하나면 되는 것을 상태를 두고 함수를 제공해 상태를 바꾸는 것을 통해 컴포넌트 리렌더링만 추가되었네요!
ㅠㅠ 커스텀 훅 어렵네요 ㅠㅠ 이해가 될 듯 잘되지 않습니다.. 좀 더 실험해보고 다른 커스텀 훅을 읽어보면서 발전해나가겠습니다..

### 고민하고 노력한 점
- 커스텀 훅을 몇개 만들어봤습니다. 여전히 잘 쓴건지 모르겠지만 컴포넌트에 '이벤트와 UI'만 있도록 하는 게 좋다는 수업내용을 기억해서 왠만한 다른 로직들을 커스텀 훅이나 유틸로 분리하려고 노력했습니다.

- 유효성검사 훅이 재사용성은 없지만 로직을 분리해서 컴포넌트를 좀 간결하게 만든 것 같은데 헤인티가 보시기엔 어떠신가요? 

- CardItem.tsx 안에 있는 카드넘버 뒤 8자리를 숨겨주는 로직을 분리하고 싶었는데 어디로 빼줘야 할지 몰라서 안빼줬습니다. ㅎㅎㅎutil에 빼기에는 범용성이 없고 hook으로 빼기에는 React hook을 사용하고 있지 않아서 고민하다가 그냥 뒀는데... 그냥 있어도 괜찮아 보이나요? 

React를 시작하면서 공부할 것들이 늘어가고 최적화도 고민해야하고 하는데, 미션을 구현하는 것만으로 모든 에너지를 다 쓰고 있고 개인적으로도 마음이 쉽지가 않습니다. ㅠㅠ 그래서 헤인티가 제안해주시는 부분들도 찾아보고 알아보기는 하는데 깊이 있는 공부와 고민을 하지 못해서 죄송한 마음이 듭니다.. 조금 더 열정있고 의미있게 소통하고 싶은데 그러지 못하는 것 같아 아쉽고 죄송합니다. 그래도 헤인티 리뷰가 좋은 개발자로 성장하는 데 도움이 되고 발판이 된다고 느끼고 있습니다. 남겨주시는 코멘트 적어놓고, 또 다시 와서 보면서 꼭 공부하고 적용하려고 노력하겠습니다!

이번 리뷰도 감사합니다 헤인티!

2023-04-30 03:06 UTC, HyeonaKwon requested changes
안녕하세요 헤다! 제가 워케이션 갔다오느라 지금 미션을 확인했습니다ㅠ 늦어서 죄송합니다!

우선 배포된 사이트에서 런타임 에러가 발생해 아무것도 노출되지 않아서 확인해보지 못했습니다. 요거 한번 확인해주세요~!

말씀해주신 것들 중 유효성 관련 로직 부분에서 따로 빼신거는 좋은 것 같습니다! 훅이 꼭 재사용되어야 사용할 수 있는 것은 아니니까요! 비즈니스 로직을 따로 빼둔다는 점에서 좋았습니다. 
그리고 컴포넌트 내에 무조건 비즈니스 로직을 없애야 한다 라는 강박을 가질 필요는 없을 것 같아요. 분리하면 좋긴 하지만 어디에 놓기에도 애매한 것들도 있을 수 있잖아요! 그래서 너무 강박관념을 가질 필요는 없을 것 같아요!

나머지는 코멘트를 확인해주세요! 고생 많으셨습니다~!

2023-05-02 06:15 UTC, Dahyeeee commented on src/components/cardForm/CardNumberInput.tsx
> +  validateNumbersInput,
타입이나 큰 컴포넌트에 card가 항상 나와서 numbers로 통일했습니다!
04e32a5ac06ea4247808d18c6511d85c2b8ba87f

2023-05-02 06:16 UTC, Dahyeeee commented on src/components/cardForm/CardNumberInput.tsx
> +  ];
6b002de9b516df8b0d01d3a9027717dba20f6d66

2023-05-02 06:17 UTC, Dahyeeee commented on src/components/cardForm/CardNumberInput.tsx
>          {[2, 3, 4].map((ind) => (
카드넘버 input 인덱스인데 의미가 모호한 것 같네요! 변경했습니다!
cdceb6ddf88fed562065f41e8dea82f8c8b3226c

2023-05-02 06:21 UTC, Dahyeeee commented on src/components/cardForm/index.tsx
>    };
f01a6c35e746eff90fcd2eb63f7943d7fcb5d00b

2023-05-02 06:22 UTC, Dahyeeee commented on src/components/common/Input.tsx
> +      $textPosition,
styled-component 변수로 사용되는 props들 앞에 react component props와 구분하기 위해서 붙여줬습니다! 
컨벤션으로 쓰이는 곳이 있다는 코멘트를 봤고 좋은 생각인 거 같아서 저도 붙여서 구분했습니다.

2023-05-02 06:40 UTC, Dahyeeee commented on src/constant/cardCompany.ts
> +];
c35a17694fa5659f690259c2c4ff56225d9d3197

Readonly와 as const 모두 변수나 속성을 수정하지 못하도록 하는 스펙이네요. 
약간의 차이점은 as const는 타입스크립트가 변수의 타입을 타입리터럴로 인식해서 변경이 불가능하게 하고 
Readonly는 객체의 모든 속성을 읽기전용으로 만들어 수정이 안되게 하는 것으로 보이네요!

CARD_COMPANY같은 경우 사실상 데이터라 as const로 수정이 불가능하게 묶어주는 게 좀 더 합당해보여서 as const로 고정해줬습니다.

2023-05-02 06:42 UTC, Dahyeeee commented on src/hook/useFocusChain.tsx
> +};
오 너무 좋은 생각이에요!! 
시도해봤는데 eslint에서 map 콜백함수 안에서 useRef를 쓸 수 없다고 오류를 내서 esLint disable 해줘야 했습니당.. 
이 부분은 더 좋은 방법이나 안전한 방법이 있을 텐데 추후에 더 공부해보도록 하겠습니다! 

6b002de9b516df8b0d01d3a9027717dba20f6d66

2023-05-02 06:47 UTC, Dahyeeee commented on src/hook/useValidation.tsx
> +};
특정 벨리데이션이 수정된다는 게, 사용자가 인풋에 입력한다는 말씀이실까요? 아니면 state로 가지고 있는 inputValidity가 수정된다는 말씀이신가요? 

사용자가 입력함에 따라 input전체가 리랜더링이 일어나긴 하는데 useValidation 때문이 아니라 모든 input이 상위 컴포넌트에서 setCardData, 카드정보 변경 함수를 프롭스로 받고 있어서 일어나는 리랜더링이었습니다.  

제가 잘 이해한게 맞을까요..?

2023-05-02 06:51 UTC, Dahyeeee commented
리뷰 감사합니다 헤인티!

제가 이것저것 많이 시도해보고 context도 추가해보고 했는데 결국 더 좋은 방법이 아닌 것 같아 없애고 했더니 시간은 오래걸렸는데 실제로 변한 커밋은 몇개 없어서 좀 민망하네요.. 🥲

훅이 좀 더 범용성있게 된 거 같아 기쁩니다. 제안 감사합니다! 👍

2023-05-02 09:28 UTC, HyeonaKwon commented on src/hook/useFocusChain.tsx
> +};
참 hook 을 반복문 안에서 사용할 수가 없게 되어있죠! 😂

2023-05-02 09:33 UTC, HyeonaKwon approved these changes
아하 사파리로 열어서 봤습니다 ㅎㅎ 
![image](https://user-images.githubusercontent.com/46472795/235631209-1adee2e4-cc3e-4bb8-bea8-4bcc8a31925b.png)
카드 번호 UI 가 깨지네요! white-space 속성 추가해보셔도 좋을 것 같습니다!

3단계에서 뵈어요 헤다! 고생하셨습니다.

2023-05-02 09:33 UTC, merged