[페이먼츠 미션 Step 2] 참새(김규) 미션 제출합니다.
woowacourse/react-payments pull request #250
Opened 2023-04-28 12:08 UTC by WaiNaat

파노 안녕하세요! step2 수행하고 다시 리뷰 요청 드려요.

## 배포 페이지
[페이먼츠 미션](https://wainaat.github.io/react-payments/)
[스토리북](https://wainaat.github.io/react-payments/storybook)

##  고민했던 점

### DOM을 직접 접근하는 것을 최대한 줄이고자 하였습니다.

step1 때는 input값 길이 제어 등을 할 때, `event.target.value`를 직접 건드리는 방향으로 진행했습니다. 하지만 찾아보니까 이 방법은 비효율적이라고 하더라구요. 그래서 `Input` 컴포넌트에서 value를 state로 관리하도록 하였습니다. 위쪽에서 props로 parser를 내려서 value에 어느 정도 간섭이 가능하게 하였고, value state의 변화를 구독하는 함수들을 받아 value값에 접근할 수 있도록 했어요.

### Context API를 사용해 보았습니다.

기존에는 form 제출 시 값들을 받아오기 위해 모든 input에 id를 부여한 후 `FormData`를 이용했는데요. 이번에는 Context API를 이용해서 이 안에 현재 입력중인 신용카드 하나의 값을 저장할 수 있도록 하였습니다. 이렇게 하니 prop drilling 없이도 데이터를 전달할 수 있다는 점은 매력적이었는데요. 하지만 Provider 안쪽 컴포넌트들이 Provider에 의존하게 되어 "이게 과연 독립적인, 좋은 컴포넌트인가?" 라는 질문에는 의문이 들었습니다. 스토리북을 작성할 때 decorator를 이용해서 context를 사용하는 컴포넌트에 전부 Provider를 달아주다 보니 이런 생각이 들더라구요😥

### 스토리북을 만들어 보았습니다.

step1 에서는 스토리북을 단순히 렌더링만 해보는 용도로 사용했었고, 배포가 가능하다는 것조차 생각하지 못했습니다. 이번에는 컴포넌트를 만들고 고치면서 스토리북을 최대한 이용해봤어요. 컴포넌트만 렌더링이 가능하다는 점은 좋은 것 같습니다. 카드 사를 선택해야 하는 부분에서는 control을 이용해서 확인이 가능하도록 했어요. 기존의 테스트와는 다르게 ui도 이쁘고 직관적이라서 잘 만든다면 비 개발자들과의 협업에도 굉장히 좋겠다는 생각이 들었어요. 하지만 아직 interations를 이용한 자동화 테스트까지는 구현하지 못한 상태입니다. 다음 리팩터링 때 만들어서 올게요!

### '커스텀 훅'이라는 것의 기준이 무엇인지 모르겠습니다.

저는 기존에 커스텀 훅은 내부적으로 useState와 같은 것들을 사용하는 것이라고 생각했습니다. 하지만 수업을 듣다 보니 그렇지 않은 것도 훅이라고 부를 수 있는지 궁금해졌어요.
```javascript
export const useLengthValidator = (value, length) => (value.length <= length);
```
만약에 state는 사용하지 않지만 이름을 훅처럼 짓고 입력값의 길이 검사에 사용한다고 하면 이걸 훅이라고 볼 수 있을까요? '훅'이라는 이름만 고려해 본다면 이 역시 컴포넌트 외부에 있지만 컴포넌트에 '걸어서' 사용한다는 느낌이라 가능할 것 같아요. 하지만 리액트에서 제공하는 어떤 기능도 사용하지 않는데 이걸 리액트식으로 '커스텀 훅'이라고 부를 수 있을지 의문이 듭니다🤔 파노는 어떻게 생각하시나요???

2023-05-01 08:52 UTC, jho2301 commented
https://user-images.githubusercontent.com/44419181/235431320-dd1b6243-faf3-4347-aaa4-01dbc2ee0a2a.mov

요거 해결해보시면 어떨까요? 
유저가 새로고침했는데 404페이지를 만나면 당황할 것 같아요

2023-05-01 09:08 UTC, jho2301 requested changes
안녕하세요 참새~!
회사로고 돌아가는거 귀엽네요 ㅋㅋ
contextAPI 관련해서 고민을 해주셨는데, 전역상태를 사용할 때 프로바이더가 존재하는 것은 어쩔 수 없는 부분이 아닌가 싶어요.
과도하게 사용하는 것을 지양하고, 적절하게 전역적으로 공유가 필요한 상태만만 가려내어 사용하면 좋을듯 합니다. 쿼리파라미터나 스토리지API 등등 데이터캐싱에 활용할수있는 수단이 여러가지가 있는데요. 각각 어떤 상황에 활용할수있을지 고려해보는 시간을 가져봐도 좋을 것 같습니다.

두번째로 커스텀훅에대해서 고민을 해주셨는데

> state는 사용하지 않지만 이름을 훅처럼 짓고 입력값의 길이 검사에 사용한다고 하면 이걸 훅이라고 볼 수 있을까요?

왜 훅 함수 이름 앞에는 use를 붙여야하는지 리액트에서 컨벤션을 정한 맥락을 파악해보시면, 위 고민이 해결될것이라 생각해요. 요것도 제가 직접 답을 드리기보단 한 번 디깅해보는 시간을 가져보시면 좋을 것 같아요. 그래도 고민에 대한 해결이 안되면 연락주세요~~

코멘트 남겨봤으니 자유로이 댓글 남겨주세요 화이팅입니다

2023-05-03 09:57 UTC, WaiNaat reviewed
안녕하세요 파노 😃 코드 리뷰 감사합니다!!
말씀해주신 내용과 개선 방향이나 제 의견은 코멘트로 같이 남겼어요. 

## 새로고침 관련

배포 페이지에서 새로고침을 누르면 404로 가는 현상은 제대로 해결하지 못했어요.
처음에는 리액트 라우터를 이용한 페이지 이동 시 History.state를 지정해서 해당 값의 유무를 바탕으로 검사하려고 했어요. 하지만 그 검사보다 먼저 깃허브 서버에서 404를 띄워주는 것 같더라구요. 결국 제가 따로 404페이지를 만들어서 스크립트를 이용해 초기 화면으로 강제 리다이렉트 하는 방향으로 구성하였습니다.

다른 방법으로는 브라우저 라우터 대신 해시 라우터를 사용하는 방법이 있을 것 같은데요. 해시를 이용한 페이지네이션은 웹 표준이 아니고, 나중에 페이지 내에서 해시를 이용한 이동을 할 수 없다는 문제가 있어서 사용하지 않았습니다. 

## stroybook 관련

storybook interaction test도 input form만을 대상으로 간단하게 진행해 보았습니다. 그 과정에서 테스트를 진행할 input을 선택할 필요가 있었는데요. 저는 `data-testid` 속성을 각 input에 추가하여 `getByTestId()`를 이용했습니다. 하지만 코드를 짜다 보니 아무리 dataset 속성을 이용했다지만 너무 테스트를 위한 코드 수정이 아닌가 하는 생각이 들었어요. `getByTestId()`가 testing library에서 기본적으로 제공해주는 기능이기는 하지만 이걸 이용하기 위해서 제 코드에 실제 배포에는 불필요한 코드를 넣어도 괜찮을까요?

2023-05-03 09:57 UTC, WaiNaat commented on src/App.tsx
>            />
페이지 컴포넌트가 context api를 이용해서 카드 목록이나 새로운 카드 정보를 받아도 독립적으로 사용하기 어렵다는 생각이 들어요. props로 정보를 전달받는 것과 context api에 의존해서 전역 정보를 읽어오는 방법 둘 다 컴포넌트의 독립성에 영향을 주는데 context api를 사용하여 얻는 이점이 있는지 궁금합니다!

2023-05-03 09:57 UTC, WaiNaat commented on src/component/CardInputPage/CardCompany/CardCompanyButton.tsx
> +        alt={`${cardCompanyEnglishToKorean(companyName)} 로고`}
이 이미지는 바로 근처에 글자로 무엇인지 나타내고 있으며, 이미지 자체가 어떤 기능이나 역할을 한다기보다는 텍스트만 있으면 밋밋하니까 보는 사람이 편하라고 넣은 것에 가깝다는 생각이 들었어요, 그래서 [W3C](https://www.w3.org/WAI/tutorials/images/decorative/) 를 참고하여 alt를 빈 문자열로 넣는 방향으로 수정하였습니다.

관련 커밋: af325d2626778edf3c6af0dd1783eca4d6f6ff6e

2023-05-03 09:57 UTC, WaiNaat commented on src/component/CardInputPage/InputBoxPassword/CardPassword.tsx
> +    }
말씀해주신 것을 참고하여 고치니 훨씬 깔끔해진 것 같아요 감사합니다 !!

관련 커밋: 6761129017efe28e7e30671aaf386994f7ad8f6f

2023-05-03 09:57 UTC, WaiNaat commented on src/component/CardInputPage/InputBoxPassword/InputBoxPassword.tsx
>    const [error, setError] = useState(true);
이름을 더 명료하게 고쳤습니다 👍

관련 커밋: 5cf2e94180fb24144751dc1fc8f1cce9467fb700

2023-05-03 09:57 UTC, WaiNaat commented on src/component/common/CardPreview.tsx
> +  const c = company ?? 'woori';
카드사 항목을 반드시 입력하도록 하기보다는 다른 카드사를 이용하는 사람들을 고려하는 게 더 좋을 것 같다는 생각이 들었습니다. 그래서 카드사를 선택하지 않을 경우 `기타 카드`로 분류하여 따로 표시할 수 있도록 고쳤어요.

관련 커밋: b435467076e5707ca962bc3d762a7b3197121c1c

2023-05-03 09:57 UTC, WaiNaat commented on src/component/common/Modal/BottomModal.tsx
> +}
dialog에서는 open 속성을 통해 판별하네요! 제 모달에서도 open이라는 이름을 사용하도록 수정하였습니다. 

관련 커밋: 7e7433e13369caac530b8fff80a87ff39bfd9755

2023-05-03 09:57 UTC, WaiNaat commented on src/component/common/Modal/BottomModal.tsx
> +export default function BottomModal(props: BottomModalProps) {
따로 표현하는 말이 있다는 걸 처음 알았어요 😅 감사합니다!!

2023-05-03 09:57 UTC, WaiNaat commented on src/component/common/Modal/BottomModal.tsx
> +  const escCloseHandler = (e: KeyboardEvent) => {
동사형태로 바꿨어요!

관련 커밋: ad9c5153337f752120e2d1b7463018b617b8e65c

2023-05-03 09:57 UTC, WaiNaat commented on src/component/common/Modal/BottomModal.tsx
> +  }, [isOpen])
따로 이름을 만들고 함수로 분리하였습니다!

관련 커밋: ad9c5153337f752120e2d1b7463018b617b8e65c

2023-05-03 09:57 UTC, WaiNaat commented on src/context/CreditCardContext.tsx
> +  return { card, setCardInfo };
앗 그러네요 변경하였습니다.

관련 커밋: 2fc49ccaa981376bd380d068142f019479238a43

2023-05-03 09:57 UTC, WaiNaat commented on src/hook/useMultipleInputStatus.ts
> +
이런 기능이 있는 줄 생각지 못했네요. initializer 함수를 만들어서 적용하였습니다. 감사해요 😀

관련 커밋: dcb5ded577eb4942a562f13a15df5dceb1be838c

2023-05-03 09:57 UTC, WaiNaat commented on src/hook/useSingleCreditCard.ts
> +
CreditCard만이 아니라 오브젝트 형태의 자료들에 대해서 적용할 수 있게 훅을 확장하였습니다!
콜백함수를 이용하는 것은 아래 메모이제이션을 진행하면서 같이 적용했어요.

관련 커밋: 010590e818791cb2323e7f4384d2fd0025fc2f83

2023-05-03 09:57 UTC, WaiNaat commented on src/hook/useSingleCreditCard.ts
> +
훅의 콜백에 useCallback을 이용해서 불필요한 함수 재정의를 줄이고자 하였습니다.

관련 커밋: 61207a6a200d58069ca53501e414758b5ee70b00

하지만 파노가 말씀하신 의도가 이게 맞는지 궁금해요!
저는 처음에 '기억'이라는 점에 집중해서 기존의 state와 비교했을 때 변한 점이 없다면 setState를 하지 않는 방향을 생각해서 아래와 같은 코드를 작성했었어요.

```typescript
const isPartialShallowEqual = <T extends Object>(object: T, partial: Partial<T>) => (
  Object.entries(partial).every(([key, value]) => (
    object[key as keyof T] === value
  ))
);

const setPartialState = useCallback((partialState: Partial<T>) => {
  if (!isPartialShallowEqual(state, partialState)) {
    setState((prevState) => Object.assign({}, prevState, partialState));
  }
 }, [state]);
```

혹시 이 정도 비교까지는 필요가 없을까요?

2023-05-03 09:57 UTC, WaiNaat commented on src/type/CardCompany.ts
> +};
이렇게 하면 키값을 제한할 수 있네요 감사합니다!!

관련 커밋: 93b63998eb3b84ef00bd53740bb7ee6c6f06d474

2023-05-05 13:42 UTC, jho2301 commented on src/App.tsx
>            />
위에 말씀드린대로 ssr프레임워크에서 어떻게 페이지 모듈을 관리하는지 알아보셔도 좋았을것같아요.
말해준것처럼 전역 프로바이더에 의존해야하는 사실은 여전하나, 프로그램 전역에 유지되는 프로바이더는 ssr에서도 사용이 가능해요 
next.js같은 경우는 _app모듈에서 프로바이더를 공통적 사용할 수 있게 구성되어 있는데요
요즘 프론트엔드 같은 경우에는 ssr도 옵션으로 자주 고려되기 때문에 마이그레이션에 용이한 코드를 고려해보시면 좋겠습니다

2023-05-05 13:47 UTC, jho2301 commented on src/hook/useSingleCreditCard.ts
> +
기본적으로 setState에서 값이 같으면 re-render가 일어나지는 않는데요. 리액트에서는 값을 비교할 때 얕은 비교를 하나요 깊은 비교를 하나요?
그리고 그 반대의 방법을 react 에서 채택하지 않은 이유에 대해서 한 번 찾아보고 고려해보시면 좋을 것 같습니다.
그러면 참새 스스로 기준을 세울 수 있을 것 같네요

2023-05-05 13:49 UTC, jho2301 commented on src/hook/useMultipleInputStatus.ts
> +
```  
const [states, setStates] = useState<INPUT_STATUS[]>(() => getStateInitializer(length));
```

변경해주신 인자는  함수를 전달하지 않은 것 같아요. 근데 그렇게 연산이 무거운 동작이 아니라 차이가 미미할 거라 괜찮을 것 같습니다

2023-05-05 13:52 UTC, jho2301 commented on src/hook/useMultipleInputStatus.ts
> +
커리함수네였네요. 적절하게 적용해주셨군용

2023-05-05 13:53 UTC, jho2301 commented on src/component/common/Modal/BottomModal.tsx
> +  }, [isOpen])
아예 분리할거라면  useEffect도 커스텀훅으로 분리하면 어떨까 싶네요.
말씀드린 상황은 컴포넌트에 사용될때 이야기였어유

2023-05-05 14:02 UTC, jho2301 commented
### 새로고침 관련
배포 페이지에서 새로고침을 누르면 404로 가는 현상은 제대로 해결하지 못했어요.
처음에는 리액트 라우터를 이용한 페이지 이동 시 History.state를 지정해서 해당 값의 유무를 바탕으로 검사하려고 했어요. 하지만 그 검사보다 먼저 깃허브 서버에서 404를 띄워주는 것 같더라구요. 결국 제가 따로 404페이지를 만들어서 스크립트를 이용해 초기 화면으로 강제 리다이렉트 하는 방향으로 구성하였습니다.

다른 방법으로는 브라우저 라우터 대신 해시 라우터를 사용하는 방법이 있을 것 같은데요. 해시를 이용한 페이지네이션은 웹 표준이 아니고, 나중에 페이지 내에서 해시를 이용한 이동을 할 수 없다는 문제가 있어서 사용하지 않았습니다.

해시라우터여도 브라우저에서 직접 해당 path 페이지를 요청하면 똑같은 현상이 발생할 것 같아요! 
일반적인 웹서버에서 html서빙하는 방식에 대해 알아보셔도 좋을 것 같아요.

### stroybook 관련
storybook interaction test도 input form만을 대상으로 간단하게 진행해 보았습니다. 그 과정에서 테스트를 진행할 input을 선택할 필요가 있었는데요. 저는 data-testid 속성을 각 input에 추가하여 getByTestId()를 이용했습니다. 하지만 코드를 짜다 보니 아무리 dataset 속성을 이용했다지만 너무 테스트를 위한 코드 수정이 아닌가 하는 생각이 들었어요. getByTestId()가 testing library에서 기본적으로 제공해주는 기능이기는 하지만 이걸 이용하기 위해서 제 코드에 실제 배포에는 불필요한 코드를 넣어도 괜찮을까요?

testing library 문서 보시면 쿼리종류에 대한  우선순위가 나와 있는데요. 요거 참고해보시면 좋을 것 같습니다.
웬만하면 -byRole에서 해결보시는걸 추천드려요. name옵션으로 대부분 케이스에 대응가능합니다.
 
https://testing-library.com/docs/queries/about/#priority

2023-05-05 14:03 UTC, merged

2023-05-08 04:57 UTC, WaiNaat commented on src/hook/useSingleCreditCard.ts
> +
찾아보니 리액트에서는 `Object.is()`를 사용해서 얕은 비교를 수행하네요. 깊은 비교를 한다면 어디까지 깊어지는지 쉽게 판단할 수 없어서 성능상의 문제로 얕은 비교에서 그치는 것 같습니다. 그러면 저도 기본적으로는 얕은 비교를 염두에 두고, 깊은 비교를 해야 한다면 꼭 필요한지 다시 한 번 더 생각해야겠어요 감사합니다!