[페이먼츠 미션 Step 2] 세인(이세민) 미션 제출합니다.
woowacourse/react-payments pull request #257
Opened 2023-04-29 04:23 UTC by semnil5202

2023-04-30 05:17 UTC, JeongBin0227 commented
> 케빈은 보통 어떤 방식으로 디렉토리 구조를 사용하시나요?

당연히 프로젝트마다 다르게 가져가겠지만, 우선 가장 베이스로 생각하는 구조는

`public`: 정적 파일이 위치하는 폴더로, index.html 파일이 있습니다. 웹팩 등의 빌드 툴을 사용하지 않고, 바로 접근할 수 있는 파일들이 위치합니다.
src 안에  
`assets`: 이미지, 스타일 시트 등의 리소스 파일
`services`: API 요청 등의 비즈니스 로직을 처리하는 서비스 파일
`utils`: 공통으로 사용되는 함수 등의 유틸리티 파일

개인적으로 제일 중요하다고 생각하는 컴포넌트는
components: 컴포넌트들이 위치하는 폴더
containers: 페이지와 같은 최상위 컴포넌트들이 위치하는 폴더 components 의 조합
pages: 페이지를 모아 놓고, containers 의 조합
아래의 구조로 관리하고 전역적으로 사용하지 않는(재사용이 없는) 타입, 스타일, 훅은 해당 컴포넌트와 같은 위계로 사용하고 있습니다.

또한 컴포넌트 폴더 안에서도 common 폴더, layout 폴더, ui 폴더 등으로 구분해 관리하기도 합니다.

2023-04-30 05:20 UTC, JeongBin0227 commented
> Context API가 필요해보이나요?

Context API 는 전역상태를 관리하기 위해 사용하는데, 제 생각에는 세인이 Context API 가 불필요하다고 느낀 것은 충분히 타당하고 합리적이라고 생각합니다. 그 이유는 첫째는 현재 만들고 있는 서비스가 그리 크지 않고 복잡한 구조를 가지지 않고, 둘째는 현재 세인이 다루는 서비스에서 가장 중요한 상태인 카드를 

> useEffect(() => {
>     setLocalStorage('cards', cards);
>   }, [cards]);

이렇게 앱 최상단에서 로컬스토리지에서 관리 해주고 있어서 더더욱 필요없다고 느끼셨을수도 있을거 같아요

2023-04-30 05:33 UTC, JeongBin0227 commented
<img width="490" alt="image" src="https://user-images.githubusercontent.com/45503248/235337366-656fbc4a-b079-4369-87c1-e12c0ab5007c.png">
혹시 여기서 선택하지 않고 딤 되어 있는곳을 누르면 카드사를 선택하지 않는데 예상하신 부분일까요?

2023-04-30 05:57 UTC, JeongBin0227 requested changes
안녕하세요 세인 :) 

세인이 감이 안잡힌다고 말씀하셨는데, 걱정하는 거와 달리 세인이 깔끔하게 분리를 잘하시고 개발 잘해주셔서 굉장히 쉽게 코드가 잘 읽혔습니다! 👍👍👍 

질문해주신 부분이랑 좀더 개선하면 좋은점 코멘트 남겨드렸습니다 :)
확인부탁드려요~ 👍  고생하셨습니다!! 💯

2023-04-30 05:57 UTC, JeongBin0227 commented on src/components/@common/CardAliasInput.tsx
> +      autoFocus={autofocus}
(공통질문)
이름이 같은 프롭은 {...CardAliasInputProps} 으로 한번에 넘길 수 있는데 혹시 따로 이렇게 넘기는 이유가 있을까요?

2023-04-30 05:57 UTC, JeongBin0227 commented on src/components/@common/CardLabel.styles.ts
> +  color: ${(props) => props.color || '#000000'};
👍

2023-04-30 05:57 UTC, JeongBin0227 commented on src/components/@common/CardLogo.tsx
> +        setIsModalOpen(false);
사람마다 취향이 다를 순 있지만, 저는 이벤트 액션이 두개 이상 되면 함수로 빼서 네이밍으로 하는 역할을 알려주는 편인데 세인은 어떠신가요?

2023-04-30 05:57 UTC, JeongBin0227 commented on src/components/CardCompanyModal/CardCompanyModal.tsx
> +        }}
아까 코멘트에도 남겼는데, 카드사 선택안했는데 꺼져도 되나요?

2023-04-30 05:57 UTC, JeongBin0227 commented on src/components/CardCompanyModal/CardCompanyModal.tsx
> +            key={uuidv4()}
uuid 보다 카드사 이름이 고유한거 같은데 이걸 활용해보면 어떨까요?

2023-04-30 05:57 UTC, JeongBin0227 commented on src/components/CardNumbers/CardNumbers.tsx
>  };
해당 CardNumber 파일의 절대적인 코드양이 많아서 눈에 잘 안들어오는데,
뷰와 로직을 분리하는느낌으로 같은 위계에서 hook 을 사용해보면 어떨까요?

2023-04-30 05:57 UTC, JeongBin0227 commented on src/components/CardOwnerName/CardOwnerName.tsx
>    const nameRef = useRef<HTMLInputElement>(null);
너무 잘아시겠지만, 중요한 개념이라서 useRef 와 useState 의 차이점을 명확하게 알고, 클로져 기반으로 동작원리를 설명할 수 있어야합니다.

2023-04-30 05:57 UTC, JeongBin0227 commented on src/components/CardPassword/CardPassword.tsx
>      1: useRef<HTMLInputElement>(null),
아직 ref 가 많진 않지만, 여유가 된다면 연습삼아 https://github.com/woowacourse/react-payments/pull/192#issuecomment-1521493421 예전에 다중 ref 관련해서 질문 주신 부분을 활용해보면 어떨까요?

2023-04-30 05:57 UTC, JeongBin0227 commented on src/types/Image.ts
> +}
이 부분도 지금은 필요없지만, 이런 방법도 있다는걸 말씀드리고 싶어서 
카드사가 추가되면 수정해야하는 부분이 두군데 이지만, 그러면 휴먼에러가 발생하기 쉬워서 카드사를 관리하는 배열을 하나만 두고 그걸 이용해서 IMAGE_PATH와 ImagePathType 를 작성해보면 어떨까요?

2023-04-30 05:57 UTC, JeongBin0227 commented on src/utils/setLocalStorge.ts
> +};
파일명이 setLocalStorage 인데 setLocalStorage 와 getLoacalStorage 이 두개가 있는게 어색한데, 파일을 분리하던가 파일명을 바꿔보면 어떨까요?

2023-04-30 05:57 UTC, JeongBin0227 commented on src/pages/AddCardAlias.tsx
> +    if (/[~!@#$%^&*()_+=[\]\\';,./{}|\\":<>?]/.test(alias)) return;
`[~!@#$%^&*()_+=[\]\\';,./{}|\\":<>?]` 해당 정규식을 코드를 처음보는사람도 쉽게 이해할수 있게 변수로 빼보면 어떨까요?

2023-04-30 05:57 UTC, JeongBin0227 commented on src/pages/AddCardAlias.tsx
> +    setCardAlias(alias);
validateAlias 가 함수명인데 setCardAlias 이 있는게 어색하고, 함수가 여러 일을 하는거 같아서 개선해보면 어떨까요?

2023-05-01 13:39 UTC, semnil5202 commented on src/components/CardPassword/CardPassword.tsx
>      1: useRef<HTMLInputElement>(null),
배열 방식으로 리팩토링 해보겠습니다! 😀

2023-05-01 13:39 UTC, semnil5202 commented on src/pages/AddCardAlias.tsx
> +    if (/[~!@#$%^&*()_+=[\]\\';,./{}|\\":<>?]/.test(alias)) return;
전반적으로 정규표현식 상수화 진행하겠습니다!

2023-05-01 13:39 UTC, semnil5202 commented on src/pages/AddCardAlias.tsx
> +    setCardAlias(alias);
그러네요 네이밍과 거리감이 좀 있는 함수 동작 같군요. 함수를 분리하거나 함수명을 다시 생각해보겠습니다!

2023-05-01 13:39 UTC, semnil5202 commented on src/types/Image.ts
> +}
아하 이제보니 한 번에 처리할 수 있는데 이상하게 작성했었네요. 🤔

인덱스 시그니처를 활용해보겠습니다.

2023-05-01 13:39 UTC, semnil5202 commented on src/utils/setLocalStorge.ts
> +};
파일명을 수정해보겠습니다!

2023-05-01 13:44 UTC, semnil5202 commented on src/hooks/useSecurityCode.ts
> +    setSecurityCode(value);
아하 이 부분도 다시 보니 굳이 boolean 값을 반환할 필요가 없어보이는데 전반적으로 리팩토링해보겠습니다!!

2023-05-02 09:41 UTC, semnil5202 commented
### [배포링크](https://semnil5202.github.io/react-payments/)

안녕하세요 케빈! 연휴 잘 보내셨나요? 빠르게 리뷰해주셨는데 이것저것 시도해보느라 리뷰 재요청이 많이 늦어졌네요.. 🥲

최대한 리팩토링을 진행해보았습니다..! 주요 리팩토링 내용을 정리해보면 다음과 같습니다.

### 주요 리팩토링 요약
- [x] 각 컴포넌트 관심사 커스텀 훅 분리 및 리팩토링
- [x] 공통 프롭 전개 연산자로 할당
- [x] 최초 카드사 선택 전 모달 딤 영역 선택 시 모달이 닫히는 오류 수정
- [x] ref 객체 보관 방법 변경 및 context API 적용
- [x] input 컨테이너 간 오토 포커스 기능 추가
- [x] 매직넘버 상수화 및 전반적인 코드 가독성 개선

### 추가로 궁금한 점
리액트와 관련된 내용은 아니지만, 문득 궁금해져서 질문드립니다!

현업에서는 크로스 브라우징 이슈를 어떻게 해결하시나요? 맥북 크롬에서 미션을 진행하면서 작업한 내용을 집에서 윈도우 크롬으로 확인할 때 간혹 디폴트 글씨체 크기(?)로 인해 맥북에서는 안보이던 스크롤 바가 생기거나, 일부분은 잘려서 보이는 오류가 있었습니다.

같은 브라우저인데도 운영체제에 따라서 차이가 발생하나요? 이러한 이슈는 어떻게 해결하나요? 🧐

2023-05-03 08:33 UTC, JeongBin0227 commented
> 이러한 이슈는 어떻게 해결하나요? 🧐

이런 이슈는 크로스 브라우징 이슈라고 합니다. 크로스 브라우징 이슈를 해결하기 위해서는 

1. 백분율 단위로 크기를 설정하기
2. 가능한 한 표준 웹 기술을 사용하기
3.  브라우저마다 다르게 렌더링되는 것을 고려해서, 브라우저별로 CSS 스타일 시트를 작성하여 적용하기
4. 크로스 브라우징 라이브러리 사용하기

정도 생각 해 볼 수 있을거 같아요~ 저는 보통 현업에서 1번 2번 방법을 주로 사용해서 해결합니다

2023-05-03 08:35 UTC, JeongBin0227 requested changes
안녕하세요 세인~

수정해주신 곳 모두 확인했습니다. 꼼꼼히 수정해 주셔서 감사합니다 :) 
남겨주신 질문에 대해서 답변 남겼어요~ 한번 확인 부탁드립니다

스텝2 하느라 고생하셨습니다  스텝3도 화이팅입니다!! 👍 💯

2023-05-03 08:35 UTC, merged

2023-05-03 08:45 UTC, semnil5202 commented
리뷰 정말 감사드립니다!! 👍👍 운영체제마다 다른 렌더링 엔진을 사용하는군요..! 같은 브라우저라 차이가 없을 줄 알았는데 키워드 감사드립니다!!

몇 시간 전에 안 사실인데, validate 부분을 커스텀 훅으로 분리하면서 마지막 글자 입력시 유효성 검사를 불통하는데도 다음 input으로 포커스 되는 자잘한 오류가 보이네요..

스텝 3때 리팩토링해서 리뷰 요청드리도록 하겠습니다. 감사합니다! 😀😀