[페이먼츠 미션 Step 2] 아이크(하지원) 미션 제출합니다.
woowacourse/react-payments pull request #268
Opened 2023-04-30 11:30 UTC by afds4567

안녕하세요 체프✋ 
step2에서 context Api와 타입스크립트를 같이  활용하려다보니 오래걸렸던 것 같습니다…

## Context api
제가 작성한 코드에서는 사용자가 등록하고 있는 카드 번호부터, 색깔, 별칭까지 카드 정보의 모든 것을 갖는 CardContext와 카드 회사 선택 창의 열고 닫힘을 관리하는 DrawerContext가 있습니다. 
 각 Context의 저장된 상태가 필요하거나 변경이 필요할때마다 불러서 사용했는데 ContextApi를 사용하기 위해 작성해야할 코드만 많아진거 같고 너무 남발해서 사용한것 아닌가 생각했습니다. 
체프가 생각하는 ContextApi를  잘 활용하기 위한 방법이 있다면 알려주시면 감사하겠습니다.

## 재사용성
step1에 이어 재사용성에 대해 고민해보면서 저번 리뷰에 남겨주신  말랑말랑한 컴포넌트와 딱딱한 컴포넌트를 step2동안 제 나름대로 정리해봤습니다.  
말랑말랑한 컴포넌트라면 멍청한(?) 컴포넌트로, 받아온 정보를 보여주기만 하는 컴포넌트라고 생각됩니다. 제가 만든 컴포넌트에선 대표적으로 Input, Card 가 포함된다고 생각됩니다. 이번 미션에서 재사용도 나름 잘 되었던 것 같습니다. 
반대로 딱딱한 컴포넌트는  똑똑하게 로직을 처리하는 역할을 한다고 생각하여 제 코드를 봤는데 Page 폴더에 있는 컴포넌트들이 가깝지 않은가 생각됩니다.  
이런 방향으로 분리하는게 질문의 의도에 맞았는지 궁금합니다. 

## 아쉬운점
너무 제출이 늦어지는듯 해서 Storybook 상호 작용 테스트,Uncontrolled Components에 입각하여 Form 핸들링 부분은 다음 step까지 계속 이어서 하겠습니다!
이번 리뷰도 잘 부탁드립니다~ 🙇

2023-05-01 06:06 UTC, Puterism requested changes
아이크 안녕하세요! 2단계 미션 수행하시느라 고생 많으셨어요! 👏 👏 👏 
리뷰 확인해주시고 답변 및 수정 부탁드릴게요!

---

> 체프가 생각하는 ContextApi를 잘 활용하기 위한 방법이 있다면 알려주시면 감사하겠습니다.

음, 저는 우선 전역 상태 관리가 필요한 경우에는 Context보다는 상태 관리 라이브러리를 사용하는 편이예요. (아마 미션에서는 상태 관리 라이브러리를 사용할 수 없으셨을 것 같지만...) Context는 전역 상태를 관리하기에 적합하지 않다고 생각해요. 리렌더링이 일어나니까요. 구조적으로 전역 상태 관리에 최적화된 다른 라이브러리를 사용하는 것이 더 좋다고 생각해요.
그럼에도 Context를 사용해야 하는 경우에는, 범위를 최대한 좁혀서 사용해요. 다른 부분이 리렌더링되지 않고, 필요한 부분만 리렌더링될 수 있게요.

---

> 말랑말랑한 컴포넌트라면 멍청한(?) 컴포넌트로, 받아온 정보를 보여주기만 하는 컴포넌트라고 생각됩니다. 제가 만든 컴포넌트에선 대표적으로 Input, Card 가 포함된다고 생각됩니다. 이번 미션에서 재사용도 나름 잘 되었던 것 같습니다.
반대로 딱딱한 컴포넌트는 똑똑하게 로직을 처리하는 역할을 한다고 생각하여 제 코드를 봤는데 Page 폴더에 있는 컴포넌트들이 가깝지 않은가 생각됩니다.
이런 방향으로 분리하는게 질문의 의도에 맞았는지 궁금합니다.

비슷하지만 조금 다릅니다.
제가 생각했던 말랑말랑한 컴포넌트는 재사용성이 좋아야 한다고 생각해요. 재사용성이 좋다는 것은 다양한 상황에서도 컴포넌트가 유효한다는 걸 의미한다고 생각해요.
딱딱한 컴포넌트는 그와 반대죠. 특정 상황에서 로직이 매우 유효한 컴포넌트예요.
그래서 prop을 많이 받는다고 해서 무조건 재사용성이 좋은 컴포넌트는 아니라는 것을 말씀드리고 싶었습니다.

말씀하신 것처럼 Dumb Component와 Smart Component도 상황에 따라서 유효한 방법이 될 수는 있습니다. 개인적으로 지금 아이크가 작성해 주신 컴포넌트는 이번 미션에서 유효했다고 생각합니다 :)

2023-05-01 06:06 UTC, Puterism commented on src/custom.d.ts
> +  export const ReactComponent: REact.FC<React.SVGProps<SVGSVGElement>>;
여기도 오타일까요? 

```suggestion
  export const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
```

2023-05-01 06:06 UTC, Puterism commented on src/hooks/useFormValidation.tsx
> +  const isTitleFilled = title === "";
isTitleFilled라는 이름은 타이틀이 채워져 있는지에 대한 여부를 확인하는 것 같은데, 조건식은 타이틀이 비워져 있는지 체크하고 있는 것 같네요. 의도하신 코드가 맞으실까요?

2023-05-01 06:06 UTC, Puterism commented on src/context/CardContext.tsx
> +    </CardStateContext.Provider>
필요한 Provider를 두 개로 묶어서 하나의 Provider Component로 잘 만들어주셨네요 :)

2023-05-01 06:06 UTC, Puterism commented on src/components/Page/AddNicknamePage.tsx
> +    setCardList(cardList ? [...cardList, newCard] : [newCard]);
setState는 비동기로 동작하는데요, 이 때의 cardList는 최신 상태를 보장할 수 없습니다. 따라서 다른 형태의 코드로 작성해야 하는데요. 최신 상태의 cardList를 가지고 상태를 변경할 수 있는 방법은 무엇이 있을까요?

2023-05-01 06:06 UTC, Puterism commented on src/components/Card.tsx
> +  const isHomePage = type === "homepage";
이렇게 조건식 하나도 const로 묶어서 네이밍을 주는 것은 좋은 습관이라고 생각합니다 :)

2023-05-03 15:11 UTC, afds4567 commented on src/context/CardContext.tsx
> +function cardTypeReducer(state: CardState, action: Action) {
Redux를 써본적은 없는데... Context를 처음 사용해보는거라 공식문서의 "reducer와 context"로 확장하기를 참고했습니다 😓
사실 useReducer도 처음 사용해봤는데 여러개의 setState를 할 것을 cardTypeReducer 한곳에 모아서 볼 수 있어서 좋았습니다.

2023-05-04 06:41 UTC, afds4567 commented on src/components/Page/AddNicknamePage.tsx
> +    setCardList(cardList ? [...cardList, newCard] : [newCard]);
타입이랑 같이 변경하려니 어렵네요... 😓 😓 
[c2ab1c6](https://github.com/woowacourse/react-payments/pull/268/commits/c2ab1c6cdbb5f92894cc11b134a8dca8dae3923b)

2023-05-04 07:18 UTC, afds4567 commented on src/context/DrawerContext.tsx
> +      <DrawerDispatchContext.Provider value={{ setIsDrawerOpen }}>
최적화를 할 때 state의 값이 바뀌면 StateContext를 구독하는 컴포넌트만, setIsDrawerOpen가 재생성되면 DispatchContext를 구독하는 컴포넌트만 렌더되게 할 수 있다고 생각해서 분리했는데 하나로 합치고 React.memo로 카드 정보가 입력될때 불필요한 렌더링을 방지했습니다. 
[2530897](https://github.com/woowacourse/react-payments/pull/268/commits/25308971edd6068606da16309b385365bea64f77)

2023-05-04 07:32 UTC, afds4567 commented on src/hooks/useFormValidation.tsx
> +  const isTitleFilled = title === "";
form이 모두 다 채워졌는지 판정해서 disable 속성에 true, false값으로 사용되기 때문에 isFormNotFilled로 수정해봤습니다.

2023-05-04 08:20 UTC, afds4567 commented
체프가 남겨주신 리뷰 반영해서 수정하고 컴포넌트 렌더링에 관해 공부해봤습니다.
가장 불필요한 렌더링이라고 생각되었던 카드 정보 입력 페이지에서 input에 정보를 입력할 때마다 카드회사 선택 모달이 렌더링 되는 것을 React.memo를 통해 해결했습니다. 
미션 요구사항에 "react에서 제공하는 hook을 이용하여 성능 최적화를 고려한다."가 이런 방식으로 불필요한 렌더링을 줄이는 것도 포함되는 것인지 궁금합니다.

2023-05-05 03:50 UTC, Puterism commented on src/context/CardContext.tsx
> +function cardTypeReducer(state: CardState, action: Action) {
그렇군요! 코드 형태가 나쁘다는 뜻은 아니었습니다! 좋은 학습이 되었다면 그걸로 좋다고 생각합니다. 😃

2023-05-05 03:52 UTC, Puterism commented
> 미션 요구사항에 "react에서 제공하는 hook을 이용하여 성능 최적화를 고려한다."가 이런 방식으로 불필요한 렌더링을 줄이는 것도 포함되는 것인지 궁금합니다.

준이 의도했던 성능 최적화가 아닌지는 저도 잘 모르겠습니다 😅 하지만 성능 최적화를 시도했다는 점에서 저는 괜찮다고 생각합니다 :)

2023-05-05 03:53 UTC, Puterism approved these changes
반영해주신 내용 모두 확인했습니다! 수고 많으셨어요 👏 👏 👏 
다음 단계에서 만나요!

2023-05-05 03:53 UTC, merged

2023-05-05 03:55 UTC, Puterism commented on src/hooks/useFormValidation.tsx
> +  const isTitleFilled = title === "";
사소한 부분이지만 다음에는 부정형이 아닌 긍정형으로 작성해보시기를 추천드려요! 예를 들어서 isFormNotFilled -> isFormFilled와 같이요! 부정형으로 변수를 작성하게 되면 한 번 더 뒤집어서 생각해야 하기 때문에 코드 가독성에 영향을 미치기도 하거든요 :)