[1단계 - 페이먼츠 미션] 파노(전환오) 미션 제출합니다.
woowacourse/react-payments pull request #3
Opened 2021-04-26 11:12 UTC by jho2301

작성 중

2021-04-28 01:45 UTC, Vallista requested changes
안녕하세요 파노님!
코드가 많아서 보는데 오래걸렸고, CRA 로 만들어지는 부분도 피드백을 하느라 좀 오래걸렸네요. (CRA인 줄 모르고 생각없이 리뷰하다 그만;)

## 전반적인 코드 리뷰

1. React 컴포넌트를 생성하실 때, 함수 컴포넌트 같은 경우에는 `React.FC`를 붙여주시는 게 좋고, children이나 리액트 컴포넌트 스펙을 제한적으로 사용한다면 `React.VFC`를 써주는게 좋겠습니다.

2. CRA를 사용하는 것은 좋으나, 무언가 제대로 사용이 안된 느낌이 듭니다. 관련해서는 코드 라인에 리뷰를 드렸으니, 한번 읽어보시고 과연 올바른 형태로 사용을 하고 있는지, CRA의 장점을 잘 쓰고 있는지, webpack이나 tsconfig 설정은 제대로 되어있는지 검토가 필요해보입니다.

3. 전반적으로 상태가 너무 날 것으로 구현이 되어 있습니다. 이렇게 되어 있으면, useEffect등으로 subscribe를 할 때 다량의 상태에 대해 변화를 감지하고, 해당 상태당 다양한 사이드 이펙트를 제공하기 때문에 앱 변화에 대한 추적이 어려울 수 있습니다. 이러한 상태 관리의 대안으로 Context API를 이용해 상태를 묶는다던가 (HTML Hierarchy 상으로 구분을 할 수 있습니다.) Redux, Mobx같은 상태 라이브러리를 사용한다는 선택지들이 있겠습니다. 다만 Context API는 렌더링 최적화에 대한 사이드이펙트를 제공하므로, 후자를 추천드리긴 함니다.

4. 결제 쪽을 구현하셨다보니, 에러에 대한 부분이 안전하게 코딩 되어야 할 것으로 보입니다. 하지만 프로덕트내에 코드를 보면 컴포넌트가 뻗거나 내부 배열에 직접 접근하는 로직이 많아보입니다. 이러한 부분들은 장기적으로 장애를 충분히 낼 수 있는 부분으로 보입니다. (지금 당장은 괜찮겠지만, 요구사항이 추가되면 상태가 많기 때문에 실수로 배열 조작이 달라진다거나...) 특히 `AddCardForm` 쪽에서요! 

5. 요것도 생각해보면 좋겠습니다. 컴포넌트가 장애가 나면 어떻게 보여줘야 할까요? 등록 프로세스 전체를 안되게 해야할 지, 이전 뎁스로 돌아가게 해야할 지, 대체될 컴포넌트를 보여줄게 좋을지... 

7. Color Palette를 추가 하셨는데 제대로 전체적인 부분에서 못쓰고 있는 걸로 보입니다. 전체적으로 쓸 수 있게 수정해주세요 :)

2021-04-28 01:45 UTC, Vallista commented on src/constants/cardData.ts
> +    color: '#E24141',
color palette가 있던데 그걸 쓰는게 좋겠습니다.

2021-04-28 01:45 UTC, Vallista commented on src/constants/palette.ts
> +export const GRAY = '#ECEBF1';
Color palette를 설정해둔 것은 좋으나, GRAY도 워낙 종류가 많고 비슷한 색상이 많아서 GRAY_000, GRAY_100 등등으로 100단위로 구별하는게 좋겠습니다.

2021-04-28 01:45 UTC, Vallista commented on src/global.styles.ts
> +    color: #333333;
color palette를 쓰는게 좋겠습니다.

2021-04-28 01:45 UTC, Vallista commented on src/pages/CardListPage/index.tsx
> +      color: '#547CE4',
Color Palette!

2021-04-28 01:45 UTC, Vallista commented on tsconfig.json
> +  "compilerOptions": {
https://linedevday.linecorp.com/2020/en/sessions/5101

NoImplicitAny를 꼭 추가해서 사용하세요.

2021-04-28 01:45 UTC, Vallista commented on tsconfig.json
> +  "compilerOptions": {
any의 사용은 장기적으로 제어하지 않으면, 생산성을 저하시킵니다.

2021-04-28 01:45 UTC, Vallista commented on src/utils/format.ts
> +export const formatNumber2Digits = (number: number) =>
formatNumber 를 하고, parameter에서 digit수를 받으면 더 범용적으로 쓰일 수 있겠네요.

2021-04-28 01:45 UTC, Vallista commented on src/pages/AddCardPage/index.tsx
> +const title = '카드추가';
CONSTANT에 추가되어도 상관없겠습니다.

2021-04-28 01:57 UTC, JaeYeopHan commented
@Vallista  안녕하세요, 우연히 리뷰를 봤는데요, 자칫 한 쪽의 의견만 전달될 것 같아서 제 생각 추가합니다.

> 함수 컴포넌트 같은 경우에는 `React.FC`를 붙여주시는 게 좋고

저는 이 리뷰에 동의할 수가 없는데요, FC<PropsType> 타입은 암묵적으로 children을 props에 포함시킵니다. 합성을 의도하지 않는 컴포넌트도 합성 대상이 될 수 있고 컴포넌트에서 가장 중요하다고 생각되는 props design에 암묵적인 property가 포함되는 것이라고 생각합니다.

Props는 필요한 부분만 별도로 정의하고 parameter에 선언해주는 것이 좋다고 생각합니다.

cra typescript template에서는 React.FC 타입을 제거했습니다 (https://github.com/facebook/create-react-app/pull/8177)

2021-04-28 03:55 UTC, Vallista commented
@JaeYeopHan 안녕하세요 재엽님!

합성이 대상이 되는 컴포넌트와 대상이 안되는 컴포넌트를 FC와 VFC 두 가지로 나누어서 볼 수 있다고 생각했습니다.
그래서 이후 VFC에 대한 설명을 덧 붙인 이유이구요, 그리고 Function Component의 경우 (뿐만아니라 다양한 부분에서) 리액트 컴포넌트 타입은 암묵적으로 정해질 수 있는 부분이 상당히 위험하다고 생각합니다. Function Component인지, Arrow Function인지 return 타입을 보고 추론을 해야하는 부분이니까요. 리액트를 진행한 지 얼마 안되는 시점에서는 타입에 대한 추론을 진행하기보다는 명확하게 제공해주는 편이 좋다고 생각합니다.

2021-04-28 13:01 UTC, JaeYeopHan commented
확인이 늦었습니다 🙇 

음;;;;
1. 일단 React.FC 타입으로 명시를 하면 실제로 함수 컴포넌트에서 children을 받든 안 받든 children을 넘길 수 있게 됩니다. 즉, 잘못된 타이핑인 것입니다.
2. 그리고 애초에 React.FC 타입은 children을 제공하는 것이 의도된 것이 아니라 호환성을 위해 남겨진 것입니다.

children을 제공하는 컴포넌트의 경우에는 다음 두가지로 Props를 정의해야 합니다.

```ts
interface Props {
  children: React.ReactNode
}
```
or
```ts
```

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33602

2021-04-29 02:36 UTC, Vallista commented
@jaeyeonling 님 답변을 남겨주셔서 감사합니다!

위 부분은 예전부터 많은 의논이 있었던 걸로 알고 있고, 요 부분에 대해서 이야기를 해볼 수 있어서 좋네요!

```
일단 React.FC 타입으로 컴포넌트의 타입을 명시하면 실제로 함수 컴포넌트에서 children을 받든 안 받든 children을 넘길 수 있게 됩니다. 즉, 컴포넌트에 대한 잘못된 타이핑인 것입니다.
그리고 애초에 React.FC 타입이 children을 제공하는 것은 의도된 것이 아니라 호환성을 위해 남겨진 것입니다. (SFC)
children을 제공하는 컴포넌트의 경우에는 다음 두가지로 Props를 정의해야 할 수 있고 이 방법을 사용하는 것이 더 좋습니다.

interface Props {
  children: React.ReactNode
}
or

type Props = PropsWithChildren<P>
```

요 위에서 이야기 된 내용에 대한 제 생각은.

1. React.FC에서 children 을 제공하는 부분은 저도 단점이라고 생각합니다. 다만, FC와 VFC(요 부분은 FC를 위한 임시 기능이긴 해도)를 사용해서 children이 필요없는 부분에는 명시적으로 VFC를 써줌으로써, children을 제어할 수 있다고 생각이 듭니다. (여기서 문제는 FC의 children이 nullable 이라는 부분이겠네요! 그래서, VFC를 사용해주면 좋겠습니다) 다만, 18.0.0(?)에 어떻게 변할지는 몰라서 말씀하신대로 모호한 점이 있어서, 안쓰는 편이 더 좋을 것 같다는 생각이 드네요! 👍 

2. `그리고 애초에 React.FC 타입이 children을 제공하는 것은 의도된 것이 아니라 호환성을 위해 남겨진 것입니다. (SFC)` DefinitelyTyped/DefinitelyTyped#33602 에서 확인했으며, 사용하려면 VFC를 적극적으로 권해야겠네요!

3. 인터페이스로 명시적으로 children을 써주는 방법은 위에 말씀하신대로 이해를 하면 될 것 같고, `type alias`를 사용하여 처리하는 부분은 Generic으로 사용할 수 있어서 더 좋다는 뜻으로 이해했는데, 맞을까요? 👍 

```
그리고 말씀해주신 부분을 굳이 짚어보자면,

정리하면, 암묵적으로 넘어가는 부분은 최대한 배제해야한다고 생각하며, 첫 시작하는 입장에서는 귀찮거나 힘들어도 강력하게 코딩 컨벤션을 lint로 제한하거나 명확한 표현을 써서 가져가야 한다고 생각합니다.

FC를 쓰는게 암묵적이라고 생각하고, children을 명시적으로 typing해야 한다고 생각합니다.

조금 길어졌는데, 일단 잘못된 타입을 가지고 안정성(?) 그리고 첫 시작하는 입장(?) 같은 것을 따지는게 조금 엇나간 것 같습니다 😅
아래는 관련 타입과 관련된 논의가 이루어진 이슈입니다. 🙇
```

그리고 짚어주신 부분에서 이야기를 해보면, 

1. children을 명시적으로 typing 해야하는 부분은 저도 동의하는 부분이고, 다만 제공하는게 있어 FC를 쓰는게 암묵적이라고 생각하는 부분에 대해서는 컴포넌트에 반환형을 넣어주는게 좋겠습니다.

2. 그 이유는, 현재 프로젝트는 결제와 연관된 부분이고 저 디테일한 체크가 필요하다고 생각됩니다. 함수가 쓰이는 곳이 함수 컴포넌트, 커스텀 훅, 이벤트 핸들러, 행동을 제어하기 위한 메소드 및 함수 다양한 부분에서 사용이 됨에 따라 컴포넌트 hierarchy 등이 고려되지 않은 상황 (이번 2단계에서는 고려하지 않았다고 하셔서) 에서는 실수를 할 여지가 있기 때문에 (또한 이 부분은 첫 시작하는 부분에서 실수를 제어하는 부분이기도 합니다) 반환형에 대해 구별을 할 수 있도록 코드를 작성하면 좋을 것 같다는 생각에서 나온 부분입니다. 그렇기에 적어도 FC를 사용하므로써 함수 컴포넌트에 대한 영역은 구별이 될 것이라 생각합니다. 

3. 다만 요 부분은 함수 컴포넌트만 구별이 된다고 제어가 되는 부분은 아니여서, LINT에 옵션을 추가하도록 피드백을 드리는게 더 좋겠네요 👍

2021-04-29 05:03 UTC, jho2301 commented
리뷰 감사드립니다.
1. 환경세팅에 대한 이해가 부족한 것 같습니다. 반성하고 공부하겠습니다
2. 스텝2부터 컨텍스트API에 대한 요구사항이 들어가는 것으로 알고있습니다. 다음 단계가 리덕스를 이용해 구현한다고 하네요! 모두 구현할 수 있을 것 같아 기대가 큽니다. 이번 과제에서는 컨텍스트API로 개선을 해보도록 하겠습니다!
3. 컴포넌트가 뻗는다는 상황에 대한 이해가 좀 더 필요한 것 같습니다. 런타임에러로 이해를 하면 좋을까요? 배열 직접 접근하는 부분 고치겠습니다!
4. 에러상황에 대한 부분 어렵네요..! 고민해보도록하겠습니다.
5. 주신 피드백 오늘 중으로 최대한 반영하겠습니다

2021-04-29 05:10 UTC, jho2301 commented on .eslintignore
> +scripts/
cra로 생성된 디렉토리 내 파일들이 linter에 감지되어서 ignore해준 부분입니다.
직접 구성해보는 연습부터 해봐야겠네요!

2021-04-29 05:18 UTC, jho2301 commented on .eslintrc.json
> +    "ecmaVersion": 12,
https://eslint.org/docs/user-guide/configuring/language-options#specifying-parser-options

eslint에서 가장 최신으로 사용할 수 있는 ecmaVersion이 12여서 12로 명시했습니다.

2021-04-29 05:18 UTC, jho2301 commented on config/env.js
> +  `${paths.dotenv}.${NODE_ENV}.local`,
제가 한 부분이 아니지만 많이 배우겠습니당..ㅜㅜ

2021-04-29 05:25 UTC, jho2301 commented on config/jest/babelTransform.js
> +  if (process.env.DISABLE_NEW_JSX_TRANSFORM === 'true') {
https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
https://github.com/facebook/create-react-app/issues/9873

17버젼에 이르러서 jsx 변환이 새롭게 코드가 써졌는데 새로운 jsx변환을 disable하고 이전의 jsx변환을 동작하게하는 환경변수로 보여집니다

2021-04-29 05:39 UTC, jho2301 commented on package.json
> +  "name": "temp",
react-payments로 바꿨습니다!

2021-04-29 05:39 UTC, jho2301 commented on package.json
> +  "dependencies": {
모두 dev-dependencies로 이동시켰습니다!

2021-04-29 05:56 UTC, jho2301 commented on package.json
> +  "private": true,
cra가 디폴트로 세팅하는 부분입니다. 
이런 부분 신경 못 쓴 것 같아서 부끄럽네요

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#private

publish를 막는 플래그로 학습했습니다.  
굳이 필요없는 부분으로 제거하겠습니다.

2021-04-29 06:02 UTC, jho2301 commented on package.json
> +  "jest": {
testing-library, jest를 현재 과제에서 사용하고 있지 않기 때문에 제거를 하는게 좋을 것 같습니다!

2021-04-29 10:39 UTC, jho2301 commented on public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
검색사이트에 노출을 고려하고 있지 않기때문에 필요하지 않다고 생각합니다 ㅎㅎ..

2021-04-29 11:07 UTC, jho2301 commented on tsconfig.json
> +  "compilerOptions": {
![image](https://user-images.githubusercontent.com/44419181/116541441-70b9ac80-a926-11eb-92b3-eea25a5e662b.png)

공유 감사합니다!

2021-04-29 11:33 UTC, jho2301 commented on src/constants/cardData.ts
> +    color: '#E24141',
모두 상수화 하겠습니다!

2021-04-29 12:19 UTC, Vallista commented on config/jest/babelTransform.js
> +  if (process.env.DISABLE_NEW_JSX_TRANSFORM === 'true') {
CRA에 대한 부분은 요 코드를 인지하고 작성하셨는지에 대해서 여쭤본 질문들이었습니다~ 한번씩 확인하시면 도움이 될 것 같습니다!

2021-04-29 15:45 UTC, jho2301 commented on src/components/AddCard/AddCardForm/index.tsx
> +              .map(({ type, ref }, index) => (
![image](https://user-images.githubusercontent.com/44419181/116577249-45958400-a94b-11eb-960b-06ad2eef5e72.png)

제시해주신 fragment를 활용하면 컴포넌트 안에 컴포넌트가 선언되어서 리렌더링되면서 input요소의 포커스가 계속 풀렸습니다. 그래서 마지막에 말씀해주신 것처럼 컴포넌트를 바깥으로 빼야했는데, props가 reduce 콜백의 매개변수 + addCardForm의 상태를 props로 전달받게돼서 코드의 복잡도가 높아지는 것으로 느껴졌습니다.  (제가 잘못 판단했을 수도 있습니다.. )
제시해주신 방법을 변형해서 acc배열에 계속 push해서 리턴하는 것으로 코드를 개선해보았습니다. 
같이 고민해주셔서 감사합니다 ㅜㅜ..

2021-04-29 16:12 UTC, jho2301 commented on src/components/AddCard/AddCardForm/index.tsx
> +            {[
![image](https://user-images.githubusercontent.com/44419181/116582782-a96e7b80-a950-11eb-9eab-aafbd98ecef1.png)

상태 디펜던시가 있어서 함수바깥으로 빼지 않기로 판단했고, 
function컴포넌트에서 훅스아니고선 배열생성반복을 멈추기는 어려울 것 같아서useMemo활용해봤습니다.

2021-04-29 16:18 UTC, jho2301 commented on src/components/AddCard/AddCardForm/index.tsx
> +    if (cardNumber[0].length !== CARD_NUMBER_DIGITS || cardNumber[1].length !== CARD_NUMBER_DIGITS) {
![image](https://user-images.githubusercontent.com/44419181/116584059-ebe48800-a951-11eb-9e78-1292c5a07e4d.png)
이런 식으로 구조분해할당과 메서드를 이용해서 직접 접근 코드를 제거하겠습니다.

2021-04-29 17:16 UTC, jho2301 commented on src/components/AddCard/AddCardForm/index.tsx
> +    nextValue[index] = value;
함수가 배열을 가지고 있는 경우 union type으로 인자전달받는 것을 제한하고 type predicate 유효성검사 만들어주고, 갖고있지 않은 경우에는 try-catch문으로 감싸주었습니다.  


> 컴포넌트가 장애가 나면 어떻게 보여줘야 할까요?
 등록 프로세스 전체를 안되게 해야할 지, 
이전 뎁스로 돌아가게 해야할 지,
 대체될 컴포넌트를 보여줄게 좋을지.


일단 서비스의 성격에 따라 다를 것 같습니다.

결제와 같이 예상하지 못한 변수를 최대한 통제해야하는 파트에서는 등록프로세스 전체를 막아야할 것이고,

비교적 유연한 서비스 운용이 가능한 파트에서는 바로 이전 뎁스로 돌아가게 하는 것이 좋을 수도 있겠다는 생각이 듭니다.

다만 두 경우 모두 유저가 오류상황을 충분히 인지하도록 안내가 되어야 합니다.
따라서 현재는 예외상황을 통제해야하는 결제파트이므로 등록프로세스 전체를 막고, 에러 상황을 표시하는 에러모달을 만들어주면 좋다고 생각합니다.

2021-04-29 17:39 UTC, jho2301 commented on src/components/AddCard/AddCardForm/index.tsx
> +  const [password, setPassword] = useState<PasswordState>(['', '']);
상태를 나눠서 관리하면 편리할 것이라 생각했는데 오히려 가독성을 해치고 있는 것 같습니다. 하나로 모아보겠습니다!

2021-04-30 00:11 UTC, jho2301 commented on src/components/AddCard/AddCardForm/index.tsx
> +              .map(({ type, ref }, index) => (
![image](https://user-images.githubusercontent.com/44419181/116633184-d1330300-a993-11eb-80dd-a39f5bcdd975.png)
![image](https://user-images.githubusercontent.com/44419181/116633198-dabc6b00-a993-11eb-8876-63081c718084.png)

돌아돌아온것같지만 이런식으로 분리하는게 더 나을수도있을것같네요

2021-05-01 03:06 UTC, jho2301 commented
원래의 생각보다 고민하고, 고칠부분이 많아서 하루 늦었습니다. 죄송합니다

1. children을 명시적으로 타이핑하고, FC/VFC를 사용해봤습니다.  JBee님이 올려주신 https://github.com/facebook/create-react-app/pull/8177 FC타입의 장단점에 대해 파악해보고, 고민을 해봤는데 children에 대한 제어를 할 수 있다면 FC가 갖는 가장 큰 단점이 제거되는 것으로 생각했습니다.  버그를 컴파일타임에 잡아내는 것이 타입스크립트의 큰 장점인 만큼,  Vallista님의 의견에 동의해서 실수를 방지하기 위해 변수타입을 지정해보았습니다. 

![image](https://user-images.githubusercontent.com/44419181/116769197-53472880-aa75-11eb-8ffb-370d52848130.png)
2. 리뷰를 반영해서 form 상태를  하나의 객체로 만들었는데, 가독성이 상승한 반면,  단일 프로퍼티만 수정하는 상황만 존재해서 각 프로퍼티를 변경하는 setState함수를 추상화해 만들어 주었습니다.  이 부분은 트레이드오프로 생각하면 좋은 부분일까요?

2021-05-01 05:38 UTC, Vallista commented
안녕하세요 파노님!
당연히 죄송할 필요 없습니다 ㅠㅠ 고민하신 것 충분히 알고 있고, 코드 잘 보았습니다!

위에 말씀해주신 부분은 trade-off긴 합니다. 다만 추후 context api 형태로 옮기거나 store를 만든다면 요러한 부분은 어느정도 해소가 될 부분일 것 입니다!

2021-05-01 05:38 UTC, Vallista commented
안녕하세요 파노님!
당연히 죄송할 필요 없습니다 ㅠㅠ 고민하신 것 충분히 알고 있고, 코드 잘 보았습니다!

위에 말씀해주신 부분은 trade-off긴 합니다. 다만 추후 context api 형태로 옮기거나 store를 만든다면 요러한 부분은 어느정도 해소가 될 부분일 것 입니다!

2021-05-01 05:39 UTC, Vallista commented
전반적으로 잘 피드백을 적용해주셔서 좋고, 다음 미션 Context API에서 적용해보면서 기존 부분과 비교를 해보면 좋겠습니다!

2021-05-01 05:40 UTC, merged