[페이먼츠 미션 Step 3] 룩소(우정균) 미션 제출합니다.
woowacourse/react-payments pull request #329
Opened 2023-05-08 08:54 UTC by woo-jk

안녕하세요 브콜🥦 연휴는 잘보내셨나요!?

이번 스텝3는 테코톡 준비와 여러 행사들이 겹쳐 온전히 집중하지 못했습니다..🥲
요구 사항을 지키지 못한 부분(카드 등록 시 로딩)도 있어 아쉽네요 ㅠㅠ

스텝1,2에 비해 리팩토링 한 부분이 많지 않지만 그래도 잘 부탁 드리겠습니다!!!

### [페이먼츠 배포 사이트](https://woo-jk.github.io/react-payments/register)
### [라이브러리 배포 사이트](https://www.npmjs.com/package/luxo-react-modal)
### [페이먼츠 스토리북 📚](https://644c07750ea1cea860282338-fmfkdgqhso.chromatic.com/?path=/docs/payment-common--docs) (스텝2와 동일)

# 리팩토링 진행한 점
### UX 개선
UX 측면에서 피드백 해주신 부분들을 수정했습니다.
> 카드 등록 페이지에 진입하자마다 카드사 input에 error 메시지가 뜹니다.

모달이 open 되었을 때는 에러메시지가 뜨지 않도록 수정했습니다!

> 카드 등록 페이지에 진입하지마자 카드사 bottom sheet가 나타나네요..! 의도하신 동작일까요?

넵 사용자가 카드사를 바로 선택할 수 있도록 유도하기 위해 카드사 모달이 바로 뜨도록 유도했습니다.

> 만료일 input을 다 입력하기도 전에 error 메시지가 나타납니다.

만료일 input이 블러 될 때 입력 검증을 하도록 변경했습니다. 이로 인해 useInput 훅을 조금 변경했는데요,
기존에는 onChange validator만 받았었지만 onBlur validator 까지 따로 받도록 수정했습니다.
그리고 기존 onChange 함수와 더불어 onBlur 함수도 return 하도록 변경했습니다.

> 유효하지 않은 달을 입력했는데 커서가 넘어갑니다.

이 부분은 아직 해결 못했습니다 ㅠ 인풋 포커싱을 잘 다루기가 참 어렵네요..

### Modal 배포
모달 관련 부분을 npm 라이브러리로 배포했습니다. [chakra ui의 모달](https://chakra-ui.com/docs/components/modal/usage)의 사용 방식을 참고해서 비슷하게 만들고 싶긴했는데 잘 한건지는 모르겠네요..ㅎㅎ 기존에는 package.json의 값들이 어떤 값인지 잘 모르고 사용했었는데 이번 라이브러리 배포를 통해 package.json의 값이 어떤 의미인지 많이 알게된 것 같습니다!

# 궁금한 점
### context api의 구조
Input 컴포넌트의 훅 사용에 대한 계층 구조는 다음과 같습니다.

useInput(혹은 useMultipleInputs) 
-> 인풋 별 커스텀 훅(useCardNumber 등) 
-> Context Provider(CardItemProvider)
-> 컴포넌트에서 사용

이번에 useInput에 onBlur 함수를 추가하면서 느낀건데, onBlur 함수를 추가하니 위 계층의 모든 파일에 onBlur 관련 코드를 하나하나 다 추가해줘야하는 번거로움이 있었습니다. 아래 계층(useInput)에서 변화가 생기면 위 계층에서 모두 변화를 줘야 한다는 점에서 유지보수가 많이 번거롭다고 생각하는데.. 제가 구조에 대한 의존성 제거를 잘 못해서 이런 문제가 발생하는 건가요? 아니면 원래 이런 계층 구조에서 어쩔 수 없이 발생하는 문제인가요?

2023-05-09 18:34 UTC, Tanney-102 requested changes
안녕하세요 룩소~
Step3까지 정말 고생 많으셨습니다!
코드 작성하기도 바쁜 미션이었을텐데 라이브러리 배포까지..!👍
코드레벨에서 크게 코멘트 드릴만한 점은 없었어요
사소한 내용들만 있으니 확인부탁드려요!

> 이번에 useInput에 onBlur 함수를 추가하면서 느낀건데, onBlur 함수를 추가하니 위 계층의 모든 파일에 onBlur 관련 코드를 하나하나 다 추가해줘야하는 번거로움이 있었습니다. 아래 계층(useInput)에서 변화가 생기면 위 계층에서 모두 변화를 줘야 한다는 점에서 유지보수가 많이 번거롭다고 생각하는데.. 제가 구조에 대한 의존성 제거를 잘 못해서 이런 문제가 발생하는 건가요? 아니면 원래 이런 계층 구조에서 어쩔 수 없이 발생하는 문제인가요?

계층 구조 때문에 변경이 많았다기 보다는 실제 사용처에서의 변경들이었다고 느꼈어요!
(기획상 onBlur 이벤트 핸들링 자체가 추가된 것이니까요)
바뀐기획에 의한 필연적인 변경이었다고 생각하시는 편이 편하실 것 같습니다.
작성하신 코드의 구조자체는 크게 문제가 있을만한 구조는 아니라고 생각되어요. 앱 자체도 그렇게 큰 규모가 아니기도 하구요!

2023-05-09 18:34 UTC, Tanney-102 commented on src/hooks/cardItemInputs/useExpirationDate.ts
> +  console.log(inputValue.length);
필요한 로깅인가요?

2023-05-09 18:34 UTC, Tanney-102 commented on src/components/CardRegistrationPage/Modal/Modal.tsx
이 모달은 사용처가 있나요?

2023-05-11 08:04 UTC, woo-jk commented on src/hooks/cardItemInputs/useExpirationDate.ts
> +  console.log(inputValue.length);
아니요 불필요한 로그를 미처 삭제하지 못했네요 ㅜ 삭제하겠습니다!

2023-05-11 15:57 UTC, Tanney-102 approved these changes
고생하셨습니다!

2023-05-11 15:57 UTC, merged