[1단계 - 페이먼츠] - 지니(손진영) 미션 제출합니다.
woowacourse/react-payments pull request #333
Opened 2024-04-18 06:09 UTC by jinyoung234

안녕하세요 유조 :) 다시 만나뵙게 되어 영광이고 잘 부탁드립니다!!

# 배포
## 스토리북
[스토리북 링크](https://6620c82d3a152f94d7e38f6a-kfxkmytbxi.chromatic.com/?path=/docs/base-input--docs)

## 앱
[앱 링크](https://jinyoung234.github.io/react-payments) 

# Getting Start
```terminal
# 실행 환경 구성
npm install

# 로컬 환경에서 실행
npm run dev

# 로컬 환경에서 스토리북 실행
npm run storybook
```
# 컴포넌트 설계
<img width="911" alt="image" src="https://github.com/woowacourse/react-payments/assets/87177577/15a6b752-1a19-4c4b-9164-c70a325428bf">

# 이런 것을 고려해보았습니다.
## 미션 구현
이번 미션의 학습 목표는 총 3가지 였습니다.
- 재사용 가능한 Input Component
- Storybook을 사용하여 컴포넌트의 다양한 상태를 시각적으로 테스트한다.
- 카드 정보를 효과적으로 렌더링 하기 위한 상태 관리를 경험한다.

이 학습 목표들을 어떻게 고려했는지 위주로 작성해보려고 합니다.

### 재사용 가능한 Input Component
제 페어인 월하와 함께 이번 미션에서 Input 컴포넌트가 `어떤 역할`을 하는지에 초점을 맞춰 구현을 진행했습니다.

Input 컴포넌트의 경우 아래와 같은 역할을 수행한다고 생각했습니다.
1. 기본 스타일 정의
2. 타입에 따른 동작 제어(type)
3. 최대 입력할 수 있는 글자 제어(maxLength)

따라서, 해당 역할을 부여할 수 있도록 코드를 구성해보았으며, 공통 컴포넌트로 만든 후 Input을 확장하는 CardNumberInput, ExpirationDateInput, OwnerNameInput를 만들어 도메인 의미를 부여하는 형태로 개발을 진행했습니다.

### Storybook을 사용하여 컴포넌트의 다양한 상태를 시각적으로 테스트한다.
모든 Domain 컴포넌트에 대해 스토리북을 추가해둔 상태이며, 각 컴포넌트에 따른 다양한 story를 부여하여 쉽게 확인할 수 있도록 신경써보았습니다.

또한, control과 decorator를 추가함으로써 직접 동작하면서 상태가 어떻게 변화하는지 쉽게 확인할 수 있돌고 신경써보았습니다.

마지막으로 generateArgTypes 라는 유틸 함수를 추가하여 control을 자동 완성할 수 있도록 신경써 보았습니다.

### 카드 정보를 효과적으로 렌더링 하기 위한 상태 관리를 경험한다.
리액트의 state의 경우 `유저가 trigger 하는 interaction을 관리한다.`라는 것에 초점을 두었습니다.

따라서, 5단계 원칙으로 state 설계를 진행했습니다.

1. 디자인 내 시각적 상태들을 정의
2. state update를 trigger 하는 요소들 정의
3. useState 위치 정하기
4. 불필요한 state 제거
5. 이벤트 핸들러 연결

카드 정보 state의 경우 `카드 번호`, `유효 기간`, `소유자 이름` 별로 state를 나누었습니다.
value와 error state는 별도의 action이라고 생각했기 때문에 각 카테고리 별로 value와 error state를 따로 관리하였습니다.

또한, state & error state & event handler를 custom hook으로 각각 분리함으로써 확장하기 쉬운 구조로 만들고자 했습니다.

### 스타일 라이브러리 선정
저희는 결과적으로 `css modules`을 사용하여 개발하였습니다.

이유는 다음과 같습니다.

**CSS Modules**

특징

- 지역 스코프를 가지고 있다.
    - CSS 클래스 이름이 중복되어도 새로운 이름이 입혀져 중복 및 관리의 위험성이 적다.
    - CSS 네이밍 규칙이 간소화 된다.
- 모듈화 된 CSS를 컴파일러 내부에서 특정 해시 값으로 변환하여 컴파일하는 형태다.
    - 런타임 오버헤드가 발생하지 않는다.

**CSS-IN-JS(styled-components & emotion)**

특징

- 사용자 정의 컴포넌트와 스타일링 컴포넌트를 분리할 수 있다.
- theme과 조건부 스타일링 설정이 용이하다.
    - 조건부 스타일링의 경우 조건을 스타일링 컴포넌트 내 props로 전달 받아 스타일을 다르게 설정할 수 있다.
    - theme provider 내 theme을 설정하여 다크 모드 등을 설정할 수 있다.
- 스타일 상속이 가능하다.
- css props를 통해 mixin의 형태로 스타일을 재사용 가능하다.
- 반응형 디자인도 원활하게 적용이 가능하다.

**css modules 사용 이유**

1. CSS-IN-JS의 높은 비용

- 자바스크립트 변수를 css로 변환하기 때문에, 이 과정에서 런타임 오버헤드가 발생한다.
- 라이브러리 설치가 필요하므로, 의존성이 발생하며 번들 사이즈가 커진다.

2. 스타일링 컴포넌트의 복잡성

- 스타일을 정의하기 위해 만든 스타일링 컴포넌트들은 JSX를 복잡하게 만들 수 있다.

3. 굳이 필요하지 않은 기능

- theme과 css 상속, css prop 기능들이 현재 작은 애플리케이션 내에서 불필요한 기능인 것 같다.

4. css-in-js의 탄생 배경

- 스타일 관리의 어려움, 전역 범위 등의 문제점을 해결하기 위해 css-in-js가 탄생했지만, 현재 css modules 내에서 모두 제공하는 기능이다.

# 참고해주시면 좋습니다!
## 폴더 구조
- assets - 이미지 파일을 모아놓는 디렉터리
- components - 컴포넌트 파일을 모아놓는 디렉터리
- hooks - 커스텀 훅 파일을 모아놓는 디렉터리
- styles - reset.css와 공통 css 파일을 모아놓는 디렉터리
- utils - 유틸 함수 파일을 모아놓는 디렉터리

component 내 layout(스타일링 컴포넌트), common(공통 컴포넌트), payments(도메인 컴포넌트)로 분리하였으며, 각 컴포넌트 마다 style, type, story 파일을 모두 모아 관리해보았습니다.

2024-04-19 00:39 UTC, yujo11 requested changes
안녕하세요 지니~

다시 만나뵙게 되어 반갑습니다 ㅎㅎ 이번 페이먼츠 미션도 잘 부탁드려요~

전체적으로 코드가 깔끔하게 작성되어 있다는 인상을 받았습니다. Storybook 코드도 굉장히 꼼꼼하게 작성해주셔서 놀랐습니다 👍 👍 👍 

스타일 라이브러리들의 장단점을 꼼꼼하게 비교하고 라이브러리를 선정한 부분도 인상 깊었네요 👍 👍 💯 

전체적으로 코드를 보는게 어렵지 않았지만 폴더 구조 관련해서 개선해보면 좋을만한 점이 있었는데요. `components/payments` 폴더를 보면 현재 모든 컴포넌트가 같은 레벨로 flat하게 존재하는데 컴포넌트의 역할에 따른 depth를 줘서 어떤 컴포넌트가 어떤 컴포넌트 하위에서 사용되는지 명확하게 보이도록 해주시면 컴포넌트의 상-하 관계를 폴더 구조만으로 유추할 수 있어 좋을거 같습니다 ㅎㅎ


ex)
```
components/payments/
- CreditCardForm
- - PreviewCreditCard
- - CardNumberTextField
- - ...
```


storybook이나 module.css 파일을 사용하는 곳 가까이에서 정의해서 사용하는 점은 정말 좋았습니다 👍 👍 👍 

---

미션 진행하느라 고생 많으셨습니다 지니~~ 👍 👍 👍

2024-04-19 00:39 UTC, yujo11 commented on src/components/layout/PreviewCreditCardStyleContainer/PreviewCreditCardStyleContainer.tsx
보통 Layout 이라는 이름을 가진 폴더 하위에는 애플리케이션의 Header, GNB, LNB 같은 앱 전체의 Layout을 결정 짓는 요소들을 많이 둬서 `PreviewCreditCardStyleContainer`, `TextFieldStyleContainer`가 이 위치에 있는게 조금 어색하게 느껴지네요

2024-04-19 00:39 UTC, yujo11 commented on src/components/layout/PreviewCreditCardStyleContainer/PreviewCreditCardStyleContainer.tsx
`PreviewCreditCardStyleContainer`와 `TextFieldStyleContainer` 모두 단 한 번만 사용되는 컴포넌트이고 특별한 기능을 수행하기 보다는 단순히 Style이 적용 된 컴포넌트들로 보이는데 별도로 컴포넌트로 정의해서 사용하시는 이유가 있을까요? 어떤걸 기준으로 컴포넌트를 정의하고(나누고) 사용하시는지 궁금합니다

2024-04-19 00:49 UTC, jinyoung234 commented on src/App.tsx
> +      }}
기능 확인을 위해 빠르게 작성했던 코드였는데 더 꼼꼼히 봤어야 했던거 같습니다 🥲🥹

2024-04-19 00:52 UTC, jinyoung234 commented on src/hooks/creditCard/useCreditCardLogo.ts
> +  const isMasterCardNumber = /^5[1-5]/.test(firstCardNumbers);
변수명으로 의도를 드러내려고 했는데, 유조 말씀 처럼 도메인 규칙의 경우 주석으로 더 명확히 드러내도 좋을거 같습니다!!

좋은 의견 감사합니다 :)

2024-04-19 00:58 UTC, jinyoung234 commented on src/hooks/creditCard/useCreditCardLogo.ts
> +  const isMasterCardNumber = /^5[1-5]/.test(firstCardNumbers);
조금 더 의도를 드러낼 수 있는 방향을 찾아보고 적용해보겠습니다 🥹

2024-04-19 06:05 UTC, jinyoung234 commented on src/utils/expiration.ts
> +  expirationDate.setDate(expirationDate.getDate() - 1);
이 객체의 월을 하나 증가시킨 후, 그 달의 첫 번째 날에서 하루를 빼서 그 월의 말일을 얻어 그 값과 현재 날짜를 비교하기 위함이었습니다!

2024-04-19 06:16 UTC, jinyoung234 commented on src/hooks/creditCard/useChangeOwnerName.ts
> +    const error = /^[A-Za-z]{0,}$/.test(value)
전반적인 유효성 검사들이 정규 표현식 이외 다른 코드 작성 방법을 생각하지 못해 모두 정규표현식으로 작성하게 되었습니다. 🥲

2024-04-19 06:32 UTC, jinyoung234 commented on src/hooks/creditCard/useChangeOwnerName.ts
> +    const error = /^[A-Za-z]{0,}$/.test(value)
유효성 검사 항목들이 다음과 같이 있었습니다.

  1. 월이 01 ~ 12 이외 다른 값이 입력 될 경우 `월은 01에서 12 사이의 숫자여야 합니다.` 라는 메시지를 화면에 보여줄 수 있어야 한다.
  2. 년도가 현재 년도 이전의 값이 입력 될 경우 `카드 유효기간이 지났습니다.` 라는 메시지를 화면에 보여줄 수 있어야 한다.
  3. 영문자 이외 다른 값이 입력되었을 경우 `카드 소유자 이름은 대문자로 입력해야 합니다.` 라는 메시지를 화면에 보여줄 수 있어야 한다.
  4. Visa 카드는 앞자리 번호가 `4`로 시작하며, 마스터카드는 앞자리 번호가 `50` ~ `55`로 시작해야 한다.
  5. 카드 소유자 이름은 `성(영어 대문자) 이름(영어 대문자)`의 형태로 보여질 수 있어야 한다.

전반적인 유효성 검사들이 정규 표현식 이외 다른 코드 작성 방법을 생각하지 못해 모두 정규표현식으로 작성하게 되었습니다. 🥲

물론 정규표현식이 모든 문자 내에서 특정 패턴을 충족하는지 확인한다는 점, 가독성이 그렇게 좋지는 않다는 점이 걸렸기 때문에 더 좋은 방법을 고민해보겠습니다!

2024-04-19 06:34 UTC, jinyoung234 commented on src/hooks/creditCard/useChangeOwnerName.ts
> +    const error = /^[A-Za-z]{0,}$/.test(value)
유조 의견 처럼 현재의 변수명이 더 의도를 전달하는 방향인거 같아 적용해보겠습니다!

2024-04-19 06:35 UTC, jinyoung234 commented on src/hooks/creditCard/useChangeOwnerName.ts
> +  return { ownerName: ownerName.toUpperCase(), ownerNameError, handleOwnerNameChange };
이거 까지 QA 해볼 생각을 못했네요 .. 🥹 꼭 적용해보겠습니다!

2024-04-19 06:36 UTC, jinyoung234 commented on src/hooks/creditCard/useCreditCardLogo.ts
해당 컴포넌트의 util 함수로 분리해도 좋을거 같아 한번 적용해보겠습니다!

2024-04-19 06:39 UTC, jinyoung234 commented on src/components/common/Input/Input.tsx
> +}
유조 의견대로 해당 타입을 추가함으로써, props의 자동 완성을 제공할 수도 있겠네여 한번 적용해보겠습니다 😀

2024-04-19 06:40 UTC, jinyoung234 commented on src/main.tsx
font가 os마다 달라지는걸 고려하진 못했던거 같아 한번 적용해보겠습니다!! 🥹

2024-04-19 06:41 UTC, jinyoung234 commented on src/components/common/Input/Input.type.ts
> +export type InputType = 'text' | 'number';
props 타입은 컴포넌트 내부에 위치시키고, 나머지 타입은 해당 파일의 `type.ts`에서 관리해보고자 했습니다.

props 타입을 컴포넌트 내부에 위치시켰던 이유는 props가 **컴포넌트의 모양을 나타낸다고 생각**했기 때문입니다.

따라서, 컴포넌트 파일에서 props를 위치시킴으로써 **이 컴포넌트가 어떤 역할을 하는지 더 빠르게 확인할 수 있도록 제공**하고자 했습니다.

2024-04-19 06:44 UTC, jinyoung234 commented on src/components/common/TextField/TextField.tsx
> +);
Title을 h1으로 SubTitle을 span 태그로 했어야 했는데, 착오가 있었던거 같습니다 .. 🥲 리뷰 반영해놓겠습니다!

2024-04-19 06:45 UTC, jinyoung234 commented on src/components/common/index.ts
감사합니다 !! 참고해보겠습니다 😀

2024-04-19 07:03 UTC, jinyoung234 commented on src/components/layout/PreviewCreditCardStyleContainer/PreviewCreditCardStyleContainer.tsx
CreditCardForm의 경우 애플리케이션의 state를 담당하는 컴포넌트로 지정해두었기 때문에 해당 컴포넌트에선 오직 `상태에 대한 책임`(Container)만 두고 싶었습니다.

반면, JSX에서 반환되는 PreviewCreditCard나 Textfield 컴포넌트들은 state 및 handler를 props로 받아 `화면에 보여지는 책임`(Presenter)만 두고 싶었습니다.

다만 CreditCardForm 내 PreviewCreditCard나 Textfield의 container style을 정의해야했기에 styled-component 처럼 오직 `스타일에 대한 책임`만 부여할 수 있는 컴포넌트를 만들어 관심사를 분리하고 싶었습니다.

그러다보니 생김새가 layout과 유사하게 생겼다고 판단해 layout 디렉터리에서 관리하고자 했던거 같습니다. 🥲

`PreviewCreditCardStyleContainer`, `TextFieldStyleContainer` 컴포넌트와 같은 `style wrapper`들은 어디서 관리하는게 좋을지 아직 감이 잘 오지 않는데 어떤 방식으로 접근해야할지 인사이트를 주시면 열심히 적용해보겠습니다..!!

2024-04-20 12:25 UTC, jinyoung234 commented
@yujo11 안녕하세요 유조 :) 제안 주신 내용을 충분히 고민 후 리뷰 반영해보았습니다.

# 리뷰 반영
## App.ts
- inline css로 작성 된 부분을 style class 형태로 수정하였습니다.

## useCreditCardLogo.ts
- 도메인 규칙에 대한 주석을 명시해두었습니다.
- 정규 표현식 대신 다른 형태로 고쳐 볼 수 있을거 같아 변경해보았습니다.
- [react-custom-hook을 어떻게 써야할까?]([https://medium.com/@asdfg9377/react-custom-hook%EC%97%90-%EB%8C%80%ED%95%B4-%EC%9D[…]5%98%EA%B3%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-75f0e8f55df6](https://medium.com/@asdfg9377/react-custom-hook%EC%97%90-%EB%8C%80%ED%95%B4-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B3%A0-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-75f0e8f55df6)) 내 react custom hook 부분을 읽어본 후 util 함수와 custom hook의 차이점을 이해하여 해당 로직을 util 함수 형태로 변경해보았습니다.
- 파일 위치를 적절한 위치로 변경해보았습니다.

## expiration.ts
- month를 더하고 빼는 부분이 이해하는데 어색하다고 느껴져 자연스러운 형태로 변경해보았습니다.

## generateArgTypes.ts
- 중복된 객체와 서로 다른 case의 동일한 값인 부분에 대해 리팩터링 해보았습니다.

## useChangeOwnerName.ts
- error라는 포괄적인 네이밍 대신 `isValidName`과 같은 네이밍으로 변경했으며, 정규표현식을 제거하는 방향으로 리팩터링 해보았습니다.

## Input.tsx
- 컴포넌트 props 타입에 `InputHTMLAttributes`를 추가하여 자동 완성을 제공하고자 했습니다.

## TextField.tsx
- 어색한 태그 네임을 sementic tag의 형태로 변경해보았습니다.

## PreviewCreditCardStyleContainer.tsx
- layout이라는 네이밍이 Layout 컴포넌트들과 겹칠 수 있다고 판단되어, 사용 되는 컴포넌트의 container 디렉터리에 위치시키도록 변경했습니다.

## UX

<img width="272" alt="image" src="https://github.com/woowacourse/react-payments/assets/87177577/5e230e02-ae5e-4b05-896d-d04ab6c12a16">

- 소유자 이름의 길이가 너무 길어져 카드를 초과하는 경우 위와 같이 ...의 형태로 되도록 변경해보았습니다.
- mac과 window 환경에서 폰트가 달리 보이는 이슈가 있다고 판단되어 웹 폰트(프리텐다드)를 추가해보았습니다.
   - 웹 폰트를 쓸 때 cdn을 사용하지 않고, woff의 subset 형태로 사용하여 최대한 번들 사이즈를 키우지 않으려고 신경써보았습니다!
- 추가적으로 카드 번호에 대한 ux를 조금 개선해보았으며, 개선된 ux는 아래 gif를 참고해주시면 감사드리겠습니다!

https://github.com/woowacourse/react-payments/assets/87177577/9856d945-2d42-4243-811d-9f3b5a6edace
 
# 궁금한 점

## payments 디렉터리 depth에 대한 생각

유조가 제안 주신 payments 디렉터리에 있는 컴포넌트들의 flat한 depth에 대해 충분히 고민해보았습니다.

제 생각에는 `CreditCardForm`에 사용되는 컴포넌트들을 넣어두는게 파일 추적에는 용이할 것 같지만, 만약 `CreditCardForm`이 아닌 다른 Form을 만들 때 특정 `TextField` 컴포넌트(ex - `CardNumberTextField`)가 필요하다면 오히려 의문점이 생길 것 같다는 생각이 들었습니다. (ex - 얘는 여러 곳에서 쓰니까 다시 빼야하는거 아닌가?)

즉, 가독성 측면에선 좋은 방향 같지만 확장된`TextField` **컴포넌트를 재사용 해야 할 경우도 존재할거라고 생각해 일단은 그대로 두는 형태로 진행**을 해보았습니다.

이에 대한 유조의 의견도 들어보고 싶습니다 :)

## State 설계

이번 미션에서 State를 설계할 때 `관심사의 분리`에 초점을 맞추어 카드 번호, 유효 기간, 소유자 이름을 각각 state로 관리하였습니다.

이렇게 설계 했던 이유는 확장성을 고려하려 했기 때문입니다.

```js
const [cardDetail, setCardDetail] = useState({
  cardNumbers: ['', '', '', ''],
  cardExpiration: ['', ''],
  userName: "",
});
```
다른 항목들이 추가되었을 때 모두 cardDetail에 추가된다면 state가 너무 비대해져 복잡해질 것이라고 생각해 어느 정도의 flat함이 필요하다고 생각했습니다.

만약 소유자 이름이 성, 이름으로 구분되거나 유효 기간이 년, 월이 아닌 년, 월, 일의 형태로 변경된다면 cardDetail 전체에 영향을 받게 되므로 다른 state에 영향을 줄 수도 있어 결합도가 높은 것 같다고 생각했습니다.

또한 [연관된 state 묶기](https://ko.react.dev/learn/choosing-the-state-structure#group-related-state)에서 두 개의 state 변수가 항상 함께 변경된다면, 단일 state 변수로 통합하는 것이 좋다고 언급해서 그런지 현재의 form은 함께 변경된다는 느낌을 받지 못한 것도 있었습니다.

결론적으로 현재의 카드 정보들을 하나의 state로 관리하는 것이 옳은 방향인지 궁금하며, 유조는 어떤 기준으로 state를 설계하시는지의 방향성도 여쭤보고 싶습니다.

# etc
- 이번에 ci/cd를 통해 chromatic(storybook)과 앱을 자동 배포 하는 형태로 바꾸는 과정에서 build 부분 커밋이 늘었는데, 이 점 양해 부탁드립니다 ㅜㅜ 죄송합니다!! 🥲

2024-04-21 06:08 UTC, yujo11 commented on src/components/payments/CardNumberTextField/CardNumberTextField.stories.tsx
> +    cardNumberError: { errorConditions: [false, false, false, false], errorMessage: '' },
👍

2024-04-21 06:08 UTC, yujo11 commented on src/components/layout/PreviewCreditCardStyleContainer/PreviewCreditCardStyleContainer.tsx
저는 보통 style warpper들도 component의 역할을 수행하기 때문에 components/ 폴더 하위에 두고 보통 같이 관리하는거 같아요 ㅎㅎ

이게 정답이니 따라야 한다는 얘기는 아니고 앞으로도 많은 코드들을 작성하고, 많이 보게 될텐데 적절한 방법을 찾아가보시면 좋을거 같아요 ㅎㅎ

2024-04-21 06:17 UTC, yujo11 approved these changes
안녕하세요 지니~

리뷰 꼼꼼히 반영해주셨군요 ㅎㅎ  커밋 단위로 따라가며 변경 내역을 확인했는데 커밋도 꼼꼼하게 잘 작성되어 있어 보기 좋았습니다 👍 

폰트를 적용하거나 카드 소유자의 이름이 길 때, 카드 번호를 입력할 때 등 UX에서 개선한 부분들도 아주 좋았습니다 ㅎㅎ 👍 👍 👍 💯 

>State 설계

>결론적으로 현재의 카드 정보들을 하나의 state로 관리하는 것이 옳은 방향인지 궁금하며, 유조는 어떤 기준으로 state를 설계하시는지의 방향성도 여쭤보고 싶습니다.

저는 좋은 방법이라고 생각합니다 ㅎㅎ

state를 어떻게 설계하고 관리할지는 상황마다 달라질거 같은데요. 저는 보통은 연관되어 있는 상태끼리 함께 관리하는 경우가 많은거 같아요. 

예를 들어 아직은 submit 기능이 없지만 지니처럼 `cardDetail`로 묶어서 관리하고 있는 state들은 submit 될 때 한번에 제출되어야 하니 묶어서 관리하고, 그 외의 state들은 별도로 관리하는 방식으로요. 

하나의 방법이 정답이라고 생각하는 대신에 코드를 많이 작성하고, 다른 사람들의 코드를 많이 보면서 상태를 독립적으로 관리했을 때와 묶어서 관리했을 때의 장단점을 고려해보시면서 작성하는 코드와 애플리케이션의 특성에 맞게 적절한 선택을 내리시면 좋을거 같습니다 ㅎㅎ

---

이번 step은 여기서 이만 merge하고 다음 step으로 넘어가면 좋을거 같네요!

고생 많으셨습니다 지니~~ step2에서 다시 만나요~~~ 👍 👍 👍

2024-04-21 06:18 UTC, merged

2024-04-21 06:22 UTC, jinyoung234 commented on dist/index.html
> +<html lang="en">
아 정말 그러네요 ... ㅋㅋㅋㅋㅋㅋ 이건 생각도 못했던거 같습니다 ! step2때 반영해보겠습니다 감사합니다!

2024-04-21 06:24 UTC, jinyoung234 commented on src/styles/font.css
아 font.css를 link 태그로 import 하는 형태를 말하시는걸까요?! 

한번 참고해서 체크해보겠습니다!

2024-04-23 13:01 UTC, yujo11 commented on src/styles/font.css
당장 변경하라고 드린 리뷰는 아니고 각 방법에 어떠한 차이가 있는지를 알아보시고 적절한 방법을 선택하시면 좋겠어서 남긴 리뷰였습니다 ㅎㅎ