[1단계 - 페이먼츠 Component & Storybook] - 쿠키(김진호) 미션 제출합니다.
woowacourse/react-payments pull request #337
Opened 2024-04-18 07:30 UTC by jinhokim98

안녕하세요 하루! 6기 FE 리뷰이 쿠키입니다.
아래 링크에 접속하면 페이먼츠 서비스와 스토리북을 확인하실 수 있습니다.

+ [서비스 링크](https://jinhokim98.github.io/react-payments/)
+ [스토리북](https://jinhokim98.github.io/react-payments/storybook)

## 🗃️컴포넌트 구조
![image](https://github.com/woowacourse/react-payments/assets/81083461/82f64c34-8b3d-47de-a875-021506d0a312)

App에서 Preview와 Form으로 나누었습니다.
Form에서는 FormField를 3개를 가지며, FormField 안에 각각 inputField 그 안에 Input들이 있습니다.
입력의 state들은 useForm custom hook을 통해서 관리됩니다.
useForm은 카드 번호, 유효 날짜, 소유자 이름을 관리하며, 이 안에서 각 필드의 입력 상태를 관리합니다.
각 입력은 useInput을 통해서 관리되며 useInput에서 useState를 사용해서 value와 error를 관리합니다.
각 입력의 상태를 모은 것이 useForm이며, App에서 useForm을 불러서 Preview와 Form으로 상태를 전달해주는 구조입니다.

## 🤔고민점과 질문
1. `재사용 가능한 Input Component를 개발한다.` 학습 목표에 대한 고민
학습 목표로 재사용 가능한 Input Component를 개발한다는 학습 목표가 있었지만 이번 미션을 하면서 Input 컴포넌트를 만들었을 때, 외부에서 기존 input의 기능에서 단 하나만(invalid) 기능을 추가해줬습니다.
이것이 학습 목표에 맞는 구현방식인지 의문이 듭니다.
이 내용은 아래 Comment에도 추가하겠습니다.

2. Form 상태에 대한 고민
처음에 설계했을 때 Form에 관한 상태는 Form에서 관리하려고 생각했습니다. 하지만 props는 상위에서 하위로 정보를 넘겨주므로 Form에서 상태를 가지면 형제인 Preview에 상태를 넘겨주기 어렵다고 생각해서 App에서 두 컴포넌트로 상태를 넘겨주는 방식으로 구현했습니다. step2에서 기능이 확장이 될텐데 지금 App에서 정보를 넘겨주는 방식을 유지하면 나중에 App이 너무 비대 해질 것 같아서 고민입니다.

2024-04-18 09:37 UTC, 365kim commented on package-lock.json
(단순 궁금) lock 파일은 왜 변경사항이 생긴 걸까요?

2024-04-18 09:37 UTC, 365kim commented on README.md
> +- [x] 입력은 숫자만 가능하며, 유효하지 않은 번호 입력 시 피드백을 제공한다.
> 입력은 숫자만 가능하며

지금은 숫자가 아닌 character도 입력할 수 있는데, 개선해볼 수 있을까요?

<img width="351" alt="image" src="https://github.com/woowacourse/react-payments/assets/60066472/dfcc9f98-e68c-40f3-934e-d54a91a08c18">

2024-04-18 09:43 UTC, 365kim commented on package.json
> +    "eslint-plugin-react": "^7.34.1",
이 패키지들 모두 쓰이고 있나요? `eslintrc.json`에 안보이는 것도 있어서 질문드려보아용

2024-04-18 09:43 UTC, 365kim commented on .eslintrc.json
> +        "plugin:react-hooks/recommended",
👍

2024-04-18 09:49 UTC, 365kim commented on package.json
> +    "styled-components": "^6.1.8",
> 스타일링에는 CSS Module, styled-components, emotion 중 한 가지를 선택하여 사용한다.

`styled-components` 를 픽해주신 이유가 궁금합니다 :)

2024-04-18 09:52 UTC, 365kim commented on src/components/InputField/InputField.tsx
> +const InputField = ({ label, error, children }: InputFieldProps) => {
`label` 요소와 `input` 요소의 연결이 끊겨있어 보여요. 웹 표준을 준수하여 연결해볼 수 있을까요?

- 참고: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

2024-04-18 09:53 UTC, 365kim commented on src/components/InputField/InputField.tsx
> +      <Field.Error>{error}</Field.Error>
`error`가 optional이라, error가 없을 경우 불필요한 `span` 태그가 렌더링될 것 같아요. error가 있을 때만 `Field.Error`를 렌더링하도록 조건부 렌더링 처리를 하면 어떨까요?

2024-04-18 09:55 UTC, 365kim commented on src/components/InputField/style.tsx
> +export const Error = styled.span`
간결한 지금도 좋지만, `ErrorCaption` 처럼 조금 더 구체적인 네이밍을 지어줘도 좋을 것 같아요.

2024-04-18 09:56 UTC, 365kim commented on src/components/CardInformationPreview/style.tsx
> +export const UserInfomation = styled.div<{ $typo: string }>`
Information 오타가 있어용 👀

2024-04-18 09:58 UTC, 365kim commented on src/constants/Message.ts
> +  userName: 'LAST_NAME FIRST_NAME',
시안의 placeholder를 그대로 사용하면 어떨까요? 언더스코어 없는 버전의 `JOHN DOE`가 훨씬 일반적인 것 같아서요 :)

2024-04-18 09:58 UTC, 365kim commented on src/constants/Message.ts
> +  month: '01~12 사이의 숫자를 입력해주세요.',
`01` 이라고 명확하게 표현해주신 것 좋네요 👍

2024-04-18 10:00 UTC, 365kim commented on src/stories/FormField/UserName.stories.tsx
> +export const UserNameLowerCaseTypeError: Story = {
(UX 피드백이라, 꼭 반영안해주셔도 됩니다.)

소문자로 입력하더라도 에러로 보지 않고 대문자로 치환해주면 어떨까요? 그렇게 해주는 서비스를 이용해본 적이 있는데 편하더라고요 :)

2024-04-18 10:03 UTC, 365kim commented on src/hooks/useForm.ts
> +  userName?: string;
이 프로퍼티는 왜 optional 일까용?

2024-04-18 10:04 UTC, 365kim commented on src/hooks/useForm.ts
> +  expirationDate: Array<number | undefined>;
`Array<number>` 이렇게 타이핑하면 문제가 있을까요?

`[number, number, undefined]` 이런 순간이 있나요?

2024-04-18 10:05 UTC, 365kim commented on src/hooks/useForm.ts
> +    },
`cardNumberState: { ...firstState }`, 또는 `cardNumberState:firstState` 로 바꾸어 쓸 수 있을까용~?

2024-04-18 10:07 UTC, 365kim commented on src/hooks/useCardNumber.ts
> +const useCardNumber = (defaultValues: Array<number | undefined>) => {
사소한데 array를 다루고 있어 복수형으로 `useCardNumbers` 로 표현해도 좋겠습니다 :)

2024-04-18 10:08 UTC, 365kim commented on src/hooks/useInput.ts
> +  return [value, onChange, error] as const;
반환 타입을 `{ value, onChange, error }`가 아닌 array 잡아주신 이유가 궁금해요 :)

2024-04-18 10:12 UTC, 365kim commented on src/hooks/useInput.ts
> +const useInput = <T>(defaultValue: T, condition: RegExp) => {
커스텀 훅에서 defaultValue 받는 인터페이스도 좋고, UI랑 상태 관리 로직이 재사용 가능하도록 잘 분리된 것도 좋네요 👍

2024-04-18 10:12 UTC, 365kim commented on src/hooks/useInput.ts
> +  const [error, setError] = useState<boolean>(false);
boolean 값이 isError 같은 네이밍은 어떨까요? (error 네이밍은 타입확인 전에는 객체로 읽을 수도 있을 거 같아요)

2024-04-18 10:16 UTC, 365kim commented on src/stories/FormField/ExpirationDate.stories.tsx
> +export const ExpirationDateDefault: Story = {
단순 제안) 혹시 스토리명을 한글로 해보시는 것은 어떨까요? 제 개인적인 경험으로는 가독성 개선에 도움이 되더라고요 :) e.g. `유효기간_입력전`, `유효기간_유효한입력`, ...

2024-04-18 10:17 UTC, 365kim commented on src/stories/FormField/ExpirationDate.stories.tsx
> +            value="2d"
역시 UX 제안인데 문자 입력은 아예 입력이 되지 않도록 막아주어도 좋겠습니다. (꼭 반영 x)

<img width="492" alt="image" src="https://github.com/woowacourse/react-payments/assets/60066472/81b741e1-314d-42b1-be0f-6686626c04d2">

2024-04-18 10:18 UTC, 365kim commented on src/components/CardInformationPreview/CardInformationPreview.tsx
> +        <Preview.CardImg src={magnetic} alt="magnetic" />
이 이미지의 alt 값은 빈문자열로 지정하면 어떨까요? `alt=""`

- 참고: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/alt#value

2024-04-18 10:23 UTC, 365kim commented on src/components/Input/Input.tsx
> +};
> 재사용 가능한 Input Component를 개발한다. 학습 목표에 대한 고민
학습 목표로 재사용 가능한 Input Component를 개발한다는 학습 목표가 있었지만 이번 미션을 하면서 Input 컴포넌트를 만들었을 때, 외부에서 기존 input의 기능에서 단 하나만(invalid) 기능을 추가해줬습니다. 이것이 학습 목표에 맞는 구현방식인지 의문이 듭니다.
이 내용은 아래 Comment에도 추가하겠습니다.

음 저는 잘 만들어주셨다고 보이는데요, 쿠키의 Input UI 컴포넌트는 스타일을 단 한번만 정의하고도 쿠키의 프로젝트 전체에 동일한 스타일로 보여지도록 설계되어있지요. 그래서 충분히 '컴포넌트 재사용'의 효용을 크게 잘 활용하고 계시다고 생각합니다 :)

2024-04-18 10:26 UTC, 365kim commented on src/App.tsx
> +  };
> Form 상태에 대한 고민
처음에 설계했을 때 Form에 관한 상태는 Form에서 관리하려고 생각했습니다. 하지만 props는 상위에서 하위로 정보를 넘겨주므로 Form에서 상태를 가지면 형제인 Preview에 상태를 넘겨주기 어렵다고 생각해서 App에서 두 컴포넌트로 상태를 넘겨주는 방식으로 구현했습니다. step2에서 기능이 확장이 될텐데 지금 App에서 정보를 넘겨주는 방식을 유지하면 나중에 App이 너무 비대 해질 것 같아서 고민입니다.

상태 끌어올리기 과정을 경험하셨군요

- 참고: https://react.dev/learn/sharing-state-between-components#lifting-state-up-by-example

지금은 단일 페이지 라서 그렇고 실제 프로덕트에서는 CardAddPage 라는 중간 컴포넌트가 있고 그게 form의 상태를 관리할 것 같다. 지금으로서는 최적의 구조로 잘 만들어주신 것 같다는 생각이 듭니다.

다만, App에서 필요한 것은 previewProps와 formProps 이니, 가능하다면 useForm 내부에서 이것을 만들어서 반환해주면 어떨까 싶어요

```tsx
const { previewProps, formProps } = useForm({
    cardNumber: [],
    expirationDate: [],
    userName: '',
  });
```

2024-04-18 10:28 UTC, 365kim commented on src/hooks/useInput.ts
> state 개수
제가 구현한 방식은 각 input 당 한 개의 state를 가지는 형식으로 구현했습니다.
그 이유는 구현의 편리함도 있었고, state가 변할 때 리렌더링이 발생하는데, state를 각 input에 주었으므로 각 Input 컴포넌트의 하위만 리렌더링되기 때문에 비용을 아낄 수 있다고 생각했습니다.
하지만 한 개의 state를 가지고 객체로 하위 input들을 관리하는 방식으로 구현했다는 크루들의 이야기를 들었습니다. 과연 어떤 방식이 더 좋은 방식이었을까 고민이 됩니다.

음 쿠키의 생각을 더 들어보고 싶습니다. 쿠키가 생각하시기에, Form 요소 내부의 Input들을 단 하나의 state로 관리하면 어떤 장점이 있을 것 같나요? 반대로 지금처럼 여러 state로 관리하면 어떤 단점이 생길 수 있을까요?

2024-04-18 10:30 UTC, 365kim commented on src/main.tsx
> +import theme from './styles/theme.ts';
사소한데 중간 커밋이더라도 실행 가능한 상태로 커밋해주시는 게 좋습니다 :) 

52cd651a09c5b9ed2f65ba61d7e625fcfca428e7 이 커밋에서 theme.ts 모듈이 누락되어 있고, 중간중간 커밋 중에 작업 내용이 섞인 것들이 보여서 살짜쿵 말씀드려보아용

2024-04-18 10:33 UTC, 365kim requested changes
안녕하세요, 쿠키!
작업해주신 코드 잘봤습니다. 👏

리액트 첫 미션 기능 요구사항과 프로그래밍 요구사항을 충족하도록 잘 작성해주신 것 같아요. 💯
컴포넌트 구조를 아주 이해하기 쉽게 도식과 함께 설명해주셔서 코드 리뷰하는데 도움이 많이 되었어요 감사합니다 좋은 질문 적극적으로 해주셔서 또 좋았어요 :)

코멘트 몇 가지 남겼는데, 천천히 보시고 확인 완료되시면 리뷰 재요청 부탁드릴게요~!
고생하셨습니다 👍

2024-04-20 12:53 UTC, jinhokim98 commented on src/components/CardInformationPreview/style.tsx
> +export const UserInfomation = styled.div<{ $typo: string }>`
[7fbd192](https://github.com/woowacourse/react-payments/pull/337/commits/7fbd192c77a724e2c9f1febc0113cbf9e8849c21)

2024-04-20 12:55 UTC, jinhokim98 commented on src/components/InputField/InputField.tsx
> +      <Field.Error>{error}</Field.Error>
변경해봤습니다!
[7dea53d](https://github.com/woowacourse/react-payments/pull/337/commits/7dea53df79b223ac0fb34431568b129349111046)

2024-04-20 12:56 UTC, jinhokim98 commented on src/hooks/useCardNumber.ts
> +const useCardNumber = (defaultValues: Array<number | undefined>) => {
변경해봤습니다!
[0034d4f](https://github.com/woowacourse/react-payments/pull/337/commits/0034d4fd5ca572823bf2204a6f044844015252f2)

2024-04-21 04:26 UTC, 365kim commented on src/hooks/useInput.ts
좋은 답변 감사합니다.

쿠키가 말씀해주신 것처럼 Form 요구사항에 따라서 이 방식이 더 유리할 수도, 저 방식이 더 유리할 수도 있어보여요. 

예를 들어 쿠키가 말씀해주신 것처럼 각 Input 필드의 상태가 **상호 의존적**이라면, 하나의 상태로 묶어서 관리하는게 처리하기 편할 것입니다.

혹은, Input 필드가 **상호 독립적**이고 또 필드 개수도 많다면, 굳이 하나로 묶지 않고 개별 state로 관리해서, 코드흐름을 더 직관적으로 전개하고 상태 갱신 코드도 심플하게 작성할 수 있겠지요.

저는 지금 코드에서 어느 한쪽이 더 유리하다 판단이 어려운데, 특별히 의존적이다, 독립적이다 를 판단하는게 큰 의미가 없을만큼 폼의 복잡도가 높지 않아서 인게 아닐까 싶습니다.

그래서 저는 지금의 요구사항으로는 두 방식 다 좋다고 생각하지만, 제가 지금 useCardNumbers 내부 로직을 작성한다고 가정해보면, 카드넘버의 `{ first, second, third, fourth }` 는 하나의 상태로 관리할 것 같아요.

(first 라는 상태 하나만을 필요로 하기 보다) 결국 "카드번호"라는 하나의 관심사를 다루기 위한 상태이고, "카드번호"라는 단위로 묶어서 관리한다고 해도 해당 상태관리 복잡도가 크게 늘어나지 않으며 오히려 가독성을 올릴 수 있지 않을까 싶습니다. (이게 정답이라는 것이 아닙니다)

2024-04-21 04:27 UTC, 365kim commented on src/App.tsx
> +  };
App 이 훨씬 간결해졌네요 👍 반영 감사합니다

2024-04-21 04:29 UTC, 365kim commented on src/components/CardInformationPreview/CardInformationPreview.tsx
> +        <Preview.CardImg src={magnetic} alt="magnetic" />
> 큰 의미가 없는 이미지는 alt 속성을 빈 문자열로 설정해야 한다는 의미인거죠?

맞습니다👍 보조기기 사용자에게 불필요한 정보 제공하지 않도록 하기 위함입니다 :)

2024-04-21 04:30 UTC, 365kim commented on src/stories/FormField/ExpirationDate.stories.tsx
> +            value="2d"
반영 감사합니다 ☺️

2024-04-21 04:36 UTC, 365kim commented on src/stories/FormField/ExpirationDate.stories.tsx
> +export const ExpirationDateDefault: Story = {
오 한눈에 파악하기 너무 좋네요 😎 반영 감사합니다.

<img width="292" alt="image" src="https://github.com/woowacourse/react-payments/assets/60066472/e13e0bc7-c56a-41cc-84dd-4230c9d76335">

2024-04-21 04:37 UTC, 365kim commented on src/hooks/useInput.ts
> +  return [value, onChange, isError] as const;
useInput 함수의 반환값을 직접 타이핑하는 방법이 아니라 `as const`를 활용해주신 이유가 궁금합니다 :)

2024-04-21 04:38 UTC, 365kim commented on src/hooks/useInput.ts
> +  const [error, setError] = useState<boolean>(false);
반영 감사합니다! 한번에 제일 잘 맞는 변수명을 지을 수 있다면 가장 좋겠지만, 지금처럼 지속적으로 코드에 관심을 가지면서 제일 잘 어울리는 이름으로 붙여주시면 좋을 것 같아요 :)

2024-04-21 04:41 UTC, 365kim commented on src/hooks/useInput.ts
> +  return [value, onChange, error] as const;
아하 처음에 생각했던 useState처럼 상태만 관리하는 책임보다 더 큰 책임을 다루게 된 거군용 그렇다면 순서에 의존적인 배열보다 객체로 작성하면 어떨까요?

2024-04-21 04:52 UTC, 365kim commented on src/hooks/useForm.ts
> +import useCardNumber from './useCardNumbers';
```suggestion
import useCardNumbers from './useCardNumbers';
```

변수명 리팩터링은 특히 놓치게되는 부분이 생기기 쉬운 것 같아요 이를 방지하기 위해 제가 사용하는 방법은 default export 대신 항상 named export를 사용하거나, 그래도 놓치는 부분이 생길 수 있으니 코드 에디터를 통해 일괄 변경 기능을 사용해 누락된 부분이 없도록 합니다.

<img width="385" alt="image" src="https://github.com/woowacourse/react-payments/assets/60066472/6d1613b3-6b71-467b-a1b1-773128ad1c6d">

2024-04-21 04:58 UTC, 365kim commented on src/hooks/useForm.ts
> +  expirationDate: Array<number | undefined>;
아하 초기값이 undefined이군요 충분한 설명이 되었습니다. 타이핑 개선 반영도 감사합니다 👍

(참고: 사용자가 input 요소에 입력하는 값이 핸들러에서 string 타입으로 전달되니, 아예 문자열로 다루고 빈값은 `''`로 설정하는 방법도 있을 것 같아요.)

2024-04-21 05:04 UTC, 365kim commented on src/constants/Message.ts
> +  userName: 'LAST_NAME FIRST_NAME',
아하 지금보니 Last name이 먼저군용~! 이걸 놓쳤네용 

실제 카드 도메인에서도 'HARU KIM' 순서로 작성하기도 하고, 디자인 시안에서도 `이름 성`인데, 유효성 검사를 `성 이름` 구조로 작성하게 되신 이유가 일있을까요?

한편으로는 placeholder 문구 자체도 디자인 시안(요구사항)으로 간주하고 그대로 반영해주시면 더 좋을 것 같습니다. 🙏🏻

2024-04-21 05:12 UTC, 365kim commented on package.json
> +    "styled-components": "^6.1.8",
그렇다면 `styled-components`를 사용하면서 불편하다고 느꼈거나, 혹은 다른 단점도 있을까요~?

2024-04-21 05:40 UTC, 365kim commented on src/components/InputField/InputField.tsx
> +const InputField = ({ label, error, children }: InputFieldProps) => {
fieldset legend 활용 시도 너무 좋습니다 👍 

<img width="569" alt="image" src="https://github.com/woowacourse/react-payments/assets/60066472/38a76e97-cfef-4e90-9ade-25df2d187b46">

<br/>

다만 fieldset/legend 는 상위의 그룹을 묶는데 사용하는 것이라 여전히 label 지정은 필요해보입니다. 각 input에 의미있는 label을 붙여볼 수 있을까요?

2024-04-21 05:41 UTC, 365kim commented on src/components/Input/Input.tsx
> +const Input = ({ invalid, ...props }: InputProps) => {
이 코멘트가 이제 추가된 것 같네용 👀

2024-04-21 05:48 UTC, 365kim commented on src/hooks/useExpirationDate.ts
> +  const yearCondition = (value: string) => value.length === 2;
https://github.com/woowacourse/react-payments/assets/60066472/a806a537-9f41-4092-a840-532a63c97ec8

혹시 이런 케이스를 말씀해주신 걸까요? 맞다면 정상적으로 두 자리 다 입력된 경우에는 아예 error message를 표시하는 로직을 타지 않도록 하면 어떨까요?

2024-04-21 05:54 UTC, 365kim commented on src/hooks/useExpirationDate.ts
> +  const yearCondition = (value: string) => value.length === 2;
아하 위 케이스는 별개 케이스고 이런 경우를 말씀해주신 것 같네용

https://github.com/woowacourse/react-payments/assets/60066472/bde7f063-1f68-44b1-98cb-d3a51648d8ee

그런데 역시 같은 방식으로 해결할 수 있지 않을까 싶은데 쿠키의 생각은 어떠신가용?

2024-04-21 05:59 UTC, 365kim commented on src/hooks/useInput.ts
> +  additionalEffect: (value: string) => string = (value) => value,
`additionalEffect` 함수의 시그니처와 기능이 잘 이해되지 않는데, 어떤 함수인지 설명 부탁드려도 될까용?

2024-04-21 06:03 UTC, 365kim requested changes
쿠키, 적극적으로 피드백 반영해주셔서 감사해요! 
이미 충분히 Approve해도 될 것 같지만서도, 의견을 조금 더 나누고 마무리하고 다음단계로 넘어가도 좋을 것 같아 다시한번 Request changes 드려봅니다 :)

2024-04-21 07:34 UTC, jinhokim98 commented on package.json
> +    "styled-components": "^6.1.8",
styled-components를 사용하면서 불편하다고 느낀 점은 태그 이름을 항상 지어주어야 한다는 점 같아요.. (div, section, a, button) 태그를 그대로 쓰지 못해서 이름을 지어줘야하고, 그 과정에서 가독성도 조금 떨어지게 되는 것 같습니다

2024-04-21 08:06 UTC, jinhokim98 commented on src/constants/Message.ts
> +  userName: 'LAST_NAME FIRST_NAME',
페어와 이야기하면서 자연스럽게 이렇게 정하자! 하고 정해버린 것 같아요!
그러네요 다시 보니깐 디자인 시안이 이름 성이었네요;;;🥲🥲

디자인 시안대로 다시 고쳐보겠습니다!

2024-04-21 08:13 UTC, jinhokim98 commented on src/hooks/useInput.ts
> +  return [value, onChange, error] as const;
그러네요! 그렇게 변환하는 것이 더 좋을 것 같아요! 예상보다 규모가 커졌으니,,

2024-04-21 08:21 UTC, jinhokim98 commented on src/hooks/useInput.ts
> +  return [value, onChange, isError] as const;
이게 밖에서 onChange를 그냥 return 했을 때 onChange 타입이 예상한 대로 되지 않아서 계속 타입 에러가 나더라구요,,ㅜ 그런데 여기에 `as const`를 붙여서 반환해줬을 때 예상한 대로 타입이 설정이 돼서 이렇게 작성했었습니다. 지금은 객체 타입을 반환을 바꾸니 `as const` 키워드를 제거해도 타입 에러가 발생하지 않게 됐습니다

2024-04-21 08:22 UTC, jinhokim98 commented on src/hooks/useForm.ts
> +import useCardNumber from './useCardNumbers';
앗;;;;;;;; 이런 실수를;;;;;; 바꿨다고 생각했는데 정작 import 하는 부분에서 변경하지 못 했네요..ㅠ

2024-04-21 08:26 UTC, jinhokim98 commented on src/hooks/useInput.ts
> +  additionalEffect: (value: string) => string = (value) => value,
소유자 이름에서 소문자를 입력했을 때 대문자로 변경하는 기능을 넣기 위해서 추가했습니다.
소유자 이름을 관리하는 쪽에서는 특정 이름을 지을 수 있지만 useInput은 전반적으로 사용하는 hook이라고 생각해서 이름을 일반적으로 지어야 하지 않을까!? 해서 부가적인 효과라고 생각해서 additionalEffect라고 이름을 지었습니다!

2024-04-22 05:41 UTC, jinhokim98 commented on src/components/InputField/InputField.tsx
> +const InputField = ({ label, error, children }: InputFieldProps) => {
각 input에 aria-label 속성을 이용해서 의미있는 label을 붙여봤습니다!
[cbd7cf5](https://github.com/woowacourse/react-payments/pull/337/commits/cbd7cf5822645299574ff4a2e82ace8d5289d141)

2024-04-22 05:46 UTC, jinhokim98 commented on src/hooks/useForm.ts
> +  expirationDate: Array<number | undefined>;
원래는 처음에 undefined로 전달해주다보니 uncontrolled 라고 인식했다가 사용자가 입력을 시도하면 controlled로 변경됐다는 콘솔 에러가 나왔었는데 빈 문자열로 넘겨주니깐 에러가 사라진 것 같아요!
[97b8082](https://github.com/woowacourse/react-payments/pull/337/commits/97b80820f81248e30752493325db669ec1c177fd)

2024-04-22 05:52 UTC, jinhokim98 commented on src/hooks/useExpirationDate.ts
> +  const yearCondition = (value: string) => value.length === 2;
제가 처음에는 마지막 문자만 정규식에 맞지 않는 입력이 들어올 것이라 생각해서 마지막 문자만 지워지도록 했는데 중간으로 커서를 옮겨서 입력하는 상황을 생각할 때 원하는 결과가 나오지 않았던 것 같아요;;; 그래서 아에 방식을 사용자가 입력할 때마다 정규식에 맞지 않으면 그 문자만을 지워버리는 로직으로 변경했습니다!!
그런데 한글을 입력할 때 지워지는 건 동일하네요;;;;
[d770216](https://github.com/woowacourse/react-payments/pull/337/commits/d770216cf7c70393df3f9175870fcafd7459ac60)

2024-04-22 17:32 UTC, 365kim commented on src/hooks/useInput.ts
> +  additionalEffect: (value: string) => string = (value) => value,
아하 친절한 설명 감사합니다.

저는 조금 더 구체적인 이름이어도 좋겠다는 생각이에요. 
`modifyValue`, `formatValue`, `sanitizeValue` 와 같은 이름은 어떨까요?

2024-04-22 17:34 UTC, 365kim commented on src/hooks/useInput.ts
> +  return [value, onChange, isError] as const;
배열에서 객체로 바꾼다고 에러가 사라지는 것은... 왜지.. 신기하네요,..

2024-04-22 17:38 UTC, 365kim commented on src/components/CardInformationForm/CardInformationForm.tsx
> +              aria-label="first-card-numbers"
앱 전체 환경에서 언어를 한글로 사용하고 있어서, 레이블도 한글로 작성해도 좋겠습니다 :)

2024-04-22 17:42 UTC, 365kim commented on src/hooks/useForm.ts
> +  expirationDate: Array<number | undefined>;
아하 의도한 것은 제어컴포넌트인데, 초기 렌더링 시 value={undefined}인 순간에 비제어 컴포넌트로 인식되어서인 것이죠? 여러모로 value는 문자열로 다루는 게 좋아보이네용 ㅎㅎ

2024-04-22 17:47 UTC, 365kim commented on src/hooks/useExpirationDate.ts
> +  const yearCondition = (value: string) => value.length === 2;
앗 정확한 기억은 아닌데, 저도 실무에서 비슷한 이슈를 만났었어요. 한 브라우저 대응까지는 어떻게 해보는데 각 브라우저마다도 동작이 달라서 완벽하게 대응할 수 있는 방법이 없어서 결국 아예 처리하지 않기로 했던 것 같네요... 🥲 지금 쿠키가 경험하신 트러블슈팅 경험을 잘 기록해두셔도 좋을 것 같아요! 🚀

2024-04-22 17:55 UTC, 365kim approved these changes
![pok](https://github.com/woowacourse/react-payments/assets/60066472/c4bbc3f5-053e-480f-975c-95b2a722513a)


쿠키, 페이먼츠 1단계 미션 완료 축하드립니다 🥳

리액트 미션에서 꼭 다루면 좋을 고민과 경험들을 빠르게 잘 채워나가고 계신 것 같아요 💯👍 쿠키의 2단계가 더 기대됩니다. 

리뷰 과정 동안에 적극적으로 임해주셔서, 또 친절하게 코멘트로 해당 커밋 남겨주셔서 감사해요. 덕분에 피드백 반영해주신 히스토리를 제가 쉽게 따라갈 수 있었고 리뷰하는데 도움 많이 받았어요. :)

고생하셨습니다 👏

2024-04-22 17:56 UTC, merged