[1단계 - 페이먼츠] - 포메(김우성) 미션 제출합니다.
woowacourse/react-payments pull request #351
Opened 2024-04-18 08:19 UTC by novice0840

안녕하세요, 호프. 레벨 1에 이어서 레벨 2도 잘 부탁 드립니다.  

# 배포 링크 

## 스토리북 
https://6620c7218f91f7257a7bf47e-vdaqkwnhnz.chromatic.com/?path=/story/field--owner-name

## 리액트
https://novice0840.github.io/react-payments/

# 느낀 점 
그 동안에 별도의 라이브러리 없이 바닐라 자바스크립트로 SPA를 만들어왔는데 리액트를 쓰니 확실히 상태 관리와 모듈화 측면에서는 편해진 것 같다. 특정 상태 값이 바뀔 때 마다 알맞게 UI를 변경해 주어야 했는데 이 부분이 리액트에서 자동으로 되어 편리했다. 

# 질문  
전체적인 구조에 대한 피드백을 부탁 드립니다! 또한, 각 입력 값을 확인하고 상황에 맞는 에러 메세지를 띄우는 부분을 커스텀 훅으로 만들었는데 코드가 다소 장황해졌다고 느낀 부분이 있어 이 부분에 대한 피드백도 해주시면 감사하겠습니다.  

# 구조 

![image](https://github.com/woowacourse/react-payments/assets/111696934/b4e0249b-551c-4186-bde4-e9e993da3fe9)

2024-04-18 14:21 UTC, moonheekim0118 requested changes
안녕하세요 포메! 저도 지난 레벨1에 이어서, 레벨2 첫번째 미션 잘부탁드려요 :) 
리액트 첫 미션 구현해주시느라 고생많으셨어요.
첨부해주신 구조도 덕분에 전체적인 컴포넌트 구조를 이해하는데 수월했습니다. 감사해요 👍 

컴포넌트는 각각 목적에 맞게 아주 깔끔하게 잘 분리해주신 것 같아서 관련해서 따로 피드백 드릴게 없었네요ㅎㅎ. 구조도에 그려주신 것 처럼 
`일반 컴포넌트 (도메인) >> 레이아웃 컴포넌트  >> 공통 UI 컴포넌트 (가장 작은 단위)`의 계층을 지켜서 잘 작성 및 사용해주신 것 같아요 👏 👏  


그럼 고생하셨어요! 반영 후 다시 요청주세요 :)

2024-04-18 14:21 UTC, moonheekim0118 commented on src/hooks/useAddCardInput.tsx
> +}: useAddCardInputProps<T>) {
공통되는 로직을 커스텀훅으로 분리해주시는 시도 매우 좋습니당 👏 👏 
- input value 를 관리하고 (onChange, onBlur)
- validation 을 처리하고
- error 상태를 관리한다.

라는 역할도 제 생각에는, 과하지 않은 것 같습니다.
다만 위의 피드백에도 남겨드린 것과 이어지는데, value 를 관리하는 곳이 두곳이다 보니 processData 와 같은 prop이 필요하게 되는데요, 요  prop을 제거하는 방법을 한번 고민해보시면 좋을 것 같아요. 그러려면 구조적으로 상태의 위치나 현재 정의해주신 상태의 구조 자체를 바꿔야 할수도 있을 것 같기도 한데..ㅎㅎ한번 포메가 가볍게 고민해봐주세요~!

2024-04-18 14:21 UTC, moonheekim0118 commented on src/types/CardInfo.d.ts
해당 파일을 `d.ts`로 만들어주신 이유가 있을까요?

2024-04-18 14:21 UTC, moonheekim0118 commented on src/stories/Field.stories.tsx
> +    ),
현재 스토리북의 컨트롤 탭에서는 아래와가이 children argument 도 스토리북 사용자가 조작할 수 있는데요,
잘못 조작하다보면 이렇게 스토리북 자체가 터져버려요 😅 

개발에서만 필요하고, 사용자는 조작할 필요 없는 이런 argument 들의 컨트롤을 막는 방법은 없을까요?
<img width="1182" alt="스크린샷 2024-04-18 오후 11 13 20" src="https://github.com/woowacourse/react-payments/assets/61469664/65480e51-e828-452d-b25c-53e8d1f0791d">

2024-04-19 05:12 UTC, novice0840 commented on src/components/CardPreview/CardPreview.tsx
> +                className={`${styles.cardNumber} ${isMask && styles.mask}`}
객체의 각 key 값들의 true, false 여부를 확인해 class 이름으로 사용될 문자열을 만들어 주는 라이브러리이군요. 감사합니다.

2024-04-19 05:23 UTC, novice0840 commented on src/types/CardInfo.d.ts
d.ts 파일에 타입을 선언하면 최상단에 import를 해주지 않아도 돼서 사용하였습니다. 다만, 제가 알기로는 d.ts는 JS으로 만들어진 라이브러리가 사용자에게 타입을 제공해 줄 때  사용되는 걸로 알고 있는데 이런 식으로 사용해도 괜찮을까요?

2024-04-19 05:34 UTC, novice0840 commented on src/hooks/useAddCardInput.tsx
> +interface useAddCardInputProps<T extends InitialValuesType> {
컨벤션을 통일하고 조금 더 명시적으로 이름을 바꾸었습니다!

2024-04-19 05:52 UTC, novice0840 commented on src/domain/validators.ts
> +
고민을 해봤는데 domain이라는 이름의 폴더에는 어울리지 않는다고 생각하여 검증 관련 함수들을 util로 옮겼습니다.

2024-04-19 06:08 UTC, novice0840 commented on src/constants/messages.ts
> +export const ERRORS = Object.freeze({
as const를 쓰면 각 요소 별로 readonly가 붙어 더 자세하게 타입을 명시할 수 있군요 감사합니다. 수정했습니다.

2024-04-19 06:52 UTC, novice0840 commented on src/components/layout/Field/Field.tsx
> +      </label>
input 태그가 children에 들어있어 htmlFor에 넣을 id가 해당 파일에서는 보이지 않는 상황입니다. label 안쪽에 input 태그가 있는 것이 마음에 걸리긴 했는데 input 태그 하나에 각각 대응하는 label 태그 하나를 대응 시키는 것이 일반적인가요?

2024-04-19 06:59 UTC, novice0840 commented on src/components/common/Input/Input.tsx
> +  handleOnBlur?: (event: React.FocusEvent<HTMLInputElement>) => void;
수정하였습니다!

2024-04-22 01:45 UTC, novice0840 commented on src/components/CardNumberInput/CardNumberInput.tsx
> +  } = useAddCardInput<CardNumbers>({
전체 state를 app에서 관리하면서 props로 넘겨주는 방식으로 구조를 변경하였습니다.

2024-04-22 07:19 UTC, novice0840 commented on src/stories/Field.stories.tsx
> +    ),
children 옵션의 control 못하게 만들어 깨짐을 막았습니다.

2024-04-22 07:48 UTC, novice0840 commented
안녕하세요, 요구 사항들 읽어 보고 수정 사항을 반영하였습니다. state를 App에서 모두 관리하게 하고 useCallback과 memo를 활용하여 특정 Input 입력 중에 다른 Input과 CardPreview는 리렌더링이 되지 않도록 구조를 변경 하였습니다.

## 배포 링크 
[배포 링크](https://novice0840.github.io/react-payments/)
## 스토리북 링크
[스토리북 링크](https://6620c7218f91f7257a7bf47e-zvqvjcaton.chromatic.com/)

2024-04-23 00:32 UTC, moonheekim0118 commented on src/types/CardInfo.d.ts
>  다만, 제가 알기로는 d.ts는 JS으로 만들어진 라이브러리가 사용자에게 타입을 제공해 줄 때 사용되는 걸로 알고 있는데 이런 식으로 사용해도 괜찮을까요?

저도 앱 내부에 사용될 타입은 d.ts 로 정의해주는 경우를 잘 못봤어서 질문드렸어요ㅎㅎ
무조건 사용하지 않아야한다!는 아니긴 하지만 흔하진 않은 것 같아요ㅎㅎ

2024-04-23 00:41 UTC, moonheekim0118 commented on src/components/layout/Field/Field.tsx
> +      </label>
아하 그렇네요ㅎㅎ제가 구조를 확인하지 못했었는데 두 가지 방법 모두 기능상 크게 차이는 없을 것 같은데요,
다만, 현재 방법(label 내부에 input 넣기)은 스크린리더기 등에서 이를 제대로 읽지 못하는 문제가 있다고도 하네요ㅎㅎ

2024-04-23 00:54 UTC, moonheekim0118 approved these changes
안녕하세요 포메 :) 변경사항 잘 봤습니다!

이전에 비해 훅들도 작은 크기로 제 역할을 아주 잘 하고 있는 것 같고, 상태 구조 및 위치도 아주 좋아요 👍 👍 
memo, useCallback 사용해봐주신 것도 좋습니다 😊 다만, 메모이제이션 연산은 그 만큼의 비용을 요한다는 것만 인지해주세요ㅎㅎ

추가로 남겨드린 소소한 피드백들은 2단계에서 같이 반영해도 괜찮을 것 같아요.
고생하셨습니다! 2단계에서 뵈어요~~ 👋

2024-04-23 00:54 UTC, moonheekim0118 commented on src/components/CardPreview/CardPreview.tsx
> +    if (prev.ownerName.ownerName !== next.ownerName.ownerName) return false;
memo 시도 좋습니다 👍 👍 
다만 요런 비교 부분 함수로 분리해봐도 좋을 것 같아요!

2024-04-23 00:54 UTC, moonheekim0118 commented on src/components/ExpirationDateInput/ExpirationDateInput.tsx
> +            ></Input>
self closing tag 적용안된 부분들이 곳곳에 보이는데,
관련 eslint 룰 추가해도 좋을 것 같아요 :)

2024-04-23 00:54 UTC, moonheekim0118 commented on src/components/layout/Field/Field.tsx
> +  children: React.ReactNode;
리액트의 propsWithChildren 이란 것도 있습니다ㅎㅎ
ReactNode 로 타입을 잡아주는 것과 PropsWithChildren 을 사용하는게 어떻게 다른지 알아보셔도 좋을 것 같아요.

2024-04-23 00:54 UTC, moonheekim0118 commented on src/components/layout/Field/Field.tsx
> +    <div className={styles.field}>
지금보니 요건 fieldset 태그 사용해도 되겠네요ㅎㅎ

2024-04-23 00:54 UTC, merged