[1단계 - 페이먼츠] - 헤인(방세린) 미션 제출합니다.
woowacourse/react-payments pull request #352
Opened 2024-04-18 08:25 UTC by Hain-tain

안녕하세요, 샐리! 다시 뵙게되어 반갑습니다! 🙇🏻‍♀️
부족한 점이 많지만, 그만큼 더 열심히 배우겠습니다!
이번 페이먼츠 미션도 잘 부탁드립니다 !!

## 📍배포 및 실행방법
- 배포 페이지 
  - [💳 페이먼츠](https://hain-tain.github.io/react-payments/dist/)
  - [🎀 스토리북 배포](https://6620cd9799e8a4a3cde136fc-ugmvlojlhf.chromatic.com/?path=/story/app--default)
- 로컬 환경 실행 방법
```
npm install

// 프로젝트 실행
npm run dev

// 스토리북 실행
npm run storybook
```
## 📁 프로젝트 구조
![payments](https://github.com/woowacourse/react-payments/assets/157036488/16a9e00f-e40d-4f60-8ae2-c51cb636b089)

## 🤔 고민했던 점 및 질문
### 1. Headless 컴포넌트를 어떻게 구현할 수 있을까?
- Headless 컴포넌트란 기능과 ui요소를 분리하여, ui 변화에 유연하게 대처할 수 있는 컴포넌트입니다.
- 커스텀 훅(useInput)을 사용하여 Headless 컴포넌트를 구현해보려고 하였습니다. 그런데 useInput을 사용하는 과정에서 validator와 errorHandler를 props로 내려주어야 했고, 때문에 각각의 컴포넌트 내부에서 또 다시 기능과 ui가 묶이고 있다는 생각이 들었습니다. (현재는 errorMessage 상태를 CardNumbers 와 같은 비즈니스 컴포넌트에서 가지고 있기 때문에 기능을 분리하지 못하는 상태입니다ㅠㅠ)
- 스토리북을 적용하려고 하니, 더더욱 ui 분리가 되지 않은 것 같다는 생각이 들었습니다. 이 
### 2. 상태를 어떻게 관리하는 것이 현명할까?
- 현재 페이먼츠에는 사용자로부터 총 3개의 필드(카드 번호, 카드 유효기간, 카드 소유자)를 받고있고, 카드 번호에서 유추하는 카드 발급사까지 총 4개의 상태를 가집니다. 
- 각각의 비즈니스 컴포넌트들(Card...)에서 상태를 가지고 있고, CardPreview 에서 해당 상태를 조회해야 합니다. 이를 위해 useContext를 사용하였습니다. 
### 3. 에러 처리를 어떻게 해주는 것이 좋을까?
- 현재 유효하지 않은 입력이 들어오면, Error 객체를 상속받은 `BlockedError` 와 `NonBlockedError` 를
---
+) 기능 구현에만 급급하여 스토리북에 대해 고려하지 못한점이 개인적으로 아쉽습니다.
다음 피드백 반영시, 추가적으로 작업해보도록 하겠습니다.
많은 질문과 피드백 부탁드립니다. 감사합니다 🙏

2024-04-19 01:51 UTC, liswktjs requested changes
안녕하세요 헤인 
리액트에서 다시 보게 되었네요 🔮 반갑습니다 👋

전체적으로 코드를 깔끔하게 잘 작성해주신 것 같아요 
pr에 남기신 질문들은 코드 단에 코멘트로 달았으니 확인 부탁드려요 👍

추가적인 ux 적인 개선 사항을 제안하자면 , 
유저가 유효하지 않은 값을 입력했을 때 카드 preview를 빨간색으로 보여준다는 등이 될 수 있으면 좋을 것 같아요 혹시 시간이 되시면 구현해보시는 것 도 추천드립니다

2024-04-19 01:51 UTC, liswktjs commented on src/App.tsx
> +});
context관련된 것들은 따로 훅으로 분리해주는 건 어떨까요?

2024-04-19 01:51 UTC, liswktjs commented on src/hooks/useInput.tsx
> +  const [value, setValue] = useState("");
pr에 적어주신 고민 중 1번과 2번과 관련된 답이 같이 될 것 같습니다 

Headless에 대해서 고민하시고 구현을 시도 하신 것에 대해서는 좋은 시도라고 생각합니다 👍
Headless도 만들어 가다 보면 유연하게 여러 곳에 사용할 수 있다 보니 좋은 컴포넌트 구조라고 생각합니다 
헤인이 리액트에 대해서 많은 공부를 하고 오신 것 같아요 🏃‍♀️

다만, 현재 미션 요구사항들을 고려해볼 때 상태를 이중화하고 Headless한 컴포넌트를 만드는 것이 적절한 것인지는 살짝 의문이 들긴 합니다 그래서 1번 2번에 대한 직접적으로 답을 드리기 보다는 제가 제안드리고 싶은 점들은 심플하게 생각하면서 점점 더 develop하는 방식으로 미션을 진행해보는 것도 추천드리고 싶어요! 

예를 들어 현재 페이먼츠 미션의 경우 useState로 app에서 다 선언을 해줘서 컴포넌트에 다 넘겨 주게 구현을 한 다음 -> 
어 이런게 조금 개발하면서 불편했어 혹은 2단계에 추가 미션 요구사항을 반영하려니깐 여기서 상태관리를 하는게 불편하네 
등이 생겼을 때 develop시켜나가는 방향으로 공부를 해보시면 좋을 것 같아요

이렇게 공부를 했을 때 개인적으로는 아 이래서 context가 필요하구나 등의 깨달음(?)을 얻을 수 있어서 추천드리고 싶습니다

2024-04-19 01:51 UTC, liswktjs commented on src/components/CardNumbers.tsx
> +
useContext를 사용해서 props drilling없이 preview에서 보여줄 상태값들을 보여주는 시도는 좋은것 같아요 
다만 관리하는 상태를 이중화 한 것에 대해서는 우려스러운 점들이 있습니다 

개인적으로 상태관리를 심플 할 수록 추후 유지보수도 쉬워지고 추후에 상태관련 요구사항 변경이 있을 때 대응하기도 쉬워질 수 있다고 생각합니다 
현재의 상황을 예시로 들어보면 만약 카드의 cvc번호나 카드 별칭등을 입력받는 요구사항이 추가로 들어온다면 
context에서도 cvc번호를 넣어주고 useInput도 새롭게 만들어줘야하는 2번  일을 해야한다는 번거로움이 있을 것 같습니다 

context또는 state 둘 중 하나만 사용하는 건 어떨까요?

2024-04-19 01:51 UTC, liswktjs commented on src/components/CardPreview.tsx
> +
preview부분을 깔끔하게 구현하셨네요 👍

2024-04-19 01:51 UTC, liswktjs commented on src/hooks/useInput.tsx
> +  };
에러 핸들링에 대해서 고민을 적어주셨네요 
에러 핸들링은 매번 고민되는 지점이긴 하지만 저의 경험을 토대로 답변을 드리자면, 
팀에서 어떻게 정하냐에 따라 달라지는 것 같습니다 
현재 에러 객체를 사용하는 것에 대해서도 코드 내에서 일관성있게 에러 객체를 활용해서 에러를 일관적으로 처리하고 있다면 좋은 에러 처리 방식이라고 생각합니다 

일관성있게 컨벤션에 따라 처리해주는 것이 제일 좋다고 생각합니다 
현업에서의 사례에 대해서도 질문을 주셨는데 [react-hook-form ](https://react-hook-form.com/) 을 한 번 살펴보시는 것을 추천드리고 싶습니다 
폼관련해서 상태를 관리하는데 사용하는 유명한 라이브러리이고 실제로도 많은 기업들이 사용하고 있어 이곳을 직접 한 번 살펴보시는 걸 추천드려요!

2024-04-19 01:51 UTC, liswktjs commented on src/components/FormItem.tsx
> +      <label css={styledLabel}>
emotion을 활용해서 스타일링을 해주셨군요 
emotion의 css props와 객체 스타일 선언 방식의 차이점이 무엇인지 공부해보셔도 좋을 것 같아요 
css props의 방식은 성능 이슈가 있을 수 있습니다!

2024-04-19 01:51 UTC, liswktjs commented on src/domain/validateInput.ts
> +export const validateOnlyDigit = (string: string) => {
현재 파일이름을 validateInput으로 해주셨는데요 추후 다른 domain들이 추가된다는 가정하에 
card정보에 대한 validate를 담고 있는 파일임을 파일 명으로 표기해주면 좋을 것 같아요

2024-04-19 01:51 UTC, liswktjs commented on src/stories/CardPreview.stories.tsx
> +
CardPreview 스토리북에서도 CardPreview 컴포넌트 단에 적용해주신 스타일을 한 번 더 선언 해주고 계시는 군요 
이렇게 스타일이 2번 선언 되어 있다보면 스토리북에 대한 관리비용도 늘어 나기 때문에 (예를 들어 스타일이 변경될때 preview에서 한 번 storybook에서 한 번 이런식으로 수정을 해줘야 하게 때문입니다) 지양하는 것이 좋습니다!

2024-04-22 14:51 UTC, Hain-tain commented on src/App.tsx
> +});
이번에 샐리의 피드백을 반영하며 context를 사용하지 않게 되었습니다. 추후 다시 context를 사용하게 된다면 별도의 훅으로 분리하여 사용해보도록 하겠습니다!🙏

2024-04-22 15:42 UTC, Hain-tain commented on src/domain/validateInput.ts
> +export const validateOnlyDigit = (string: string) => {
좋은 포인트인 것 같아요!  현재 `validateCardInfo` 라는 이름으로 변경해보았습니다! 

(👉 [ff5a424](https://github.com/woowacourse/react-payments/pull/352/commits/ff5a4246b23b44190def3d363ffca6340172ec14) 커밋에 반영되었습니다)

2024-04-22 15:43 UTC, Hain-tain commented on src/stories/CardPreview.stories.tsx
> +
스토리북에 대한 학습이 부족한 상태로, 다급하게 컴포넌트를 복사하여 스토리북을 생성하다보니 이런 부끄러운 상황이 된 것 같습니다. 🥲 현재는 컴포넌트를 불러와 사용하는 방식으로 변경되었습니다.

2024-04-22 15:48 UTC, Hain-tain commented on src/hooks/useInput.tsx
> +  const [value, setValue] = useState("");
처음에는 각 컴포넌트에서 각자의 상태를 가지고 있는 것이 의미론적으로 더 맞다고 생각하여 각 컴포넌트에서 상태를 가지도록 하고, 상위로 상태를 끌어올리기 위해 context를 사용하게 되었습니다. 

그러나, 샐리의 피드백을 읽으면서 `상태관리를 심플 할 수록 추후 유지보수도 쉬워진다`, `변동사항이 생기면 2번 일을 해야한다는 번거로움이 있을 것` 이라는 부분을 읽으면서, 깊게 공감하였습니다. 이에 상태관리 방법을 전면적으로 교체하게 되었습니다. 

< 변경된 상태관리 방법 >
- 최상단(App) 에서 각각의 커스텀 훅(useCardNumbers, useCardExpirationPeriod, useCardHolder) 를 통해 상태 및 핸들러(value 와 onChangeHandler, errorMessage) 를 생성한다.
- Props 로 해당 상태들을 필요한 각각의 컴포넌트에 넘겨준다

2024-04-22 15:50 UTC, Hain-tain commented on src/components/CardNumbers.tsx
> +
현재 상태들을 최상단에서 커스텀 훅을 이용하여 만들고, 하위 컴포넌트들에게 props 로 내려주는 방식으로 변경해보았습니다. ☺️

2024-04-22 16:12 UTC, Hain-tain commented on src/hooks/useInput.tsx
> +  };
역시 일관성이 가장 중요하군요..! 감사합니다🙏

2024-04-22 16:41 UTC, Hain-tain commented on src/components/FormItem.tsx
> +      <label css={styledLabel}>
emotion에서는 타입스크립트와 함께 사용할 경우 객체 스타일 사용하길 권장하고 있습니다. 

그러나 객체 스타일로 사용하였을 때, 아주 일부의 속성(flexDirection, textAlign) 의 타입이 오류가 나는 현상이 있었습니다. `as const`로 해결할 수는 있었으나  ([관련 이슈](https://github.com/cssinjs/jss/issues/1344)),  현재의 방법이 css 문법처럼 사용하기 편리하여 현재의 방법을 채택하게 되었습니다. (현재처럼 css함수에 ``(백틱)을 사용하여 인자로 넘겨주는 것이 css props 방식이라고 이해했는데, 맞을까요?)

emotion에서 아래와 같이 inline으로 css를 설정해줄 경우 렌더가 될 때마다 css함수를 실행하고, css 속성이 중복 되었는지 여부와 상관없이 모두 각각 고유한 이름을 가진 css 생성하여 성능이 저하될 수 있다는 글을 보았습니다. 
```
<div css={css`
  font-size: 20px;
  color: red;
`}
>
  hello world!
</div>
```


그러나 css props 방식의 성능 이슈와 관련된 내용을 찾지 못하였습니다. 혹시 샐리가 참고하신 아티클이나 자료가 있으시다면 공유해주시면 정말 감사할 것 같습니다. 🙏

아래는 제가 참고한 글입니다.
- [Emotion의 css Prop을 효과적으로 사용하기](https://velog.io/@parksil0/Emotion%EC%9D%98-css-Prop%EC%9D%84-%ED%9A%A8%EA%B3%BC%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
- [Consider defining styles outside your components](https://emotion.sh/docs/best-practices#consider-defining-styles-outside-your-components)

2024-04-23 12:32 UTC, liswktjs commented on src/hooks/useInput.tsx
> +  const [value, setValue] = useState("");
의견을 자세히 공유해주셔서 감사해요 😊

확실히 현재 단계에서는 컴포넌트의 depth가 깊지 않아 props driling이 그렇게 까지 거슬릴 단계는 아니긴 합니다 
그렇지만 헤인이 말한 그대로 추후에  2단계 요구사항을 반영하거나 다음 미션 등을 진행할 때는 depth가 깊어지거나 페이지 간에 상태를 공유해줘야 하는 일이 생기는 등  app에서 state로 다 넘겨주는 것이 불편함을 느낄 수 있어요! 

그 때 지금 헤인이 해준 것 처럼 context등의 전역 상태 등을 활용해서 개선 해보면  context의 필요성도 느끼게 되고 좋은 경험이 될 것 같습니다 👍
추가로 어떤 기능을 구현할 때 전역상태를 써야할지 useState를 써야할지도 나름 기준을 스스로 세워볼 수도 있을 것 같아요

2024-04-23 12:34 UTC, liswktjs commented on src/hooks/useInput.tsx
> +  };
아무래도 주어진 요구사항과 프로젝트 규모 기존의 컨벤션 등등의 여러 상황에 따라 
상황마다 좋은 에러 관리 방식이 달라지는 것 같아요 

미션마다 여러 에러 핸들링 방법을 찾아서 적용해보고 장단점을 느끼시면 다르게 전달되는 요구사항마다 최적의 방법을 찾을 수 있을 거라고 생각해요!

2024-04-23 13:44 UTC, liswktjs approved these changes
안녕하세요 헤인 
컨디션은 괜찮으신가요? 요즘 일교차가 심해서 🥲 컨디션이 괜찮아 지셨으면 좋겠네요 

코멘트들에 상세하게 의견과 답변 달아주셔서 감사해요! 덕분에 리뷰할 때 도움이 많이 되었습니다 
상태를 이번에 간결하게 해주시면서 코드도 한층 더 깔끔해진 것 같아요 👍

질문주신 점들 코멘트로 답글을 달았습니다! 그럼 2단계 미션도 파이팅입니다

2024-04-23 13:44 UTC, liswktjs commented on src/components/FormItem.tsx
> +      <label css={styledLabel}>
👍👍👍 
차이점을 잘 알고 써주셨군요! 공부를 많이 해주신 것 같아요 
헤인이 말한대로 css props를 사용할 때 inline으로 사용 해서 랜더링 마다 스타일을 재 계산 해서 성능상에 불리하게 동작할 때도 있어요 이점을 잘 알고 써주셨군요 

스타일링 컴포넌트에 대해서 잘 알고 계신 것 같아 추가 공부(?) 점을 공유해드리자면 
서버사이드 렌더링이 각광 받게 되면서 같이 주목 받게 된 [panda css](https://panda-css.com/) 라는게 있어요 
이것도 나~중에 시간 될 때 한 번 보셔도 좋을 것 같아요

2024-04-23 13:44 UTC, liswktjs commented on src/App.tsx
> +
3개로 상태를 분리해서 선언해주니깐 더 직관적으로 알아보기 쉬운 코드가 된 것 같아요

2024-04-23 13:44 UTC, liswktjs commented on src/components/CardNumbers.tsx
> +        {cardNumberInputs.map((cardNumbersInput, idx) => (
inputs에서 네이밍이 더 이해하기 쉬운 cardNumberInputs로 바뀌었네요 👍

2024-04-23 13:44 UTC, liswktjs commented on src/constants/message.ts
> +  cardHolderPlaceHolder: "SALLY",
😎

2024-04-23 13:44 UTC, merged