[1단계 - 페이먼츠] 올리(이예진) 미션 제출합니다.
woowacourse/react-payments pull request #365
Opened 2024-04-18 08:53 UTC by ImxYJL

안녕하세요 카일!
처음부터 미흡한 코드로 인사드리게 돼서 죄송한 마음입니다.
일단 시간상의 문제로 storybook은 별도로 배포하지 못했고, 타입 에러가 남아 있어서 타입 체크 무시 주석을 달고 build한 상황입니다 추후 개선하도록 하겠습니다ㅠㅠ

> 배포 사이트: https://imxyjl.github.io/react-payments/dist/index.html

2024-04-19 00:44 UTC, igy95 requested changes
안녕하세요 올리~ 코드가 미흡하다고 해서 죄송할 필요는 없습니다 :) 오히려 시간을 엄수하여 제출하신 부분을 더 긍정적으로 봐주셔도 될 것 같아요 👍

코드 전반적인 피드백으로는, 리액트라는 도구를 사용하고는 있지만 아직 리액트 내에서 제공하는 훅이나 리액트의 패러다임에 대한 이해도를 좀 더 높여보면 좋을 것 같다는 생각이 드네요!

추가적인 사항은 세부 코멘트 확인 부탁드리겠습니다 ㅎㅎ

2024-04-19 00:44 UTC, igy95 commented on src/components/Card/CardLogo.tsx
> +  let cardType = "";
중간 변수를 두지 않고 특정 타입을 바로 반환하여 사용하는 방법은 없을까요?

2024-04-19 00:44 UTC, igy95 commented on src/components/Card/CardLogo.tsx
> +  }
`cardNumbers`의 nullable 여부를 체크하는 이유가 있을까요?

2024-04-19 00:44 UTC, igy95 commented on src/components/Card/CardLogo.tsx
> +    .find((item) => item.index === "0");
props로 받아온 배열의 불변성을 유지시키는 방향을 고려해보면 좋겠네요!

2024-04-19 00:44 UTC, igy95 commented on src/components/Card/CardLogo.tsx
> +  }
- 좀 더 분기문을 간결하게 풀어보면 좋을 것 같습니다 :)
- 곳곳에 상수처리가 필요한 부분도 보이는 듯 하네요!

2024-04-19 00:44 UTC, igy95 commented on src/components/Card/CardNumber.tsx
> +const CardNumber = ({ number }:{number:string}) => {
- `string`, `number`와 같이 타입명과 혼동될 수 있는 네이밍은 되도록 피하는 것을 권장드립니다~
- props의 인터페이스 선언부를 보았을 때 prettier가 동작하지 않는 걸로 보이네요 🤔 포맷팅이 필요할 것 같습니다!

2024-04-19 00:44 UTC, igy95 commented on src/components/Card/CardPreview.tsx
> +    <>
여기에서는 Fragment를 안감싸도 되지 않을까요?

2024-04-19 00:44 UTC, igy95 commented on src/components/Card/ExpirationDate.tsx
> +  });
현재와 같은 방식에서는 컴포넌트가 리렌더링할 때마다 계산이 계속 될 것 같은데, 반복되는 계산의 빈도수를 줄여볼 수 있는 방법이 없을까요~?

2024-04-19 00:44 UTC, igy95 commented on src/components/Card/ExpirationDate.tsx
> +          )}
어떠한 자료구조에서 인덱스로 접근하게 되면, 가져오려는 데이터가 정확하게 어떤 데이터인지 바로 알기가 힘든 단점이 있습니다. 때문에 가능하다면 특정 key를 선언하거나 배열 구조 분해 할당을 통해 가독성을 높여주시는 것이 좋을 것 같아요.

2024-04-19 00:44 UTC, igy95 commented on src/components/Form/CardNumberForm.tsx
> +  //const [isInputValid, setIsInputValid] = useState(true);
사용하지 않는 주석은 임시 처리 항목임을 나타내거나 지워주세요!

2024-04-19 00:44 UTC, igy95 commented on src/components/Form/Input.tsx
> +  index: string;
`Input` 컴포넌트에서 index를 props으로 받아야하는 이유가 무엇일까요?

2024-04-19 00:44 UTC, igy95 commented on src/components/common/FormElement.tsx
> +const FormElement = ({ labelContent, inputs, errorMessage }: {labelContent: string, inputs: JSX.Element[], errorMessage: string}) => {
label, input, error, helper text 등 인풋의 주요 구성 요소를 모아둔 컴포넌트는 대개 `Field`라는 네이밍을 많이 쓰고는 합니다.

2024-04-19 00:44 UTC, igy95 commented on src/components/Form/UserNameForm.tsx
> +    const regex = /^[A-Z\s]{1,30}$/;
1, 30에 대해서 상수처리를 해보면 좋겠네요!

2024-04-19 05:16 UTC, ImxYJL commented on src/components/Card/CardLogo.tsx
> +  }
무의식적으로 undefined 요소에 length를 호출하면 에러가 날 거라고 생각했는데, 없어도 잘 동작하네요 😅 불필요한 체크인 것 같아 삭제하도록 하겠습니다!

2024-04-20 13:07 UTC, ImxYJL commented on src/components/Card/CardLogo.tsx
> +  let cardType = "";
카드사 판별 로직을 별도로 분리하고, 그에 맞춰 알맞은 카드사 타입을 바로 리턴하게 리팩토링했습니다!

2024-04-20 13:41 UTC, ImxYJL commented on src/components/Card/ExpirationDate.tsx
> +          )}
여기서 구조 분해 할당을 생각하지 못하다니... 아직도 JS에 익숙하지 않나 봅니다 😂

말씀해주신 방법대로 리팩토링을 시도하니까 두 가지 방법이 떠올랐는데, 일단 두 번째 방법이 더 적용하기 쉬워서 그렇게 고쳐둔 상태입니다. 첫 번째 방법은 어떻게 생각하시는지 궁금합니다!

1. `Input` 컴포넌트에 key를 전해줄 때부터 용도에 맞는 이름을 부여하기: 단순한 숫자 인덱스를 사용하지 않고 상위 요소인 `ExpirationDateForm` 컴포넌트에 별도의 key 배열을 둬서 렌더링해 처음부터 특정 key 이름을 사용할 수 있게 제작

2. Input 렌더링할 때는 숫자 인덱스를 사용하되 사용하는 측에서 별도로 이름을 지정해서 사용하기
```ts
const month = expirationDate.get("0");
const year = expirationDate.get("1");

...

{month && (
        <ExpirationDateStyled>
          {month}/{year && <ExpirationDateStyled>{year}</ExpirationDateStyled>}
        </ExpirationDateStyled>
)}
```

2024-04-21 02:31 UTC, ImxYJL commented on src/components/Card/ExpirationDate.tsx
> +  });
이렇게 계속 최신값을 계산해야 하는 방식이 번거로운 것 같아 입력값을 저장하는 자료구조를 Map으로 변경했습니다!

2024-04-21 02:53 UTC, ImxYJL commented on src/components/Form/Input.tsx
> +  index: string;
Input을 생성해 줄 때 각 Input에서 가져온 값을 구분해야 할 필요가 있다고 생각해서 인덱스를 부여해줬습니다. Props로 index 정보를 받지 않는다면 Input 내부에서 자신이 몇 번째 Input인지 알아내야 할 것 같은데 그렇게 하는 방법은 떠오르지 않아서 props로 넘겼습니다.

2024-04-21 02:57 UTC, ImxYJL commented on src/components/common/FormElement.tsx
> +const FormElement = ({ labelContent, inputs, errorMessage }: {labelContent: string, inputs: JSX.Element[], errorMessage: string}) => {
이 컴포넌트 네이밍을 고민했는데 역시 가장 대중적인 네이밍 방식을 따르는 것이 좋다고 생각해서 수정했습니다 ~!

2024-04-21 06:25 UTC, ImxYJL commented on src/components/Card/CardLogo.tsx
> +    .find((item) => item.index === "0");
받아온 데이터를 직접적으로 수정하지 않는다면 괜찮은 것으로 알고 있는데, 제가 놓친 부분이 있는지 궁금합니다!

2024-04-21 08:14 UTC, ImxYJL commented
안녕하세요 카일! 피드백 주신 부분들 개선해서 다시 PR 요청드립니다.
코멘트에 있는 질문들도 확인해주시면 감사하겠습니다!

storybook 배포도 완료했습니다.
> storybook 배포 링크: http://localhost:6006/?path=/story/app--default


## 주요 변경사항

- 상수화
    - **card**: `CardPreview` 컴포넌트에서 사용하는 상수들을 모았습니다.
    - **form**: 폼 컴포넌트에서 사용하는 상수들을 각 컴포넌트별로 모아 상수화했습니다.
- 중간 인터페이스 삭제
    - 기존 `ICardInfo` 인터페이스를 삭제했습니다.
- input 입력 정보를 담는 자료형을 (state로 사용하는 자료형) Map으로 변경
    - Map이 잦은 접근, 수정에 가장 적합한 자료구조라고 판단
    - Input에 전달되는 index (props)를 number에서 string으로 변경
        - 인덱스 정보를 꼭 number로 저장해야 할 이유가 없음
        - 이제 (상위)자료구조가 배열이 아니므로 string을 고집할 필요가 없음
        - 추후 백엔드/웹 통신을 통해 데이터가 가공된다면 number가 계속 string으로 변환되므로 불필요한 작업이 증가할 것이라고 생각
        
        상기한 이유로 index가 string인 것이 더 맞다고 판단해 수정했습니다.
        

- 그 외 자잘하게 피드백 주신 부분들을 개선했습니다.

## 질문

- 코멘트에 달아둔 질문 외의 내용입니다!
- `CardLogo`에서 카드사 식별 로직을 별도의 함수로 분리했습니다. 이때 이 함수를 `CardLogo` 함수 안에 두어야 할지, 전역에 두어야 할지 고민이 됐습니다. 보통 컴포넌트 함수에 이런 (state처럼 갖고 있어야 하는 정보가 아니라 상수에 가까운) 보조 로직을 모두 담는 편인지 궁금합니다.

- 자료구조를 Map으로 변경한 다음 스토리북 리팩토링을 진행했는데, 스토리북의 `args`가 Map 객체는 지원하지 않는다는 걸 그제서야 알게 됐습니다. 이렇게 프로덕트와 다른 도구들이 충돌하는 경우에 그냥 프로덕트 코드를 수정해야 하나요?

- 일단 자료구조를 Map으로 변경하긴 했지만 정보를 Map으로 저장하는 것이 과연 옳은 선택인지 의구심이 들었습니다. 추후 서버와 통신할 때 대개 JSON으로 데이터를 주고받을 텐데 그렇다면 별도의 변환 작업이 필요한 Map보다 일반 Object를 사용하는 것이 더 호환성 측면에서 올바른 판단일지 궁금합니다.

2024-04-21 09:21 UTC, igy95 approved these changes
안녕하세요 올리~ 리뷰 코멘트가 꽤 많았음에도 잘 대응해주셨네요! 추가적인 코멘트 확인 부탁드리고 질문에 대한 답변 남기고 마무리하겠습니다. 다음 단계에서 뵈어요!

> CardLogo에서 카드사 식별 로직을 별도의 함수로 분리했습니다. 이때 이 함수를 CardLogo 함수 안에 두어야 할지, 전역에 두어야 할지 고민이 됐습니다. 보통 컴포넌트 함수에 이런 (state처럼 갖고 있어야 하는 정보가 아니라 상수에 가까운) 보조 로직을 모두 담는 편인지 궁금합니다.

분리하는 건 적절해 보이나, 분리된 로직이 노출된 범위를 무조건적으로 전역으로 두는 것은 권장하지 않는 방향입니다. (아마 함수 외부를 전역으로 표현하신 거겠죠?) 컴포넌트 내의 로직은 컴포넌트가 호출될 때마다 같이 선언되기 때문에 컴포넌트 내의 의존성과 강하게 결합되어 있지 않다면 가독성 측면까지 고려하여 외부로 분리해주면 좋을 듯 하네요!

> 자료구조를 Map으로 변경한 다음 스토리북 리팩토링을 진행했는데, 스토리북의 args가 Map 객체는 지원하지 않는다는 걸 그제서야 알게 됐습니다. 이렇게 프로덕트와 다른 도구들이 충돌하는 경우에 그냥 프로덕트 코드를 수정해야 하나요?

어떤 도구를 사용하든 실제 사용자에게 보여질 프로덕트의 코드가 우선이라고 생각하며 맞춰야 한다면 도구 쪽에서 맞추는 것이 맞다고 생각합니다. 현재는 구체적인 코드가 없어서 리팩터링의 방향을 제안드리기 어려우나, 스토리북과 컴포넌트 사이에 중간 레이어를 두어 자료구조를 적절히 변환시킬 수 있는 방법은 없을지 고민해 볼 것 같네요.

> 일단 자료구조를 Map으로 변경하긴 했지만 정보를 Map으로 저장하는 것이 과연 옳은 선택인지 의구심이 들었습니다. 추후 서버와 통신할 때 대개 JSON으로 데이터를 주고받을 텐데 그렇다면 별도의 변환 작업이 필요한 Map보다 일반 Object를 사용하는 것이 더 호환성 측면에서 올바른 판단일지 궁금합니다.

우선 코드를 먼저 적용하고 트레이드 오프를 고려하는 건 순서가 바뀌었다고 생각합니다. 말씀 주신 부분은 성능과 로직의 복잡성 간 비교를 해볼 수 있을 듯 한데요. 현재의 사이즈에서 객체와 Map 자료 구조의 성능을 따질 만큼 크고 복잡한 모델을 다루고 있지는 않다고 봅니다.

따라서 이 부분은 로직을 좀 더 효율적으로 작성할 수 있는 쪽으로 고려해보면 어떨까 싶네요!

2024-04-21 09:22 UTC, merged

2024-04-21 12:59 UTC, ImxYJL commented on src/components/Card/ExpirationDate.tsx
> +  });
저는 처음에 props가 변한다 -> 재렌더링이 이루어진다 -> 그러니까 매 렌더링 때마다 최신 props 정보를 가져오는 게 당연한 거 아닌가? 라고 생각했는데, 찾아보니까 재렌더링은 자신의 props가 변하지 않더라도 다양한 상황에서 이루어질 수 있다는 걸 알게 되었습니다. 
이렇듯 자신의 props 변경 외에도 다양한 재렌더링 트리거가 있으니 메모 등을 사용해서 최적화하라는 맥락으로 말씀하신 것 같은데 제가 이해한 내용이 맞는지 궁금합니다~!

2024-04-21 13:06 UTC, ImxYJL commented on src/components/Form/Input.tsx
> +  index: string;
아래처럼 현재 Input에서는 props로 받은 set 함수를 통해 자신의 인덱스 정보(key)와 함께 입력값 정보(value)를 세팅해주고 있기 때문에 Input에 index 정보를 넘겨주었습니다. 이렇게 만들었던 이유는 각 인풋의 인덱스 정보가 있어야 몇 번째 카드 번호를 입력한 것인지 (입력란이 총 4개이므로) 상위 컴포넌트에서 바로 알 수 있다고 생각했기 때문입니다. 
하지만 Input의 책임이 과한 것 같기도 한데, 그러면 역시 다른 방식을 고안해야 할까요?!
 
``` ts
 const inputChangeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
    const currentValue = e.target.value;

    ....

    setData((prevCardNumbers) =>
      new Map(prevCardNumbers).set(index, currentValue)
    );

   ...
```