[2단계 - 페이먼츠] - 버건디(전태헌) 미션 제출합니다.
woowacourse/react-payments pull request #371
Opened 2024-04-25 12:15 UTC by brgndyy

(배포중...)

2024-04-25 22:53 UTC, brgndyy commented on src/stories/RegisterCardNumber.stories.tsx
> +  },
이번에 카드넘버를 부모 컴포넌트에서 `ref` 4개를 만들어서 `RegisterCardNumber`에게 props로 넘겨주고, 

`RegisterCardNumber` 컴포넌트에서  받아서 map함수로 뿌려주면서 input 컴포넌트를 총 4개 만들어주는데요..! 

이렇게 되니까 스토리북을 작성할때 ref를 props로 전달해야해서 이런식으로 스토리를 작성하게 되더라구요.

근데 이런식으로 스토리를 복잡하게 작성하는게 맞는건가? 라는 의구심이 들었습니다.

`스토리북을 작성하기 힘들다.`라는 것이 컴포넌트 자체가 독립적으로 존재하지 않는다. 즉 의존성이 많다. 라는 것으로 느껴지기도 합니다. 

이렇게 되면 아예 `useCardNumbers` 커스텀 훅 자체를 변경해주어서 설계를 뒤바꾸어주어야 할것 같다고 판단이 드는데요.

하루의 생각 한번 여쭤보고 싶습니다!

2024-04-25 22:53 UTC, brgndyy commented on src/hooks/useInput.ts
## - 책임이 작은 커스텀 훅들을 모아서 책임을 넓혀보는 것에 대한 방향성

❗️ **이번에 제일 신경쓰였던 부분입니다** ❗️

이번 미션을 진행하면서 처음에 그렸던 방향성은 가장 작은 커스텀 훅들이 뭉쳐지면서, 하나의 큰 커스텀 훅이 되는 것이었어요!

예를 들어서 `useInput`이라는 커스텀 훅에서는 유효성 검사를 제외하고 단순히 상태값만 받도록 하고

## - useInput

```ts
const useInput = () => {
  const [inputValue, setInputValue] = useState('');

  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const inputValue = e.target.value;

    setInputValue(inputValue);
  };

  return { inputValue, onChange };
};
```

## - usePassword.ts

```ts

const usePassword = () => {
  const { inputValue, onChange } = useInput();

  const handlePassword = (e: React.ChangeEvent<HTMLInputElement>) => {
    // 여기서 password 와의 관련된 유효성 검사를 진행
    // 그 후에 상태 업데이트나 다음 인풋 포커스나 다른 기능 수행
    onChange(e);
  };

  return {
    passwordValue: inputValue,
    handlePassword,
  };
};
```

이런식의 흐름을 원했었는데, 어차피 이 안에서 다음 포커스를 넘겨주어야하고, 다음 스텝(카드넘버 => 카드사 선택)을 렌더링 해주기 위해서는 인자를 넣어줄수 밖에 없지 않나? 라는 생각이 들었습니다.

즉, 작은 커스텀훅들을 모아서 책임이 큰 훅으로 점진적으로 넓혀가는것이 정말 재사용성이 있나? 라는 생각이 들었던거 같아요 

그래서 현재  단일 인풋값을 체크해주어야할때는 `useInput` 하나로 재사용을 해준 상태인데요.

이 커스텀 훅내에 들어가는 인자가 많은거 같다는 생각도 듭니다.

------

저는 결국 단일 인풋값을 다룰때, 

1. 값을 입력한다.
2. 유효성 검사를 해준다.
3. maxLength 에 충족할때까지 정상적인 값을 입력한다면 다음 스텝으로 인풋 포커싱을 옮겨준다.

같은 거시적인 큰 틀의 기능이 같다고 판단해서 이렇게 구현해준것인데요.

하지만 자세히 살펴보면 각각의 유효성 검사가 다르다보니, 그냥 각각 섹션에 대한 커스텀훅을 따로따로 만들어주는게 코드 가독성이 더 높을까.. 라는 생각도 들어요

키워드로 따져보면, `코드 가독성 vs 재사용성` 이라고 말씀드려볼수 있을거 같습니다! 

하루의 의견 한번 여쭈어보고 싶어요! 제가 놓치고 있는 부분이 있다면, 짚어주신다면 새겨듣고 배우겠습니다 🙇

2024-04-26 03:28 UTC, brgndyy commented on src/App.tsx
> +  const handleNavigateToConfirmPage = () => {
해당 함수 같은 경우, 아예 `ConfirmButton` 이라는 컴포넌트를 하나 만들어준다음에, 거기 props 로 isSucceed, cardNumbers, cardIssuer 값을 props로 넘겨주고 해당 컴포넌트내 에서 핸들러 함수를 정의해줄까 했는데요..!

단순히 가독성을 위해 props로 3개의 값을 내려주어서 사용한다는 것 자체가 조금 더 비효율적이라고 판단해서, App 단에서 선언을 해주었습니다!

혹시 아예 props로 state 값들을 내려주어서 핸들러 함수를 내부에서 정의해주는것이 나을까요 ?

잘못 짚고 있는 점이 있다면, 말씀 주시면 감사하겠습니다! 🙇

2024-04-26 15:44 UTC, 365kim commented on src/components/composables/Select.tsx
> +const Select = forwardRef<HTMLSelectElement, PropsWithChildren<SelectProps>>((props, ref) => {
(Select 쪽 피드백 남기려고) 이 컴포넌트를 사용하는 곳을 찾아보려고 했었는데, 지금은 사용되지 않고 있는 것 같네용 혹시 활용해주실 예정인 걸까용?

2024-04-26 15:47 UTC, 365kim commented on src/components/composables/Select.tsx
> +}
![image](https://github.com/woowacourse/react-payments/assets/60066472/29748e5c-9d4c-4b27-a692-2bd4cfbe3a1c)

(사용하지 않는 코드이지만 참고차 코멘트 남겨보아용) extends 해주신 타입 안에 이미 onChange가 있어서 재정의하지 않아도 될 것 습니당 아니면 required로 만들고 싶으셨던 걸까용 🤔 ?

2024-04-26 15:50 UTC, 365kim commented on src/constants/cardSection.ts
>    description: '월/년도(MMYY)를 순서대로 입력해 주세요.',
저도 1단계 때 놓쳤던 것 같은데 🙏🏻 `MMYY`이 아닌 `MY` 으로 입력해도 유효성 검사를 통과하는 것 같네요,

MM을 입력하려면 `01`, `02` 등도도 입력가능해야하는데 이것도 막혀있더라고요. 이미 2단계이지만 그래도 개선해볼 수 있을까요?

<img src="https://github.com/woowacourse/react-payments/assets/60066472/14bbfb0c-686e-4798-8c15-ac58590c7558" width="300"/>

2024-04-26 15:52 UTC, 365kim commented
(내일점심 햄)버건디, 2단계 빠르게 제출해주셨네요! 👍 리뷰는 내일 점심전후로 이어서 진행할게요 조금만 기다려주세용 🙌

2024-04-27 03:43 UTC, 365kim commented on src/components/cards/creditCard.style.ts
사소한데 이 파일은 `cards.style.ts`가 되어야할 같습니당 혹은 

- index.style.ts -> 카드 공통 스타일
- CreditCard.style.ts -> CreditCard 컴포넌트 스타일
- CvcCard.style.ts -> CvcCard 컴포넌트 스타일 

이렇게 나누어 관리하면 어떨까요? 그러면 스타일 변경사항이 생겼을 때 어디를 변경해야할지 더 빠르게 탐색할 수 있을 것 같습니당

2024-04-27 03:47 UTC, 365kim commented on src/components/composables/Input.tsx
> +  ({ value, onChange, type, placeholder, id, isError, maxLength, onKeyDown, onBlur }, ref) => {
`fowardRef`를 사용해주셨군요 👍 

`ref` 는 왜 다른 prop이랑 다르게 특별히 `forwardRef` 를 통해서 전달해야할까요? 한번쯤 생각해보면 좋을 것 같아 코멘트 남겨보아용

2024-04-27 03:49 UTC, 365kim commented on src/components/composables/Button.tsx
> +}
![image](https://github.com/woowacourse/react-payments/assets/60066472/9409e18b-69d2-4177-bddd-e6d17d19bfd3)

`ButtonHTMLAttributes<HTMLButtonElement>`에 이미 포함된 `children`을 그대로 사용하면 어떨까요? 혹은 text로 재정의하려면 children을 Omit처리해주시면 좋을 것 같습니다 :)

2024-04-27 03:54 UTC, 365kim commented on src/hooks/useCardIssuer.ts
> +    }
단순 궁금) 필요 시 next에 focus를 해주는데 current에 blur를 미리 해줄 필요가 있나용?

2024-04-27 04:01 UTC, 365kim commented on src/hooks/useRegister.tsx
> +  );
`stepIndex`라는 상태를 관리하는데, `currentIndex`를 꼭 여기서 다시 계산해주어야하는 이유가 있을까용?

2024-04-27 04:07 UTC, 365kim commented on src/hooks/useCardIssuer.ts
> +  const [backgroundColor, setBackgroundColor] = useState('');
가벼운 제안입니다. `cardIssuer`를 업데이트할 때, 항상 `bgColor`도 업데이트한다면 하나로 묶어서 관리해도 좋을 것 같아요. 상수에서도 두 값이 하나로 묶여서 관리되고 있네용

```ts
const [cardIssuer, setCardIssuer] = useState({ name: '', bgColor: '' });
```

그러면 `setCardIssuer(foundCardIssuer);` 이렇게 한번만 업데이트 해주면 될 것 같습니당

2024-04-27 04:07 UTC, 365kim commented on src/hooks/useCardIssuer.ts
> +import INITIAL_CARD_ISSUER_INFO from '../constants/initialCardIssuerInfo';
단순궁금) 이 상수의 네이밍에 INITIAL이 포함된 이유가 궁금합니다 :)

2024-04-27 04:08 UTC, 365kim commented on src/hooks/useCardIssuer.ts
> +  const [isCompleted, setIsCompleted] = useState(false);
혹시 `isCompleted`는 별도 상태로 관리하지 않는 방법도 가능할까요?

```ts
  const [cardIssuer, setCardIssuer] = useState('');
  const isCompleted = Boolean(cardIssuer);
```

2024-04-27 04:10 UTC, 365kim commented on src/hooks/useRegister.tsx
> +  const [stepIndex, setStepIndex] = useState(0);
역시 비슷한 피드백인데. `stepIndex`만을 상태로 관리하고 currentStep(step)은 `stepIndex`를 통해 계산하는 방법도 가능할까요? 

```ts
const { stepIndex } = useRegister();
const currentStep = steps[stepIndex];
```

2024-04-27 04:15 UTC, 365kim commented on @types/global.d.ts
이 타입정의 파일 안에 들어간 타입들은 전역적(global)으로 사용되는 타입은 아닌 것 같은데 버건디의 생각은 어떠신가용~!

2024-04-27 04:16 UTC, 365kim commented on src/pages/confirm/ConfirmPage.tsx
> +  };
변수명 맛집 👍

2024-04-27 04:20 UTC, 365kim commented on src/pages/confirm/ConfirmPage.tsx
> +  const cardIssuer = state?.cardIssuer ?? '기본 카드 발급자';
`'기본값'`, `'기본 카드 발급자'`와 같은 값이 기본값으로 들어가 있는게 어색해보여서 살펴보게 되었는데용 (아마 평생 노출되지 않을 레이블 같아서..?)

state 값 없이 ConfirmPage에 도달하는게 가능한게 아니라면 12행 직후에 바로 NotFoundPage를 렌더링하도록 하면 어떨까요?

```tsx
if (!state || !state.isSucceed) {
  return <NotFoundPage />
}
```

2024-04-27 04:20 UTC, 365kim commented on src/pages/notFound/NotFoundPage.tsx
> +export default function NotFoundPage() {
엣지 케이스 챙겨주셔서 너무 좋네용 👍

2024-04-27 04:28 UTC, 365kim commented on src/main.tsx
> +]);
ConfirmPage 내부에서 다시금 'Global'Style을 주입해주어야하는 이유가 궁금해서 살펴보다가 여기를 보게 되었어요.
현재 App은 다른 'Page'와 같은 위계이기도 하고, '카드 등록' 이라는 앱의 매우 구체적인 기능을 모두 직접 관리하고 있어보여요.

```
현재
- App(카드등록폼✅) 
- ConfirmPage
- NotFounPage
```

App은 위계 상에 최상위에 배치하고, `<GlobalStyles />`도 App에서 한번만 넣어주도록 개선해볼 수 있을까요?

```
제안
- App - 글로벌스타일
  - AddFormPage(카드등록폼✅) 
  - ConfirmPage
  - NotFounPage
```

2024-04-27 04:34 UTC, 365kim commented on src/hooks/useDetectComplete.ts
> +    setIsValidAllFormStates(false);
사소한데 이렇게 작성하면 분기문을 생략할 수 있을 것 같아요

```ts
const isAllFilled = ...

setIsValidAllFormStates(isAllFilled)
```

2024-04-27 04:37 UTC, 365kim commented on src/hooks/useDetectComplete.ts
> +  const [isValidAllFormStates, setIsValidAllFormStates] = useState(false);
```
  cardNumbers,
  month,
  year,
  cvc,
  password,
  name,
```

위의 값 모두 이미 상태로 관리되고 있으니, 이 값들을 통해 구할 수 있는 isValidAllFormStates는 상태로 관리하지 않으면 어떨까요? 그렇다면 `useDetectComplete`라는 훅이 아니라 `checkIfAllFormStateFilled`라는 단순한 함수로 관리하면 될 것 같네용

2024-04-27 04:41 UTC, 365kim commented
`index.html` html 태그의 lang 속성도 같이 살펴봐주시면 좋겠습니다 :)

2024-04-27 04:45 UTC, 365kim commented on src/App.tsx
> +            )}
버튼이 표시되면 마지막 InputSection이 가려지는 현상이 있어요. 하단에 패딩이 추가해보면 어떨까용?


https://github.com/woowacourse/react-payments/assets/60066472/0dea0bf6-3aa4-4029-9c0c-1eef18bd8b05

2024-04-27 04:48 UTC, 365kim commented on src/pages/confirm/components/ConfirmImageIcon.tsx
> +        <img src={CheckImageIcon} width={20} height={20} alt="체크 이모티콘 이미지" />
체크 표시를 피그마와 완전히 같도록 표현해볼 수 있을까요? 

또 왕사소맨인데 👉👈  시안에는 `등록 되었어요` 사이의 띄어쓰기가 없습니다. (제 실무 경험 상 띄어쓰기 변경 등 단순 문구 개선 건으로 재배포를 하는 경우도 있었습니다.)

| 개발 | 피그마 |
| --- | --- |
|  ![image](https://github.com/woowacourse/react-payments/assets/60066472/6274cce1-05dc-4b44-8567-44ab29b10241) |  <img width="365" alt="image" src="https://github.com/woowacourse/react-payments/assets/60066472/713bc05f-5a84-4b69-8be9-f3975c983009"> |

2024-04-27 04:50 UTC, 365kim commented on src/pages/error/ErrorPage.tsx
> +export default function ErrorPage() {
👍

2024-04-27 04:51 UTC, 365kim commented on src/pages/error/ErrorPage.tsx
> +      <button onClick={handleClickBackButton}>되돌아가기</button>
나중에는, 이전 지면으로 돌아갈 경우 다시 에러가 발생해서 무한 루프에 빠지는 시나리오도 고려해보면 좋을 것 같습니다 :)

2024-04-27 04:52 UTC, 365kim commented on src/stories/ConfirmPage.stories.tsx
> +import { reactRouterParameters, withRouter } from 'storybook-addon-remix-react-router';
단순 궁금) 오 이건 왜 필요한 건가요?

2024-04-27 04:54 UTC, 365kim commented on src/components/registerSection/RegisterCardIssuer.tsx
> -import Select from '../composables/Select';
참고) 개발자가 일일이 린팅을 하지 않아도 commit 단계에서 자동으로 실행되게끔 하는 방법도 있습니다.

- 추천 키워드: `husky` `pre-commit` `lint-staged`

2024-04-27 04:56 UTC, 365kim commented on src/pages/confirm/ConfirmPage.tsx
> +    navigate('/');
ConfirmPage에서 App으로 돌아오면 `//` 두 개가 쌓이게 되는데 요것도 같이 확인해주시면 좋을 것 같습니당 :)

![image](https://github.com/woowacourse/react-payments/assets/60066472/bda3d9e1-ca56-4f8c-971b-b66d5641c91a)

2024-04-27 05:11 UTC, 365kim commented on src/stories/RegisterCardNumber.stories.tsx
> +  },
오 너무 좋은 고민의 흐름이네요 👍 더 좋은 인터페이스를 위해 계속 고민하는 모습 멋져요 😎

refs는 `<RegisterCardNumber />` 하위에서 관리하고, 

`cardNumbersChangeHandler(e, { index, nextRef })`이런 식으로 핸들러에 인자로 전달하면 어떨까요?

2024-04-27 05:15 UTC, 365kim commented on src/App.tsx
> +    isValidCurrentStep: step === REGISTER_STEP.CARD_CVC,
`isValidCurrentStep`는 isActive의 의미에 가까워보이는데 맞을까요?

2024-04-27 05:16 UTC, 365kim commented on src/hooks/useInput.ts
> +  isValidCurrentStep: boolean;
`isValidCurrentStep`는 `isActive`의 의미에 가까워보이는데 맞을까요?

2024-04-27 05:18 UTC, 365kim commented on src/hooks/useInput.ts
> +  nextStepHandler?: () => void;
단순 제안) onComplete라는 네이밍은 어떠세용?

2024-04-27 05:29 UTC, 365kim commented on src/hooks/useInput.ts
아하 고민의 포인트를 이해한 것 같습니다.

> 이 커스텀 훅내에 들어가는 인자가 많은거 같다는 생각도 듭니다.

인자가 많다는 것은 책임이 많다는 것이겠지요. 질문에 적어주신 `useInput`과 달리, 현재의 `useInput`은 코드량이 꽤 되보이는데요, 이 코드를 모두 `usePassword.ts`로 보내면, 정말로 코드 가독성이 더 좋아질까 하는 생각도 드네요.

둘 중 하나만 사용하는 것이 아니라 둘 다 사용하는 방향으로 리팩터링 시도해주시면 어떨까요? useInput의 책임을 조금 덜고, 각 섹션의 특수성은 usePassword등을 통해 다루는 방향으로요.(말로는 참 쉽네요.. 🙄) 그렇게 변경했는데 useInput 없이도 코드 가독성이 좋을 것 같다고 판단되시면 그 때 아예 제거해주시면 어떨까 싶습니다 :)

2024-04-27 05:34 UTC, 365kim commented on src/App.tsx
> +  const handleNavigateToConfirmPage = () => {
큰 차이는 없는 것 같지만, 굳이 고르자면 props로 작성해주시는 것에 데이터 흐름이 더 잘 보일 것 같다는 생각이 듭니다. (개인적으로 navigate의 state는 state로만 가능할 때 쓰는 편이에요.)

2024-04-27 05:41 UTC, 365kim requested changes
안녕하세요 버건디, 
작업 잘봤습니다~! 

2단계 커밋만 잘 보이게 깔끔하게 관리해주시고 😎 기능 단위로 잘 나눠주셔서 흐름 따라가기 수월했어요 감사합니다 

역시나 요구사항에 기술되어있지 않는 시나리오까지 검토해주시는 버건디의 모습 인상적이었어요 👍👍👍 그리고 좋은 코드를 작성하기 위해 고민했던 부분 질문으로 자세히 남겨주셔서 또 좋았어요. 

코멘트 몇 가지 남겼는데 확인해주시고, 완료되시면 리뷰 재요청 부탁드릴게요~!
고생하셨습니다 :)

p.s. 버건디도 식사 잘챙겨드세요~🍔

2024-04-28 06:02 UTC, brgndyy commented on src/stories/RegisterCardNumber.stories.tsx
> +  },
헉 맞네요! 

말씀주신 방향대로 한번 수정해보았습니다.

짚어주셔서 감사합니다 하루~!

2024-04-28 09:50 UTC, brgndyy commented on src/components/composables/Input.tsx
> +  ({ value, onChange, type, placeholder, id, isError, maxLength, onKeyDown, onBlur }, ref) => {
하루 말씀 듣고

[블로그 글](https://brgndy.me/posts/ref-%EB%8A%94-%EC%99%9C-forwardRef-%EB%A5%BC-%ED%86%B5%ED%95%B4%EC%84%9C-%EC%A0%84%EB%8B%AC%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C--)

로 한번 정리해보았는데, 혹시나 더 추가할 점이나 잘못 작성한 점이 있다면 피드백 주시면 감사하겠습니다..!

2024-04-29 03:56 UTC, 365kim commented on src/components/registerSection/RegisterCardNumber.tsx
> +const RegisterCardNumber = forwardRef<HTMLInputElement, RegisterCardNumberProps>((props, ref) => {
@brgndyy 

참고) 리팩터링 하다보면 값의 네이밍 말고 타입의 네이밍을 놓치는 경우가 왕왕 생기더라고요. export하지 않고 한 모듈 안에서만 사용할 것이라면 단순하게 `Props` 로 지어주는 방법도 있습니다 :)

![Screenshot 2024-04-29 at 12 55 10 PM](https://github.com/woowacourse/react-payments/assets/60066472/07545286-0399-49b1-a1bd-8b317506c0b3)

2024-04-29 03:59 UTC, 365kim commented on src/components/composables/Input.tsx
> +  ({ value, onChange, type, placeholder, id, isError, maxLength, onKeyDown, onBlur }, ref) => {
오 학습한 내용 정리 너무 좋아요 👍

지금 내용도 충분하지만 제목 `ref 는 왜 forwardRef 를 통해서 전달해야할까 ?`의 의미를 살려 `왜` 리액트 팀에서 ref를 프롭으로 지원하지 않다가, 다시 지원하는 인터페이스로 변경하게 되었는지의 내용이 들어가도 좋을 것 같습니다 :)

2024-04-29 04:00 UTC, 365kim commented on src/hooks/useCardIssuer.ts
> +    }
@brgndyy 이 코멘트 확인부탁드려용!

2024-04-29 05:36 UTC, brgndyy commented on src/hooks/useCardIssuer.ts
> +    }
헉 수정사항은 반영해놓았는데, 코멘트를 놓쳤던거 같습니다 하루..! 불편끼쳐드려서 죄송합니다.

원래 의도는 `현재 입력을 하는 ref를 blur 해주고 다음 ref로 focus`해준다라는 절차를 그냥 정직하게 작성해본것인데요..!

말씀 듣고 보니 아예 focus만 관리해주어도 괜찮다고 생각이 들더라구요..!

근데 또 더 리팩토링 하다보니 ref 자체를 인자로 안받아도 될거 같아서 아예 이 부분을 없애주었습니다!

2024-04-29 05:37 UTC, brgndyy commented on src/hooks/useCardIssuer.ts
> +  const [isCompleted, setIsCompleted] = useState(false);
위의 커멘트처럼 아예 `isCompleted`라는 상태값 자체를 없애보았어요! 짚어주셔서 감사합니다 하루 🙇

2024-04-29 05:49 UTC, brgndyy commented on src/components/composables/Input.tsx
> +  ({ value, onChange, type, placeholder, id, isError, maxLength, onKeyDown, onBlur }, ref) => {
> 리액트 팀에서 ref를 프롭으로 지원하지 않다가, 다시 지원하는 인터페이스로 변경하게 되었는지의 내용이 들어가도 좋을 것 같습니다

이 부분 한번 더 공부해보고 추가해보겠습니다! 추가적으로 말씀 주셔서 감사해요 하루~!

2024-04-29 05:49 UTC, brgndyy commented on src/components/registerSection/RegisterCardNumber.tsx
> +const RegisterCardNumber = forwardRef<HTMLInputElement, RegisterCardNumberProps>((props, ref) => {
관련 타입들 `Props`로 변경해보았어요! 

몰랐던 부분 알려주셔서 감사합니다 하루~!

2024-04-29 07:05 UTC, brgndyy commented on src/components/registerSection/RegisterCardIssuer.tsx
> +          })}
placeholder 값을 넣어서 구현해보았어요 하루! 

제일 중요했던 부분인데, 이걸 빼먹었었네요.. 부족한 부분 많은데 양해해주시고 짚어주셔서 감사합니다 🥲

2024-04-29 08:02 UTC, 365kim commented on src/main.tsx
> +]);
오.. ErrorPage와 NotFoundPage 에서는 GlobalStyles 가 안쓰이나요? '글로벌' 인데 '일부' 페이지에만 들어가야하는 이유가 있을까요?

2024-04-29 08:02 UTC, 365kim commented on src/hooks/useDetectComplete.ts
> +  const [isValidAllFormStates, setIsValidAllFormStates] = useState(false);
아하, 그렇군요.

> 리액트적으로 사고한다. 라는 것이 저는 상태로 선언해서 관리해주어야한다. 

조금 더 짚어보자면, 이 말씀이 불필요한 값까지 상태로 선언해서 관리한다는 의미는 아니었을 것 같아요. 상태는 최소화해서 관리하는 것이 좋습니다.

다음 리액트 공식문서를 참고해보셔도 좋겠습니다.

- 참고: [React - Avoid redundant state](https://react.dev/learn/choosing-the-state-structure#avoid-redundant-state)

useEfffect를 사용하는 것이 맞나?에 대한 해소는 지난번에 추천해드렸던 [You Might Not Need an Effect](https://react.dev/learn/you-might-not-need-an-effect)를 추천드려봅니다 :)

2024-04-29 08:02 UTC, 365kim commented on src/stories/ConfirmPage.stories.tsx
> +import { reactRouterParameters, withRouter } from 'storybook-addon-remix-react-router';
오 그런데 스토리북에서 라우터가 왜 필요했을까요?

2024-04-29 08:09 UTC, 365kim commented on src/hooks/useRegister.tsx
> +  const [stepIndex, setStepIndex] = useState(0);
아하 저는 `<Register step={step}>` 대신에 `<Register stepIndex={stepIndex}>`을 생각했는데요 `function Register`에서 currentIndex를 계산하지 않고 stepIndex를 바로 사용하는 방법으로요. 제가 놓친게 있을까요?

2024-04-29 08:14 UTC, 365kim commented on src/App.tsx
> +            )}
저는 크롬 브라우저에서 375 * 667로 확인했어용!

![image](https://github.com/woowacourse/react-payments/assets/60066472/9d1d66b1-2b76-4875-937c-0fb7e33ac975)

2024-04-29 12:16 UTC, 365kim approved these changes
![image](https://github.com/woowacourse/react-payments/assets/60066472/a06da6c7-10c1-4459-8e4e-ca06d81537e5)

🔥버건디🔥, 2단계 미션 완수 축하드립니다 :)

피드백 놀랍도록 빠른 속도로 반영해주셔서 감사합니다~! 페이먼츠 2단계에서 꼭 학습해야하는 주요 개념들 하나하나 진지하게 고민하고 구현해주시는 모습 멋졌습니다 👍 학습한 내용을 블로그에 정리하는 모습도 너무 보기 좋네요 :)

리액트 첫 미션 고생하셨습니다. 다음 미션도 화이팅이에요~! 👏 👏 👏

2024-04-29 12:16 UTC, merged

2024-04-29 12:20 UTC, brgndyy commented on src/hooks/useInput.ts
와와 감사합니다!! 
잘 읽어보겠습니다 마지막까지 배움주셔서 감사해요 하루!

2024-04-29 12:34 UTC, brgndyy commented on src/hooks/useRegister.tsx
> +  const [stepIndex, setStepIndex] = useState(0);
아하 인덱스로 이예 `step`을 관리하는 부분이었군요! 

짚어주셔서 감사합니다 하루! 

`index`로만 관리하는것이 조금 더 유연성을 가질수 있겠네요..!

일단 머지 된 상태이지만, 한번 더 고심해보겠습니다!

2024-04-29 12:34 UTC, brgndyy commented on src/stories/ConfirmPage.stories.tsx
> +import { reactRouterParameters, withRouter } from 'storybook-addon-remix-react-router';
제가 설명이 충분치 못했네요..! 죄송합니다.

메인 어플리케이션 스토리 내에서, 확인 버튼을 클릭하면 라우팅이 되어야한다는 표시가 나타났어야했는데, 

해당 addon없이 구현하면 에러 페이지로 넘어가는 현상이 발생해서 설치해서 적용시켜주었습니다! 

https://github.com/woowacourse/react-payments/assets/109535991/336b9ff0-4ebf-411e-b009-d7c73520c0bd