[2단계 - 페이먼츠] - 지니(손진영) 미션 제출합니다.
woowacourse/react-payments pull request #372
Opened 2024-04-25 13:17 UTC by jinyoung234

안녕하세요 유조 :) step 2 미션 마치고 PR 남겨봅니다!

이번 미션도 잘 부탁드리겠습니다 🙇‍♀️

# 학습 목표
1.  다양한 Form 구성 요소들간의 상태를 효율적으로 관리한다.
2.  hooks API를 이용하여 상태 관리 로직을 구현한다.
3.  custom hooks를 생성하여 Form 관리 로직을 컴포넌트에서 분리하고 재사용한다.
4.  Controlled & Uncontrolled Components에 입각하여 Form을 핸들링한다.

# 배포 URL
## 스토리북
- [스토리북](https://6620c82d3a152f94d7e38f6a-ileqjmvjak.chromatic.com/)

## 앱
- [App](https://jinyoung234.github.io/react-payments)

# 실행 영상

https://github.com/woowacourse/react-payments/assets/87177577/53c0f22c-64dc-4313-bf58-3a54fcdf49b9

# 학습 목표에 따른 구현 세부 사항
## 다양한 Form 구성 요소들간의 상태를 효율적으로 관리한다.
## hooks API를 이용하여 상태 관리 로직을 구현한다.
기존 state에 complete(입력 완료)와 dropdown toggle(드롭다운을 열고 닫기) 관련 state 정도만 추가하여 step 1에서 만든 것들을 최대한 활용해보려고 했습니다.

autofocus의 경우 `useRef`와 `useEffect`를 통해 구현(useAutofocusElements, useFocus)해보고자 하였습니다. (리액트에서의 effect는 외부 상태(ex - dom api)를 동기화 하는 목적으로 사용되기 때문)

특히 ref를 다룰 때 `forwardRef`와 `ref Callback`을 활용하여 **여러 개의 input도 핸들링** 할 수 있도록 설계해보았습니다!

## custom hooks를 생성하여 Form 관리 로직을 컴포넌트에서 분리하고 재사용한다.
현재 애플리케이션의 전반적인 client state layer에 대해 custom hook을 조합하는 형태로 구현해보았습니다. (ex - `useToggle` -> `useCardBrandDropdown` -> `useCreditCardForm`)

이렇게 구조화 하면서 느꼈던 건 action(interaction) layer와 과 view layer를 명확히 구분 지을 수 있었다고 느꼈습니다. 😀

또한 `카드 브랜드`, `카드 번호`, `cvc 번호`, `유효 기간`, `소유자 이름`, `카드 비밀번호`를 각각의 관심사로 보아 만일 다른 form을 사용할 때 재사용 할 수 있다고 생각해 각각의 hook 으로 만들었습니다.

이 hook을 합친 형태인 `useCreditCardForm`을 통해 `CreditCardForm` 컴포넌트에서는 외부 변경에 영향을 받지 않고 변경이 발생한다면 `useCreditCardForm`에서 처리할 수 있도록 코드를 구성해보았습니다!

마지막으로 `useFocus`나 `useAutofocusElement`는 input element 뿐 아닌 textarea 같은 element도 사용할 수 있도록 제네릭을 추가하여 유연하게 동작할 수 있도록 구성했습니다.

## Controlled & Uncontrolled Components에 입각하여 Form을 핸들링한다.

제가 생각하는 Controlled Component와 Uncontrolled Component의 정의는 아래와 같습니다.

- Controlled Component
  - useState에 의해 상태로 관리하고 있는 컴포넌트
- Uncontrolled Component
  - useRef에 의해 관리되고 있는 컴포넌트 

저의 경우 대부분의 input 핸들링을 `controlled` 방식으로 진행 했으며, focus의 경우 `uncontrolled` 방식을 채택했습니다.

uncontrolled의 경우 리렌더링이 발생하지 않는다는 장점이 있지만 **React의 렌더링 메커니즘(가상 DOM & 파이버 아키텍처를 통한 render phase - commit phase)을 벗어난다**는 점, **DOM 연산 비용이 크다**는 점으로 인해 state를 활용해서 핸들링 했습니다.

# 참고 사항
## 스토리북
이번 미션의 경우 스토리북 보단 미션 구현에 집중한 탓에 많은 내용을 담지 못했지만 아래와 같은 항목 들을 추가해보았습니다.

- CardBrandDropdown
- PreviewCreditCard의 각 카드 brand 및 cvc 관련 story

## 폴더 구조
현재 `components/payments` 폴더 구조가 약간 바뀐 상태이며, 현재 컴포넌트의 폴더 구조는 아래와 같습니다.

```
payments
└── @cardRegister
    ├── @cardBrand
    │   ├── CardBrandDropdown
    │   ├── CardBrandTextField
    │   └── index.ts
    ├── @cardNumber
    │   ├── CardNumberInput
    │   ├── CardNumberInputs
    │   ├── CardNumberTextField
    │   └── index.ts
    ├── @cardPassword
    │   ├── CardPasswordInput
    │   ├── CardPasswordTextField
    │   └── index.ts
    ├── @creditCard
    │   ├── CreditCardForm
    │   ├── PreviewCreditCard
    │   └── index.ts
    ├── @cvcNumber
    │   ├── CVCNumberInput
    │   ├── CVCNumberTextField
    │   └── index.ts
    ├── @expiration
    │   ├── ExpirationDateInput
    │   ├── ExpirationDateTextField
    │   └── index.ts
    ├── @ownerName
    │   ├── OwnerNameInput
    │   ├── OwnerNameTextField
    │   └── index.ts
    └── index.ts

```

# 궁금한 점
## 소유자 이름에서 cvc 번호로 넘어가는 경우
이번 미션에서 가장 의문이 들었던 점 이었습니다.

현재 figma에 있는 형태는 소유자 이름을 어느 정도 입력한 상태면 cvc 번호로 auto focus가 되어야 한다고 생각해 3자 이상 입력 되었을 때 그렇게 되도록 설정했습니다.

다만, 이럴 경우 소유자 이름이 다 입력 되지 않았을 때 넘어가서 혼란스러운 상황이 발생한다고 생각했고, 카드 비밀번호는 2자리 입력이 되었을 때 확실히 넘길 수 있기 때문에 서로의 영역을 바꾸면 좋겠다는 생각이 들었는데 유조의 의견이 궁금합니다.. 🥲

## Context 도입 관련 질문
현재 대부분의 도메인 TextField 컴포넌트들이 `~textfield` - `~input` - input의 계층 형태이며, 동일한 props가 반복되는 현상을 구현하면서 목격하게 되었습니다.

지금은 `rest parameter`로 어느 정도 불편함을 제거한 상태이긴 하지만 그래도 조금 불편함을 느꼈습니다.

이런 불편함을 느꼈을 때 context를 사용할 수 있는 상황인지 궁금합니다.

2024-04-26 14:05 UTC, yujo11 requested changes
안녕하세요 지니~

빠르게 구현해서 리뷰 요청 보내주셨는데 리뷰가 조금 늦어졌네요 😅

전체적으로 깔끔하게 코드를 잘 작성해주셔서 코멘트 남길 부분이 많지 않았습니다. custom hook을 잘 사용하고 있어서 이 부분이 특히 좋았네요 👍 👍 👍

2024-04-26 14:05 UTC, yujo11 commented on src/components/common/Dropdown/provider/DropdownProvider.tsx
> +};
Provider가 없는 곳에서 호출하면 에러가 발생할텐데 그에 대한 대비도 해보시면 좋을거 같네요 !

2024-04-26 14:05 UTC, yujo11 commented on src/components/common/Dropdown/Dropdown.tsx
> +  Option: OptionType;
Menu와 Option은 각각 어떤 역할을 하고, 따로 받는 이유는 뭘까용?

2024-04-26 14:05 UTC, yujo11 commented on src/components/common/Dropdown/Dropdown.tsx
구현하기 쉽지 않은 컴포넌트였을텐데 멋지게 구현해주셨네요 👍 👍 👍 💯

2024-04-26 14:09 UTC, yujo11 commented
작성 중에 제출 되어서 이어서 남기겠습니다 🫠

>소유자 이름에서 cvc 번호로 넘어가는 경우

이렇게 정해진 입력값의 길이가 없는게  참 어려운 부분인데요. 지니가 구현한 애플리케이션을 사용했을 때 이름을 3글자만 입력하고 바로 넘어가니 조금 당황스럽기도 했습니다 ㅎㅎ  이 부분은 사용자에 따라 매번 달라지는 부분이라 자동으로 Focus가 넘어가지 않는게 오히려 좋을거 같기도 하네요

>�Context 도입 관련 질문

여러 계층에서 동일한 prop이 반복적으로 전달 되고 있다고 하면 충분히 Context를 고려해볼만한 상황이라고 생각합니다 ㅎㅎ

미션 권장 기한은 다음 미션이 시작되고 두 개의 미션을 동시에 진행하게 되면 일정이 딜레이 될 수 있기 때문에 있다고 생각하는데요. 다음 미션에 지장가지 않는 선에서 천천히 반영하고 다시 리뷰요청 주셔도 됩니다 지니!

step2 진행하느라 고생 많으셨습니다  👍 👍 👍

2024-04-26 23:13 UTC, jinyoung234 commented on src/App.tsx
> +      <Router />
오오 레퍼런스 참고하겠습니다 😀😀

2024-04-26 23:16 UTC, jinyoung234 commented on src/utils/string.ts
> +};
섬세한 리뷰 감사합니다 😀😀😀

참고해서 리뷰 반영해놓겠습니다!

2024-04-26 23:17 UTC, jinyoung234 commented on src/routes/router.tsx
> +    </BrowserRouter>
각 라우터 들의 차이점들을 더 분석했어야했는데 조금 미흡했던거 같습니다..!

creatrBrowerRouter의 특징 및 장/단점을 분석 후 리뷰 반영해보겠습니다!!

2024-04-26 23:19 UTC, jinyoung234 commented on src/pages/CardRegisterCompletePage/CardRegisterCompletePage.tsx
직접 접근 할 생각을 못했던거 같습니다 🥲🥲🥲 참고 후 리뷰 반영해놓겠습니다!

2024-04-26 23:22 UTC, jinyoung234 commented on src/pages/CardRegisterPage.tsx
> +export default CardRegisterPage;
페이지 구분을 해놓아야 관심사(page/form)가 구분 된다고 생각했습니다..!

form + 다른 컴포넌트(ex - 네비게이션 바)에 대응하고자 이런 페이지 컴포넌트가 되었는데, 너무 큰 그림을 봤나 싶기도 합니다 😅

조금 더 고민 후에 리뷰 반영 해보겠습니다!!

2024-04-27 05:51 UTC, jinyoung234 commented on src/hooks/useUUID.ts
> +  const uuids = useRef(Array.from({ length }, () => crypto.randomUUID()));
`useRef`의 경우 `useState`와 동일하게 값을 저장한다는 특징이 있습니다. 다만 state와 다르게 값을 mutate 해도 컴포넌트 리렌더링이 발생하지 않는다는 점, ref의 current 프로퍼티를 변경할 수 있다는 차이점이 있습니다.

그렇기 때문에 React 팀에서 ref를 리렌더링을 발생시키지 않지만 값을 저장해야 하는 경우(ex - timeout id, JSX를 계산하는 데 필요하지 않은 다른 객체 저장, dom element 저장 및 조작) 사용하는 것을 권장하고 있습니다.

저의 경우 `CardNumberInput` 갯수 만큼의 key prop을 관리하기 위해 배열 index 대신 각 index 별로 uuid를 사용하도록 했습니다.  

다만 컴포넌트 리렌더링이 발생할 경우 이 값이 다시 랜덤 값으로 초기화 되기 때문에 리렌더링 마다 random id 값이 달라지는 문제점이 있었습니다.

즉, 컴포넌트 리렌더링을 발생시키지 않지만 값을 저장해야 하는 경우라고 판단되어 ref로 관리하게 되었습니다!

2024-04-27 07:19 UTC, jinyoung234 commented on src/hooks/useMovePage.ts
custom hook을 만드는 이유 중엔 관심사의 분리도 있지만, hook을 작은 것부터 조합해서 쓰고자했기 때문에 지금은 큰 차이가 없더라도 여러 컴포넌트에서 비슷한 로직을 작성한다면 중복 제거가 가능하며, 확장성 측면에서 이점이 있다고 생각해 hook으로 분리했습니다.

2024-04-27 07:19 UTC, jinyoung234 commented on src/hooks/creditCard/useCreditCardForm.ts
도메인 별 폴더구조를 실제로 사용하기도 하는군여,,,, 참고해서 리뷰 반영해보겠습니다 :)

2024-04-27 07:20 UTC, jinyoung234 commented on src/hooks/creditCard/useChangeCVCNumber.ts
> +    if (cvcNumber.length === 3) setIsCVCNumberCompleted(true);
참고해서 리뷰 반영해놓겠습니다!

2024-04-27 07:31 UTC, jinyoung234 commented on src/components/common/Dropdown/provider/DropdownProvider.tsx
> +};
Provider가 없는 경우에서 호출하는 경우를 생각 못했네요 .. ! 코멘트 반영해놓겠습니다!

2024-04-27 07:39 UTC, jinyoung234 commented on src/hooks/useMovePage.ts
**useMovePage를 사용하기 전**
```tsx
const CardRegisterCompletePage = () => {
  const navigate = useNavigate();
  const {
    state: { cardPassword, cardBrand },
  } = useLocation();

  return (
    <div className={styles.cardRegisterCompletePageContainer}>
      <img className={styles.successCircle} src={SuccessCircle} alt="successCircle" />
      <p className={styles.cardRegisterDescription}>
        {cardPassword}로 시작하는 <br /> {cardBrand}가 등록되었습니다.
      </p>
      <Button
        onClick={() => {
          navigate('/');
        }}
      >
        확인
      </Button>
    </div>
  );
};
```

**useMovePage를 적용한 후**
```tsx
const CardRegisterCompletePage = () => {
  const {
    state: { cardPassword, cardBrand },
  } = useLocation();

  const handleMoveRootPage = useMovePage(ROUTE_ENDPOINT_MAP.root);

  return (
    <div className={styles.cardRegisterCompletePageContainer}>
      <img className={styles.successCircle} src={SuccessCircle} alt="successCircle" />
      <p className={styles.cardRegisterDescription}>
        {cardPassword}로 시작하는 <br /> {cardBrand}가 등록되었습니다.
      </p>
      <Button onClick={handleMoveRootPage}>확인</Button>
    </div>
  );
};
```
또한, 사소한 차이이지만 사용하기 전보다 후의 코드가 더 깔끔하다고 느끼기도 했습니다!

2024-04-27 07:45 UTC, jinyoung234 commented on src/components/common/Dropdown/Dropdown.tsx
> +  Option: OptionType;
<img width="628" alt="image" src="https://github.com/woowacourse/react-payments/assets/87177577/1eccc4b6-e41b-45e3-98e4-c2e7870c4d0e">

Menu는 Dropdown 컴포넌트 내 OptionList의 역할을 수행하며, Option은 Menu의 Item 컴포넌트라고 이해하시면 편하실거 같습니다!

따로 받는 이유는, Menu의 역할과 Option의 역할이 엄연히 다르다고 생각했기 때문입니다.

제가 생각할 때 `Menu`는 `Option` **들을 보이게 하는 책임**을 가지며, `Option`은 **사용자가 hover 했을 때**와 **사용자가 클릭했을 때의 interaction을 담당하는 컴포넌트**라고 생각했기 때문에 **서로 다른 관심사를 분리하는 것이 필요**하다고 느꼈습니다.

2024-04-28 08:31 UTC, jinyoung234 commented on src/hooks/creditCard/useCardBrandDropdown.ts
> +  const [cardBrand, setCardBrand] = useState<CardBrand | ''>('');
일단 undefined의 경우 값을 선언이 되었지만 할당이 되지 않은 case의 값이기 때문에 현재의 상황과 맞지 않다고 생각했습니다.

또한, empty String으로 설정한 이유는 현재 cardBrand가 전체적으로 string의 형태를 띄고 있기 때문에, 초기 브랜드가 empty string으로 설정 후 카드 브랜드와 관련된 string으로 변경되는게 자연스럽다고 생각했습니다.

empty string과 null의 가장 큰 차이라면 nullable한 값과 falsy한 값을 비교할 수 있다는 차이점이 있지만 현재 상황에서 크게 중요하지 않은 부분이라 생각해 empty string으로 적용했습니다.

유조가 질문 주신 의도와 어떤 방향이 올바른지에 대해 여쭤보고 싶습니다 😀

2024-04-28 13:03 UTC, jinyoung234 commented
@yujo11 안녕하세요 유조 :) step 2 작업 마친 후 PR 남겨봅니다!

# step 2 반영 사항
## string.ts
- generateUpperCase의 함수명을 convertPascalCase로 변경 후 단위 테스트를 진행했습니다. (number.ts도 마찬가지)
   - 테스트 툴은 vite를 사용하는 만큼 테스트 코드만을 위한 별도의 설정 없이, 프로젝트의 기본 빌드 설정을 그대로 이용할 수 있다는 장점이 있어 vitest를 통해 약간의 단위 테스트 코드를 추가했습니다.
        - [chore: vitest 의존성 추가](https://github.com/woowacourse/react-payments/pull/372/commits/5147c070b9390a6a8f1a52a659c230053d34d947)
        - [refactor(string): 함수명 변경](https://github.com/woowacourse/react-payments/pull/372/commits/9c811dbe943fc6b39cc2759a1744e80b0a87dbb3)
        - [test(string): convertPascalCase에 대한 단위 테스트 작성](https://github.com/woowacourse/react-payments/pull/372/commits/aa2a894416027c75c4315c265cfc33336fa037d8)
        - [test(number): 숫자가 아닌 값의 포함 여부에 대한 단위 테스트 추가](https://github.com/woowacourse/react-payments/pull/372/commits/15246aeb134833900afeac35d3793957c41b9072)

## router.tsx
- 코멘트 주신 BrowserRouter에 대해 BrowserRouter와 createBrowserRouter의 차이점을 비교하며 `사용해야 할 이유`에 대해 고민해보았습니다.
   - 1. loader를 통해 각 라우팅 경로마다 렌더링 전 `loader`함수를 정의함으로써 경로 요소에 데이터를 제공이 가능합니다.
   - 2. errorElement나 ErrorBoundary를 통해 라우팅 중 잘못 되었을 때 렌더링 되는 Element를 정의할 수 있습니다. (렌더링 되어야 할 페이지에서 오류 발생 or loader에서 오류 발생, action에서 오류 발생, 이상한 주소로 이동하는 case)

저는 2번 상황에서 `404` 에러 및 `임의 접근` 시 **예상과 다른 동작을 대처할 수 있다고 생각해 createBrowserRouter로 변경**해보았습니다.

- CardRegisterCompletePage 내부에서 useLocation 내 state가 null일 경우 fallback이 보여지도록 리팩터링 해보았습니다. (임의로 접근 시 방지하기 위함)
   - [fix: 임의 접근 및 404 에러 발생 시 github pages 내 제공하는 fallback page가 보이는 문제 해결](https://github.com/woowacourse/react-payments/pull/372/commits/9816ebed17776e30ca029ca7ef719ad41762238b) 
[9816ebe](https://github.com/woowacourse/react-payments/pull/372/commits/9816ebed17776e30ca029ca7ef719ad41762238b)
   - [fix: github pages에서 404 및 임의 접근 url 오류 해결](https://github.com/woowacourse/react-payments/pull/372/commits/d0190f7f70e14a281ff7ea88feece0c86b9a456d)
   - [fix: fallback page에서 <br/>이 보이는 부분 수정](https://github.com/woowacourse/react-payments/pull/372/commits/343cbb755a477092aef58cab3a2cb6099810e1b9)

## useChangeCVCNumber.ts
- 매직 넘버를 상수로 분리해보았습니다.
  - [fix: 소유자 이름이 3자일 경우 cvc 번호 입력 필드가 보이는 현상 수정](https://github.com/woowacourse/react-payments/pull/372/commits/9abb296edbdd06accec06d055088a2950dc7bb34)

## DropdownProvider.tsx
- Provider 내부에서 호출 시 에러가 발생하는 경우에 대해 대비해보았습니다.
    - [refactor(useDropdownContext): provider 내부에서 사용할 때 error를 발생시키도록 변경](https://github.com/woowacourse/react-payments/pull/372/commits/db42237f30bbf865b6a969d2ed0d36da4a235a32)
## etc
- OwnerNameInput에서 keydown 이벤트를 통해 enter를 입력했을 때 다음 cvc 필드가 보여지도록 코드를 수정했습니다.
   - [fix: 소유자 이름이 3자일 경우 cvc 번호 입력 필드가 보이는 현상 수정](https://github.com/woowacourse/react-payments/pull/372/commits/9abb296edbdd06accec06d055088a2950dc7bb34)

2024-04-28 15:10 UTC, yujo11 commented on src/hooks/creditCard/useCardBrandDropdown.ts
> +  const [cardBrand, setCardBrand] = useState<CardBrand | ''>('');
어떤 배경을 가지고 코드를 작성했는지 궁금해서 남긴 부분이었습니다 ㅎㅎ

2024-04-28 15:16 UTC, yujo11 approved these changes
안녕하세요 지니~

코멘트로 남긴 내용들 꼼꼼하게 확인하고 빠르게 반영해주셨군요 👍 👍 👍 

이번 미션은 여기서 merge해도 좋을거 같습니다! 추가로 코멘트 남긴 내용들은 한번 확인해보시면 좋을거 같아요!

앞으로의 미션들도 응원하겠습니다 고생 많으셨어요~~ 👍 👍 👍

2024-04-28 15:16 UTC, yujo11 commented on package.json
> +    "vitest": "^1.5.2"
오 vitest 좋네요 ㅎㅎ 👍 👍 👍

2024-04-28 15:16 UTC, yujo11 commented on src/utils/string/string.ts
> +export const convertPascalCase = (string: string) => {
👍 👍 👍

2024-04-28 15:16 UTC, yujo11 commented on src/utils/string/string.test.ts
크 테스트 코드 완전 좋군요 ㅎㅎ 👍 👍 👍

2024-04-28 15:16 UTC, yujo11 commented on src/utils/number/number.test.ts
👍 👍 👍 💯 💯 💯

2024-04-28 15:16 UTC, yujo11 commented on src/pages/CardRegisterCompletePage/CardRegisterCompletePage.tsx
에러에 대한 분기 처리를 하셨군요 ㅎㅎ 👍

2024-04-28 15:16 UTC, yujo11 commented on src/pages/CardRegisterCompletePage/CardRegisterCompletePage.tsx
> +  const { state } = useLocation();
useLocation에서 state를 받아오면 새로고침이나 바로 접근 시 state를 받아올 수 없는 문제가 있는데요.

이런 문제를 어떻게 해소할 수 있을지에 대해서도 찾아보시면 좋을거 같습니다 ㅎㅎ

2024-04-28 15:16 UTC, yujo11 commented on index.html
> +<html lang="ko">
👍 👍 👍

2024-04-28 15:16 UTC, yujo11 commented on src/components/common/Dropdown/provider/DropdownProvider.tsx
> +  }
👍 👍 👍

2024-04-28 15:16 UTC, merged