[2단계 - 페이먼츠] - 파슬리(김윤아) 미션 제출합니다.
woowacourse/react-payments pull request #373
Opened 2024-04-26 07:41 UTC by anttiey

안녕하세요, 호프! 🍀 많이 부족하지만 2단계 미션 기능 구현을 완료하게 되어 PR 남깁니다 🌱

# 👩🏻‍💻 개요

첫 번째 미션 `페이먼츠` 2단계 hooks & state 코드입니다.

### 배포 페이지
> [배포 페이지](https://anttiey.github.io/react-payments/)

> [스토리북 배포 페이지](https://anttiey.github.io/react-payments/storybook/)

### 실행 방법
```javascript
npm install

// 로컬 환경 실행
npm run dev

// 스토리북 실행
npm run storybook
```

## 📚 기능 요구 사항 & 해결 과정
### 기능 요구 사항
- [ ] 다양한 Form 구성 요소들간의 상태를 효율적으로 관리한다.
- [ ] hooks API를 이용하여 상태 관리 로직을 구현하한다.
- [ ] custom hooks를 생성하여 Form 관리 로직을 컴포넌트에서 분리하고 재사용한다.
- [ ] Controlled & Uncontrolled Components에 입각하여 Form을 핸들링한다.

### 1. 컴포넌트 구조
<img width="971" alt="스크린샷 2024-04-26 오후 3 56 40" src="https://github.com/woowacourse/react-payments/assets/61104776/3aa8e3b0-90d8-4546-9d23-0efe55a19ee8">

<br />
<br />

- 1단계에서 구현한 공통 컴포넌트를 확장해 추가적인 컴포넌트를 생성하고, 이를 바탕으로 페이지 컴포넌트를 구성했습니다.

### 2. Custom Hook
- 폼 관리 로직을 `Custom Hook` 으로 분리하여 최대한 UI 로직과 분리해서 관리해 볼 수 있도록 노력했습니다. 
- 대표적으로 사용자를 통해 입력 받는 카드 정보 상태 관리 로직을 `useInput` `useInputs` 으로 분리하여 반복되는 로직을 줄일 수 있도록 구현했습니다.

### 3. React Router
- `react-router-dom` 라이브러리를 사용하여 페이지 간 네비게이션을 구현했습니다.
- 모든 입력 값이 유효하게 입력되면 `확인` 버튼이 활성화되어 클릭 시 등록 완료 페이지로 이동합니다. 카드 번호 앞 자리와 카드사 정보는 크리티컬하지 않다고 판단되어 `쿼리 스트링` 으로 정보를 전달했습니다.

### 4. Storybook
이번 미션에서는 기능 구현에 집중하느라 스토리북에 크게 신경을 쓰지 못했습니다. 그래도 최대한 여러 부분에서 사용성을 개선해 볼 수 있도록 했습니다.

- 폴더 구조를 정리하여 스토리북 파일을 분리했습니다.
- 스토리북 안에서 조작할 필요가 없는 파라미터를 컨트롤 패널에서 제거하였습니다.

## ❓ 질문
### 1. Custom Hook 분리 기준
이번 미션을 진행하면서 처음으로 <b>`Custom Hook`</b> 을 사용해 보았습니다. 자주 사용되는 로직을 Custom Hook으로 관리하며 유용함을 느꼈지만, 이번 미션이 각각의 입력마다 다른 입력 조건과 유효성 검증 로직을 가지고 있기 때문에 어떤 부분까지 추상화를 해야 할지, 적정 수준의 추상화 기준을 잡기 어려웠습니다. 결국 현재는 간단한 로직인 입력 값과 입력 필드 포커스 관리 정도만 Custom Hook으로 분리한 상태입니다.

<b>호프는 보통 어떤 경우에 Custom Hook 분리를 고려하시나요? 너무 단순하거나 복잡한 추상화를 피하고, 적정 선을 정하는 기준이 궁금합니다.</b>

### 2. 카드 소유자 이름 동적 렌더링 관련
기능 요구사항에 따라 입력 필드에 유효한 값이 입력되면 다음 입력 필드가 자동으로 열리도록 로직을 구성하였습니다. 

다른 입력 필드의 경우 들어와야 할 입력 값의 길이가 확실히 정해져 있어 수월하게 구현할 수 있었습니다. (예를 들어 카드 번호는 4자리가 모두 입력되어야 다른 입력 필드로 넘어가기 때문에 사용자 입장에서 자연스럽게 느껴집니다) 하지만 카드 소유자 이름의 경우 너무 길지 않다면 1글자만 입력해도 유효한 값으로 인정하기 때문에, 1글자만 입력해도 유효한 값으로 처리하고 바로 다음 입력 필드로 넘어가게 됩니다. 사용자 입장에서 이름을 다 입력하기도 전에 갑자기 다음 입력 필드로 포커스가 옮겨지면 불편한 경험이 될 것 같습니다.

대안으로 사용자가 엔터를 누르거나, blur 이벤트를 통해 다음 입력 필드로 넘어가도록 하는 방법도 고려해보았지만, 사용자가 동작 방법을 모르는 상황에서 이러한 이벤트로 입력 필드를 제어한다면 오히려 혼란스러울 수 있다는 생각이 들었습니다.

<b>이런 상황에서 UX를 개선해 본다면 어떤 방향성을 가지는 게 좋을까요?</b>

<hr />

이번에도 잘 부탁드립니다 ☺️

2024-04-27 07:27 UTC, moonheekim0118 requested changes
안녕하세요 파슬리 🌱 이번 미션도 잘 구현해주셨네요! 카드가 휘리릭 돌아가는 인터렉션이 너무 멋져요 🥹👍

## Q&A
### 1. Custom Hook 분리 기준
(일단 현재 코드상 파슬리가 아주 적절히 잘 분리해주셨다고 생각했어요.)

파슬리가 질문 주신것의 요점은 결국 어떻게 추상화를 잘할까?라는 고민이라고 생각이 들어요.
이거는..제가 이렇다 저렇다 답변을 드리는 것보다 파슬리가 여러번 시행착오를 겪으시면서 파슬리만의 기준을 만들어가시는게 더 도움이 될 것 같아요.
 상황에 따라서 그 기준이 달라지기도 하고요ㅎㅎ
예를들어 validation 조건이 모두 통일된 input 을 가진 프로젝트에서는 validation 조건을 훅 안에 포함시키는게 맞겠죠?
근데 반대로 validation 조건이 인풋별로 다른 프로젝트에서는 훅에서 해당 조건을 모르는게 나을거고요.

저도 이런 고민을 꽤 많이 했었고, 지금도 많이 하고 있는데요, 추상화 관련해서 읽었을 때 도움이 되었던 글을 놓고 갑니다.
- [촉촉한 코드, 건조한 코드](https://velog.io/@sunjoo9912/%EC%8A%A4%ED%81%AC%EB%9E%A9-%EC%B4%89%EC%B4%89%ED%95%9C-%EC%BD%94%EB%93%9C-%EA%B1%B4%EC%A1%B0%ED%95%9C-%EC%BD%94%EB%93%9C)
- [AHA Programming 💡](https://kentcdodds.com/blog/aha-programming)
- [Goodbye, Clean Code](https://overreacted.io/goodbye-clean-code/)


추가로 말씀드리자면, 커스텀 훅 분리 기준이 오로지 '재사용'일 필요는 없다고 생각이 듭니다.

컴포넌트와 훅의 분리는 결국 비즈니스 로직과 UI를 분리하고, 비즈니스 로직을 선언적으로 사용하게 만들어주는 이점도 있다고 생각합니다.
따라서 저는 컴포넌트 내의 로직이 비대해지면 재사용이 안되더라도 커스텀훅으로 분리해서 사용하기도 하기도 해요! 이런 관점도 있을 수 있구나~~라고 알아주심 좋을 것 같아요 😉 

### 2. 카드 소유자 이름 동적 렌더링 관련
오 좋은 고민을 해주셨네요 👏 
일단..저 같으면 이름 필드에 한해서 엔터 시 다음 필드로 이동하도록 개선할 것 같아요.
> 사용자가 동작 방법을 모르는 상황에서 이러한 이벤트로 입력 필드를 제어한다면 오히려 혼란스러울 수 있다는 생각이 들었습니다.

엔터나 onBlur 시 넘어가게 하면 딱히 혼란스럽진 않을 것 같습니다ㅎㅎ크게 사용자의 인지범위를 넘어가는 동작은 아닌 것 같아요. 

추가로 앞으로 개발자로 업무 하시게 된다면 미션에서 처럼 누군가가 작성해준 요구사항을 받으실텐데요.
파슬리가 이번에 경험해주신 것 처럼 요구사항에 명시되지 않은 부분들이나, 개발하면서 발견되는 여러 엣지케이스들이 있을거에요ㅎㅎ
이럴때 그냥 1차적으로 요구사항만 충족하고 넘어가기보다는, UX적으로 먼저 고민해봐주시는 습관이 정말정말 좋다고 생각합니다 👍😊👍

---

그럼 고생하셨습니다ㅎㅎ몇가지 코멘트 남겼는데 확인부탁드릴게요 :)

2024-04-27 07:45 UTC, moonheekim0118 commented
추가로 complete 페이지에서 새로고침을 하거나 직접 접근을 하면 404가 뜨는데 한번 확인해주세요~! 🙏 
<img width="745" alt="스크린샷 2024-04-27 오후 4 44 52" src="https://github.com/woowacourse/react-payments/assets/61469664/89d5d606-745b-421a-9cfe-1bdeb179ec14">

2024-04-28 08:00 UTC, anttiey commented on src/App.tsx
라우팅 경로를 상수로 관리하면 `<Link>` 태그 내부 등에서 활용할 수 있겠군요 🙌🏻

- 라우팅 경로를 상수로 분리했습니다. [510a287](https://github.com/woowacourse/react-payments/pull/373/commits/510a287f67ce66d945bb7a2580294fa566669617)
- `ErrorPage` 를 추가하여 잘못된 경로로 접근 시 에러 페이지를 노출하도록 변경했습니다. [df43184](https://github.com/woowacourse/react-payments/pull/373/commits/df43184edf576f18410bb8d2990468162164072a)

2024-04-28 08:10 UTC, anttiey commented on src/components/common/Input/Input.tsx
> +  return <S.Input $isValid={isValid} ref={ref} {...rest} />;
호프의 리뷰를 바탕으로 코드를 다시 보니 함수 선언식과 표현식이 혼재되어 있었네요! 평소 함수 표현식으로 컴포넌트를 주로 작성하는데, 1단계 미션에서는 함수 선언식으로 컴포넌트를 만들어서 통일되지 않은 것 같아요 😅 코드 전반에서 함수 표현식을 쓰고 있으므로 둘을 섞어서 쓰는 것보단 함수 표현식으로 통일하는 게 좋을 것 같아 컴포넌트도 모두 <b>`함수 표현식`</b> 으로 수정하였습니다 🙌🏻

[e0456b5](https://github.com/woowacourse/react-payments/pull/373/commits/e0456b55c62d699e74c74e08e0e56e7f95ed858c)

2024-04-28 08:16 UTC, anttiey commented on src/hooks/useInput.ts
> +
`useInput`, `useInputs` 커스텀 훅에 제네릭 타입 `T` 를 추가하여 `string` 뿐 아니라 다양한 타입에 대응할 수 있도록 확장해 보았습니다 ☺️

[dd2399b](https://github.com/woowacourse/react-payments/pull/373/commits/dd2399be4e3130ee3bedd9fea4d58cab94e8a7a3)

2024-04-28 08:34 UTC, anttiey commented on src/components/CardForm/CardCompanyInput/CardCompanyInput.tsx
> +  const toggleOptionList = () => setIsOptionOpen(!isOptionOpen);
호프의 리뷰를 바탕으로 리액트에서 `state` 가 업데이트되는 과정을 전반적으로 살펴 보게 되었습니다! 🧐

리액트에서 `useState` 를 이용한 상태 업데이트는 다음과 같이 처리됩니다.

- 이벤트 핸들러가 실행된다.
- `setState` 가 새로운 렌더링을 `state 업데이트 큐`에 넣는다.
- 컴포넌트가 리렌더링 된다.
- 리렌더링을 실행하는 동안 `state 업데이트 큐`를 처리한다.

이때 리액트는 너무 많은 리렌더링을 발생시키지 않고 다수의 상태를 업데이트하기 위해 `batch update` 를 진행합니다. `16ms` 동안 변경된 상태 값들을 모아서 한 번 리렌더링이 됩니다. 따라서 상태 업데이트 시 기존 상태 값을 기준으로 새로운 상태를 결정하는 경우, 최신 값을 항상 반영한다고 보장할 수 없습니다.

현재 상태에 의존하여 상태를 업데이트 할 때는 `함수형 업데이트` 를 사용하는 것이 안전하다는 사실을 새롭게 알게 되었습니다. 해당 코드를 함수형 업데이트로 개선해 보았습니다.

2024-04-28 08:39 UTC, anttiey commented on src/components/CardForm/CardExpirationInput/CardExpirationInput.tsx
> +      : '';
> 위와 같이 isClicked와 isValid 가 모두 확인된 상태를 하나 더 내려주는건 어떤가 제안드려봅니다😌

`isClicked` 와 `isValid` 를 합쳐서 내려 줄 생각을 못했네요 😅 대부분 `isClicked` 가 단독으로 사용되지 않고 `isClicked` 와 `isValid` 가 합쳐서 쓰이므로 해당 상태를 합쳐서 새로운 상태인 `isError` 로 한 번에 처리하도록 수정해 보았습니다!

이렇게 사용하니 훨씬 가독성이 좋아진 것 같아요 👍

[dd2399b](https://github.com/woowacourse/react-payments/pull/373/commits/dd2399be4e3130ee3bedd9fea4d58cab94e8a7a3) [6df25d4](https://github.com/woowacourse/react-payments/pull/373/commits/6df25d488caba67a9a179bcd7b6a703cbc78c21d)

2024-04-28 09:09 UTC, anttiey commented on src/components/CardForm/CardExpirationInput/CardExpirationInput.tsx
> +  const isClicked = [month.isClicked, year.isClicked];
`useInput` 자체에 새로운 상태인 `isError` 을 추가하면서 컴포넌트 내부에서 따로 정의하던 <b>`isValid, isClicked 배열을 삭제하고`</b> `month.isError` 와 `year.isError` 만으로도 똑같이 작동할 수 있도록 로직을 개선해 보았습니다!

[dd2399b](https://github.com/woowacourse/react-payments/pull/373/commits/dd2399be4e3130ee3bedd9fea4d58cab94e8a7a3)

2024-04-28 09:10 UTC, anttiey commented on src/components/CardForm/CardExpirationInput/CardExpirationInput.tsx
> +          isValid={isClicked[0] ? isValid[0] : true}
위의 코멘트와 동일하게 `month.isError` 와 `year.isError` 만으로도 똑같이 작동할 수 있도록 로직을 개선하며 배열을 삭제하였습니다 ☺️

2024-04-28 09:12 UTC, anttiey commented on src/hooks/useAutoMoveIndex.ts
> +    validationList.some(Boolean) && handleIndex(defaultIndex + validationList.filter(Boolean).length);
`useEffect` 내부 로직을 `if문` 으로 변경하며 가독성을 개선할 수 있도록 수정해 보았습니다!

[a48ddf6](https://github.com/woowacourse/react-payments/pull/373/commits/a48ddf67c9f3fb2f2090d648f1008b0a49a9c0a7)

2024-04-28 09:24 UTC, anttiey commented on src/components/CardForm/CardCompanyInput/CardCompanyInput.tsx
> +          </S.CardCompanyOptionList>
`SelectBox` 공통 컴포넌트를 생성하고 이를 활용하여 `CardCompanyInput` 에서 카드사 정보를 받을 수 있도록 구조를 개선해 보았습니다 🙌🏻

[16e49b3](https://github.com/woowacourse/react-payments/pull/373/commits/16e49b32497a361c2d752a9aac78fb873f93e53b)

2024-04-28 10:06 UTC, anttiey commented on src/components/CardForm/CardCompanyInput/CardCompanyInput.tsx
> +  company: InputType;
처음에는 객체를 통으로 받지 않고, 전개하여 props로 넘기도록 코드를 구성했는데요. 필요한 기능이 많아지고 매개변수가 증가하면서 코드 가독성이 떨어진다는 생각이 들었습니다.

```js
const {
  value: month,
  isValid: isValidMonth,
  isError: isErrorMonth,
  handleValue: handleMonthValue,
} = useInput<string>(validateMonth, '');

...

<CardExpirationInput 
  month={month}
  year={year}
  isValidMonth={isValidMonth}
  isValidYear={isValidYear}
  ...
/>

```

다음과 같은 코드가 여러 번 반복되다 보니 코드의 길이가 길어지고 하나의 변수를 추가하려면 타입, 매개변수, 사용되는 곳을 모두 수정해야 해서 불편하게 느껴지더라고요. 호프의 리뷰처럼 객체를 통으로 넘겼을 때 해당 객체 안에 어떤 프로퍼티가 있을지 바로 알 수 없다는 단점이 있지만, 입력 컴포넌트들이 `InputType` 이라는 타입을 반복적으로 사용하고 있으므로 `InputType` 타입을 체크하면 어떤 프로퍼티가 있는지 그나마 빠르게 파악할 수 있지 않을까 생각했습니다!

이번 미션에서는 객체를 통으로 넘기는 형태로 props를 구성했지만, <b>이런 상황에서 코드 가독성을 높일 수 있는 다른 개선 방향이 있을까요?</b> 🥹

2024-04-28 10:07 UTC, anttiey commented on src/constants/Condition.ts
> +export const CARD_COMPANY: Record<string, string> = {
카드사 종류로 이루어진 유니온 타입을 정의해 사용해 보았습니다 ☺️

[f5ffb41](https://github.com/woowacourse/react-payments/pull/373/commits/f5ffb4163a9ee8fb1bc100748424acd6c06f7656)

2024-04-28 10:22 UTC, anttiey commented on src/pages/CardRegistrationCompletePage/CardRegistrationCompletePage.tsx
> +  const cardCompany = searchParams.get('company');
> 가령 지금은 UI상 단순히 카드번호 앞자리와 카드회사 이름만 넘겨주면 되지만
만약 이름, 유효기간, cvc 번호, 카드번호 전체가 페이지간 공유되어야한다면, 어떻게 해야할지 고민해봐주셔도 좋겠습니다 🙂

- Link, useNavigate 등을 이용해 이동 경로로 state 값을 전달한다.
- 상태 관리 라이브러리를 이용해 전역 상태로 관리한다.
- 서버와 소통하는 경우라면 React-Query 라이브러리를 이용해 데이터를 동기화한다.

당장 생각나는 방법은 이 정도인데, 페이지 간 복잡한 데이터를 넘겨 본 경험이 많지 않아 아직은 기준이 명확하지 않습니다 🥲 앞으로 각 미션마다 적절한 방법을 사용할 수 있도록 노력하겠습니다 🥰

2024-04-28 10:34 UTC, anttiey commented
안녕하세요, 호프! 🍀 피드백 반영을 완료하여 코멘트 남깁니다 🌱

## 피드백 반영 사항
- [refactor: 함수 표현식 통일](https://github.com/woowacourse/react-payments/pull/373/commits/e0456b55c62d699e74c74e08e0e56e7f95ed858c)
- [feat(ErrorPage): 에러 페이지 생성 및 라우팅 처리](https://github.com/woowacourse/react-payments/pull/373/commits/df43184edf576f18410bb8d2990468162164072a)
- [refactor(SelectBox): SelectBox 공통 컴포넌트로 분리](https://github.com/woowacourse/react-payments/pull/373/commits/16e49b32497a361c2d752a9aac78fb873f93e53b)
- [refactor(useAutoMoveIndex): useEffect 안 로직 수정](https://github.com/woowacourse/react-payments/pull/373/commits/a48ddf67c9f3fb2f2090d648f1008b0a49a9c0a7)
- [refactor(Routes): 라우팅 되는 경로 상수로 분리](https://github.com/woowacourse/react-payments/pull/373/commits/510a287f67ce66d945bb7a2580294fa566669617)
- [refactor: useInput, useInputs 커스텀 훅 내 isError 반환값 추가](https://github.com/woowacourse/react-payments/pull/373/commits/dd2399be4e3130ee3bedd9fea4d58cab94e8a7a3)
- [refactor: Input 매개변수 변경](https://github.com/woowacourse/react-payments/pull/373/commits/6df25d488caba67a9a179bcd7b6a703cbc78c21d)
- [refactor: useInput, useInputs 커스텀 훅이 다양한 타입을 대응할 수 있도록 수정](https://github.com/woowacourse/react-payments/pull/373/commits/e0d7c291a993e9df1de884b7e64f3761dce4c571)
- [refactor(Condition): 카드사 종류 타입 추가](https://github.com/woowacourse/react-payments/pull/373/commits/f5ffb4163a9ee8fb1bc100748424acd6c06f7656)
- [fix: Github Pages 라우팅 오류 해결](https://github.com/woowacourse/react-payments/pull/373/commits/71bcb4d226f8e6d83d286f6ce1def3e1c89cc741)

각 피드백 반영 사항에 대한 자세한 설명과 추가 질문은 답글로 남겨 두었습니다!

> 추가로 complete 페이지에서 새로고침을 하거나 직접 접근을 하면 404가 뜨는데 한번 확인해주세요~! 🙏

이 부분도 해결하여 다시 배포해 두었습니다 ☺️

<hr />

늘 꼼꼼하고 자세하게 코멘트 달아 주셔서 정말 감사드립니다 🥰 호프의 피드백 덕분에 한층 더 성장하고 확실하게 개념을 확립할 수 있었어요. 질문에 대해서도 친절하게 답변 주셔서 감사드립니다 💞 좋은 하루 되세요!

2024-04-29 10:57 UTC, moonheekim0118 commented on src/components/CardForm/CardCompanyInput/CardCompanyInput.tsx
> +  const toggleOptionList = () => setIsOptionOpen(!isOptionOpen);
와우 훌륭하시네요 🥹 
공유해주셔서 감사합니다 :)

2024-04-29 10:58 UTC, moonheekim0118 commented on src/components/CardForm/CardCompanyInput/CardCompanyInput.tsx
> +          </S.CardCompanyOptionList>
척하면 척이시네요 👍 👍

2024-04-29 11:01 UTC, moonheekim0118 commented on src/components/CardForm/CardCompanyInput/CardCompanyInput.tsx
> +  company: InputType;
상황에 따라서 다를 것 같은데
현재 구조라면 그냥 객체를 통으로 넘기는게 최선일 것 같아요.
아니면 사용처에서는 통으로 받아온 객체를 구조분해 할당해서 사용해도 될 것 같기도 하고요! (이것도 역시 취향차이임니다)

```tsx
//..생략
const { month , year, isValidMonth, isValidYear } = company;
```

2024-04-29 11:04 UTC, moonheekim0118 commented on src/hooks/useInput.ts
> +
오오 아주 좋습니다 👍 👍 👍

2024-04-29 11:13 UTC, moonheekim0118 approved these changes
안녕하세요 파슬리🌱 확인이 조금 늦어서 죄송합니다 🙏
반영 사항 모두 확인했고 질문 남겨주신 부분에 코멘트 추가했습니다! 너무 잘 개선해주셔서 추가로 리뷰 드릴부분이 없네요 👏 👏  
이번 미션동안 리뷰 반영 적극적으로 해주시고, 파슬리만의 고민도 공유해주셔서 정말 감사했습니다 :)
덕분에 리뷰하면서 저도 정말 즐거웠습니다 😄 

그럼 이번 미션은 여기서 이만 마무리할게요! 고생하셨어요~~ 다음 미션도 파이팅입니다 :) 🍀

2024-04-29 11:13 UTC, moonheekim0118 commented on src/components/CardForm/CardExpirationInput/CardExpirationInput.tsx
>    };
오 뭔가 함수인데 함수같지 않은 이름인 것 같아요.
getErrorMessage 등으로 개선해볼 수 있지 않을까요?ㅎㅎ

2024-04-29 11:13 UTC, merged