[2단계 - 페이먼츠] -헤일리(최혜림) 미션 제출합니다.
woowacourse/react-payments pull request #378
Opened 2024-04-26 12:42 UTC by healim01

안녕하세요 블링! 
step2 로 다시 뵙게 되었네요! 

---

### ✅ 베포 사이트 
[페이먼츠](https://healim01.github.io/react-payments/dist/)

[스토리북 배포](https://662b9be31b954f0f664a267e-zsdenvskgu.chromatic.com/)

### ❗️ 이번 과정에서 집중해서 고민한 부분 

**Custom Hooks** 
이번에 커스텀 훅을 사용해서 구현해보았는데 제대로 커스텀 훅을 사용해본 건 처음이다보니 초반에 많이 헤맸던거 같네요
특히 초반엔 예시들로 봐왔던 재사용성이 강한 커스텀 훅들과 달리 해당 컴포넌트에서만 사용가능한 저의 커스텀 훅을 보고 이렇게 사용하는 것이 맞나? 라는 등 많은 고민을 했던거 같습니다. 이에 대해 답을 찾기 위해 주변 크루들과도 많은 이야기를 나누었는데 `로직 분리` 자체에 더 의미를 두어서 이렇게 사용해도 괜찮다는 결론이 나왔습니다. 블링은 제 커스텀 훅 코드 분리 구조에 대해 어떻게 생각하시는지 궁금합니다. 

**동적 입력 구현** 
사용자가 입력을 다하면 그 다음 입력창으로 동적으로 이동하게 작업해봤습니다. 이 부분도 정말 저를 많이 고민하게 했던거 같은데 특히 이름 작성칸은 maxlength 로는 입력 완료를 확인하기 어려운 부분이 있다고 판단해서 엔터값을 받아도 넘어갈 수 있도록 해보았습니다. 물론 엔터값도 내부 입력창 요구사항이 다 통과되지 않으면 넘어가지 못하게 막아놨습니다! 

**폼 제출 및 상태 관리** 
폼 내부에 모든 데이터가 유효해야 확인 버튼을 누를 수 있게 작업했습니다. 초반에는 폼에서 가지고 있는 값들로 유효한지를 다시 확인했었는데 그러다보니 한번 유효한 후 폼 내부에 유효하지 않는 값을 다시 넣다보면 예외처리 때문에 폼으로 값이 넘어오지 못해서 확인을 못하는 문제가 있어서 다시 입력필드 내부에서 해당 필드가 모두 입력이 완료되고 유효한지 검사하고 넘겨줄 수 있도록 변경해보았습니다. 

--- 

생각보다 이번 step2 가 꽤 어려웠던거 같네요.. 정말 많은 고민을 해보았던 과정이었던거 같습니다. 
카드 회전 애니메이션이나 UX 디테일을 더 작업해볼까도 했지만 당장 다음주에 있을 테코톡 준비가 필요해서 일단 요구사항을 우선적으로 진행해보았습니다.

이번에도 잘부탁드립니다!!

2024-04-27 11:58 UTC, uk960214 requested changes
2단계도 구현하느라 고생 많으셨습니다!!
여전히 깔끔하고 파악하기 좋은 코드인 것 같아요!
리뷰하는데에 큰 어려움이 없었습니다 😁 
그리고 입력시 다음 칸으로 넘어가는 UX도 아주 깔끔하고 좋았어요.

아래 부분들을 한 번 더 고민해보면 좋을 것 같아요!
- 페이지 상단에 카드 미리보기 쪽에 커서를 올리면 클릭할 수 있는 것처럼 보이던데 의도한 것일까요??
- 도메인 로직이 모든 컴포넌트에 꽤 많이 퍼져있다는 느낌을 받았습니다. 도메인 로직은 InputForm까지에서 다루는 것이 좋지 않을까 하는 생각이 들고, Input, InputField는 최대한 깨끗하게, 순수한 컴포넌트로 만들 수 있지 않을까요??
- 커스텀 훅은 충분히 잘 사용중이신 것 같아요! 다만 훅을 무조건 하나의 디렉토리에 묶어두다보니, 컴포넌트를 보다가 이 훅은 무얼하는 거지? 보려면 같은 위치에 있지 않아서 바로 찾기 어려운 아쉬운 부분이 있네요!

나머지 코드에 남겨둔 코멘트까지 확인해주시면 감사하겠습니다!

2024-04-27 11:58 UTC, uk960214 commented on src/components/CardFrontView.tsx
> +  const cardImgSrc = getCardImage(cardNumbers.cardNumber1);
지금 로직대로라면 2단계의 요구사항에 있는 이 항목을 충족시키지 못할 것 같아요!
> 불필요한 상태 관리나 리렌더링이 발생하지 않도록 한다.
예를 들어 카드 번호 입력 시 매 입력마다 브랜드 식별 로직이 동작하는 것은 비효율적일 수 있다. 일정 자릿수 이상 입력된 경우에만 브랜드 식별을 하는 등의 방법으로 개선한다.

이 부분도 확인 부탁드립니다!

2024-04-27 11:58 UTC, uk960214 commented on src/components/CardView.tsx
> +      <Back> {showBack && <CardBackView cvc={cardInfo.cvc} />}</Back>
```suggestion
      {showBack 
        ? <Back><CardBackView cvc={cardInfo.cvc} /></Back>
        : <Front><CardFrontView cardInfo={cardInfo} /></Front>
      }
```

삼항 연산자로 처리할 수도 있을 것 같은데요,
어떤 게 더 낫다고 보시나요?? (삼항이 맞다거나 더 낫다는 것은 아니고 의견이 궁금합니다!)

2024-04-27 11:58 UTC, uk960214 commented on src/components/Input.tsx
> +      $error={isError}
error에는 왜 $로 프리픽스를 붙여주었나요??

2024-04-27 11:58 UTC, uk960214 commented on src/hooks/useInput.tsx
> +  };
지금 계속해서 나오는 `try { ... } catch (e) { if (e instanceof Error) { ... }  }` 로직은 묶어서 리팩토링해도 좋을 것 같아요!

2024-04-27 11:58 UTC, uk960214 commented on src/hooks/useInputField.tsx
> +  };
```suggestion
  const isCompleted = () => (
    Object.keys(values).length === inputTypes.inputInfo.length &&
    Object.values(errorMessages).every((message) => message === '') &&
    Object.values(values).every((value, index) =>
      checkLength(value, inputTypes.inputInfo[index].minLength)
  );
```

2024-04-27 11:58 UTC, uk960214 commented on src/hooks/useInput.tsx
> +  };
useInput은 모든 Input에서 사용하는 훅인데요,
지금의 이런 유효성 검사 함수로 인해서 다른 도메인, 다른 기능에서는 사용할수 없을 것 같아요.
Validation 규칙은 prop 등으로 전달되는 것이 아니고, 직접 모듈을 import 해오고 있고,
길이가 max가 되면 onNext로 간다는 규칙도 일반적인 Input의 규칙으로 보기 힘들지 않을까 생각이 들었습니다.
다시 말해서 공통 Input 컴포넌트로서 관심을 가지지 않아도 되는 로직이 너무 많이 포함되어있습니다!
이 부분을 개선하기 위한 고민을 해봐주시면 좋을 것 같아요!

2024-04-27 11:58 UTC, uk960214 commented on src/hooks/useNextRef.tsx
> +    }
`const inputLength = inputTypes.inputInfo.length - 1`을 한 번 할당해준다면
가독성이 훨씬 올라갈거 같아요! 특히 조건문에서 변수 뎁스가 깊어지면 복잡하더라구요.

2024-04-27 11:58 UTC, uk960214 commented on src/hooks/useNextRef.tsx
> +  }, []);
지금은 구현이 한 번에 하나의 inputField만 나오기 때문에 큰 문제는 없는데요,
만약에 동일한 inputField를 활용해서 여러 개의 필드가 동시에 나오는 경우에는
focus가 의도한대로 동작하지 않을 가능성도 있을 것 같아요!

2024-04-27 11:58 UTC, uk960214 commented on src/hooks/useInputForm.tsx
> +  };
함수의 이름으로 봐서는 전혀 어떤 역할을 하는 함수인지 알수가 없는 것 같아요!

2024-04-27 11:58 UTC, uk960214 commented on src/hooks/useInputForm.tsx
> +  }, [complete]);
complete을 굳이 useState로 상태로 선언할 필요가 없지 않았을까요?
cardInfo를 이 훅에서 받고 있기 때문에 이 form에서 정의하는 규칙에 따라서 충분히 파싱해서 상태를 파악할 수 있을 것 같아요.

유일하게 걸리는 부분이라면 카드 소유자 부분일텐데요,
원칙적으로는 한 글자만 입력해도 정상적으로 처리될 수 있어야 하니까 한 글자만 채워도 다음 단계의 인풋을 보여줘도 되지 않을까 생각합니다!

2024-04-27 11:58 UTC, uk960214 commented on src/page/SucceedSubmit.tsx
> +          <Button> 확인 </Button>
사소한 부분인데요 확인 앞뒤로 있는 공백은 의도하신걸까요??

2024-04-27 11:58 UTC, uk960214 commented on src/components/SelectBox.tsx
> +  };
저도 최근에 비슷하게 로직을 작성하다 문득 떠오른 방법인데요, 매번 선택 때마다 select 내에 있는 option을 모두 루프하면서 option을 찾기보단, 지금처럼 option에 직접 접근할 수 있다면 option의 onClick 핸들러로 넣는건 어떨까요?? 지금은 큰 문제가 없겠지만, 만약 select 내의 옵션이 수백, 수천가지가 될지도 모르는 일이니까요!

2024-04-28 06:07 UTC, healim01 commented on src/components/CardFrontView.tsx
> +  const cardImgSrc = getCardImage(cardNumbers.cardNumber1);
앗 요구사항을 잘못 판단해서 로직을 잘못 생각했네요!

```
  const cardImgSrc = useMemo(() => {
    if (cardNumbers.cardNumber1.length >= 2) {
      return getCardImage(cardNumbers.cardNumber1);
    }
  }, [cardNumbers.cardNumber1]);
```

useMemo 를 사용해서 cardNumber1 이 2 이상일 때와, cardNumber1 이 변경될 때만 카드 브랜드 식별 로직이 실행될 수 있도록 변경해보았습니다!

2024-04-28 06:09 UTC, healim01 commented on src/components/CardView.tsx
> +      <Back> {showBack && <CardBackView cvc={cardInfo.cvc} />}</Back>
삼항 연산자가 state 하나의 True/False 에 대해 다른 컴포넌트를 가져온다는 코드를 이해하는데 더 쉬울거 같네요! 반영하겠습니다!

2024-04-28 06:25 UTC, healim01 commented on src/components/Input.tsx
> +      $error={isError}
error 로 작성해주다보니 React가 알 수 없는 속성을 DOM에 전달한다는 경고가 발생하보니 $를 붙여 수정해보게 되었습니다. 
해당 속성이 StyledInput에 전달된 후 해당 속성은 HTML 요소에 직접 전달되면 안되는 속성이라서 경고가 발생하더라구요.

2024-04-28 06:41 UTC, healim01 commented on src/hooks/useInput.tsx
> +  };
안그래도 커스텀 훅에 너무 많은 로직이 있어서 이번 프로젝트가 아닌 다른 프로젝트에서는 사용할 수 없을거 같아서 이렇게 짜는게 맞는건가 고민이 많았는데 다시 한번 더 고민해보겠습니다!

2024-04-28 06:43 UTC, healim01 commented on src/page/SucceedSubmit.tsx
> +          <Button> 확인 </Button>
앗 아니요 잘못들어간거 같네요 수정하겠습니다!

2024-04-28 06:56 UTC, healim01 commented on src/components/SelectBox.tsx
> +  };
해당 사항에 대해서 생각하고 찾아봤는데 option 에 onClick 이벤트가 작동이 안하는 경우가 있는거 같습니다. 몇몇의 기기 (스크린 리더나 모바일 사용자) 에서도 작동 안할 가능성도 있다고 하네요!
일반적으로 <select> 요소의 변경 이벤트를 사용하여 선택이 변경되었음을 감지한다고 하고, 수백 개 이상의 옵션이 있는 경우에도 일반적인 DOM 이벤트 처리는 충분히 빠르다는 결과가 있어서 select 내부에서 확인을 하는 것이 유지보수 입장에서도 괜찮을거 같다고 생각합니다!

2024-04-28 07:20 UTC, healim01 commented on src/hooks/useInput.tsx
> +  };
```
  const handleTryCatch = (funcs: () => void) => {
    try {
      funcs();
    } catch (error) {
      if (error instanceof Error) {
        handleErrorMessage(error.message);
      }
    }
  };
```

이런 형태로 로직을 묶어 리팩토링해봤습니다!

2024-04-28 07:36 UTC, healim01 commented on src/hooks/useInputForm.tsx
> +  }, [complete]);
사실 처음에는 한글자만 채워도 넘어가게 작동되었으나 UX 상으로 사용자 이름 한글자 입력 후 새로운 필드가 나오고 포커스가 이동하는 것이 좋지 않다고 판단해서 추가 로직을 더 넣었던거 같아요!

2024-04-28 08:05 UTC, healim01 commented on src/hooks/useInputForm.tsx
> +  }, [complete]);
지금 InputForm 에 있는 complete 여부는 내부에 필드에 내용이 모두 최소 조건에 통과하고 에러 벨리데이션에 통과하여 에러메세지가 없는지를 판단해서 true/false 로 저장하여 이후에 카드 추가 버튼 보여주는 로직에 사용되고 있습니다.

블링이 말씀하시는 것이 가지고 있는 cardInfo 를 사용해서 벨리데이션 체크를 하고 complete 인지를 판단하라는 의미실까요!? 

말씀하신 바가 맞다면 처음에 그런 방법도 고민해봤으나 cardInfo 로 넘어오는 정보들이 모두 유효한 정보들만 넘어오고 있다보니 입력창에 틀린 정보 입력시(e.g. HAHA99) 입력창은 에러 표시를 해주지만 가지고 있는 cardInfo 는 HAHA로 유효하다보니 폼에는 에러 표시가 나타나지만 카드는 등록할 수 있다고 버튼이 표시되는 현상이 생겨서 UX 적으로 고려했을 때 필드에서 이를 관리해서 넘겨주는 것이 좋을거 같다고 판단해서 이렇게 작성해보았습니다!

2024-04-28 08:10 UTC, healim01 commented on src/hooks/useInput.tsx
> +  };
useInput 을 한번 수정해보았습니다!!

Validation 규칙은 prop 로 전달받아서 사용하고 있으며, 길이가 max가 되면 onNext로 간다는 규칙도 분리해보았습니다!
다만 `enter` key 를 입력했을 때 다음으로 이동하는 경우는 엔터값에 대한 이동이라고 같이 존재해도 되지 않을까 생각해서 그대로 두었습니다. 

변경된 훅 로직에 대해서 어떻게 생각하시는지 궁금합니다!

2024-04-28 08:14 UTC, healim01 commented on src/hooks/useInput.tsx
> +  };
사실 이번에 커스텀 훅을 작업하면서 커스텀 훅이 어느정도의 관심사를 가져도 되는지에 대해서 고민이 많았던거 같습니다. 

useInputForm 과 같이 하나만의 폼에 대한 관심사를 모두 가지고 있어도 되는걸까 
혹은 useForm 을 따로 구현하고 이를 다시 사용하는 useCardForm 을 만드는 것이 더 좋은걸까 고민되는거 같습니다 ㅜㅜ

2024-04-28 08:21 UTC, healim01 commented
안녕하세요 블링! 
반영해주신 코멘트 감사합니다! 
하나하나 적용해보면서 궁금한 점들도 달아놨습니다! 

> 페이지 상단에 카드 미리보기 쪽에 커서를 올리면 클릭할 수 있는 것처럼 보이던데 의도한 것일까요??

확인해봤는데 작업할 때 hover 로 연습해보면서 넣은 cursor css 가 빠지지 않아서 그런거 같네요..! 수정했습니다! 

>  훅을 무조건 하나의 디렉토리에 묶어두다보니, 컴포넌트를 보다가 이 훅은 무얼하는 거지? 보려면 같은 위치에 있지 않아서 바로 찾기 어려운 아쉬운 부분이 있네요!

대부분 커스텀 훅들을 hooks 폴더에서 관리하길래 이렇게 하는 방법이 일반적인 방법이라고 생각했는데 hooks 폴더에 관리하는 훅들은 useTheme이나 useFetch 와 같은 여러 컴포넌트에서 사용할 수 있는 것들을 묶어놓고 지금 프로젝트처럼 하나의 컴포넌트에서만 사용되는 것들은 컴포넌트 폴더에서 함께 관리해도 되는 걸까요? 

--- 
감사합니다!!

2024-04-28 11:56 UTC, healim01 commented
커스텀 훅에 대해서 조금 더 공부하다가 조금 수정을 해보았습니다..! 
사실 제가 커스텀 훅에 관련해서 테코톡을 이번 주에 준비 중에 있는데 제가 작성한 피피티 내용을 제가 위반하고 있는건 아닌지 확인하다가 useInputForm 이 너무 이름과 달리 다른 일을 하고 있는게 아닐까 생각이 들어서 수정해보았습니다. 

`만들어진 커스텀 훅은 한 가지 기능만을 하고 있는가?` 가 커스텀 훅을 작성할 때 주의해야할 점이라고 생각하고 있었는데 useInputForm 이라는 이름 아래에 complete 확인에 card value handler 들까지 모두 들어있더군요..! 이후에 complete 로직을 따로 분리하니 핸들러만 존재하고 훅은 없는 그냥 함수가 되어 있었습니다... 

혹시 이래서 아래와 같은 느낌을 받으셨던 걸까도 싶어서 급하게 수정해보았습니다. 
> 도메인 로직이 모든 컴포넌트에 꽤 많이 퍼져있다는 느낌을 받았습니다. 

리뷰 요청 이후 수정하여서 죄송합니다 ㅜㅜ

2024-04-29 15:53 UTC, uk960214 requested changes
피드백 반영해주시느라 고생하셨습니다!
input 관련 로직들이 전보다 훨씬 더 도메인으로부터 자유로워진 것 같아요.

욕심을 조금 더 부리자면 부릴 수 있을 것 같아 코멘트를 더 남기긴 했는데요,
다음 미션을 진행해야하긴 하니, 내일 저녁 쯤에는 어쨌든 머지를 하도록 하겠습니다!
그 동안 마무리를 하고 싶으시다면 자유롭게 마무리 피드백 반영을 해보셔도 좋을 것 같아요!

> 커스텀 훅의 위치

는 저는 크게 구애받지 않아도 된다고 생각합니다. 저는 필요에 따라서 해당 컴포넌트나 페이지와 같은 디렉토리에 hooks.tsx 파일을 만들어두고 사용하기도 하구요!

남긴 코멘트들 한번씩 확인해주세요~!

2024-04-29 15:53 UTC, uk960214 commented on src/components/Input.tsx
> +      $error={isError}
오호 [transient props](https://styled-components.com/docs/api#transient-props) 하나 배워갑니다!

2024-04-29 15:53 UTC, uk960214 commented on src/components/SelectBox.tsx
> +  };
오호 네넵 좋습니다! 한 번 더 확실하게 검증해주셔서 감사합니다!

2024-04-29 15:53 UTC, uk960214 commented on .gitignore
> -dist
앗 왜 gitignore에서 dist가 빠졌을까요??
빌드된 파일들이 모두 올라와버렸네요 ㅠㅠ

2024-04-29 15:53 UTC, uk960214 commented on src/hooks/useInput.tsx
> +  };
👍

2024-04-29 15:53 UTC, uk960214 commented on src/page/EnrollCard.tsx
> +          handleSubmit={setCanSubmit}
사실 이 prop은 submit을 하는 것이 아니라 submit을 해도 된다는 것을 설정하는 prop인데 이름 때문에 오해가 발생할 수 있을 것 같아요! handleSubmitReady라던가 아예 setCanSubmit으로 해도 되지 않았을까 하는 생각이 듭니다!

2024-04-29 15:53 UTC, uk960214 commented on src/hooks/useComplete.tsx
> +    useState<Record<string, boolean>>(DEFAULT_CARD_BOOLEAN);
여기에서 기본값도 prop으로 받거나 하면 어떨까 하는 생각이 듭니다!
그렇게 하면 꼭 card가 아니더라도 다른 폼에도 적용할 수 있을것 같아요!

2024-04-29 15:53 UTC, uk960214 commented on src/components/Input.tsx
> +  }, [value]);
조금더 욕심을 부리자면, 이 로직은 모든 input에서 실행될 것을 기대하는 바는 아니니까 handleInput 프롭으로 전달되는 함수에 일부가 되어도 되지 않나 하는 생각이 듭니다! 어차피 value가 바뀔 때 마다 이펙트 훅이 돌면서 검증을 할거라면 아예 변경을 처리하는 핸들러에서 해주더라도 무방할테니까요!

2024-04-30 04:03 UTC, healim01 commented on .gitignore
> -dist
헉 배포하는 과정에서 빠졌나보네요 ㅜㅜ 항상 올라간 파일 더블체크했는데 이번에 이런 실수를 했네요 ㅜㅜ

2024-04-30 04:06 UTC, healim01 commented on src/page/EnrollCard.tsx
> +          handleSubmit={setCanSubmit}
setCanSubmit 과 같은 네이밍이 로직을 더 잘설명하는거 같네요!! 수정하겠습니다!

2024-04-30 04:09 UTC, healim01 commented on src/hooks/useComplete.tsx
> +    useState<Record<string, boolean>>(DEFAULT_CARD_BOOLEAN);
확실히 더 재사용성이 높아질거 같네요!

2024-04-30 04:20 UTC, healim01 commented on src/components/Input.tsx
> +  }, [value]);
이렇게 변경해보았습니다!

``` 
<StyledInput
      ref={ref}
      $error={isError}
      type={info.type || 'text'}
      maxLength={info.maxLength}
      placeholder={info.placeHolder}
      onChange={(e) => handleChange(e, info.maxLength)}
      onBlur={handleBlur}
      onKeyDown={handleKeyDown}
    />
```

```
const handleChange = (
    e: React.ChangeEvent<HTMLInputElement>,
    maxLength: number
  ) => {
    const inputValue = e.target.value;
    handleTryCatch(() => {
      validate(inputValue);
      setValue(inputValue);
      handleInput(inputValue);
      handleErrorMessage('');

      if (inputValue.length === maxLength) {
        onNext();
      }
    });
  };
```

2024-04-30 04:22 UTC, healim01 commented
안녕하세요 블링! 
이번 피드백도 반영해보았습니다! 
이번 미션이 제 테코톡 일정이랑도 겹쳐서 정말 정신없었는데 블링 덕분에 잘 마무리 할 수 있었던거 같습니다!

항상 소중한 코드리뷰 피드백 감사합니다!!

2024-04-30 14:15 UTC, uk960214 commented on src/components/Input.tsx
> +  }, [value]);
와 너무 좋습니다!

2024-04-30 14:16 UTC, uk960214 approved these changes
마지막까지 피드백 반영해주시느라 고생 많으셨습니다!
테코톡 준비하면서 미션과 피드백 반영까지 훌륭하게 해주셨어요!
테코톡도 화이팅이고 남은 미션들도 화이팅입니다!! 💪

2024-04-30 14:16 UTC, merged