[2단계 - 페이먼츠]  수야(최영수) 미션 제출합니다.
woowacourse/react-payments pull request #395
Opened 2024-04-27 12:30 UTC by cys4585

안녕하세요 카일! 2단계 PR로 다시 인사 드립니다!
미션의 난이도가 높아, 리뷰 요청 권장일 보다 많이 늦어졌습니다..ㅠ
이번 2단계 미션 피드백도 잘 부탁드려요 :)

---

# 배포 URL
- [Application](https://cys4585.github.io/react-payments/)
- [Storybook](https://662ce6a438236b5e5d4e2605-bhsxuattdz.chromatic.com/?path=/story/stories-cardenrollform-cardownername--default)

---

# 학습목표

- 다양한 Form 구성 요소들간의 상태를 효율적으로 관리한다.
- hooks API를 이용하여 상태 관리 로직을 구현한다.
- custom hooks를 생성하여 Form 관리 로직을 컴포넌트에서 분리하고 재사용한다.
- Controlled & Uncontrolled Components에 입각하여 Form을 핸들링한다.
# 핵심 기능
사용자에게 유효한 카드 정보를 입력 받아 카드를 등록하면 카드 등록 완료 페이지로 이동한다.

---

# 집중한 부분
1. 코드 가독성
2. Custom Hooks

이번 미션에서는 custom hook을 활용하여 로직과 UI를 분리하는 데 집중했어요. react를 사용해 본 경험은 있지만, custom hook을 만든 건 처음이어서 어색했어요. 아쉽게도, 로직과 UI의 재사용까지 깊게 고민할 여유는 없었어요. 그래도 custom hook을 통해 로직과 UI를 관심사에 따라 분리해 본 경험이 의미 있었다고 생각합니다. 리팩터링 과정에서 UI와 로직을 분리함으로써 코드의 구조를 파악하는 게 수월해진 걸 체감했습니다! 
Custom Hook과 관련된 내용과 가독성을 중점적으로 피드백을 주시면 성장에 큰 도움이 될 것 같습니다!! 

---

# 추가적으로
[ 재사용성, 퍼포먼스(불필요한 리렌더링/상태관리), Storybook UI Test ] 는 아직 실력 이슈로 인해, 저에게 확실히 와닿는 키워드는 아니었지만, 중요한 학습 키워드라 생각합니다! 제 코드를 리뷰하는 과정에서 이 부분과 관련해서 인사이트를 주시면 감사하겠습니다!
(예를 들면, 제가 짠 어느 코드가 퍼포먼스나 재사용성과 연관이 있다 와 같은 것들이 있을 것 같아요..!)

2024-04-27 12:35 UTC, cys4585 commented on src/hooks/useCardEnrollForm.ts
> +    useCardNumbers();
카드 등록과 관련된 모든 로직이 useCardEnrollForm에서 시작됩니다.
모든 로직(훅)이 여기에 있고, 다른 컴포넌트들은 CardEnrollForm 컴포넌트로 부터 상태나 로직을 props로 내려받아요.

지금 드는 생각은, 
- CardEnrollForm Component - useCardEnrollForm Hook
- CardNumbers Component - useCardNumbers Hook
- CardIssuer Component - useCardIssuer Hook
...
과 같은 연결 방식이 코드를 이해하기 쉽다는 측면에서 더 좋은 코드가 아니었을까? 란 생각이 듭니다.
카일은 어떻게 생각하시나요??

2024-04-27 12:49 UTC, cys4585 commented on src/hooks/useCardEnrollForm.ts
> +    useCardNumbers();
![image](https://github.com/woowacourse/react-payments/assets/77481524/f8deabc8-2ea8-4464-97ea-599738b333ce)

2024-04-28 04:13 UTC, igy95 requested changes
안녕하세요 수야~ 이번 미션의 난이도로 인해 제출 기간이 늦어졌다고 말씀 주셨는데, 개인적으로 파일 변경지점을 보면서 '이 diff가 모두 필요한 diff였을까'하는 생각이 어느정도 들었던 것 같아요. 미션 내용에 필요한 구현을 우선적으로 하고 파일 이동과 같은 추가 리팩터링을 후순위로 두었다면 일정에 맞게 적절히 취사선택할 수 있지 않았을까 싶네요 ㅎㅎ

세부 코멘트 확인 부탁드릴게요! 고생 많으셨습니다 👍

2024-04-28 04:13 UTC, igy95 commented on src/hooks/useIsReadyToSubmit.ts
> +const isAllFilled = (cardInformationValueState: CardInformationValueState) => {
인풋의 타입이 여기서 더 늘어날수록 `isAllFiled` 내의 로직의 복잡성도 빠르게 증가할 것 같은데, 각 인풋에서 `isValid`를 판단하여 상위 폼에 전달해주는 방식을 고려해볼 수 있지 않을까요?

2024-04-28 04:13 UTC, igy95 commented on src/hooks/useIsReadyToSubmit.ts
> +const isExistError = (cardInformationErrorState: CardInformationErrorState) => {
이것도 `isAllFilled`와 같은 맥락입니다.

2024-04-28 04:13 UTC, igy95 commented on src/hooks/useIsReadyToSubmit.ts
> +type dependencies = [CardInformationValueState, CardInformationErrorState];
변수명과 충돌 방지 위해 타입은 파스칼 케이스로 작성하는 것을 권장드립니다.

2024-04-28 04:13 UTC, igy95 commented on src/hooks/useCardEnrollForm.ts
> +    useCardNumbers();
폼 컴포넌트는 결국 상위에서 각 필드 간 교류 및 최종 제출을 위한 폼 영역과 그 하위에 각 필드에 대한 세부적인 관심사를 가지는 필드로 구분지을 수 있습니다. 따라서 이러한 로직을 완전히 분리할 수는 없으며 어느정도는 연관성을 가지되, 어떻게 하면 공통적인 부분을 잘 추상화할 수 있을지 고려하는 것이 중요할 듯 싶습니다.

말씀주신 방향에 대해서는 해당 훅이 들고있는 로직이 무엇이냐에 따라 답이 달라질 수 있는 부분이라 생각합니다. 때문에 `react-hook-form` 혹은 `formik`과 같은 폼 라이브러리에서 어떠한 패러다임을 제시하는지 미리 참고해보시는 것이 어떨까 싶네요.

2024-04-29 08:52 UTC, cys4585 commented on src/constants/cardIssuers.ts
> +    text: "신한카드",
카카오뱅크 카드의 경우, select > option 에는 "카카오뱅크"로 표시돼야 했고, 카드 등록 완료 페이지에는 "카카오뱅크카드"로 표시되길 바랬습니다!
혹시 카일이 제안하는 방향이 있을까요?

2024-04-29 12:15 UTC, cys4585 commented on src/styles/common.ts
Text라는 공통 컴포넌트를 만들라는 게, 스타일만 입힌 리액트 컴포넌트를 만들어서 사용하라는 의미일까요..? 
styles/common.ts에 전체에 적용되지 않는 style이 있어서 어색하다는 말씀은 이해했는데, 제안해 주신 방향은 이해를 못했습니다!

2024-04-29 12:31 UTC, cys4585 commented on src/hooks/common/useBoolean.ts
> +  };
혹시 `다른 훅의 의존성으로 걸릴 가능성`에 대한 간략한 예시 같은 게 있을까요..? 아래와 같은 경우일까요?? 맞다면, 의존성 배열에 함수를 넣는 경우가 어떤 경우가 있을까요??

```js
const { setTrue } = useBoolean();
useEffect(() => {
    // something...
}, [setTrue]);
```

2024-04-29 12:34 UTC, cys4585 commented on src/hooks/useCardEnrollForm.ts
> +    useCardNumbers();
'어느 정도는 연관성을 가지되, 어떻게 하면 공통적인 부분을 잘 추상화할 수 있을지 고려하는 것이 중요'하다는 조언이 도움이 되었어요! 폼 라이브러리가 제시하는 패러다임도 참고해보겠습니다 감사합니다! :)

2024-04-29 13:25 UTC, cys4585 commented on src/constants/cardIssuers.ts
> +export const CARD_ISSUERS = [
말씀하신 방향이 
```typescript
export enum CardIssuer {
  BcCard = "bc-card",
  ShinhanCard = "shinhan-card",
  KakaoBankCard = "kakaobank-card",
  HyundaiCard = "hyundai-card",
  WooriCard = "woori-card",
  LotteCard = "lotte-card",
  HanaCard = "hana-card",
  KbCard = "kb-card",
}

export const CARD_ISSUERS = Object.values(CardIssuer);
```
맞을까요? 어떤 유의미한 차이가 있는지 느낌이 잘 오질 않네요..!

2024-04-30 01:03 UTC, igy95 commented on src/hooks/common/useBoolean.ts
> +  };
네 올려주신 예시가 맞습니다. 의존성 배열에 추가되었다면, 말 그대로 `useMemo`, `useCallback`, `useEffect` 등의 훅 내에서 해당 함수가 호출될 때겠죠!

2024-04-30 01:07 UTC, igy95 commented on src/styles/common.ts
질문 주신 부분이 맞습니다. 단순 스타일만 적용하는 코드라도 재사용이 가능하다면, 컴포넌트화 할 수 있어 보여요. 좀 더 직관적인 이해를 위해 저희 회사 [디자인 시스템 중 일부](https://main--62bead1508281287d3c94d25.chromatic.com/?path=/docs/components-text--docs)를 첨부해둘게요! 나중에 참고해보시면 좋을 듯 합니다.

2024-04-30 01:12 UTC, igy95 commented on src/constants/cardIssuers.ts
> +export const CARD_ISSUERS = [
아래의 예시를 보면, 배열은 값의 접근을 위해 반드시 서로 간의 순서를 의식하면서 작성해야 한다는 불편함이 존재합니다.

```ts
// 배열 사용례

// 값 접근
const kbCard = CARD_ISSUERS[7]

// destructuring
cosnt [, , , , , , kbCard] = CARD_ISSUERS

// 객체 사용례

// 값 접근
const kbCard = CardIssuer.KbCard

// destructuring
const { KbCard } = CardIssuer
```

2024-04-30 01:19 UTC, igy95 commented on src/constants/cardIssuers.ts
> +    text: "신한카드",
아하, 기획 의도가 그러하다면 key를 분리해서 데이터를 각각 관리할 수 있을 듯 합니다. 다만 `label`, `text`라는 키는 서로 간의 큰 구별성이 없기 때문에 추후 다른 작업자가 이 쪽에서 데이터를 추가하고자 할 때 헷갈릴 수 있을 것 같아요~ 때문에 `cardName`, `bankName`과 같이 사용처를 추론할 수 있는 구체적인 이름을 부여하는 게 어떨까 싶습니다.

2024-04-30 01:21 UTC, igy95 approved these changes
안녕하세요 수야~ 추가 코멘트 남겨두었으니 확인 부탁드리며 해당 미션은 이만 머지하도록 하겠습니다. 고생 많으셨습니다!

2024-04-30 01:21 UTC, merged