[2단계 - 페이먼츠] 빙봉(김윤경) 미션 제출합니다.
woowacourse/react-payments pull request #400
Opened 2024-04-28 08:19 UTC by Yoonkyoungme

2024-04-29 16:35 UTC, uk960214 requested changes
2단계도 구현하느라 수고가 많으셨습니다!
훅의 사용도 깔끔하고, 디테일적인 부분도 많이 챙겨주셔서 너무 좋았습니다!
크게 구조적으로는 손 볼 것이 없을 것 같고 주로 리팩토링 관련 부분들 위주로 코멘트 남겼습니다!

추가적으로 구현 결과물에서 발견한 부분이 있는데요,
number 인풋을 사용한 것은 좋은 방식이라고 생각합니다! 다만 이 경우에도 e 같은 수학적으로는 숫자로 판단될 수 있는 일부 문자열이 들어갈 수 있어요! 이는 물론 악용하는 사례고 다행히 regex로 유효성에서 막히긴 하겠지만 정말 엄격하게 입력 자체를 막고 싶다면 text 인풋에 regex로 입력을 제한하는 방법이 더 적합하긴 합니다!
<img width="475" alt="image" src="https://github.com/woowacourse/react-payments/assets/43166681/6b1d8c83-f4d3-460b-b868-cb3da6b8d460">

다음 미션까지 시간이 짧긴 하지만 코멘트 한 번 확인해보시고 다시 리뷰요청 주세요!

2024-04-29 16:35 UTC, uk960214 commented on src/components/common/Select/index.tsx
> +      )}
이런 처리는 아주 꼼꼼하네요!

2024-04-29 16:35 UTC, uk960214 commented on src/components/common/Input/style.module.css
> +
input의 타입을 활용하고 number일 때도 이 스타일까지 신경써준 부분 아주 좋습니다!

2024-04-29 16:35 UTC, uk960214 commented on src/components/common/Button/index.tsx
> +/* eslint-disable react/button-has-type */
이 lint 룰을 꺼야만 했던 이유가 무엇인가요??

2024-04-29 16:35 UTC, uk960214 commented on src/components/CardPreview/CardFront/index.tsx
>              />
기존의 이 함수를 그대로 사용한다면 미션의 요구사항 중 이 항목을 충족하지 못할 것 같아요!
> 불필요한 상태 관리나 리렌더링이 발생하지 않도록 한다.
예를 들어 카드 번호 입력 시 매 입력마다 브랜드 식별 로직이 동작하는 것은 비효율적일 수 있다. 일정 자릿수 이상 입력된 경우에만 브랜드 식별을 하는 등의 방법으로 개선한다.

2024-04-29 16:35 UTC, uk960214 commented on src/components/CardInput/InputContainer/ExpirationPeriodInput/index.tsx
> +  }, [period.month]);
month의 input에 onChange 핸들러에 이 로직을 넣는다면
이펙트 훅을 사용하지 않고도 focus에 대한 부분을 처리할 수 있지 않을까요??

2024-04-29 16:35 UTC, uk960214 commented on src/components/CardInput/InputContainer/PasswordInput/index.tsx
> +        <div>
이 div는 어떤 의미가 있나요? 스타일 상 필요한 부분이었을까요??

2024-04-29 16:35 UTC, uk960214 commented on src/hooks/cardForm/useCVCInput.ts
> +    }
이 로직을 밖으로 빼서 이 훅에서 상태가 아닌 변수로 관리할 수도 있지 않을까요??

```tsx
const isCVCNumberFilled = CVCNumber.length === maxLength
```

2024-04-29 16:35 UTC, uk960214 commented on src/constants/regex.ts
> +export default INPUT_REGEX;
regex로 검증을 해주는 부분 아주 좋습니다!

2024-04-29 16:35 UTC, uk960214 commented on src/hooks/cardForm/useCardExpirationPeriodInput.ts
> +    );
이 조건문은 조금 더 쉽게 쓸수 있지 않을까요!

2024-04-29 16:35 UTC, uk960214 commented on src/hooks/cardForm/useCardExpirationPeriodInput.ts
> +    }
이것도 위에 언급한 것처럼 밖으로 빼서 상태가 아닌 일반 변수로 관리하게되면 핸들러 함수의 길이도 짧아질 수 있을 것 같네요!

2024-04-29 16:35 UTC, uk960214 commented on src/hooks/cardForm/useCVCInput.ts
> +  const [showCardBack, setShowCardBack] = useState(false);
이 상태가 CVCInput의 훅에만 존재한다면,
(가능성은 적겠지만) 다른 방식으로 카드의 뒷면을 보고자한다면 구현을 바꾸지 않고는 어려울 것 같아요!
오히려 이 훅의 외부에서 set할 수 있는 함수만 넘겨주고, 이 훅에서는 필요할 때 그 함수를 호출하기만 하는 것은 어떨까요?

2024-04-30 16:47 UTC, Yoonkyoungme reviewed
안녕하세요 블링✨

남겨주신 피드백 확인하고, 반영해 보았습니다😊
한 가지 질문이 있습니다!
Q. 현업에서는 주로 input 태그의 type 속성을 text로 사용하는지 궁금합니다! 
블링이 언급해주신 것처럼 엄격하게 입력 제한을 하기 위해 숫자를 입력 받는 필드에서도 type 속성을 number가 아닌 text를 주로 사용하는지 궁금합니다!

이번 미션에서 step1, step2 모두 어려웠지만, 피드백을 바탕으로 고민을 많이 해보고 새로운 내용도 많이 배워서 즐거웠습니다! 
그래서인지 블링과 더 많은 리뷰를 주고 받지 못한 것이 아쉽네요ㅜ0ㅜ (더 빨리 구현할걸...후회중입니다 핳핳)
그만큼 너무나도 도움이 되고, 귀중한 시간이었어요!! 감사합니다 블링⭐️

2024-04-30 16:47 UTC, Yoonkyoungme commented on src/components/CardInput/InputContainer/PasswordInput/index.tsx
> +        <div>
엇! 의미없는 div 태그입니다😂 
스타일 적용하려고 <Input />을 감싸기 위해 사용했던 div가 중복되었던 것 같아요.
사용하지 않는 div 태그를 삭제하였습니다!

반영 커밋: 0ad37fa1fe9ab86ce7d1412f4bb23a80c853bb77

2024-04-30 16:51 UTC, Yoonkyoungme commented on src/hooks/cardForm/useCVCInput.ts
> +  const [showCardBack, setShowCardBack] = useState(false);
카드 방향 상태를 관리하는 `useCardDirection` 커스텀 훅을 만들어서 사용해 보았습니다!

반영 커밋: b72bbf88157e27b65d88507927c505190f528e95

2024-04-30 16:52 UTC, Yoonkyoungme commented on src/hooks/cardForm/useCVCInput.ts
> +  const [showCardBack, setShowCardBack] = useState(false);
카드 방향 상태를 관리하는 `useCardDirection 커스텀 훅`을 만들어서 리팩터링 해보았습니다!

반영 커미시 b72bbf88157e27b65d88507927c505190f528e95

2024-05-03 07:38 UTC, uk960214 approved these changes
늦어서 죄송합니다 빙봉! 페이먼츠 미션 구현하느라 고생 많으셨습니다!
의견을 많이 주고받지는 못해서 저도 아쉽지만 지금 결과물은 아주 훌륭하다고 생각합니다!

> 숫자를 입력 받는 필드에서도 type 속성을 number가 아닌 text를 주로 사용하는지 궁금합니다!

네 종종 있었어요! 원하는 것이 HTML의 스펙처럼 숫자로 취급될 수 있는 모든 것 (e 등 특수 숫자, 소숫점 등등)이 아니라 정말 자연수만 원할 때는 확실히 텍스트로 받아서 정규식 등으로 컨트롤하는 경우가 많은 것 같습니다. 지금은 입력값을 토대로 어떤 계산을 하거나 서버에 저장하는 것은 아니라서 큰 문제가 되지 않을 수는 있지만 나중에는 예상하지 못한 값이 어떤 로직을 깨뜨리게 될지는 확실히 모르는 것이니까요!

이번 미션이 즐거우셨다니 다행입니다. 앞으로 남은 미션들도 다 더 즐겁길 바랍니다! 화이팅 💪

2024-05-03 07:38 UTC, uk960214 commented on src/components/CardInput/InputContainer/CVCInput/index.tsx
> +        <div>
(사실 여기도 안쓰는 div가 있답니다! 여러 군데 있었어요!)

2024-05-03 07:38 UTC, uk960214 commented on src/constants/regex.ts
> +};
👍

2024-05-03 07:38 UTC, uk960214 commented on src/hooks/cardForm/useCVCInput.ts
> +    }
그렇다면 지금 구현대로 가도 충분할 것 같아요! 충분히 고민해주셔서 감사합니다!

2024-05-03 07:38 UTC, uk960214 commented on src/hooks/cardForm/useCardExpirationPeriodInput.ts
> +    setPeriodErrors((prevErrors) => ({ ...prevErrors, expired: isExpired }));
```suggestion
    setPeriodErrors((prevErrors) => ({
      ...prevErrors,
      [type]: !isValidPeriod,
      expired: isExpired
    }));
```

로 해도 동일한걸까요?

2024-05-03 07:38 UTC, uk960214 commented on src/hooks/useCardDirection.ts
> +export default useCardDirection;
이렇게 커스텀 훅을 빼서 아주 깔끔하게 잘 관리해주신 것 같아요!

2024-05-03 07:38 UTC, uk960214 commented on src/components/common/Button/index.tsx
> +/* eslint-disable react/button-has-type */
오호 처음 보는 룰이고 좀 답답한 룰이네요.. 이런건 아예 eslintconfig 수준에서 전체 프로젝트에 대해서 꺼주어도 좋을 것 같네요!

2024-05-03 07:38 UTC, merged