[2단계 - 페이먼츠 미션] 서니(박선희) 미션 제출합니다.
woowacourse/react-payments pull request #50
Opened 2021-05-16 06:41 UTC by sunhpark42

안녕하세요! 페이먼츠 2단계 미션 제출합니다. 

장바구니 미션을 하다보니 많이 늦어졌네요. 죄송합니다 💦💦

리뷰 잘 부탁 드립니다!🙏🙏

### 1단계 PR 링크

*   #14 

### [데모페이지](https://ww-sunny-payment.netlify.app/)

### 작동 화면

![](https://user-images.githubusercontent.com/67677561/118388028-e929a880-b65c-11eb-9242-d2be90e55d99.gif)

## **2단계 필수 요구사항**

*   **`Storybook`** 상호 작용 테스트
*   **`Controlled`** & **`Uncontrolled Components`**에 입각하여 **`Form`** 핸들링
*   **`Context API`**를 활용해 전역 상태 관리 및 계층 재구성

#### **필수 구현**

*   카드 목록

## 2단계 기능 구현 목록

\- \[x\] 사용자의 카드 목록을 바탕으로 카드 이미지와 별칭을 나열하여 표시한다.

\- \[x\] 카드를 클릭 시 카드 별칭을 수정할 수 있다.

\- \[x\] 카드 추가 버튼 ( + 가 있는 빈 카드 이미지 )를 클릭하면 카드 추가 화면으로 이동한다.

## 변경된 부분

*   Context API를 이용하여 전체 카드 목록을 관리해 보았습니다.
*   customHook을 이용하여 form 을 핸들링 해보았습니다.
*   CardCompanySelectOption, CardCompanySelector가 앱에 한정적인 것 같아 Option, Select로 다른 곳에서도 이용할 수 있도록 변경해 보았습니다.
*   공통되는 css 속성을 추출했습니다.

2021-05-16 15:46 UTC, ysm0622 requested changes
고생하셨습니다! 👏 👏 👏

2021-05-16 15:46 UTC, ysm0622 commented on src/pages/AddCardForm/Inputs/SerialNumberInput.js
> +  const getCurrentSerialNumber = {
객체인데 변수의 이름은 get으로 시작하네요..!

2021-05-16 15:46 UTC, ysm0622 commented on src/pages/AddCardForm/Inputs/SerialNumberInput.js
> +    },
이건 무슨코드인가요? 👀

2021-05-16 15:46 UTC, ysm0622 commented on src/pages/AddCardForm/Inputs/SerialNumberInput.js
> +  };
파라미터를 받아서 좀더 범용적인 형태로 작성할 수 있지 않을까요? 👀

2021-05-19 07:35 UTC, sunhpark42 commented on src/pages/AddCardForm/Inputs/SerialNumberInput.js
> +  const getCurrentSerialNumber = {
앗 그러네요! 실제 사용할 때 함수처럼 사용하다보니 이름을 지을 때 생각을 잘못한 것 같습니다 ㅠㅠ

2021-05-19 07:35 UTC, sunhpark42 commented on src/pages/AddCardForm/Inputs/SerialNumberInput.js
> +    },
현재 카드 번호의 입력을 input 하나로 받고있고,
예를 들어 사용자가 1234123412341234 라는 값을 작성하면
1234-1234-****-**** 로 변환해서 input value로 다시 넣어서, 포맷팅 된 채로 보여지게끔 코드를 작성하였습니다.

그 과정에서 * 로 숨김처리 된 부분이 실제 숫자인 1 이아니라 * 로 저장되게 되어 이후에 수정을 할 때
target.value가 마스킹 처리된 텍스트로 불러와지는 문제가 있었습니다.
이를 해결하기 위해서 input이 발생할 때 지우는 이벤트인지, 삽입하는 이벤트인지를 구분해서
저장된 상태에 들어온 값을 저장시켜주는 과정을 거쳤고,
붙여넣기의 경우에는 몇글자가, 어느위치에 삽입되는지 파악이 어려워, 붙여넣기를 못하게끔 코드를 작성하였습니다.

2021-05-19 07:35 UTC, sunhpark42 commented on src/pages/AddCardForm/Inputs/SerialNumberInput.js
> +  };
파라미터를 이용하면, 다른 컴포넌트에서도 사용할 수 있을 것 같네요. 이 부분은 수정해 보겠습니다~🙂🙂

2021-06-04 10:18 UTC, sunhpark42 commented
안녕하세요, 성민님! 많이 늦었네요 ㅠㅠ 2단계 리뷰 반영해보았습니다. 🙏

항상 리뷰 감사드립니다 :)

변경된 부분

*   checkValidity 분리   
    c50abe7
*   getCurrentSerialNumber => currentSerialNumberByInputType 변경   
    71e7c77
*   에러 메세지 상수화   
    df7603b
*   securityCode Input을 컴포넌트로 분리   
    f509c34

2021-06-05 05:32 UTC, ysm0622 approved these changes
피드백 잘 반영되었네요! 감사합니다 🙇 

고생하셨습니다! 👏 👏 👏 👏

2021-06-05 05:32 UTC, merged

2021-06-23 08:55 UTC, sunhpark42 commented
## 페이먼츠 학습로그

### Context API

* Context를 이용하면 tree의 level별로 props 를 전달하지 않고, Context에 포함되어 있는 컴포넌트 트리 전체에 데이터를 제공할 수 있다. 
* 전역으로 관리되는 데이터를 공유할 때 유용함(ex, 로그인 정보, 테마, 언어 등)
* Context로 관리하는 값이 변화하면 해당 Context에 속한 전체 Component가 rerendering 된다.
* ! Context를 이용하면 컴포넌트를 재사용하기 어려워진다는 단점이 있다.
* 참고자료
  * [Context](https://ko.reactjs.org/docs/context.html#api)

### Controlled Component & Uncontrolled Component

* Controlled Component

  1. 리액트가 변화하는 상태에 대한 통제권을 가짐
  2. 값의 동기화
  3. 값을 이용하는 데, event, ref 등을 이용할 필요가 없어 간편함.
  4. 값의 변화가 실시간으로 다른 요소에 영향을 미치는 경우 유용하게 사용할 수 있음. (ex. 장바구니의 가격 변동)

* Uncontrolled Component

  1. 기존 html tag 와 동일함.
  2. 값이 동기화 되지 않고, 이벤트가 발생할 때 혹은 ref를 이용해서만 조작이 가능하다는 단점이 있음.
  3. 페이먼츠를 진행하면서 값을 포맷팅 하는 등 새로운 값을 넣어주거나 할 때, state가 변화되는 순서가 커서가 이동되는 순서 이후라 조작이 어려웠음. Uncontrolled Component를 이용하면 해결이 가능.

* 참고자료

  * [React Docs : React 기술 용어 모음 - 제어컴포넌트 vs 비제어 컴포넌트](https://ko.reactjs.org/docs/glossary.html#%EC%A0%9C%EC%96%B4-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-vs-%EB%B9%84%EC%A0%9C%EC%96%B4-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8)

  * [React Docs : Advanced guide - Uncontrolled Components](https://reactjs.org/docs/uncontrolled-components.html)
  * [React Docs : Main Concepts - Forms - Controlled Components](https://reactjs.org/docs/forms.html#controlled-components)