[1단계 - 페이먼츠] 마르코(장원석) 미션 제출합니다.
woowacourse/react-payments pull request #79
Opened 2022-04-28 17:24 UTC by wonsss

### [데모페이지](https://sweet-sprite-876774.netlify.app/)
### [스토리북 배포페이지](https://626aa58effc760004af7707e-ugpdoodfng.chromatic.com/)

안녕하세요. 리뷰어님. 마르코입니다. 이번에 아놀드와 함께 리액트 미션을 열심히 해보았습니다.
부족한 점이 많은 코드지만, 많은 관심과 피드백 부탁드립니다. 🙇 

구현 결과는 상단의 데모페이지와 스토리북 배포페이지 링크를 참조해주시기 바랍니다.

## 구현 사항
- [x] 카드 추가
	- [x] 인풋 입력과 동시에 카드이미지에 렌더링된다.
	- [x] 인풋 입력 시 유효성 검사(상세 유효성 검사 목록은 문서 참조) 	
- [x] 유효성 검증 실패에 대한 UI/UX(인풋 하단에 빨간색 에러메시지) 추가
- [x] 모든 유효성 검사가 통과되어야 '다음' 버튼 활성화
	- [x] '다음' 버튼 클릭 시, 입력된 인풋 데이터들을 콘솔에 기록 
- [x] 카드사 선택 모달
- [x] 선택된 카드사의 색상에 따라 모든 인풋 텍스트 및 버튼 색상 동기화  
- [x] Context API 및 reducer 활용
- [x] Storybook 상호작용 테스트(아직 스토리북이랑 덜 친해졌습니다..ㅠ)

![image](https://user-images.githubusercontent.com/59413128/165807316-afd0a45c-3f50-4501-a8f8-3f934ad00bba.png)

## 폴더 구조
```
📦 
─ src
   ├─ App.jsx
   ├─ CardAddition.jsx
   ├─ CardContext.js
   ├─ components
   │  ├─ Card.jsx
   │  ├─ CardCompany.jsx
   │  ├─ CardCvc.jsx
   │  ├─ CardExpiration.jsx
   │  ├─ CardListModal.jsx
   │  ├─ CardNumber.jsx
   │  ├─ CardOwner.jsx
   │  ├─ CardPassword.jsx
   │  ├─ Circle.jsx
   │  ├─ Dimmer.jsx
   │  ├─ ErrorMessage.jsx
   │  ├─ MoveButton.jsx
   │  ├─ PageTitle.jsx
   │  ├─ TipButton.jsx
   │  ├─ ToastModal.jsx
   │  └─ Wrapper.jsx
   ├─ constants
   │  └─ index.js
   ├─ hooks
   │  └─ useInitialAppValue.js
   ├─ index.css
   ├─ index.jsx
   ├─ reducers
   │  └─ index.js
   ├─ stories
   │  ├─ Card.stories.jsx
   │  ├─ CardCvc.stories.jsx
   │  ├─ CardExpiration.stories.jsx
   │  ├─ CardNumber.stories.jsx
   │  ├─ CardOwner.stories.jsx
   │  ├─ CardPassword.stories.jsx
   │  ├─ MoveButton.stories.jsx
   │  └─ PageTitle.stories.jsx
   ├─ styles
   │  ├─ Container.js
   │  ├─ InputBasic.js
   │  ├─ InputBox.js
   │  ├─ InputContainer.js
   │  └─ InputTitle.js
   └─ validations
      └─ validator.js
```

## 질문
### 1. form 태그 필요여부
이번 미션에서 form 태그를 사용하지 않았습니다. 왜냐하면 input 태그들이 onChange 될때마다 state가 갱신되므로, '다음' 버튼을 클릭할 때 그 시점 state들을 넘겨주면 된다고 판단했기 때문입니다.
이러한 경우에도 혹시 form 태그로 묶어줘야 할 필요가 있는지 모르겠습니다. 이와 관련하여 리뷰어님의 의견이 궁금합니다.

### 2. 컴포넌트 단위
컴포넌트를 어느 정도로 작게 만들어야 하는지 아직 잘 모르겠습니다. 이번 미션에서는 '카드번호' 인풋 컴포넌트, '카드만료일' 인풋 컴포넌트와 같이 컴포넌트에 도메인이 반영되도록 만들었습니다. 그런데 이런 컴포넌트 단위보다 '도메인이 반영되지 않은 더 작은 UI 요소적인 컴포넌트 단위'로 개발하는 것이 더 적절한지 고민됩니다. 재사용성 측면에서는 마치 라이브러리처럼 도메인을 모르는 더 작은 요소의 컴포넌트를 만드는 게 적절할 것 같다는 생각이 들기 때문입니다. 이와 관련하여 리뷰어님의 의견이 궁금합니다.

### 3. context API 사용 기준
[react 공식문서](https://ko.reactjs.org/docs/context.html)에서 "context를 사용하면 컴포넌트를 재사용하기가 어려워지므로 `꼭 필요할 때`만 사용하라"는 내용을 확인했습니다. `꼭 필요할 때`가 언제인지..아직 느낌이 잘 오지 않습니다.  페어와 함께 의견을 나눈 결과, prop drilling 해야 하는  depth가 2 이상일 때, context를 쓰면 좋을 것 같다고 생각하긴 했으나, 리뷰어님의 의견은 어떤지 궁금합니다.

2022-04-30 12:34 UTC, youngbeomrhee requested changes
마르코님 안녕하세요 리뷰를 맡은 YB입니다
기능을 테스트 해보면서 input값에 따라 실시간으로 안내메시지를 보여주는 점이나 카드 컬러에 따라 텍스트 컬러도 변경되게 한 점, 이름이 줄내림 되지 않도록 처리한 것 등등 사용성에 정말 많은 고민을 하신게 느껴졌습니다
사소한 기능적 오류와 코드 레벨에서 개선해 보시면 좋을 것 같은 사항이 일부 있어서 개선요청 드립니다

# 기능상 오류
숫자입력칸의 마지막 입력값으로 소수점 입력 가능 (예: 100.)

# 기능상 보완
보안카드 안내버튼(?) 미작동
사소한 거지만 스토리북의 컴포넌트에 설정한 기본 색상 (#04C09E)의 가독성이 좋지 않네요. 처음에는 안느껴지다가 CardOwner에서 안내문구가 길어지니 눈이 좀 부시네요

# 질문에 대한 답변
- form 태그 필요여부
form element의 사용은 편의를 위한 것이고 필수는 아닙니다. 과거에는 form을 사용할 때 몇 가지 이점이 있었지만 React를 사용하고 input의 값을 직접 state와 매핑해서 사용하는 방식에서는 사용상의 이점이 거의 없기 때문에 사용하지 않으셔도 무방할 것 같습니다
- 컴포넌트 단위
UI의 일관성과 재사용성을 위해서 컴포넌트를 특정 도메인에 종속되지 않도록 설계하고 그런 컴포넌트들을 조합해서 특정 도메인에 적합한 컴포넌트로 만들어 가는 과정은 물론 의미있는 작업입니다. 관련해서는 Atomic Design 관련된 내용을 참고하시면 도움이 될 것 같습니다. 하지만 개인적으로는 초기 개발단계에 그렇게 재사용성을 고려하여 만든다고 하더라도 예상과 달리 재사용이 안되는 경우도 많고 요구사항이 변경되는 경우도 빈번해서 너무 작은 단위로 쪼개 놓은 경우 수정이 어렵게 되기도 합니다. 그리고 실무에서 실제로 재사용을 하기 위해서는 특정 컴포넌트의 존재를 한 눈에 볼 수 있는 장치도 마련되어야 하고 디자인팀에서 제공해 주는 단위와 일치시켜야 컴포넌트 제작이 용이해지는 면도 있습니다. 정리드리자면 훈련을 위해서 그런 고민을 하고 설계해 보는 훈련은 충분히 의미있는 과정이라 시간여유가 된다면 시도해 보시면 좋을 것 같습니다. 그리고 실무에서는 충분히 팀원분들, 그리고 디자인팀등의 연관된 팀원분들과 협의를 통해 조금씩 개선해 보시면 좋을 것 같습니다
- 결국 전역으로 관리해야 될 값이나 state가 있는지, Props drilling이 너무 깊어지는 경우가 있는지가 사용기준이 될 것 같습니다. 하지만 실무에서 그렇지 않은 경우는 거의 없기 때문에 상태관리를 할 수 있는 기술은 항상 적용하게 되는 것 같습니다. 그냥 단순히 사용하자면 Context API나 Zustand 같은 것들을, 조금 더 복잡해지자면 Redux, Recoil 등을 그런 상태관리가 API에 종속된 경우라면 RTK Query, React Query 등의 도입을 고민하게 되는 것 같습니다

이외에 코드 레벨에 코멘트 드린 내용 참고하셔서 코드를 개선해 보시면 좋을 것 같습니다 :)

2022-05-02 11:12 UTC, wonsss commented on src/stories/Card.stories.jsx
> +PocoCard.args = {
그렇네요! 해당 부분 함수로 분리하는 식으로 리팩토링해봤습니다.

[refactor: 동적인 값만 넘기면 고정된 값과 조합하여 리턴하는 함수를 분리](https://github.com/woowacourse/react-payments/pull/79/commits/3e06cc3e18791178292192045e658393e0563ae6)

2022-05-02 11:19 UTC, wonsss commented on src/CardAddition.jsx
> +  const validateAllInputs = () => {
말씀처럼 이 함수에서 두 가지 사항 모두 혼란을 야기하네요. 불린 값을 리턴하는 함수이므로 is-prefix를 붙였고, 유효성 검사 통과 시 true를 리턴하도록 수정하였습니다. 그리고 해당 함수가 호출되는 input의 `disabled={}` prop에서는 `!isAllInputValidated()`처럼 앞에 `!`을 붙여줬는데 어떻게 생각하시나요? 😄 

[refactor: 유효성 검사 로직의 prefix 및 flow 개선](https://github.com/woowacourse/react-payments/pull/79/commits/5d2efeedb16a2fab4d6729ac0b8126ddfd311253)

2022-05-02 11:43 UTC, wonsss commented on src/components/CardExpiration.jsx
> +  const validate = (value) => value.join('') && validator.checkCardExpiration(value);
`value.join('')`의 목적은 인풋들이 비었을 때 유효성 검사를 하지 않도록 하는 것입니다. 사용자가 아직 인풋에 어떠한 값도 입력하지 않은 상태인데 빨간색 에러 메시지가 표시되어 있으면 사용자 경험에 좋지 않을 것이라고 판단했습니다. 

다시 코드를 살펴보니, 해당 로직은 validator.js에서 각 유효성 검사 로직 내에 포함시키는 것이 적절하다고 생각하여 이동하였고, 배열의 값이 모두 비어있는지 확인하기 위해 사용했던 join 메서드 대신에 의도가 조금 더 명확히 보이는 every 메서드를 사용하여 리팩토링해보았습니다. 리팩토링한 부분에 대해 어떻게 생각하시는지 궁금합니다. 😄 

[refactor: 인풋이 비었을 때 유효성 검사하지 않도록 하는 로직을 validator로 이동](https://github.com/woowacourse/react-payments/pull/79/commits/e4cc8ad486e2069d6a35fb2e7caf522a334be99f)

2022-05-02 12:47 UTC, wonsss commented on src/components/CardExpiration.jsx
> +          <InputBasic
말씀대로 스타일만 있는 styled-component와 로직이 있는 react 컴포넌트가  네이밍 때문에 구분되지 않네요. 검색하여 찾은 `S-dot` 네이밍 컨벤션을 적용해봤습니다.
- 참고 : [Medium 블로그 글 : naming-styled-components](https://medium.com/inturn-eng/naming-styled-components-d7097950a245)
[refactor: styled-component naming convetion을 s-dot으로 변경](https://github.com/woowacourse/react-payments/pull/79/commits/53d1d82479abb399e97d90dd42363fd049652edc)

그리고 컴포넌트에서 스타일 로직과가 기능 로직을 분리하는 작업을 추가로 해보았습니다.
[refactor: 스타일 로직과 기능 로직 분리](https://github.com/woowacourse/react-payments/pull/79/commits/0e30ba74801eb76a517b6b2c3706086c7d894575)
[refactor: styled component에 boolean 값 전달하도록 수정](https://github.com/woowacourse/react-payments/pull/79/commits/f1c757c0d7ca941488097e06dcafc570fdaac98a)

2022-05-02 15:28 UTC, wonsss commented on src/constants/index.js
> +const CARD_COMPANIES = [
reducer에서 사용하는 action type을 상수로 분리하였습니다. 😄 
혹시 추가로 더 상수 분리할만한 영역이 있을까요?

[refactor: action type 상수 분리](https://github.com/woowacourse/react-payments/pull/79/commits/11e26965a07127c98cf4442e2464e804276e20b8)

2022-05-02 17:07 UTC, wonsss commented
안녕하세요. YB님. 좋은 리뷰 감사합니다. 👍 
질문에 대하여 답변 주신 내용 확인하였습니다!
그리고 코멘트 달아주신 부분에 대해서도 수정사항을 댓글로 달고 커밋 링크도 붙였습니다.

기능상 보완을 권해주셨던 부분에 대해서도 아래와 같이 코드를 작성했습니다.

> 숫자입력칸의 마지막 입력값으로 소수점 입력 가능 (예: 100.)
[fixed: 인풋에 '.' 입력 시 숫자로 판단되던 이슈 해결](https://github.com/woowacourse/react-payments/pull/79/commits/652ac6d64fb83ec70d8b6fcec8b4b3f562edf00c)

> 보안카드 안내버튼(?) 미작동
[feat: 물음표 클릭 시 CVC 안내 문구 표시](https://github.com/woowacourse/react-payments/pull/79/commits/eab548820be3510efeac550f895e8ff6088ba4dc)

> 사소한 거지만 스토리북의 컴포넌트에 설정한 기본 색상 (#04C09E)의 가독성이 좋지 않네요. 처음에는 안느껴지다가 CardOwner에서 안내문구가 길어지니 눈이 좀 부시네요
[feat: 스토리북 인풋 기본 색상 변경](https://github.com/woowacourse/react-payments/pull/79/commits/de3868b09316a2b7a5339cddcad85d5d011ac67e)

2022-05-04 15:40 UTC, youngbeomrhee commented on src/CardAddition.jsx
> +  const validateAllInputs = () => {
예 좋습니다 함수명만 봐도 기능이 유추되서 한결 가독성이 좋아진 것 같습니다

2022-05-04 15:49 UTC, youngbeomrhee commented on src/components/CardExpiration.jsx
> +  const validate = (value) => value.join('') && validator.checkCardExpiration(value);
입력값이 모두 비어있는 경우는 검증을 피하기 위한 의도였군요!
every 메서드를 사용해서 해당 입력값이 비어있는 경우 (''인 경우)로 개선해 주셔서 한결 가독성이 좋아졌네요 👍

2022-05-04 16:14 UTC, youngbeomrhee commented on src/constants/index.js
> +const CARD_COMPANIES = [
일반적으로는 에러메시지, 안내메시지 등 여러 곳에서 재사용되고 요구사항에 따라 변경 가능성이 높은 구문들도 상수로 분리하면 좋을 것 같은데요
현재 상황에서는 요구사항이 고정이고 재사용 되는 경우도 없기 때문에 참고만 하시면 될 것 같습니다

2022-05-04 16:25 UTC, youngbeomrhee approved these changes
마르코님 안녕하세요 코드 개선해 주시느라 고생 많으셨습니다
기능상 오류 수정, 피드백 드린 사항에 대한 개선 모두 확인했습니다
Step1에 필요한 사항 모두 다 잘 구현해 주셨고 개선도 잘 수행해 주셔서 Approve 하도록 하겠습니다
코드에 남겼던 피드백에 대해 개선 및 질문주신 사항에 대해서도 답변 달았으니 확인해 보시고 Step2 구현하실 때 필요하신 사항 참고하시면 될 것 같습니다
고생하셨습니다 Step2에서 뵙겠습니다~

2022-05-04 16:25 UTC, youngbeomrhee commented on src/components/Card.jsx
> +      <S.SmallCard onClick={onClick} color={color}>
styled-component인지 react 상의 component인지 한 눈에 보이네요 💯

2022-05-04 16:25 UTC, youngbeomrhee commented on src/index.jsx
> +const GlobalStyle = createGlobalStyle`
이 부분도 다른 styled-component와 동일한 naming convention이 적용되면 좋을 것 같네요

2022-05-04 16:27 UTC, merged

2022-05-05 01:59 UTC, wonsss commented on src/components/CardExpiration.jsx
> +          <InputBasic
저두 하나의 파일에 styled-component들을 모두 정의하는 것이 과연 적합할까 고민이 들긴 했어요.
말씀하신 것처럼 styled-component는 특정 컴포넌트에서만 적용되는 개별적인 rule로서 사용하는 방향이 더 적합할 것 같네요.
말씀해주신 내용 염두하여 앞으로 각 기술이 적합한 방향으로 사용해보겠습니다!

2022-05-05 02:02 UTC, wonsss commented on src/constants/index.js
> +const CARD_COMPANIES = [
넵! 에러메시지 등도 재사용되기 시작할 때 상수로 분리해보겠습니다! 😄

2022-05-05 04:30 UTC, wonsss commented on src/index.jsx
> +const GlobalStyle = createGlobalStyle`
넵! 수정하겠습니다!