[1단계 - 페이먼츠] 병민(윤병인) 미션 제출합니다.
woowacourse/react-payments pull request #87
Opened 2022-04-28 20:48 UTC by airman5573

[데모페이지](https://airman5573.github.io/react-payments/)

안녕하세요 노스님! 이번 리뷰 잘 부탁드립니다 :D 

## Tech Stack
- CRA
- TS
- Emotion, SCSS

...작성중

2022-04-30 16:06 UTC, hyoungnam requested changes
안녕하세요 병민님 반갑습니다~! 벌써 context api를 사용하시고 로직도 잘 분리해주신 코드 잘 봤습니다. 
또한 수정이 필요한 부분도 있습니다. 거의 모든 입력 요소를 **단 하나의 input과 text 속성**으로 제어하려고 하다보니 코드가 복잡해지지 않았나 생각합니다. 특히 카드번호와 만료일 인풋은 중간부분을 삭제하거나 바꾸려고 하였을때 제대로 동작하지 않습니다.
UI와 관련해서는 지금까지 제가 본 카드중에 최고였습니다. 이름 다음에 보안 코드로 넘어갈떄 플립되는 카드 애니매이션을 보고 감탄사가 나왔네요. 다만 보안 코드가 화면에 표시되는건 옥의 티ㅎ   
상단 카드에 기본값 NAME과 MM / YY 추가하면 좋을것 같아요
다음은 질문 답변이에요

> Atomic Design을 따라가는것이 어려웠습니다. 특히 Presentational Component와 Container Component둘다 Atomic인지 아니면 Container안에 Presentational이 있으니까 molecular인지 판단이 잘 서지 않았습니다. 우선 atoms에 폴더를 만들어서 둘다 같이 넣어 줬는데, 리뷰어님이 보시기에 이렇게 하는게 좋은 분리인지 알려주시면 감사하겠습니다!

일단 저는 atomic design  패턴은 잘못된 패턴이라고 생각합니다. 디자인관점에서 봤을때 컴퓨터가 처음나오고 인터넷이 처음 나온 시절에 atomic 사고로 ui를 만들지는 않았을테고, 사이트끼리 서로 디자인을 베끼고 사용자들에게 선택되어 남은 ui 요소가 있겠죠. 그리고 스마트폰이 등장하면서 HCI,UX 학계, 구글과 같은 업체에서 2D와 터치스크린에서 만들 수 있는 요소는 다 테스트한걸로 알고있습니다. 모바일 가이드라인 애플의 human interface guideline, 구글의 material design만 봐도 모두 atomic을 언급하지 않고 있고요.
지금은 작은 프로젝트여서 괜찮겠지만 지금 같은 구조가 더 커졌을때 관리하기 편할지는 잘 모르겠습니다. 도메인과 기능을 고려하지 않고 단순히 atomic구조나 역할별로 나누면 규모가 커졌을때 관리하기 힘들다고 생각합니다. (https://ahnheejong.name/articles/package-structure-with-the-principal-of-locality-in-mind)

> Emotion을 오래전에 써보고 이번에 호기심에 다시 써보았습니다. JS안에서 CSS를 작성했기 때문에 둘이 같이 붙어다녀서 관리상에는 좋았으나, CSS코드를 작성하는건 조금 불편했습니다. 자동완성은 되지만 backgroundColor 이런식으로 작성해야 하고, 또 자식을 스타일링할때는 '& > .child' 이런식으로 작은 따움표를 매번 써주고 객체형태로 할당해야 하는것도 불편했습니다. 그래도 이름 충돌날 걱정이 없는 부분은 좋았습니다. 혹시 현업에서는 하나의 프로젝트에 SCSS와 Emotion(혹은 styled-component)를 같이 쓰나요? 저는 큰 레이아웃 잡을때는 한눈에 코드를 볼 수있어서 SCSS도 같이 쓰면 좋을것 같다는 생각이 들었습니다.

두개를 같이 사용하는 경우는 들어본적이 없습니다. 저도 css와 css-in-js 장단점때문에 두개를 같이쓰면 어떨까 생각했는데 순수 css는 BEM을 잘 지키지 않는 이상 이름충돌문제가 너무 크다고 생각해요.

> 저희는 이번에 비밀번호 입력 필드에만 Autofocus를 설정해 주었는데, 혹시 현업에서 input이 많은 페이지를 개발할때 autofocus를 많이 지원해 주시나요? 혹 자주 쓰시는 라이브러리가 있다면 추천 부탁드립니다!

input이 많은 페이지를 다뤄보지 않아서 모르겠네요.  상황에 따라서 사용자의 흐름을 자동으로 focus해주는 건 좋은 UX라고 생각합니다. formik과 react-hook-form을 많이들 사용합니다.

코멘트는 사소한 부분이니 참고정도로 해주시고 언제든 편하게 답변이나 질문주세요~!

2022-05-03 04:45 UTC, airman5573 commented on src/App.tsx
> +    </div>
아직은 div나 form이나 크게 상관 없다고 생각했습니다.  
다음 버튼을 눌렀을때 context에서 사용자가 입력한 값들을 다 가져올 수 있기 떄문입니다.

다만, id를 form으로 주고 div를 쓰는것보다는 form을 쓰는게 더 나아보입니다!
왜냐하면
- 더 읽기가 좋습니다
- form을 안쓰면 submit input도 없기 때문에 required property 혹은 pattern프로퍼티를 활용하기 어렵습니다

2022-05-03 04:55 UTC, airman5573 commented on src/components/atoms/card/Card.tsx
> +}));
말씀하신대로 중요한 정보가 먼저 나와야 더 가독성이 좋아보입니다. 수정하겠습니다 :D

2022-05-03 05:05 UTC, airman5573 commented on src/components/atoms/card/Card.tsx
> +  const _color = isActive ? (color ? color : '#94DACD') : undefined;
네, 조금 더 가독성이 낫게 수정해 보겠습니다 :D

2022-05-03 05:16 UTC, airman5573 commented on src/components/molecules/CardNumberFieldset.tsx
> +    </Fieldset>
우선 Head와 Body라는 이름을 붙인 역사(?)를 말씀드리겠습니다!

Form을 보면 대부분 label이 있는 부분과 input이 있는 부분 이렇게 두개로 나뉘어져 있습니다.
그리고 label은 margin bottom이 들어가 있습니다.  
몇몇 fieldset의 label은 마진이 다르게 들어가있지만, 대부분 비슷합니다.  
그래서 저는 Fieldset, Label, Content 이렇게 나누고 싶습니다. 하지만 이게 Label이라는 이름과는 다르게 윗부분에 label뿐만 아니라 (이름 입력 필드에) 0/30 처럼 몇글자 입력했는지에 대한 정보도 보여주고 있어서 네이밍이 어려워 졌습니다.  
그래서 윗부분을 뜻하는 Head와 아래 내용물이 담긴 Content이렇게 나누려고 했는데, Head가 있으니 Content보다는 Body가 더 자연스러울것 같아서 그렇게 선정했습니다.

저도 Head, Body라는 이름 대신 더 적절한 네이밍이 필요할듯 싶은데,  
혹시 FieldsetHead, FieldsetContent 이거는 어떨까요?

2022-05-03 05:19 UTC, airman5573 commented on src/components/atoms/PageTitle.tsx
> +export default PageTitle;
의미 자체는 Page의 Title을 표시하는 컴포넌트 입니다.  
하지만 실제로는 보시다싶이 그냥 문자열을 div로 감싸고 있을 뿐입니다.  
atomic design을 하면서 조금 더 쪼개본건데, 지금 단계에서는 불필요할까요?  
개인적으로는 지금 당장은 필요 없어보이는데, page title에 뭔가 링크나 추가적인 css가 들어가면 필요하지 않을까 싶습니다.

2022-05-03 05:27 UTC, airman5573 commented on src/components/atoms/card/CardContainer.tsx
> +  const transform = (str: string) => {
네, 맞습니다. 수정하겠습니다 :D

2022-05-03 05:31 UTC, airman5573 commented on src/components/atoms/card-cvc/CVCInputContainer.tsx
> +      dispatch(createAction(ActionType.INPUT_CVC, cvc + lastChar));
앗, 놓쳤습니다. 삭제하겠습니다 :D

2022-05-03 06:08 UTC, airman5573 commented on src/components/atoms/card-owner/CardOwnerNameInputContainer.tsx
> +      const upperName = value.toUpperCase();
오 정규식으로 더 간단하게 만들 수 있을것 같습니다. 감사합니다 :D

2022-05-03 07:50 UTC, airman5573 commented on src/components/atoms/BackButton.tsx
> +      <img css={style} src="data:image/svg+xml;utf8;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9H
네 맞습니다. 수정하겠습니다 :D

2022-05-03 10:33 UTC, airman5573 commented on src/components/atoms/BackButton.tsx
> +      <img css={style} src="data:image/svg+xml;utf8;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9H
네, 맞습니다. 수정하겠습니다 :D

2022-05-03 10:47 UTC, airman5573 commented
안녕하세요 노스! 피드백 너무 감사드립니다.

- CVC 코드 안보이게 만들기 : [c7ed7b8](https://github.com/woowacourse/react-payments/pull/87/commits/c7ed7b8480178959669f388a26dbbbd2f134ae3c)
- directory 구조를 기능 중심으로 변경 : [aa048cb](https://github.com/woowacourse/react-payments/pull/87/commits/aa048cbab2978d2f29ed7a7160564c681bc97b5b)

첨부해주신 링크 잘 읽었습니다. 캐시 메모리에 빗대어 어떤 방식으로 디렉토리 구조를 짜야하는지 설명하는 방식이 독특하고 또 글에서 말하는 취지에 많이 공감했습니다. 어떤 기능을 수정하기 위해서 접근하는 디렉토리에는 그 기능과 관련된 컴포넌트들을 같이 놓으면 우리 뇌가 덜 피곤해진다는걸 알게되었고 실제로 그렇게 될것 같습니다. 좋은글 공유해주셔서 감사합니다 :D

2022-05-04 05:04 UTC, hyoungnam commented on src/components/molecules/CardNumberFieldset.tsx
> +    </Fieldset>
네 FieldsetHead, FieldsetContent로 이름을 하는게 좋은것 같아요~!

2022-05-04 05:05 UTC, hyoungnam commented on src/components/atoms/PageTitle.tsx
> +export default PageTitle;
말씀하신것처럼 추가된다면 필요할것 같고 2단계에서 보도록 해요~!

2022-05-04 05:10 UTC, hyoungnam commented on src/components/atoms/card/CardContainer.tsx
> +  const transform = (str: string) => {
Card 넘버와 관련된 함수여서 utils보다는 해당 컴포넌트와 가까이 두는것도 좋을것 같아요. utils는 보통 도메인과 관련되지 않은 함수들만 모으는 편이니까요

2022-05-04 05:12 UTC, hyoungnam commented on src/components/atoms/BackButton.tsx
> +      <img css={style} src="data:image/svg+xml;utf8;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9H
cra가 아니였군요ㅎㅎ 꼼꼼하게 확인했어야했는데.. webpack 설정 고생하셨어요!

2022-05-04 07:47 UTC, airman5573 commented on src/components/atoms/BackButton.tsx
> +      <img css={style} src="data:image/svg+xml;utf8;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9H
> 꼼꼼하게 확인했어야했는데..cra로 만들걸로 착각했네요 webpack 설정 고생하셨어요!

아닙니다, 이전에는 CRA였어요. 이번에 바꾼겁니다!

2022-05-04 08:04 UTC, airman5573 commented on src/components/molecules/CardNumberFieldset.tsx
> +    </Fieldset>
네, 수정하겠습니다 :D

2022-05-04 08:34 UTC, airman5573 commented on src/components/atoms/PageTitle.tsx
> +export default PageTitle;
네, 알겠습니다 :D

2022-05-04 08:40 UTC, hyoungnam commented on src/components/atoms/card/CardContainer.tsx
> +  const transform = (str: string) => {
card디렉토리 안에 utils를 두기도 합니다. 전역과 지역적 사용은 구분하면 편하고, 최대한 고립시키는게 좋다고 생각해요:)

2022-05-06 06:01 UTC, woowapark approved these changes
병민 안녕하세요~! 마지막까지 꼼꼼히 피드백 반영 잘해주셨네요! 👏 
추가 피드백이 있으시거나(cc. @hyoungnam) 추가로 반영하고 싶으신 부분이 있으시다면 
2단계에서 이어서 의견 나눠주셔요 🙂 
2단계 진행을 위해 요 PR은 머지하도록 할게요! 고생 많으셨습니다~

2022-05-06 06:01 UTC, merged